### ISSUE TITLE
couldn't resolve module/action 'alternatives'. This often indicates a misspelling, missing collection, or incorrect module path

### ISSUE THREAD

**Issue by CatchKarthik** [ansible/awx#10115]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY
We have a playbook that uses alternatives module. After AWX upgrade, the particular task has been failing. The same playbook was working fine in the previous version of AWX.

We get the below error while running the playbook with verbosity on
```
redirecting (type: modules) ansible.builtin.alternatives to community.general.alternatives
couldn't resolve module/action 'alternatives'. This often indicates a misspelling, missing collection, or incorrect module path

```
##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE
Run a playbook with alternative module similar to one below in Ansible AWX

Playbook task:
```
    - name: Update alternatives
      alternatives:
        name: 'java'
        path: '/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java'
        link: '/usr/bin/java'
        priority: '100'
      when: java_item.stat.exists | bool
      loop: '{{ java_binary_collection.results }}'
      loop_control:
        loop_var: java_item
```

##### EXPECTED RESULTS

The alternative module should be found and should be passed. 

##### ACTUAL RESULTS

We get the below error while running the playbook with verbosity on
```
redirecting (type: modules) ansible.builtin.alternatives to community.general.alternatives
couldn't resolve module/action 'alternatives'. This often indicates a misspelling, missing collection, or incorrect module path

```
