### ISSUE TITLE
AWX Collection 15.0.1 tower_job_template module does not update surveys for existing job templates

### ISSUE THREAD

**Issue by snooyen** [ansible/awx#10119]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running the tower_job_template module to update an existing job template that already has a survey on AWX, the module reports `"changed": false` & does not update the survey with new items.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  2.9.10
* Operating System: OSX Catalina 10.15.3
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1.  Import a job template w/ a survey spec to AWX using the tower_job_template module
2. Update the job template json with an additional item in the survey_spec.spec field
3. Rerun the tower_job_template module

##### EXPECTED RESULTS
tower_job_template module reports `"changed": true` & the additional survey prompts are added to the job template survey in AWX.

##### ACTUAL RESULTS
tower_job_template module reports `"changed": "false` & no modifications are made to the job template survey in AWX.

##### ADDITIONAL INFORMATION
I threw some debug statements into the module code locally but it seems like the `update_survey` call is never being made?

survey spec code:
```python
# tower_job_template.py v15.0.1

# Line 326
def update_survey(module, last_request):
    spec_endpoint = last_request.get('related', {}).get('survey_spec')
    module.json_output['my_debug_spec_endpoint_new'] = spec_endpoint  # DEBUG
    if module.params.get('survey_spec') == {}:
        response = module.delete_endpoint(spec_endpoint)
        if response['status_code'] != 200:
            # Not sure how to make this actually return a non 200 to test what to dump in the respinse
            module.fail_json(msg="Failed to delete survey: {0}".format(response['json']))
    else:
        response = module.post_endpoint(spec_endpoint, **{'data': module.params.get('survey_spec')})
        if response['status_code'] != 200:
            module.fail_json(msg="Failed to update survey: {0}".format(response['json']['error']))
    module.exit_json(**module.json_output)
 .
 .
 .  
# Line 509
    on_change = None
    new_spec = module.params.get('survey_spec')
    module.json_output['my_debug'] = "FOO"  # DEBUG
    if new_spec is not None:
        module.json_output['my_debug'] = "BAR"  # DEBUG
        existing_spec = None
        if existing_item:
            spec_endpoint = existing_item.get('related', {}).get('survey_spec')
            existing_spec = module.get_endpoint(spec_endpoint)['json']
        if new_spec != existing_spec:
            module.json_output['my_debug'] = "FOOBAR"  # DEBUG
            module.json_output['changed'] = True
            if existing_item and module.has_encrypted_values(existing_spec):
                module._encrypted_changed_warning('survey_spec', existing_item, warning=True)
            on_change = update_survey
         module.json_output['my_debug_spec_endpoint_old'] = spec_endpoint
```

Debug results:
Note that `my_debug_spec_endpoint_new` is not listed in the module json output
```json
{
  "changed": false,
  "failed_when_result": false,
  "id": 70,
  "my_debug": "FOOBAR",
  "my_debug_spec_endpoint_old": "/api/v2/job_templates/70/survey_spec/",
 }
  ```

**Comment by snooyen** [comment]
I'd like to note that if the job template DOES NOT EXIST prior to running the tower_job_template module, the survey spec gets imported successfully.  So if I delete the job template prior to import, we'll get the correct results.

**Comment by AlanCoding** [comment]
Directly embeding the blurb of code:

https://github.com/ansible/awx/blob/da9a0750008e54487296825719acd910a8a5dc5e/awx_collection/plugins/modules/tower_job_template.py#L574-L585

I am a little confused here myself. If it was discovered that `new_spec != existing_spec`, then I would expect the "changed" status to be set right then and there. The `on_changed` method doesn't _establish_ that a change took place. It _runs when_ a change took place.

https://github.com/ansible/awx/blob/0bdd873bd3d1eb86ca47ae8ea69ab7d9d28cd1bc/awx_collection/plugins/module_utils/tower_api.py#L645-L650

Do we have sufficient test coverage for this? I thought we did. This looks like it's providing regression coverage against exactly this.

https://github.com/ansible/awx/blob/0bdd873bd3d1eb86ca47ae8ea69ab7d9d28cd1bc/awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml#L263-L288

**Comment by snooyen** [comment]
@AlanCoding I think I've narrowed down as to why the "changed" status is incorrectly false.

In `TowerAPIModule.update_if_needed`
https://github.com/ansible/awx/blob/e4e5d65a71b9a1507c229f1ce6d3864d4d717c3f/awx_collection/plugins/module_utils/tower_api.py#L553-L564

Adding debug statements to `json_output`
```python
  if needs_patch:
                response = self.patch_endpoint(item_url, **{'data': new_item})
                if response['status_code'] == 200:
                    # compare apples-to-apples, old API data to new API data
                    # but do so considering the fields given in parameters
                    self.json_output['changed_debug1'] = self.json_output['changed']
                    self.json_output['changed'] = self.objects_could_be_different(
                        existing_item, response['json'], field_set=new_item.keys(), warning=True)
                    self.json_output['changed_debug2'] = self.json_output['changed']
                elif 'json' in response and '__all__' in response['json']:
                    self.fail_json(msg=response['json']['__all__'])
                else:
                    self.fail_json(**{'msg': "Unable to update {0} {1}, see response".format(item_type, item_name), 'response': response})
```

Yields:
```shell
ok: [localhost] => changed=false
  changed_debug1: true
  changed_debug2: false
  id: 89
```

Preventing `on_update` from being called:

https://github.com/ansible/awx/blob/e4e5d65a71b9a1507c229f1ce6d3864d4d717c3f/awx_collection/plugins/module_utils/tower_api.py#L575-L582

**Comment by snooyen** [comment]
After looking more closely at `TowerAPIModule. objects_could_be_different` & `TowerAPIModule. fields_could_be_same`, it looks like `tower_job_template` is not passing `survey_spec` as a field to check.

Adding `survey_spec` to the "fields" for loop in `15.0.1/awx_collection/plugins/modules/tower_job_template.py` seems to resolve the issue.

BEFORE:
https://github.com/ansible/awx/blob/e4e5d65a71b9a1507c229f1ce6d3864d4d717c3f/awx_collection/plugins/modules/tower_job_template.py#L430-L437

AFTER:
```python
    for field_name in (
        'description', 'job_type', 'playbook', 'scm_branch', 'forks', 'limit', 'verbosity',
        'job_tags', 'force_handlers', 'skip_tags', 'start_at_task', 'timeout', 'use_fact_cache',
        'host_config_key', 'ask_scm_branch_on_launch', 'ask_diff_mode_on_launch', 'ask_variables_on_launch',
        'ask_limit_on_launch', 'ask_tags_on_launch', 'ask_skip_tags_on_launch', 'ask_job_type_on_launch',
        'ask_verbosity_on_launch', 'ask_inventory_on_launch', 'ask_credential_on_launch', 'survey_enabled', 'survey_spec',
        'become_enabled', 'diff_mode', 'allow_simultaneous', 'custom_virtualenv', 'job_slice_count', 'webhook_service',
    ):
```

**Comment by AlanCoding** [comment]
These all look like valid points, but I really need a playbook reproducer to move forward.

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:

    - tower_project:
        name: project_for_survey_test
        organization: Default
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git

    - tower_inventory:
        name: inventory_for_survey_test
        organization: Default

    - tower_job_template:
        name: jt_for_survey_test
        project: project_for_survey_test
        inventory: inventory_for_survey_test
        playbook: ping.yml
        survey_enabled: true
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Q1"
              question_description: "The first question"
              required: true
              type: "text"
              variable: "q1"
              min: 5
              max: 15
              default: "hello"
              choices: ""

    - tower_job_template:
        name: jt_for_survey_test
        project: project_for_survey_test
        inventory: inventory_for_survey_test
        playbook: ping.yml
        survey_enabled: true
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Q1"
              question_description: "The first question"
              required: true
              type: "text"
              variable: "q1"
              min: 5
              max: 15
              default: "hello"
              choices: ""
            - question_name: "Q2"
              type: "text"
              variable: "q2"
              required: false
      register: result

    - assert:
        that:
          - "result is changed"
```

This works correctly, so for now I'm still left unable to reproduce. There might be something very specific you did that I still need to pick up here.

**Comment by snooyen** [comment]
@AlanCoding We're running v15.0.1 of AWX & the AWX Collection if that makes a difference?  

Additionally, we're reading in the job template data from a saved file via `lookup` & then passing thos parameters to `awx.awx.tower_job_template`.  I'll try to put a playbook together shortly.

**Comment by snooyen** [comment]
Found it.  Guess you could chalk this up to user error / bad inputs, but setting `custom_virtualenv: ''` is what's causing the failure.

In our role, we're reading in the template data previously saved to a YAML file via `awx.awx.tower_export`.
We then pass those parameters back to `awx.awx.tower_job_template`.

For the field `custom_virtualenv`, `awx.awx.tower_export` sets a `null` value.
```yaml
#job_template.yaml
.
.
custom_virtualenv: null
```
So the following playbook
```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - set_fact:
        job_template: "{{ lookup('file', './job_template.yml') | from_yaml }}"

    - debug: msg="{{ job_template.custom_virtualenv }}""           
```
would yield:

```python
TASK [debug] ************************************************************
ok: [localhost] =>
  msg: ''
 ```
 
 Given that you guys are ditching custom_virtualenvs in v16+, it's probably not worth tracking down so I'm going to go ahead and close this issue here.

However, here's a playbook reproducer, should you decide to re-open & pursue the issue further:

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:

    - tower_project:
        name: project_for_survey_test
        organization: Default
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git

    - tower_inventory:
        name: inventory_for_survey_test
        organization: Default

    - tower_job_template:
        name: jt_for_survey_test
        project: project_for_survey_test
        inventory: inventory_for_survey_test
        playbook: ping.yml
        survey_enabled: true
        custom_virtualenv: ''  # BAD INPUT
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Q1"
              question_description: "The first question"
              required: true
              type: "text"
              variable: "q1"
              min: 5
              max: 15
              default: "hello"
              choices: ""

    - tower_job_template:
        name: jt_for_survey_test
        project: project_for_survey_test
        inventory: inventory_for_survey_test
        playbook: ping.yml
        survey_enabled: true
        custom_virtualenv: ''  # BAD INPUT
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Q1"
              question_description: "The first question"
              required: true
              type: "text"
              variable: "q1"
              min: 5
              max: 15
              default: "hello"
              choices: ""
            - question_name: "Q2"
              type: "text"
              variable: "q2"
              required: false
      register: result

    - assert:
        that:
          - "result is changed"
```
