### ISSUE TITLE
Blank white page fresh install 19 on Kubernetes

### ISSUE THREAD

**Issue by washburnjoe** [ansible/awx#10135]
##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

Fresh install using operator 0.9.0 using the most basic setup.  The only change is namepsace
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: prod-awx
spec:
  tower_ingress_type: Ingress
```

##### ENVIRONMENT
* AWX version: 19
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System: Tested with Mac and Win 10
* Web Browser: Edge, Chrome, Safari

##### STEPS TO REPRODUCE

Deployed the operator
Ran kubectl apply -f myawx.yml
Containers all started

##### ACTUAL RESULTS

Blank white page.  Using Dev tools shows 503 errors on several js files.  The postgres container has the following errors:
ERROR" column main_instancegroup.is_container_group does not exist at charachter 129
