### ISSUE TITLE
Where in the code is the Ingress controller built?

### ISSUE THREAD

**Issue by washburnjoe** [ansible/awx#10143]
##### ISSUE TYPE

 - Documentation

##### COMPONENT NAME

 - Installer

##### SUMMARY

I am trying to find where in the code the Ingress controller gets built.  I need to make one change to a path in order for it to work in our environment

##### ENVIRONMENT
* AWX version: 19
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System: NA
* Web Browser: NA

##### STEPS TO REPRODUCE
If I look at our ingress controller that is deployed using the vanilla install it comes out like this: (edited to show the important parts)
```
spec:
  tls:
    - hosts:
        - awx.deployment.ourdomain.com
      secretName: deployment.ourdomain.com
  rules:
    - host: awx.deployment.ourdomain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: awx-service
                port:
                  number: 80
```
The issue is with `-path: /`

With that in place the home page is just a white blank page.  If I made an edit directly and remove the / it works as expected.

We had this same issue with V14 of AWX and we were able to edit it in the ingress.yaml, but that does not seem to be possible with 19.  Any help pointing to where that is controlled now would be a great help.
