### ISSUE TITLE
Playbooks with provider do not work in AWX

### ISSUE THREAD

**Issue by joethie** [ansible/awx#1018]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
Playbooks written for ansible cli including a provider do not work in awx. States that ansible_pass is not defined.

##### ENVIRONMENT
* AWX version: Latest
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: Windows
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Run playbook with following provider defined:

provider:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_pass }}"
  timeout: 60

##### EXPECTED RESULTS

Playbook completes successfully

##### ACTUAL RESULTS

{
    "msg": "The task includes an option with an undefined variable. The error was: {u'username': u'{{ ansible_user }}', u'host': u'{{ ansible_host }}', u'password': u'{{ ansible_pass }}', u'timeout': 60}: 'ansible_pass' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_9__iansible/playbooks/ios_test.yml': line 20, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: show version\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {u'username': u'{{ ansible_user }}', u'host': u'{{ ansible_host }}', u'password': u'{{ ansible_pass }}', u'timeout': 60}: 'ansible_pass' is undefined"
}

##### ADDITIONAL INFORMATION

I anticipated playbooks could be written to work in both cli and awx at the same time. Perhaps this is not the case? Is there a built in variable to use that is associated with ssh credentials in awx?

**Comment by ryanpetrello** [comment]
@joethie can you share the full playbook you're running (or enough of one to provide a reproducible test case in awx)?

**Comment by joethie** [comment]
This is what a playbook would look like if run from the cli. I would like to find a way to make this format work in awx as well so the playbook could be run from either cli or awx
```
---
- hosts: all
  gather_facts: false
  connection: local
  vars:
    provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      timeout: 60
  tasks:
    - name: show version
      ios_command:
        commands: show version
        provider: "{{ provider }}"
      register: out
```
