### ISSUE TITLE
volume mounted to awx-ee container is not identified while executing the job templates on awx-ee

### ISSUE THREAD

**Issue by abhishek-s-a** [ansible/awx#10461]
##### ISSUE TYPE
Run time

##### SUMMARY
Volume mounted to awx-ee container is not identified while executing the job templates from AWX GUI with awx-ee. The same playbook is getting executed when running inside the awx-ee container manually and able to access mount volume.

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: kubernetes
* Ansible version:  2.
* Operating System: centos
* Web Browser:

##### STEPS TO REPRODUCE
Run the job template in awx which has mounted volume dependency.

##### EXPECTED RESULTS

Job template should be executed successfully by accessing the mount volume.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/73212230/122208649-32218680-cec1-11eb-8c5a-8f5dc5f9733a.png)

##### ADDITIONAL INFORMATION
Please find below code I used for creating volume and mount:

```
tower_extra_volumes: |
    - name: "awx-ee-extra"
      hostPath:
        path: /var/ee_mount/
        type: Directory
  tower_ee_extra_volume_mounts: |
    - name: "awx-ee-extra"
      mountPath: "/runner/"
```

**Comment by KevinBonilla** [comment]
Hey! I'm trying to figure out an issue similar to yours as well! I have an NFS server that is mounted as a PV and generated the PVC. I want to be able to use this mount for binaries, private files, etc. Here's my configuration thus far.

```
cat nfs-pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

cat nfs-pv.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: <EXPORT MOUNT PATH>
    server: <IP ADDR>

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_hostname: <hostname>
  tower_ingress_tls_secret: <secret-tls>
  tower_extra_volumes: |
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs-pvc
  tower_task_extra_volume_mounts: |
    - name: nfs-pvc
      mountPath: /AWX
  tower_ee_extra_volume_mounts:  |
    - name: nfs-pvc
      mountPath: /AWX
```

When I run apply the configuration I don't see any events or used by pods so I believe it's safe to assume its not working.
```
kubectl describe pvc nfs-pvc
Name:          nfs-pvc
Namespace:     default
StorageClass:  nfs
Status:        Bound
Volume:        nfs-pv
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      500Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       <none>
Events:        <none>
```
