### ISSUE TITLE
Default Container group not downloading collections/requirements.yml

### ISSUE THREAD

**Issue by felipe4334** [ansible/awx#10529]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

I'm currently having an issue were when a job is created on a container group, and it triggers a job pod to be created. The new pod does not use the collections/requirements.yml file or even requirements.yml in the root directory of the project.

This is the error I get when running a job from a container group, it looks like "ansible collection location" does not get updated to represent the requirements.yml file.

##### ENVIRONMENT
* AWX version: 19.2.1
* AWX install method: operator
* AWX deployment target: kubernetes
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

- Deploy AWX using Operator to Kubernetes cluster.
- Use Container group as your instance group type
- Use a project that has collections/requirements.yml file requesting for a specific package 
- Run project

##### EXPECTED RESULTS

When I write my own ansible.cfg and and download the collections and map a volume to the pods /etc/ansible location then everything works fine, but this solution is not scalable and will require for collections to manually be added every time a project is using newer collections.
![image](https://user-images.githubusercontent.com/13802820/123524109-17f06100-d696-11eb-8a2b-4fe77e2311d7.png)

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/13802820/123524121-1fb00580-d696-11eb-8fee-7e5321241caa.png)

##### ADDITIONAL INFORMATION

I'm currently having an issue were when a job is created on a container group, and it triggers a job pod to be created. The new pod does not use the collections/requirements.yml file or even requirements.yml in the root directory of the project.

This is the error I get when running a job from a container group, it looks like "ansible collection location" does not get updated to represent the requirements.yml file.
![![image](https://user-images.githubusercontent.com/13802820/123524060-ccd64e00-d695-11eb-9dad-60bf31ec748c.png)](https://user-images.githubusercontent.com/13802820/123524054-c516a980-d695-11eb-8804-3661d752db70.png)

requirements.yml:

```
---
collections:
   - name: oracle.oci
```

project:
![image](https://user-images.githubusercontent.com/13802820/123524075-e2e40e80-d695-11eb-8cda-d6d6b5a32667.png)

When I write my own ansible.cfg and and download the collections and map a volume to the pods /etc/ansible location then everything works fine, but this solution is not scalable and will require for collections to manually be added every time a project is using newer collections.
![image](https://user-images.githubusercontent.com/13802820/123524093-fee7b000-d695-11eb-8366-0055a14edce4.png)

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  dnsConfig:
    searches:
      - office.domain.com
      - prod.domain.com
  containers:
    - image: 'quay.io/ansible/awx-ee:0.4.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
        - name: oke-fsspvc-awx-etc-ansible
          mountPath: /etc/ansible
  volumes:
    - name: oke-fsspvc-awx-etc-ansible
      persistentVolumeClaim:
        claimName: oke-fsspvc-awx-etc-ansible
```
ansible.cfg

```
[defaults]
nocows = True
collections_paths = /etc/ansible/collections
roles_path = roles
library = /var/lib/awx/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/share/ansible/collections/mdules:/etc/ansible/collections/ansible_collections/oracle/oci/plugins/modules
forks = 50

[ssh_connection]
pipelining = True
ssh_args = -o PreferredAuthentications=publickey
```

This issue appears to only happen with Container group and not with instance group. Although I cannot test the tower - instance group on my new Kubernetes awx operator deployment because I get a "Status: pending: This job is not ready to start because there is not enough available capacity." error, even though my awx_tasks requirements are fairly high Request CPU 10000m and memory 15Gi when testing on my old awx deployment when the project runs out of awx_tasks the collections get automatically downloaded.

This issue is happening with both customized or non-customized pod specification.
