### ISSUE TITLE
awx_collection: Adding inventory source with duplicated project name fails in 'multi-tenant' like environment 

### ISSUE THREAD

**Issue by Tompage1994** [ansible/awx#10571]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - awx_collection

##### SUMMARY
Adding an inventory source of type `scm` fails when the source_project has the same name as another project in another organization. This therefore fails in a multi-tenant environment.

##### ENVIRONMENT
* AWX collection version: 19.2.2 

##### STEPS TO REPRODUCE

- Create 2 orgs
- Create a project and copy it so there is one in each org with the same name. 
- Create an inventory in one org
- Use the awx.awx.inventory_source as below:
```
- awx.awx.inventory_source:
        name: is1
        source: scm
        source_project: Demo Project
        organization: Default
        inventory: Demo Inventory
```

##### EXPECTED RESULTS

It should use the organization which is used for the inventory by default, but you should also be able to specify the source_project's org.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/projects/?name=Demo+Project returned 2 items, expected 1", "query": {"name": "Demo Project"} ...
```

**Comment by shanemcd** [comment]
Probably just need to add the organization to the query params here.

**Comment by john-westcott-iv** [comment]
With the merged PR solving the crash and the ability to look up items with the `lookup` module we are going to close this issue. For reference, as mentioned in the PR, once can lookup objects using the lookup module like:
```
  - name: create INVSOURCE
    inventory_source:
      name: inv1
      source: scm
      source_project: "{{ lookup('awx.awx.controller_api', 'projects', query_params={'name': 'Demo Project', 'organization__name':'org1'}, return_ids=True )}}"
      organization: Default
      inventory: Demo Inventory
  ```
