### ISSUE TITLE
Develop a more native way to obtain execution node capacity

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#10693]
As of https://github.com/ansible/awx/pull/10688, capacity checks are running by way of the Ansible `setup` module, and processing the data from that.

This is not, ultimately, how we would like capacity checking of execution nodes to work.

We discussed adding a feature to receptor which would include capacity in the service broadcast, but there was disagreement about that.

There is a constraint that jobs run through the ansible-runner advertised service

```
- work-command:
    worktype: ansible-runner
    command: ansible-runner
    params: worker
    allowruntimeparams: true
```

We don't want to assume (or mandate) that execution nodes advertise a different kind of service. However, it may be possible to implement a capacity check command with the format of:

```
ansible-runner worker capacity
```

This could possibly fit into the existing paradigm, and give us flexibility.

**Comment by AlanCoding** [comment]
this may be somewhat duplicated with https://github.com/ansible/awx/issues/10637

**Comment by AlanCoding** [comment]
Maybe another option:

```
- work-command:
    worktype: ansible-runner
    command: ansible-runner
    allowruntimeparams: true
```

And then implement the capacity check as `ansible-runner capacity`
