### ISSUE TITLE
ansible-inventory can't find ansible.cfg

### ISSUE THREAD

**Issue by sobedrinker42** [ansible/awx#10704]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

when trying to bring in an inventory, the play fails due to the fact ansible-inventory can't find an ansible.cfg.  When logging into the container, I can see all files and environmental variables are correctly populated.  I've tried this in every way I can think, and it still isn't finding ansible.cfg.

### AWX version

19.2.2

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.11.2.post0]

### Operating system

CentOS Linux release 7.6.1810 (Core)

### Steps to reproduce

according to the documentation for installation:

as specified by the docs, I added the following to my awx yaml file.
```yaml
ee_extra_volume_mounts: |
      - name: ansible-cfg
        mountPath: /etc/ansible/ansible.cfg
        subPath: ansible.cfg
      - name: pass-txt
        mountPath: /etc/ansible/vault/pass.txt
        subPath: pass.txt
  extra_volumes: |
      - name: ansible-cfg
        configMap:
          defaultMode: 420
          items:
            - key: ansible.cfg
              path: ansible.cfg
          name: awx-demo-extra-config
      - name: pass-txt
        configMap:
          defaultMode: 420
          items:
            - key: pass.txt
              path: pass.txt
          name: awx-demo-extra-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-demo-extra-config
data:
  ansible.cfg: |
      [defaults]
      vault_password_file = /etc/ansible/vault/pass.txt
      [diff]
      always = True
  pass.txt:  |
     <blahblahblahblahblah>
```
I even added environment variables to ensure that it is pointing to the right spot for the config:
```yaml
  ee_extra_env: |
    - name: ANSIBLE_CONFIG
      value: /etc/ansible/ansible.cfg
    - name: ANSIBLE_VAULT_PASSWORD_FILE
      value: /etc/ansible/vault/pass.txt
```
next, add an inventory and run the job to pull it in.  you should reproduce the issue and see the defined ansible.cfg isn't being leveraged.

### Expected results

```
ansible-inventory [core 2.11.2.post0] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

### Actual results

when logging into the container, it all seems happy :)
```
awx-master@awx101:~$ kubectl exec -it awx-demo-8558b74c7f-s6dwr --container=awx-demo-ee -- /bin/sh
sh-4.4$ echo $ANSIBLE_CONFIG
/etc/ansible/ansible.cfg
sh-4.4$ echo $ANSIBLE_VAULT_PASSWORD_FILE
/etc/ansible/vault/pass.txt
sh-4.4$ ansible --version
ansible [core 2.11.2.post0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
sh-4.4$ ansible-inventory --version
ansible-inventory [core 2.11.2.post0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

when running the job from the AWX GUI (inventories section), it doesn't look the same:
```
ansible-inventory [core 2.11.2.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
```

**Comment by sobedrinker42** [comment]
for what it's worth - I also tried setting environment variables in the job settings and had no luck.  the inventory play couldn't find the file I was referencing, even though I verified the location was correct.

**Comment by wenottingham** [comment]
ee_extra_volume_mounts is only for the control plane EE. If you want extra mounts for runtime EEs, those should be modified in the podspec.

What sort of inventory are you trying to update?

**Comment by koolfit** [comment]
Hi, any help is appreciated I'm having the same problem,  I've created and mounted a persistent volume into the awx_ee container in order to use custom ansible.cfg and install custom-made ansible modules I need but no luck, every time I launch a job from the AWX GUI it shows it's using ansible defaults always and no config file is found, I can't even use ansible-galaxy collections, they install on the container but AWX will not recognize them.

If I log into the awx_ee container it shows me it´s using my .cfg file 

```
ansible [core 2.11.2.post0] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/usr/share/ansible/collections/modules', '/etc/ansible/collections']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

this is my awx yaml:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: noctopus-awx
spec:
  service_type: LoadBalancer
  ingress_type: none
  hostname: noctopus.kionetworks.com
  replicas: 1
  extra_volumes: |
    - name: awx-ansible-cfg
      persistentVolumeClaim:
        claimName: awx-ee-pvc
  ee_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
  ee_extra_volume_mounts: |
    - name: awx-ansible-cfg
      mountPath: /etc/ansible
```

the pvc is mounted correctly according to Kubernetes and awx_ee container:

```
bash-4.4$ df -h
Filesystem                                              Size  Used Avail Use% Mounted on
overlay                                                  62G   29G   33G  47% /
tmpfs                                                    64M     0   64M   0% /dev
tmpfs                                                   7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/vda1                                                62G   29G   33G  47% /runner
/dev/longhorn/pvc-f9f5d041-d03d-4099-8727-219cb1592cac  4.9G   21M  4.9G   1% /etc/ansible
shm                                                      64M  264K   64M   1% /dev/shm
tmpfs                                                   7.9G   12K  7.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                   7.9G     0  7.9G   0% /proc/acpi
tmpfs                                                   7.9G     0  7.9G   0% /proc/scsi
tmpfs                                                   7.9G     0  7.9G   0% /sys/firmware
```
![image](https://user-images.githubusercontent.com/31895009/128271021-4b5a7540-15ba-4c8d-b82c-cbd979de7df7.png)

**Comment by wenottingham** [comment]
Closing this issue - as noted above, if you want extra mounts for runtime EEs, those should be modified in the podspec.

**Comment by alexriveraz** [comment]
Thanks @wenottingham if anyone is still trying to figure out how to do this, note that this will create a pod with a container called worker (in this example) every time a job runs in your defined instance group and once it's completed it will be destroyed:

![image](https://user-images.githubusercontent.com/8902656/128551584-1c8ed93a-9f83-40f3-8e2d-c18aaebfc312.png)

![image](https://user-images.githubusercontent.com/8902656/128551247-677d0976-d768-423b-8614-7efa5269f85a.png)

```
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  dnsConfig:
    searches:
      - name.yourdomain.com
  containers:
    - image: 'quay.io/ansible/awx-ee:0.5.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
        - name: awx-ansible-cfg
          mountPath: /etc/ansible
  volumes:
    - name: awx-ansible-cfg
      persistentVolumeClaim:
        claimName: awx-ee-runtime-pvc
```

[https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#customize-the-pod-spec](url)
