### ISSUE TITLE
Runtime Error on winRM task [19.1.0]

### ISSUE THREAD

**Issue by KevinBonilla** [ansible/awx#10717]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Cannot run winRM task that silent installs Office 365 using the win_package module. Error output is very vague and having issues finding if anyone has run into similar issues within this github issues or AWX Google group.
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1377, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2904, in run
    return self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2962, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: read tcp 10.42.2.195:56150->10.43.0.1:443: read: connection reset by peer
```

Any help in troubleshooting this is much appreciated.

### AWX version

19.1.0

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.11.3

### Steps to reproduce

I do use a custom Execution environment, but only dependencies that are required (winRM for example).

Here is the playbook where the task is failing, it is a Silent Office install.
```
--- 
    - name: Install Office Pro Plus 2016
      win_package:
        path: C:\Windows\Temp\Office_Professional_Plus_2016_64bits\setup.exe
        arguments:
        - /config C:\Windows\Temp\Office_Professional_Plus_2016_64bits\proplus.ww\config.xml
      tags: windows
```

Keep in mind, this silent install takes a long amount of time, here was the last Elapsed time before the job failed.
Elapsed: 05:30:27

With this abstract error it's really hard for me to figure out what is going wrong and if anyone has any experience if an error similar to this I would greatly appreciate your help!!!

### Expected results

Task should complete with success and not a runtime error.

### Actual results

```
ansible-playbook [core 2.11.3] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
SSH password: 
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
Loading collection ansible.windows from /usr/share/ansible/collections/ansible_collections/ansible/windows
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
redirecting (type: modules) ansible.builtin.win_group_membership to ansible.windows.win_group_membership
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_command to ansible.windows.win_command
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_command to ansible.windows.win_command
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_command to ansible.windows.win_command
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: modules) ansible.builtin.win_command to ansible.windows.win_command
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: main.yml *************************************************************
Positional arguments: main.yml
verbosity: 4
ask_pass: True
remote_user: <HOSTNAME>
connection: smart
timeout: 10
become_method: sudo
tags: ('windows',)
inventory: ('/runner/inventory/hosts',)
subset: <HOSTNAME>
extra_vars: ('@/runner/env/extravars',)
forks: 5
1 plays in main.yml

PLAY [First set of plays, runs in parallel] ************************************

TASK [Gathering Facts] *********************************************************
task path: /runner/project/main.yml:5
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<HOSTNAME> ESTABLISH WINRM CONNECTION FOR USER: <SERVICE USER> on PORT 5986 TO <HOSTNAME>
calling kinit with pexpect for principal <SERVICE USER>
EXEC (via pipeline wrapper)
ok: [<HOSTNAME>]
META: ran handlers
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy


TASK [ps_app_servers : Install Office Pro Plus 2016] ***************************
task path: /runner/project/roles/ps_app_servers/tasks/main.yml:41
redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<HOSTNAME> ESTABLISH WINRM CONNECTION FOR USER: <SERVICE USER> on PORT 5986 TO <HOSTNAME>
calling kinit with pexpect for principal <SERVICE USER>
EXEC (via pipeline wrapper)

```

### Additional information

```
cat execution-environment.yml
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt


additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs instal
```

```
cat requirements.txt
git+https://github.com/ansible/ansible-builder.git@devel#egg=ansible-builder
hvac
urllib3
```

```
cat requirements.yml
---
collections:
- community.hashi_vault
- ansible.windows
- community.general
- awx.awx
- community.windows
- ansible.posix
```

**Comment by wenottingham** [comment]
It looks like something happened with the networking reading from the pod on the other end. Can you confirm that when this happens the pod the playbook is running in is still running, and you can get logs from it?

**Comment by wenottingham** [comment]
Also, what is your kubernetes platform and version?

**Comment by KevinBonilla** [comment]
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

So I believe you were right that a network issue interrupted the playbook, and for some reason the win_package module did not like the parameters I had setup. Using win_command seemed to resolve fine and ran the task in success within minutes, so I'll attribute this to a misconfig when I setup my win_package task I guess?

New win_command task for reference:
```
    - name: Office2016 install
      win_command: 'setup.exe /config C:\Windows\Temp\Office_Professional_Plus_2016_64bits\proplus.ww\config.xml'
      args:
        chdir: C:\Windows\Temp\Office_Professional_Plus_2016_64bits\
      tags:  windows
``` 

With installation taking   "delta": "0:04:21.785071",

Will close this issue, thanks @wenottingham for your feedback.
