### ISSUE TITLE
awx-postgres does not come up

### ISSUE THREAD

**Issue by profhase** [ansible/awx#10733]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have installed the awx operator from 

https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml

>  mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied

### AWX version

latest

### Installation method

kubernetes

### Modifications

no

### Ansible version

3

### Operating system

Debian 10, k3s

### Web browser

Firefox

### Steps to reproduce

Apply following definition

```
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
      spec:
        service_type: nodeport
        projects_persistence: true
        projects_storage_access_mode: ReadWriteOnce
        web_extra_volume_mounts: |
          - name: static-data
            mountPath: /var/lib/awx/public
        extra_volumes: |
          - name: static-data
            persistentVolumeClaim:
              claimName: static-data-pvc
                
```

### Expected results

AWX comes up

### Actual results

AWX does not come up due to

mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
