### ISSUE TITLE
Add proxy setting for ansible-galaxy

### ISSUE THREAD

**Issue by msilmser** [ansible/awx#10771]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently, we have a handful of customers who require proxy configuration in order to reach out to Galaxy but not local Git repos. Our current workaround is to add the HTTP/HTTPS_PROXY setting to the ENVIRONMENT field in the project_update.yml for the ansible-galaxy tasks. If we had a setting in the UI/API to set proxy config specifically for Galaxy this would prevent us from having to edit that playbook.

Potential fix could be something like:

```
       - name: fetch galaxy roles from requirements.(yml/yaml)
          command: >
            ansible-galaxy role install -r {{ item }}
            --roles-path {{projects_root}}/.__awx_cache/{{local_path}}/stage/requirements_roles
            {{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}

...snip...

          environment:
            ANSIBLE_FORCE_COLOR: false
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            HTTP_PROXY: "{{ foo | default('') }}"
            HTTPS_PROXY: "{{ bar | default('') }}"
      when: roles_enabled|bool
      tags:
        - install_roles
```
```
        - name: fetch galaxy collections from collections/requirements.(yml/yaml)
          command: >
            ansible-galaxy collection install -r {{ item }}
            --collections-path {{projects_root}}/.__awx_cache/{{local_path}}/stage/requirements_collections
            {{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}

...snip...

          environment:
            ANSIBLE_FORCE_COLOR: false
            ANSIBLE_COLLECTIONS_PATHS: "{{projects_root}}/.__awx_cache/{{local_path}}/stage/requirements_collections"
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            # Put the local tmp directory in same volume as collection destination
            # otherwise, files cannot be moved accross volumes and will cause error
            ANSIBLE_LOCAL_TEMP: "{{projects_root}}/.__awx_cache/{{local_path}}/stage/tmp"
            HTTP_PROXY: "{{ foo | default('') }}"
            HTTPS_PROXY: "{{ bar | default('') }}"
```
