### ISSUE TITLE
Expose host trusted cert store to EEs by default

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#10787]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Mostly relevant outside of container groups, but we should consider adding
- /etc/pki/ca-trust/
- /usr/share/pki/ca-trust-source
(or whatever the appropriate paths are)

to the default for AWX_ISOLATION_SHOW_PATHS. Not everyone will want to rebuild an EE just to add certs, and inheriting from the host out of the box does make some sense.

**Comment by derhoeppi** [comment]
This feature is very important. Collections like community.vmware could not be used in a secure way with custom CA's. The only workaround is to ignore every cert validation or create an own ee image. Please prioritize the topic because i don't want to maintain an own image because of certificates.

**Comment by andrinbr** [comment]
It would be great if the EE container would use the "bundle_cacert_secret" from the awx-operator spec like the other deployed containers do.

**Comment by xx4h** [comment]
Just in case anyone else does not want to fork the awx-ee image but still needs a workaround.

My preferred workaround for now is creating a new instance group in AWX (based on default), naming it like "default-with-certs" and adding the same ```initContainers``` logic to this instance group which is used when adding certificates over the AWX spec.

This can be looked up by executing
```
kubectl get deployments.apps awx -o yaml
```

The final custom pod spec should look like
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:0.5.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
      - mountPath: /etc/pki/ca-trust/extracted
        name: ca-trust-extracted
      - mountPath:
        name: awx-bundle-cacert
        readOnly: true
        subPath: bundle-ca.crt
  initContainers:
    - command:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/pki/ca-trust/extracted/{java,pem,openssl,edk2}
        update-ca-trust
      image: quai.io/centos/centos:8
      name: init
      imagePullPolicy: IfNotPresent
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/pki/ca-trust/extracted
        name: ca-trust-extracted
      - mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
        name: awx-bundle-cacert
        readOnly: true
        subPath: bundle-ca.crt
  volumes:
    - name: awx-bundle-cacert
      secret:
        defaultMode: 420
        items:
        - key: bundle-ca.crt
          path: bundle-ca.crt
        secretName: YOUR-SECRET-NAME-FROM-INITIAL-AWX-SPEC
    - emptyDir: {}
      name: ca-trust-extracted
```

You can find the secret name with the following command:
```
kubectl get AWX -o=jsonpath='{.items[0].spec.bundle_cacert_secret}{"\n"}'
```

**Comment by keliansb** [comment]
Another vote for this feature!
Thanks @xx4h for your temporary workaround.
In case someone wants to use your workaround as well, there are just 2 typos :
- It is `quay.io/centos/centos:8` instead of `quai.io/centos/centos:8` in `initContainers` section
- `volumeMounts[1].mountPath` in `containers` section is missing the value `/etc/pki/ca-trust/source/anchors/bundle-ca.crt`

**Comment by sunnythaper** [comment]
@CaptAintHere @xx4h I am having trouble with the kubectl commands. Executing the secret name command for example gives me this:

```
error: error executing jsonpath "{.items[0].spec.bundle_cacert_secret}{\"\\n\"}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].spec.bundle_cacert_secret}{"\n"}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

I have a fairly default install so far as I've basically followed the installation guide and have stopped from progressing cause I can't get my playbooks from GitHub. Any insights? 

Edit:

I used the following command but got a blank result:

```
sudo kubectl get -n awx AWX -o=jsonpath='{.items[0].spec.bundle_cacert_secret}{"\n"}'
```

**Comment by keliansb** [comment]
`bundle_cacert_secret` is used when you have to trust a custom certificate authority (see [the documentation](https://github.com/ansible/awx-operator#trusting-a-custom-certificate-authority)). I guess you don't need to do this for GitHub, which has a certificate signed by a known certificate autorithy (DigiCert).

**Comment by sunnythaper** [comment]
@CaptAintHere ah I missed that section of the documentation. I'll be honest, I'm a techy graphic designer so some of this stuff is a bit above my head right now. I managed to get a fully installed and working version of Awx 19.5 running, added my public repo for ansible scripts that has worked with my AWX 8 (yes 8...) installation for years now and got a message around the https. Removed the https check via variables as many have suggested and while the error message changed, still no github syncing.

For me to get my default ca-certificates into Awx 19.5's environment to use, should I use this method in the documentation on the ones that exist on my host system? I've been at this for a month now, not joking, and would appreciate any headway you can provide!

EDIT: Wow, ok, that was INCREDIBLY easy and I was apply to apply it to my running instance quite easily.

First I issued this command:

```bash
sudo kubectl create secret generic awx-custom-certs --from-file=bundle-ca.crt=/etc/ssl/certs/ca-certificates.crt
```

Then I changed my yaml file for deployment:

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  bundle_cacert_secret: awx-custom-certs
```

Changed my namespace to awx again from default

```bash
sudo kubectl config set-context --current --namespace=awx
```

And finally applied the new deployment file (to my already running instance from follow default direction):

```bash
sudo kubectl apply -f awx-deploy.yml
```

Went to my browser, clicked sync project, and bam! Github sync finally freaking worked. Thanks guys for giving me the ability to get there!

**Comment by shanemcd** [comment]
Was just chatting with @tchellomello about how we are going to handle this for VM-based installs.

The first logical step was to try this:

<img width="422" alt="Screen Shot 2022-01-19 at 1 32 51 PM" src="https://user-images.githubusercontent.com/773186/150192581-db9a63df-7d12-43bf-ac53-176752f114bb.png">

Which generates a command that looks something like this:

```
podman run --rm --tty --interactive --workdir /runner/project -v /tmp/awx_9_fpr0m4tx/:/runner/:Z -v /etc/pki/ca-trust/:/etc/pki/ca-trust/:z -v /usr/share/pki/ca-trust-source/:/usr/share/pki/ca-trust-source/:z --env-file /tmp/awx_9_fpr0m4tx/artifacts/9/env.list --quiet --name ansible_runner_9 --user=root registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest ansible-playbook -u root -i /runner/inventory/hosts -e @/runner/env/extravars myplaybook.yml
```

If you try this, you will see:

```
Error: relabeling content in /usr is not allowed
```

This is because we tack on `:z` to everything in `settings.AWX_ISOLATION_SHOW_PATHS`:

https://github.com/ansible/awx/blob/9d636cad2955e43285bd9fb48845426df653b215/awx/main/tasks/jobs.py#L178-L181

Mello pointed out that `:O` works, but we can't make that the default because the data written out during job runtime will be deleted when the container goes away.

This makes me think that we need to support Podman-style volume mount expressions under `settings.AWX_ISOLATION_SHOW_PATHS`, so you would have something like this:

<img width="856" alt="Screen Shot 2022-01-19 at 1 39 01 PM" src="https://user-images.githubusercontent.com/773186/150193489-ebe59583-5aaa-4192-bee1-18fc7c0ea16e.png">

We have to be mindful about backwards compatibility, so we need to check for the presence of `:` in the filename and if it is not present treat it as we are currently.

**Comment by tchellomello** [comment]
Closing since #11566 has merged

**Comment by shanemcd** [comment]
I think what we did in https://github.com/ansible/awx/pull/11566 was great, but this issue is specifically for automatically mounting the system trust (on VMs), which we still need to do.

**Comment by tchellomello** [comment]
I'm going to draft a solution for that

**Comment by ffirg** [comment]
we need to make sure that this fix covers both control and execution planes.

**Comment by AlanCoding** [comment]
I have become confused - https://github.com/ansible/awx/pull/11844

**Comment by sbrile** [comment]
Using @xx4h example is the only way I was able to get WinRM over HTTPS working with Kerberos.  I also had to mount my custom krb5.conf file.

deploy your ca root cert as a secret
```
kind: Secret
apiVersion: v1
metadata:
  name: kerberos-cacert
  namespace: dev-awx
type: Opaque
stringData:
  bundle-ca.crt: |-
        -----BEGIN CERTIFICATE-----
        <your ca cert>
        -----END CERTIFICATE-----
```

deploy custom krb5.conf with your domains
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kerberos-config
  namespace: dev-awx
data:
  krb5.conf: |-
    # To opt out of the system crypto-policies configuration of krb5, remove the
    # symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
    includedir /etc/krb5.conf.d/

    [logging]
        default = FILE:/var/log/krb5libs.log
        kdc = FILE:/var/log/krb5kdc.log
        admin_server = FILE:/var/log/kadmind.log

    [libdefaults]
        dns_lookup_realm = false
        ticket_lifetime = 24h
        renew_lifetime = 7d
        forwardable = true
        rdns = false
        pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
        spake_preauth_groups = edwards25519
        dns_canonicalize_hostname = fallback
        qualify_shortname = ""
    #    default_realm = EXAMPLE.COM
        default_ccache_name = KEYRING:persistent:%{uid}

    [realms]

    [domain_realm]
```

create an instance group in the AWX UI

```
apiVersion: v1
kind: Pod
metadata:
  namespace: dev-awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:0.5.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
      - mountPath: /etc/pki/ca-trust/extracted
        name: ca-trust-extracted
      - mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
        name: awx-bundle-cacert
        readOnly: true
        subPath: bundle-ca.crt
      - mountPath: /etc/krb5.conf
        name: krb5-conf
        subPath: krb5.conf
  initContainers:
    - command:
      - /bin/sh
      - -c
      - |
        mkdir -p /etc/pki/ca-trust/extracted/{java,pem,openssl,edk2}
        update-ca-trust
      image: quay.io/centos/centos:8
      name: init
      imagePullPolicy: IfNotPresent
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/pki/ca-trust/extracted
        name: ca-trust-extracted
      - mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
        name: awx-bundle-cacert
        readOnly: true
        subPath: bundle-ca.crt
  volumes:
    - name: awx-bundle-cacert
      secret:
        defaultMode: 420
        items:
        - key: bundle-ca.crt
          path: bundle-ca.crt
        secretName: kerberos-cacert
    - emptyDir: {}
      name: ca-trust-extracted
    - name: krb5-conf
      configMap:
        name: kerberos-config
```
