### ISSUE TITLE
Survey Multiple Choice - Multiple Select - Breaks jinja2 in nested loop.

### ISSUE THREAD

**Issue by ghost** [ansible/awx#10835]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have designed an application installation role that dynamically includes vars for the packages to be installed. The role loops through a list of applications specified by the play, includes the vars for that package from a dynamically sourced vars file, and  loops through the installation requirements of each include.

This works from ansible-playbook on console when passing a list as an environment variable, and from AWX when passing the list as Extra Variables in the template settings.  When passing the list from a survey, debug output shows that the jinja2 variables inside the vars files are not templated out, leaving a literal jinja2 string with invalid characters passed to the package modules.

### AWX version

15.0.1

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.10.7

### Operating system

CentOS 8

### Web browser

Chrome, Edge

### Steps to reproduce

Play:
``` yaml
---
# Show us what install_applications looks like for troubleshooting
- name: Debug AWX Extra Variables
  hosts: all
  gather_facts: no
  tasks:
    - debug:
        var: install_applications

# Main Play
- name: Validate Windows Baseline configuration
  hosts: all
  gather_facts: yes
  collections:
    - local.windows
  tasks:
    - include_role:
        name: install
      vars:
        application: "{{app}}"
      loop: "{{install_applications}}"
      loop_control:
        loop_var: app
```
local.windows.install role tasks:
main.yml
``` yaml
---
# tasks file for install
- include_tasks: "{{ansible_os_family}}.yml"
  ignore_errors: yes
```
Windows.yml
``` yaml
---
# tasks file for install
- include_vars:
    file: "{{application}}_win.yml"
    name: "{{application}}"
  register: app_vars
  ignore_errors: true

# Test that the loop works - Works in several tested, non-survey scenarios.
- debug:
    msg: "{{item}}"
  loop: "{{lookup('vars', application)[lookup('vars', 'application')]}}"

# Try FQDN first
- block:
    - ansible.windows.win_package:
        path: '\\{{cached_fileserver_fact.ansible_fqdn}}\{{item.path}}'
        creates_path: "{{item.creates_path | default(omit)}}"
        creates_version: "{{item.creates_version | default(omit)}}"
        arguments: "{{item.arguments | default(omit)}}"
      loop: "{{lookup('vars', application)[lookup('vars', 'application')]}}"
      when: not app_vars.failed

# Try IP or NetBios name, whichever was set as cached_fileserver_fact.ansible_host
  rescue:
    - ansible.windows.win_package:
        path: '\\{{cached_fileserver_fact.ansible_host}}\{{item.path}}'
        creates_path: "{{item.creates_path | default(omit)}}"
        creates_version: "{{item.creates_version | default(omit)}}"
        arguments: "{{item.arguments | default(omit)}}"
      loop: "{{lookup('vars', application)[lookup('vars', 'application')]}}"
      when: not app_vars.failed
```
Example Vars file with multiple installs:
thycotic.yml
``` yaml
---
# vars file for thycotic install
thycotic:
  #Thycotic Agent
  - name: 'ThycoticAgent'
    path: install\Thycotic\{{ansible_architecture}}\ThycoticAgent_x{{ansible_architecture2.split("_")[-1].split("x")[-1]}}.msi
    creates_path: 'C:\Program Files\Thycotic\Agents\Agent\Thycotic.Agent.User.exe'
    creates_version: 11.1.1156.18035
    arguments:
    - REBOOT=ReallySuppress
    - AMSURL=https://thycotic.contoso.com/TMS/
    - INSTALLCODE=SECRET'
  #Thycotic Application Control Agent
  - name: 'Thycotic_ApplicationControlAgent'
    path: install\Thycotic\{{ansible_architecture}}\Thycotic_ApplicationControlAgent_x{{ansible_architecture2.split("_")[-1].split("x")[-1]}}.msi
    creates_path: 'C:\Program Files\Thycotic\Agents\ApplicationControl\ArelliaACSvc.exe'
    creates_version: 11.1.1157.12596
    arguments:
    - REBOOT=ReallySuppress
  #Thycotic Local Security Agent
  - name: 'Thycotic_LocalSecurityAgent'
    path: install\Thycotic\{{ansible_architecture}}\Thycotic_LocalSecurityAgent_x{{ansible_architecture2.split("_")[-1].split("x")[-1]}}.msi
    creates_path: 'C:\Program Files\Thycotic\Agents\LocalSecurity\Arellia.Agent.LocalSecurity.dll'
    creates_version: 11.1.1103.52918
    arguments:
    - REBOOT=ReallySuppress
```

### Expected results

Each Thycotic msi to be installed via win_package in index order, regardless if the `installed_applications` list is defined by Survey, Extra Variables in the Template, Environment Variables from cli, or listed manually in the playbook. We can see the application.path is a UNC path to a file server, and the path templates to the correct architecture for the target host.

Debug AWX Extra Variables play:
Successful:
``` json
{
    "install_applications": [
        "thycotic",
        "dameware"
    ],
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}
```

Example debug msg for ThycoticAgent (msg.path is our expected value, file server path is prepended later in win_package):
``` json
{
    "msg": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\64-bit\\ThycoticAgent_x64.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\64-bit\\ThycoticAgent_x64.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    }
}
```

Example successful ThycoticAgent install, we see invocation.module_args.path is our expected value:
``` json
{
    "changed": false,
    "invocation": {
        "module_args": {
            "force_basic_auth": false,
            "url_username": null,
            "client_cert_password": null,
            "password": null,
            "creates_version": "11.1.1156.18035",
            "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
            "use_default_credential": false,
            "validate_certs": true,
            "proxy_password": null,
            "log_path": null,
            "wait_for_children": false,
            "username": null,
            "headers": null,
            "use_proxy": true,
            "proxy_url": null,
            "provider": "auto",
            "maximum_redirection": 50,
            "url_method": null,
            "url_password": null,
            "proxy_username": null,
            "product_id": null,
            "expected_return_code": [
                0,
                3010
            ],
            "proxy_use_default_credential": false,
            "follow_redirects": "safe",
            "url_timeout": 30,
            "chdir": null,
            "arguments": [
                "REBOOT=ReallySuppress",
                "AMSURL=https://thycotic.contoso.com/TMS/",
                "INSTALLCODE=SECRET'"
            ],
            "state": "present",
            "http_agent": "ansible-httpget",
            "path": "\\\\fileserver.contoso.com\\install\\Thycotic\\64-bit\\ThycoticAgent_x64.msi",
            "client_cert": null,
            "creates_service": null
        }
    },
    "reboot_required": false,
    "rc": 0,
    "_ansible_no_log": false,
    "item": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\64-bit\\ThycoticAgent_x64.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    }
}
```

### Actual results

When passing a list from a Survey, single or multiple values, the play fails during the win_package loop due to item.path containing invalid characters. 

Debug AWX Extra Variables play:
Successful?:
``` json
{
    "install_applications": [
        "thycotic",
        "dameware"
    ],
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}
```

Example debug msg for ThycoticAgent (msg.path unexpectedly has not been templated by jinja2):
``` json
{
    "msg": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    }
}
```
Example failed ThycoticAgent install, we see an error about illegal characters in path, which makes sense given that our debug output showed our jinja2 template variables didn't get translated:
``` json
{
    "exception": "Illegal characters in path.\nAt line:1407 char:19\r\n+         if (-not (Test-Path -LiteralPath $path)) {\r\n+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n    + CategoryInfo          : InvalidArgument: (\\\\fileserver.contoso.com...(\"x\")[-1]}}.msi:String) [Test-Path], ArgumentException\n    + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.TestPathCommand\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1407\r\n\r\nSystem.ArgumentException: Illegal characters in path.\r\n   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)\r\n   at System.IO.Path.GetFileName(String path)\r\n   at System.Management.Automation.Utils.IsReservedDeviceName(String destinationPath)\r\n   at System.Management.Automation.Utils.NativeItemExists(String path, Boolean& isDirectory, Exception& exception)\r\n   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(String path, ErrorRecord& error)",
    "msg": "Unhandled exception while executing module: Illegal characters in path.",
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "name": "ThycoticAgent",
        "path": "install\\Thycotic\\{{ansible_architecture}}\\ThycoticAgent_x{{ansible_architecture2.split(\"_\")[-1].split(\"x\")[-1]}}.msi",
        "creates_path": "C:\\Program Files\\Thycotic\\Agents\\Agent\\Thycotic.Agent.User.exe",
        "creates_version": "11.1.1156.18035",
        "arguments": [
            "REBOOT=ReallySuppress",
            "AMSURL=https://thycotic.contoso.com/TMS/",
            "INSTALLCODE=SECRET'"
        ]
    }
}
```

### Additional information

Regarding changes made to the docker image, I have installed a handful requisite pip packages for things such as pypsrp, as well as installed powershell 7 (since I'm more of a powershell guy than a python guy, working on my first python/ansible module though!). I have also performed general updates to packages, but not necessarily to the venv for Ansible/AWX.

Other additional info:

`install_applications` from both the successful and failed runs from AWX appear to be sanitized lists (no \n\r characters, e.g.), and both appear in the Details panel Extra Variables as:
``` yaml
install_applications:
  - dameware
  - thycotic
```
