### ISSUE TITLE
Python module requests fails to import

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#11009]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Hi,

I am migrating from AWX 15.0.1 to 19.3.0 and experiencing some module related issues. Python module requests fails to import.

`k3s kubectl exec -i -t -n awx awx-59ff55b5b-h5gwp --container awx-ee -- /bin/bash`

awx-ee contains requests 2.22.0 but sudo is not possible so can't uninstall and reinstall modules.

Command `sudo -i` asks for awx password. 

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.12.0.dev0

### Operating system

Centos

### Steps to reproduce

```
- name: Export virtual machine facts
  community.vmware.vmware_guest_info:
    hostname: "{{ hostname }}"
    username: '{{ domain_user }}'
    password: "{{ domain_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    schema: vsphere
    name: VM01
  register: virtualmachine_facts
```

### Expected results

I expect the modules to work in AWX.

### Actual results

```
"exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_community.vmware.vmware_guest_info_payload_suy3w41g/ansible_community.vmware.vmware_guest_info_payload.zip/ansible_collections/community/vmware/plugins/module_utils/vmware.py\", line 26, in <module>\n    import requests\nModuleNotFoundError: No module named 'requests'\n",
  "msg": "Failed to import the required Python library (requests) on automation-job-35-75jhk's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",
  
```
