### ISSUE TITLE
Job completion status never updates in output window, however stdout does update.

### ISSUE THREAD

**Issue by sdigit** [ansible/awx#11186]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When running a playbook (via workflow or plain job template) the output from stdout comes through fine, however when the job finishes, the completion status is never reflected (the green square keeps flashing, elapsed time doesn't update, and the stdout never becomes searchable)

However, when running a project update, inventory update, or a workflow that does only project/inventory updates, completion is reflected in the UI on time as expected.

Additionally, if the playbook is very simple and runs very quickly (for example, one that just uses debug to spit out facts and runs on only one host), it will sometimes succeed and update the output normally.

I noticed this in console, in case it's relevant:

![image](https://user-images.githubusercontent.com/5579349/135668381-833c6125-648b-4cc1-a594-b208df19ea9d.png)

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

yes

### Ansible version

whatever ships with AWX 19.3.0 by default

### Operating system

Google Container-optimized OS

### Web browser

Google Chrome, Firefox

### Steps to reproduce

Create a job template that launches a playbook that takes a minute or so to complete
Launch the playbook
Observe that stdout streams just fine, however when the job completes, it never indicates that fact.

### Expected results

Completion status to update (the box to go green)

### Actual results

Completion status never updates (the green box keeps flashing)
Periodic websocket messages in console

### Additional information

Instead of the bundled postgres, I am using Google Cloud SQL.
I'm running on GKE, with an HTTP load balancer in front of AWX via Ingress.
AWX is configured as follows:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  ingress_type: ingress
  ingress_path: /*
  ingress_tls_secret: awx-testing-domain-net-tls
  ingress_annotations: |
    kubernetes.io/ingress.global-static-ip-name: testing-k8s-awx-lb
    networking.gke.io/v1beta1.FrontendConfig: "tls-modern"
  hostname: awx.testing.domain.net
  admin_user: awxadmin
  admin_email: automation@domain.com
  admin_password_secret: awx-admin
  create_preload_data: false
  garbage_collect_secrets: true
  secret_key_secret: awx-testing-secret-key
  postgres_configuration_secret: awx-db-creds
  bundle_cacert_secret: cloudsql-cacert
  extra_settings:
    - setting: REMOTE_HOST_HEADERS
      value: ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR', 'REMOTE_HOST']
  service_account_annotations: |
    iam.gke.io/gcp-service-account=ansible-k8s@project-id.iam.gserviceaccount.com
  ee_images: []
  web_resource_requirements:
    requests:
      cpu: 1200m
      memory: 2Gi
    limits:
      cpu: 1200m
      memory: 2Gi
  task_resource_requirements:
    requests:
      cpu: 1200m
      memory: 1Gi
    limits:
      cpu: 1200m
      memory: 1Gi
  ee_resource_requirements:
    requests:
      cpu: 750m
      memory: 250Mi
    limits:
      cpu: 750m
      memory: 250Mi
```
