### ISSUE TITLE
Can not create a copy of an inventory in a different organization using the same inventory name

### ISSUE THREAD

**Issue by casty8** [ansible/awx#11266]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I'm working on an automation that is executed from Ansible Tower for migrating all the elements of the Default organization to a new created organization. When trying to migrate the inventories, using the awx.awx.inventory module with the copy_from attribute (where I specify the ID of the inventory I want to copy), the automation fails because it is not possible to copy the inventory in the new organization, using the same inventory name.

### AWX version

19.4.0

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

Use the `awx.awx.inventory` module with the following parameters:

- `name`: the name of an inventory that already exists
- `organization`: a new organization that has been created and where we want to create the new inventory (copy_from one that exists on the Default organization)
- `state`: present
- `copy_from`: the ID of the inventory we want to copy from the Default organization

This is the code used, where `inventory_info` is a variable containing all the parameters of the inventory we want to migrate (the info has been requested using a query to the API).
```
- name: Create inventories inside the organization
  awx.awx.inventory:
    name: "{{ inventory_info.name }}"
    organization: "ORG_{{ team_name_create_organization }}"
    state: present
    copy_from: "{{ inventory_info.id }}"
    tower_password: '{{ api_tower_password }}'
    tower_username: '{{ api_tower_user }}'
    tower_host: '{{ api_tower_url }}' 
```

### Expected results

A new inventory will be created in the new organization using the same inventory name. This inventory will be a copy of the one we are specifying on `copy_from`.

### Actual results

The new inventory is not created because the module fails complaining about you can not use the same name for the new inventory:

```
Unable to create inventory INV_I-SSO-ES-TS-MONIT_PREVIOUS: The original object is already named INV_I-SSO-ES-TS-MONIT_PREVIOUS, a copy from it cannot have the same name
```

**Comment by ffirg** [comment]
So the module doesn't allow this directly.

The workaround is to copy to a new name, rename and then delete the copy:

```
---
- hosts: localhost

  tasks:

    - name: Copy Inventory
      awx.awx.inventory:
        name: "New Proxy Test"
        copy_from: "Proxy Test"
        organization: NewOrg
        state: present
        controller_config_file: ./tower_config.file
        validate_certs: no

    - name: Rename New Inventory
      awx.awx.inventory:
        name: "Proxy Test"
        copy_from: "New Proxy Test"
        organization: NewOrg
        state: present
        controller_config_file: ./tower_config.file
        validate_certs: no

    - name: Delete Inventory Copy
      awx.awx.inventory:
        name: "New Proxy Test"
        organization: NewOrg
        state: absent
        controller_config_file: ./tower_config.file
        validate_certs: no
```

If you want to raise this issue further, then please raise it direct with the author via the collection git repo.

Closing this issue here as it's not an awx problem.
