### ISSUE TITLE
set_stats seams to only work when set on first playbook of workflow

### ISSUE THREAD

**Issue by tkontogi** [ansible/awx#11333]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Workflow of three playbooks
Stats set on first one are available to the end
Stats set on second one, are not available to the third one.

playbook 2 stanza:
 
```
      - name: Set Stats
        set_stats:
         data:
          wf_phpIPAM_dns_server1: "{{ phpIPAM_dns_server1 }}"
          wf_phpIPAM_dns_server2: "{{ phpIPAM_dns_server2 }}"
```

Playbook 3 error:

`"The task includes an option with an undefined variable. The error was: 'wf_phpIPAM_dns_server1' is undefined`

aggregate and per_host are on default.
phpIPAM_dns_server1 & server2 are enumerated and wf_phpIPAM_dns_server1 & server2 are evaluated in playbook 2.

### AWX version

3.6.3

### Installation method

minishift

### Modifications

no

### Ansible version

2.9.1

### Operating system

RHEL8

### Web browser

Firefox

### Steps to reproduce

as above

### Expected results

variable is defined

### Actual results

variable undefined

### Additional information

Maybe I got the docs wrong???
