### ISSUE TITLE
AWX Tower not detecting role in colection

### ISSUE THREAD

**Issue by jopaha** [ansible/awx#11478]
I´ve got a collection in my ansible repository installed. Path is

```
playbooks/galaxy_collections/ansible_collections/my_collection/common/
```

My ansible.cfg looks like this:

```
[defaults]
roles_path = ./playbooks/galaxy_roles:./playbooks/roles
collections_path = ./playbooks/galaxy_collections/
inventory = inventory/hosts.yml
remote_user = test
display_skipped_hosts = false
```

Now, when I run my playbook on command line:

```
- hosts: all
  name: Common tasks
  become: true
  collections:
    - my_collection.common
  gather_facts: yes
  tasks:
    - import_role:
        name: motd
```
it works like a charm. If I run the very same playbook within AWX in the same project I was using on commandline, AWX gives me the following error:

```
ERROR! the role 'motd' was not found in my_collection.common:ansible.legacy:/runner/project/playbooks/roles:/runner/requirements_roles:/runner/project/playbooks/galaxy_roles:/runner/project/playbooks/roles:/runner/project/playbooks/galaxy_roles:/runner/project/playbooks/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project/playbooks
The error appears to be in '/runner/project/playbooks/common.yml': line 9, column 15, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - import_role:
        name: motd
              ^ here
```

Why does AWX not find the role in the collection but when I run this on CLI it works fine?
Yes, the ansible.cfg does get respected. I already checked that.
