### ISSUE TITLE
launchjob Variables braces does not take effect

### ISSUE THREAD

**Issue by hulongjiang1** [ansible/awx#11497]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

when i launch job, job's Variables as follows：
{
  "myVar": "{{ansible_nodename}} is my name"
}
The result I expect is: hostname is my name。
 But I have the result of an environment: {{ansible_nodename}} is my name.

Why the braces are parsed into strings and output as they are.
I used ansible-playbook and the results were correct. 
Just put it in an awx environment and it will go wrong.

### AWX version

17.1.0

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.9.18

### Steps to reproduce

main.yml
```
---
- hosts: all
  
  tasks:
  - name: "replace"
    lineinfile:
      path: "{{ fileName }}"
      regexp: "{{source}}"
      line: "{{target}} is my name"
```

ansible-playbook command:
`ansible-playbook -i inventory.ini main.yml -e 'fileName=/tmp/abc.txt source=abc target="{{ansible_nodename}}"`   
this command execute is correct.  but in one Awx is wrong. other's awx is correct.

### Expected results

myhostname is my name.

### Actual results

{{ansible_nodename}} is my name
