### ISSUE TITLE
Custom AWX Execution Environment fails when using 'proxmoxer' module

### ISSUE THREAD

**Issue by FireDrunk** [ansible/awx#11495]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I've been trying to build my own AWX Execution Environment image for the past few days, to accomodate the use of the `community.general.proxmoxer` module.

At first I've tried using the basic guide that uses `ansible-builder build` to build a custom image using the following settings:

```yaml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-devel'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
```
requirements.yml
```yaml
collections:
  - community.general
```
requirements.txt
```ini
proxmoxer >= 1.2.0
requests >= 2.26.0
```
This image builds perfectly, an when testing this image locally with the `ansible-runner --container-isolation` the module works fine.

When pushing this image to my private registry, and using it in AWX, it fails with this error:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/misc/proxmox.py#L530
coming from failing to import this module:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/cloud/misc/proxmox.py#L355

I've tried debugging this issue with the following steps:

- Add a sleep in the playbook
- Exec into the automation-job-<id> container using kubectl
- verified the existence of the collection, proxmoxer module, and the requests module in the container -> All there:
```shell
bash-4.4# ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.2.0
```
- Verifid that `pip list` sees the module -> it does:
```shell
bash-4.4# pip list | grep proxmoxer
proxmoxer          1.2.0
```
- Verified that a custom python script can import the proxmoxer module -> it can
```shell
bash-4.4# python3
Python 3.8.8 (default, Aug 25 2021, 16:13:02)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import proxmoxer
>>>
```
My test playbook:
```yaml
---
- name: Clone VM
  hosts: localhost

  tasks:
      - name: Sleep 300
      ansible.builtin.shell:
        cmd: sleep 300

    - name: Clone existing VM
      community.general.proxmox_kvm:
        api_user: automation@pam
        api_password: "{{ password }}"
        api_host: <address of pve server>
        clone: debian-template
        name: "{{ vm_name }}"
        node: pve
        storage: group1
        full: yes
        format: raw
        timeout: 300
```
It seems like AWX is either overriding the Python Interpreter, or modifies the Python Module include directory in some way.

To investigate I've been trying to find out if there are any environment variables 'odd' during the run, but none stand out:

Processes:
```shell
bash-4.4# ps -eaf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 10:44 ?        00:00:00 /usr/local/bin/dumb-init -- ansible-runner worker --private-data-dir=/runner
root        19     1  0 10:44 ?        00:00:00 /usr/bin/python3 /usr/local/bin/ansible-runner worker --private-data-dir=/runner
root        21    19 15 10:44 pts/0    00:00:25 /usr/bin/python3 /usr/local/bin/ansible-playbook -u root -i /runner/inventory/hosts -e @/runner/env/extravars create-vm.yml
root        79    21  0 10:44 pts/0    00:00:00 /usr/bin/python3 /usr/local/bin/ansible-playbook -u root -i /runner/inventory/hosts -e @/runner/env/extravars create-vm.yml
root        90    79  0 10:44 pts/0    00:00:00 /bin/sh -c /usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1640861065.851268-79-39671140540678/AnsiballZ_command.py && sleep 0
root        91    90  0 10:44 pts/0    00:00:00 /usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1640861065.851268-79-39671140540678/AnsiballZ_command.py
root        92    91  0 10:44 pts/0    00:00:00 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 300
root        93     0  0 10:44 pts/1    00:00:00 bash
root       115    93  0 10:47 pts/1    00:00:00 ps -eaf
```

PID: 19
```shell
bash-4.4# cat /proc/19/environ | tr '\0' '\n'
AWX_SERVER_SERVICE_PORT_80_TCP_PORT=80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT=tcp://10.101.24.222:8443
AWX_SERVER_SERVICE_SERVICE_PORT=80
HOSTNAME=automation-job-147-8975f
KUBERNETES_PORT_443_TCP_PROTO=tcp
AWX_SERVER_SERVICE_PORT_80_TCP_ADDR=10.107.88.215
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
AWX_SERVER_SERVICE_SERVICE_HOST=10.107.88.215
AWX_SERVER_SERVICE_SERVICE_PORT_HTTP=80
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/runner
HOME=/home/runner
AWX_SERVER_SERVICE_PORT_80_TCP_PROTO=tcp
AWX_SERVER_SERVICE_PORT=tcp://10.107.88.215:80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PORT=8443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP=tcp://10.101.24.222:8443
AWX_SERVER_SERVICE_PORT_80_TCP=tcp://10.107.88.215:80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT_HTTPS=8443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT=8443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PROTO=tcp
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_HOST=10.101.24.222
SHLVL=0
KUBERNETES_SERVICE_PORT=443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_ADDR=10.101.24.222
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.96.0.1
```

PID 21:
```shell
bash-4.4# cat /proc/21/environ | tr '\0' '\n'
AWX_SERVER_SERVICE_PORT_80_TCP_PORT=80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT=tcp://10.101.24.222:8443
AWX_SERVER_SERVICE_SERVICE_PORT=80
HOSTNAME=automation-job-147-8975f
KUBERNETES_PORT_443_TCP_PROTO=tcp
AWX_SERVER_SERVICE_PORT_80_TCP_ADDR=10.107.88.215
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
AWX_SERVER_SERVICE_SERVICE_HOST=10.107.88.215
AWX_SERVER_SERVICE_SERVICE_PORT_HTTP=80
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/runner
HOME=/home/runner
AWX_SERVER_SERVICE_PORT_80_TCP_PROTO=tcp
AWX_SERVER_SERVICE_PORT=tcp://10.107.88.215:80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PORT=8443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP=tcp://10.101.24.222:8443
AWX_SERVER_SERVICE_PORT_80_TCP=tcp://10.107.88.215:80
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT_HTTPS=8443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_PORT=8443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_PROTO=tcp
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_SERVICE_HOST=10.101.24.222
SHLVL=0
KUBERNETES_SERVICE_PORT=443
AWX_OPERATOR_CONTROLLER_MANAGER_METRICS_SERVICE_PORT_8443_TCP_ADDR=10.101.24.222
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.96.0.1
LC_CTYPE=C.UTF-8
ANSIBLE_FORCE_COLOR=True
ANSIBLE_HOST_KEY_CHECKING=False
ANSIBLE_INVENTORY_UNPARSED_FAILED=True
ANSIBLE_PARAMIKO_RECORD_HOST_KEYS=False
AWX_PRIVATE_DATA_DIR=/tmp/awx_147_4mpatbra
JOB_ID=147
INVENTORY_ID=3
PROJECT_REVISION=4a092666c06044fcefd0c8cec299f3d3c0b3f5a7
ANSIBLE_RETRY_FILES_ENABLED=False
MAX_EVENT_RES=700000
AWX_HOST=https://*snip*:8443/
ANSIBLE_SSH_CONTROL_PATH_DIR=/runner/cp
ANSIBLE_COLLECTIONS_PATHS=/runner/requirements_collections:~/.ansible/collections:/usr/share/ansible/collections
ANSIBLE_ROLES_PATH=/runner/requirements_roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
PYTHONPATH=:/usr/local/lib/python3.8/site-packages/ansible_runner/config/../callbacks
ANSIBLE_CALLBACK_PLUGINS=/usr/local/lib/python3.8/site-packages/ansible_runner/config/../callbacks
ANSIBLE_STDOUT_CALLBACK=awx_display
AWX_ISOLATED_DATA_DIR=/runner/artifacts/147
RUNNER_OMIT_EVENTS=False
RUNNER_ONLY_FAILED_EVENTS=False
```

The only thing that stood out was the 'PYTHONPATH', which adds extra module include directories, but to my knowledge doesn't override the normal site-packages directory include(s).

Does anyone understand what's going on?

### AWX version

19.5.0

### Installation method

kubernetes

### Modifications

yes

### Ansible version

devel

### Operating system

n/a

### Web browser

Firefox

### Steps to reproduce

- Use awx-operator 19.5.0
- Create custom EE which includes:
-- Collection: community.general
-- Python modules: proxmoxer & requests
- Add EE to AWX
- Add Job using yml:
```yaml
---
- name: Clone VM
  hosts: localhost

  tasks:
    - name: Sleep 300
      ansible.builtin.shell:
        cmd: sleep 300

    - name: Clone existing VM
      community.general.proxmox_kvm:
        api_user: automation@pam
        api_password: "{{ password }}"
        api_host: '<hostname>'
        clone: debian-template
        name: "{{ vm_name }}"
        node: pve
        storage: group1
        full: yes
        format: raw
        timeout: 300
```
- Execute the job, (after 5 minutes) it will fail with the error "Proxmoxer is required for this module"

### Expected results

The module works.

### Actual results

Import error

### Additional information

Only modification is the custom Execution Environment image.
I've tried building it with the normal `ansible-runner build` and forking the official `awx-ee` image, and including the requirements in that repository, and using the resulting image build with `tox`.

Neither works.
