### ISSUE TITLE
awx.awx.schedule_rrule generates invalid string which awx.awx.schedule rejects

### ISSUE THREAD

**Issue by AndreiBanaruTakeda** [ansible/awx#11499]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

The _awx.awx.schedule_rrule_ module while called:
`ansible localhost -m debug -a "msg={{ query('awx.awx.schedule_rrule', 'week', timezone='UTC', start_date='2021-01-01 07:00:00') }}"`

Returns:
`localhost | SUCCESS => {
    "msg": "DTSTART;TZID=UTC:20210101T070000 FREQ=WEEKLY;INTERVAL=1"
}`

Which is invalid when appended to _awx.awx.schedule_:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to update schedule Reset the filesystem ACLs in /var/log, see response", "response": {"json": {"rrule": ["RRULE required in rrule."]}, "status_code": 400}}`

Noticed in the documentation that the string, acceptable for _awx.awx.schedule_ should actually be:
`DTSTART;TZID=UTC:20210101T070000 RRULE:FREQ=WEEKLY;INTERVAL=1`

### AWX version

19.5.0

### Installation method

minikube

### Modifications

no

### Ansible version

4.10.0

### Operating system

Red Hat Enterprise Linux release 8.4 (Ootpa)

### Steps to reproduce

Generate RRULE:
```
ansible localhost -m debug -a "msg={{ query('awx.awx.schedule_rrule', 'week', timezone='UTC', start_date='2021-01-01 07:00:00') }}"

localhost | SUCCESS => {
    "msg": "DTSTART;TZID=UTC:20210101T070000 FREQ=WEEKLY;INTERVAL=1"
}
```

Create a task based on the output:
```
- name: Build the schedule for 'Reset filesystem ACLs for /var/log' template
  schedule:
    name: "Reset the filesystem ACLs in /var/log"
    state: present
    unified_job_template: "Reset filesystem ACLs for /var/log"
    rrule: "DTSTART;TZID=UTC:20210101T070000 FREQ=DAILY;INTERVAL=1"
```

Task fails with:
```
TASK [awx-config : Build the schedule for 'Reset filesystem ACLs for /var/log' template] *********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to update schedule Reset the filesystem ACLs in /var/log, see response", "response": {"json": {"rrule": ["RRULE required in rrule."]}, "status_code": 400}}
```

### Expected results

Task to be successful.

### Actual results

The task fails since "**RRULE:**" string is missing from rrule.
