### ISSUE TITLE
Add scheduling of projects/inventory to the awx.awx collection.

### ISSUE THREAD

**Issue by hyberdk** [ansible/awx#11510]
##### ISSUE TYPE
 - Feature Idea / missing functionality

##### SUMMARY
There seems to be missing feature parity between what can be done in the AWX GUI and via the awx.awx collection regarding to scheduling updates (sync) on projects and inventory..

I would like to create a schedule to update a project and inventory. I can do it like this from the GUI
![image](https://user-images.githubusercontent.com/3530739/148555446-9e23c1f2-0727-4bfc-a273-4ccb400131f1.png)

but it seems like there is no option to do this from either the awx.awx.shedule, awx.awx.project or awx.awx.project_update modules. Its the same problem with inventories, there is currently no way to create a schedule from the awx.awx collection.

Im not sure if it should be put into the awx.awx.schedule, if it should be included into the project_update module or if there should be a new awx.awx.project_update_schedule module..

Let me know if you need more information about this..

thanks.
Esben

**Comment by sean-m-sullivan** [comment]
So schedules are never part of the object as they their own objects inside the AWX API, 
However for Schedule, Using Job Templates/Inventory Sources/Projects they are all Unified job templates. the same way they work to be a source for Workflows.

The code to schedule a project update or inventory source update is as follows
```
    - name: Build a schedule with a job template's name in two orgs
      awx.awx.schedule:
        name: Project Scheduled
        state: present
        unified_job_template: Demo Project
        rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"

    - name: Build a schedule with a job template's name in two orgs
      awx.awx.schedule:
        name: Inventory Scheduled
        state: present
        unified_job_template: Inventory source
        rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
```
