### ISSUE TITLE
Async and ansible_connection=local fails using Execution Environments

### ISSUE THREAD

**Issue by lshake** [ansible/awx#11521]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

When using RH AAP 2.1 / AWX and Ansible Navigator, with asynchronous tasks and ansible_connection=local, the async_status task fails with the error "could not find job".   This does not happen when using ansible-playbook or ansible-navigator with execution environments set to false.  

The verbose task outputs suggest that the async / poll mode and the async_status module are using different values for ansible_async_dir :

```
TASK [kick off async task] *****************************************************
task path: /home/lshakesp/projects/ansible/playbooks/test_async/test_async.yml:11
changed: [myhost] => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "ansible_job_id": "634772753324.47", "changed": true, "finished": 0, "results_file": "/home/runner/.ansible_async/634772753324.47", "started": 1}

TASK [check task status] *******************************************************
task path: /home/lshakesp/projects/ansible/playbooks/test_async/test_async.yml:19
fatal: [myhost]: FAILED! => {"ansible_job_id": "634772753324.47", "attempts": 1, "changed": false, "finished": 1, "msg": "could not find job", "results_file": "/root/.ansible_async/634772753324.47", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

Setting the variable ansible_async_dir to the same value for both the initial task and the async_status task, fixes the problem, but should not be necessary.   

### AWX version

latest / Ansible Automation Platform Controller 4.1.0 

### Installation method

docker on linux

### Modifications

yes

### Ansible version

registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest

### Operating system

RHEL

### Web browser

Safari

### Steps to reproduce

Playbook : 
```
---
- name: Test Async Tasks
  hosts: all
  gather_facts: false
  become: false

  vars:
    task_time: 20s

  tasks:
    - name: kick off async task
      ansible.builtin.command: "sleep {{ task_time }}"
      register: task_result
      async: 120
      poll: 0

    - name: check task status
      ansible.builtin.async_status:
        jid: "{{ task_result.ansible_job_id }}"
      register: async_poll_results
      retries: 60
      delay: 2
      until: async_poll_results.finished
```

Inventory :
```
myhost ansible_connection=local
```

### Expected results

Playbook runs to completion, multiple status checks are performed.

### Actual results

Playbook fails with the error : "could not find job"

### Additional information

This is an issue with AAP2.1 and Ansible Navigator 1.1.0 (installed from AAP2.1 Repos, rpm ansible-navigator-1.1.0-1.el8ap.noarch).   Maybe an issue with ansible-runner as a common component.   This is *NOT* an issue with ansible-playbook from AAP2.1 [core 2.12.0] or with ansible-navigator when not using EE's.   

Advised to open issue here by @ffirg
