### ISSUE TITLE
Inventory source from project does not work anymore in 19.4.0 or 19.5.0

### ISSUE THREAD

**Issue by maveleo** [ansible/awx#11542]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Not possible to create an inventory sourced from a git project. 

### AWX version

19.4.0

### Installation method

kubernetes

### Modifications

no

### Operating system

RHEL 8

### Web browser

Chrome

### Steps to reproduce

Create a project that points to a GIT repository with the inventory definition
Sync the project
Create an inventory with a source that references the above project
Select the inventory file from the drop down menu
![image](https://user-images.githubusercontent.com/3233558/149505221-4e9109fe-bc29-4ec9-94f8-b39175f5447b.png)
Click **Sync**

### Expected results

Inventory source sync succeed, inventory created with groups and hosts

### Actual results

Inventory source sync has errors and the inventory is not created/updated

```
ansible-inventory [core 2.11.3.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
[WARNING]: Ignoring invalid path provided to plugin path:
'/runner/project/integration' is not a directory
setting up inventory plugins
host_list declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
auto declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /runner/project/integration/hosts as it did not pass its verify_file() method
[WARNING]: Unable to parse /runner/project/integration/hosts as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

### Additional information

I have noticed that the worker pod being created does not have any volume references to the projects directory. 
Also the custom ansible.cfg being defined for the ee_environment does not get loaded in the worker node.

``` yaml
containers:
    - name: worker
      image: my_satellite/ansible/awx-ee:0.6.0
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources: {}
      volumeMounts:
        - name: kube-api-access-k9m9b
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      stdin: true
      stdinOnce: true
```
