### ISSUE TITLE
RFE: refer to job information in a playbook

### ISSUE THREAD

**Issue by sugitk** [ansible/awx#11645]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I would like to refer to the variables from the playbook that is launched by a JT or a WFJT.  For example when a controller launch a JT, it will issue a new job ID and we can access the information at /api/v2/jobs/<JOB_ID>/ that includes below JSON.

```
{
    "id": 63,
    "type": "job",
    "url": "/api/v2/jobs/63/",
    "related": {
...
},
    "summary_fields": {
        "organization": {
            "id": 1,
...
    "description": "",
    "job_type": "run",
    "inventory": 1,
    "project": 6,
    "playbook": "hello_world.yml",
...
   "job_env": {
        "LAUNCHED_BY_RUNNER": "1",
        "ANSIBLE_UNSAFE_WRITES": "1",
...
}
```

A customer requests that they want to refer to these information from their playbook as `"summary_fields"."inventory"."name"` through some lookup feature or something for example;

```
- name: to know the job environment
  debug:
    msg: "do something using an actual module"
  when:
    - lookup("controller", "summary_fields.inventory.name") == "Demo Inventory"
```

This feature can protect a disaster when launched a job template with unintentional inventory from the playbook side.

**Comment by benjdudas** [comment]
@sugitk You should be able to do this now using the controller_api lookup plugin in the ansible.controller collection.
https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller?version=4.1.0

For Example:
```yaml
---
- hosts: all
  gather_facts: false

  tasks:
    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"

    - set_fact:
        job_api: "{{ lookup('ansible.controller.controller_api', 'jobs/{{ job_id }}', verify_ssl=False) }}"

    - debug:
        var: job_api.summary_fields.inventory.name
```
Controller will add the JOB_ID to the job env which you can use with the controler_api plugin to retrieve the full jobs api and then parse through that for the information needed.
