### ISSUE TITLE
License Module clarification of manifest parameter

### ISSUE THREAD

**Issue by dkolepp** [ansible/awx#11851]
https://github.com/ansible/awx/blob/c6209df1e0c6247817747a17b01f3b65f756fdb1/awx_collection/plugins/modules/license.py#L25

The license module documentation does not make it clear that the manifest must exist on the remote machine.  Some note to indicate that the manifest must exist already on the host, would be beneficial.

Most other ansible modules assume that the files exist on the controller, and are transferred (if needed) to the remote machine.  

At a minimum, suggest updating this line to something like:

```
the path to a Red Hat subscription manifest file (a .zip file), which exists on the remote host.
``

**Comment by john-westcott-iv** [comment]
It does not necessarily have to be on the remote machine; the file has to exist wherever the module is running from. For example, if your running ansible-playbook from host A against an inventory targeting host B and using the awx.awx.license module like:
```
- name: Install license
  awx.awx.license:
    manifest: ./manifest.zip
```

Then the file would need to exist host B. However, if you delegate the task like:
```
- name: Install license
  awx.awx.license:
    manifest: ./manifest.zip
  delegate_to: localhost
  connection: local
```
Then ansible will be running on host A and look for ./manifest.zip right next to the playbook.

Give it a try and let me know if that makes sense.

**Comment by dkolepp** [comment]
I can try this.  At a minimum, I suggest adding these two examples to the documentation, and add a better explanation of what is happening:
https://github.com/ansible/awx/blob/c6209df1e0c6247817747a17b01f3b65f756fdb1/awx_collection/plugins/modules/license.py#L39

I don't think this particular implementation is intuitive, so at the minimum, provide clear examples of these two use cases.

The use of "delegate" here seems awkward (or at least, very nuanced).  A (what feels like) more Ansible pattern for this is:

```yaml
# This means the license comes from the host where "ansible-playbook" runs,
# like the copy module.  The licenses is then transferred/applied to the target machine
- name: Install license
  awx.awx.license:
    manifest: ./manifest.zip
```
and
```yaml
# This means the license is located on the target host 
# (like the copy module's use of `remote_src`).  The license is then applied to the target machine
- name: Install license
  awx.awx.license:
    manifest: ./manifest.zip
    remote_manifest: yes
```
