### ISSUE TITLE
Worker failed to run task awx.main.tasks.system.purge_old_stdout_files

### ISSUE THREAD

**Issue by yw5vruox7dr** [ansible/awx#11903]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

We see some errors in the container logs of the awx task container:

```
2022-03-14 17:09:00,771 ERROR    [491eb2c3cf884c52aee0b55ac9197a2e] awx.main.dispatch Worker failed to run task awx.main.tasks.system.purge_old_stdout_files(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 90, in perform_work
--
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 325, in purge_old_stdout_files
    for f in os.listdir(settings.JOBOUTPUT_ROOT):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/job_status'
```

The directory `/var/lib/awx/job_status` did not exist.
```
bash-5.1$ ls -lahZ /var/lib/awx/job_status
ls: cannot access '/var/lib/awx/job_status': No such file or directory

bash-5.1$ namei -mo /var/lib/awx
f: /var/lib/awx
 drwxr-xr-x root root /
 drwxr-xr-x root root var
 drwxr-xr-x root root lib
 drwxrwxr-x root root awx
```

### AWX version

20.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Steps to reproduce

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-int
  namespace: awx-int
spec:
  service_type: NodePort

  replicas: 2

  web_resource_requirements:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  task_resource_requirements:
    requests:
      cpu: 2000m
      memory: 8Gi
    limits:
      cpu: 2000m
      memory: 8Gi

  ee_images:
    - name: xxxxxxx
      image: xxxxxxx/container/awx-ee:latest
  ee_pull_credentials_secret: awx-int-ee-pull-credentials
  ```
  
  We imported a postgres db dump from our v15.0.1 awx instance bevor we spawned the awx instance.

### Expected results

No error is logged. Directory (/var/lib/awx/job_status) is created?

### Actual results

2022-03-14 17:09:00,771 ERROR    [491eb2c3cf884c52aee0b55ac9197a2e] awx.main.dispatch Worker failed to run task awx.main.tasks.system.purge_old_stdout_files(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/dispatch/worker/task.py", line 90, in perform_work
--
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/system.py", line 325, in purge_old_stdout_files
    for f in os.listdir(settings.JOBOUTPUT_ROOT):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/job_status'

**Comment by AlanCoding** [comment]
I don't expect any adverse consequences from this, but it would be valid to check for existence of the folder first.

**Comment by m-krs** [comment]
Not ideal solution, but works for me
```yaml
  task_args: []
  task_command:
    - /usr/bin/bash
    - -c
    - mkdir /var/lib/awx/job_status && chown `id -u` /var/lib/awx/job_status && exec /usr/bin/launch_awx_task.sh
```
