### ISSUE TITLE
awx.awx.group option preserve hosts fails when there are no hosts.

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#11954]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

when using awx.awx.groups the preserve hosts/groups options fails if there are no groups/hosts.

### AWX version

19.4.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

minikube

### Modifications

no

### Steps to reproduce

```
    - name: Add host to temporary group for new vms
      awx.awx.group:
        name: new_vms
        inventory: "Temporary Inventory"
        hosts:
          - "{{ name }}"
        validate_certs: false
        preserve_existing_hosts: True
      when:
        - use_aap_inventory
        - vm is succeeded
```

### Expected results

It runs and adds the host to the empty group

### Actual results

```
TypeError: 'NoneType' object is not subscriptabl
```

### Additional information

Because [This line](https://github.com/ansible/awx/blob/593eebf062cd1f73c117502e0491f3c8532695a3/awx_collection/plugins/modules/group.py#L174) returns NoneType when there are no hosts in the group.

module needs to be updated to fix this issue.

**Comment by ikke-t** [comment]
Thanks for creating the issue. I verified now that the task works if I have the group and an existing host in the group.

So some error while doing it for a totally new group.

**Comment by ikke-t** [comment]
it works if the group is there but empty

**Comment by ikke-t** [comment]
so it fails only in the first ever run: there is no group.

**Comment by ikke-t** [comment]
just for reference, here are the steps after creating the vm

```
        - name: Create tower inventory
          awx.awx.inventory:
            name: "Temporary Inventory"
            description: "Temporary inventory for hosts to be created"
            organization: "Default"
            state: present
            validate_certs: false
          when:
            - use_aap_inventory
            - vm is succeeded

        - name: Add tower host
          awx.awx.host:
            name: "{{ vm_name }}"
            inventory: "Temporary Inventory"
            state: present
            validate_certs: false
            variables:
              ansible_host: "{{ vm.instance.ipv4 }}"
          when:
            - use_aap_inventory
            - vm is succeeded

        - name: Add host to temporary group for new vms
          awx.awx.group:
            name: new_vms
            inventory: "Temporary Inventory"
            hosts:
              - "{{ vm_name }}"
            validate_certs: false
            preserve_existing_hosts: True
          when:
            - use_aap_inventory
            - vm is succeeded

 ```
