### ISSUE TITLE
Can't resolve module when using collection in manual SCM

### ISSUE THREAD

**Issue by YonatanGolick** [ansible/awx#12005]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hi guys,
I have created a playbook that uses a collection from ansible galaxy, got it working great with ansible.
Now I would like to use this playbook on Ansible Tower when using Manual SCM in the project.
My home directory for the project is under /var/lib/awx/projects/test that's where I placed my playbook.
After reading the documentation I saw that I need to create a collection/requirements.yml file under the same path.
I get the following error 
`ERROR! couldn't resolve module/action 'community.general.ldap_search'. This often indicates a misspelling, missing collection, or incorrect module path.`
I did a test and used gitHub as my SCM and it worked, but there is no git or an equivalent in the organization.
Any suggestions ?  

### AWX version

3.8.5

### Select the relevant components

- [x] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Steps to reproduce

/var/lib/awx/projects/test/playbook.yaml
```
---
- hosts: localhost
  #  collections:
  #  - community.general
  tasks:
  - name: gather facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: Return all entries within the 'groups' organizational unit.
    community.general.ldap_search:
      dn: "ou=groups,dc=example,dc=com"
    register: ldap_groups
```

/var/lib/awx/projects/test/collections/requirements.yml
`- name: community.general`

### Expected results

Downloading the collection and executing the playbook.

### Actual results

```

ansible-playbook 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/bwrap_53_c19p_y9v/awx_53_r0qyozgh/tmp9_5slymc as it did not pass its verify_file() method
Parsed /tmp/bwrap_53_c19p_y9v/awx_53_r0qyozgh/tmp9_5slymc inventory source with script plugin
ERROR! couldn't resolve module/action 'community.general.ldap_search'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/tmp/bwrap_53_c19p_y9v/awx_53_r0qyozgh/project/playbook.yaml': line 9, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
      var: ansible_facts
  - name: Return all entries within the 'groups' organizational unit.
    ^ here

```
