### ISSUE TITLE
ERROR! Invalid callback for stdout specified: awx_display

### ISSUE THREAD

**Issue by anxstj** [ansible/awx#12023]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I tried to upgrade my AWX setup from 19.2.0 to 20.1.0. After the upgrade all jobs in the controlplane exit with the error `ERROR! Invalid callback for stdout specified: awx_display`. But it seems that jobs in the default queue (e.g. inventory updates) are still working.

I have a staging setup that uses the same installation method and the same image, but that is not affected. Only my production environment is affected. The main difference is that the production environment is upgraded from one version to the other and the staging environment is created from scratch if the AWX image changes.

### AWX version

20.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

yes

### Ansible version

2.11.7

### Operating system

Debian 11

### Web browser

Firefox

### Steps to reproduce

Hard to tell. The only relevant change, except the container image, was the location of the receptor socket:

docker-compose.yml:
```
       - "./receptor.conf:/etc/receptor/receptor.conf"
       - "/sys/fs/cgroup:/sys/fs/cgroup"
       - "redis_socket_1:/var/run/redis/:rw"
-      - "receptor_1:/var/run/receptor/"
       - "./containers.conf:/etc/containers/containers.conf"
       - "/usr/local/share/ca-certificates:/etc/pki/ca-trust/source/anchors:ro"
     dns_search: "anx.local"
@@ -45,7 +44,5 @@
 volumes:
   awx_db:
     name: tools_awx_db
-  receptor_1:
-    name: tools_receptor_1
   redis_socket_1:
     name: tools_redis_socket_1
```
receptor.conf:
```
 
 - control-service:
     service: control
-    filename: /var/run/receptor/receptor.sock
+    filename: /var/run/awx-receptor/receptor.sock
 
 - local-only:
 ```

The AWX 20.1.0 docker image in staging and production is the same and the same is true for the awx-ee:latest image which is pulled by the control plane execution environment. So the only other changes are the receptor socket path and the persistent database.

### Expected results

The job executes correctly.

### Actual results

```
ERROR! Invalid callback for stdout specified: awx_display
```

### Additional information

Edit: The following seems not to be related, reverting the system back to 19.2.0 shows the same errors.
~~It seems that changing the receptor socket path has caused the following errors which flood the container log.~~
```
tools_awx_1 | 2022-04-08 07:23:37,956 ERROR    [-] awx.main.consumers Request user is not authenticated to use websocket.
tools_awx_1 | 2022-04-08 07:23:37,956 ERROR    [-] awx.main.consumers Request user is not authenticated to use websocket.
tools_awx_1 | 2022-04-08 07:23:37,956 ERROR    Request user is not authenticated to use websocket.
tools_awx_1 | 2022/04/08 07:23:38 [error] 71#71: *1118 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 172.25.0.1, server: _, request: "GET /websocket/ HTTP/1.0", upstream: "http://127.0.0.1:8051/websocket/", host: "awx.example.com"
tools_awx_1 | 172.25.0.1 - - [08/Apr/2022:07:23:38 +0000] "GET /websocket/ HTTP/1.0" 101 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" "10.0.253.171
```

~~Changing the receptor socket back to the old location fixes that error, but the problem with the failing jobs persists.~~

Another observation was the receptor logs a warning when a job in the control plane fails:
```
DEBUG 2022/04/07 17:05:50 Client disconnected from control service @
WARNING 2022/04/07 17:05:50 Could not close connection: close unix /var/run/awx-receptor/receptor.sock->@: use of closed network connection
```
