### ISSUE TITLE
EE runner's inventory sync failed to parse because module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by laiweihwa** [ansible/awx#12124]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

After upgrade using operator, all inventory syncs fails due to `module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK`

```
ansible-inventory [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
redirecting (type: inventory) ansible.builtin.aws_ec2 to amazon.aws.aws_ec2
[WARNING]:  * Failed to parse /runner/inventory/aws_ec2.yml with auto plugin:
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
    plugin = inventory_loader.get(plugin_name)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 807, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 827, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
```

### AWX version

19.5.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

minikube

### Modifications

yes

### Ansible version

core 2.12.5.post0

### Operating system

Ubuntu 20.04.4

### Steps to reproduce

Running any task with inventory sync results in this error.

### Expected results

Before upgrade from v17 (docker compose), this was the result:

```
ansible-inventory 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
Parsed /tmp/bwrap_61934_wwgkrjf9/awx_61934__w3bzh29/aws_ec2.yml inventory source with auto plugin
    2.813 INFO     Processing JSON output...
    2.850 INFO     Loaded 79 groups, 7 hosts
    3.986 INFO     Inventory import completed for ec2 in 1.2s
```

### Actual results

```
ansible-inventory [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
redirecting (type: inventory) ansible.builtin.aws_ec2 to amazon.aws.aws_ec2
[WARNING]:  * Failed to parse /runner/inventory/aws_ec2.yml with auto plugin:
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
    plugin = inventory_loader.get(plugin_name)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 807, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 827, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
```

### Additional information

Custom Pod Spec in AWX Instance Group to provide vault key to ephemeral ee container
```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:latest'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
      - name: vault
        mountPath: "/var/lib/awx/projects"
        readOnly: true
  volumes:
  - name: vault
    secret:
      secretName: vault-pass
      defaultMode: 0444
      optional: false
```

**Comment by zigford** [comment]
Although this problem seems to have gone away in our environment, would like to know the root cause. 
I think we will pin all our templates to a specific AWX EE rather than 'latest'

**Comment by bpedersen2** [comment]
See https://github.com/ansible/awx-ee/issues/112

**Comment by eselvam** [comment]
I also facing same issue.  my awx version is 20.x  Shall I know how to fix it.

**Comment by eselvam** [comment]
Yes. we also got same error: awx AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK

as we used custom Ee to over come this. shall we know when we can expect AWX EE to be patched to fix this?

**Comment by bpedersen2** [comment]
See here https://github.com/ansible/awx/issues/12117

You need to install a cryptography >35,<37

**Comment by laiweihwa** [comment]
I was able to solve this by specifying image version 19.3.0 in the AWX CRD (though the UI still shows 19.5.0)
I am using ee:latet for the runner.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  postgres_configuration_secret: awx-postgres-configuration
  secret_key_secret: awx-secret-key
  service_type: ClusterIP
  image_version: 19.3.0
  ingress_type: none
```
