### ISSUE TITLE
how to add docker_container modules? 

### ISSUE THREAD

**Issue by sohwaje** [ansible/awx#12148]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

```
ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/install/docker/build_docker_image.yml': line 14, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  - name: Create a data container
    ^ here
```

playbook sample
```
---
- hosts: all
  gather_facts: no
  tasks:
  - name: Create a data container
    docker_container:
      name: mydata
      image: busybox
      volumes:
        - /data
```
