### ISSUE TITLE
21.0.1

### ISSUE THREAD

**Issue by Tioborto** [ansible/awx#12177]
Hello, 
We currently use SSH certificates through Hashicorp Vault to authenticate to all our machines.
We are stuck on the 21.0.0 upgrade which introduces a bug on the file storage. 
We are interested in the fix currently in devel (https://github.com/ansible/awx/pull/12122).
Can you create a patch version?

**Comment by rebeccahhh** [comment]
Hi @Tioborto , we will be doing an AWX release that contains the fix that you're interested in pretty soon. We try to have releases fairly regularly for situations just like this. We will announce that release in our mailing list. In the meantime you are more than welcome to just use devel for this fix.

**Comment by tmanninger** [comment]
Hi @rebeccahhh 

i also need this fix asap. How can i use the awx devel version with the current awx-operator?

I already tried the following, but this does not work:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  image_version: devel
  image_pull_policy: Always
```
