### ISSUE TITLE
can't connect awx 21 website in firefox

### ISSUE THREAD

**Issue by jskim096** [ansible/awx#12190]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

**ISSUE TYPE**
- Bug Report

**SUMMARY**
- Unable to access the web interface of AWX, I get this message "Unalbe to connect" in firefox. 

### AWX version

21.0.1

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

-

### Operating system

ubuntu 20.04

### Web browser

Firefox

### Steps to reproduce

**Here's some more information about my set up:**
- kubernetes version 1.23.6
- AWX Operator 0.21.0
- OS Ubuntu 20.04

**awx-deploy.yml**
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  nodeport_port: 31818
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/projects
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: static-data-pvc
```

### Expected results

-

### Actual results

**kubectl get pods**
```
root@awx: /home/awx/awx-operator# kubectl get pods
NAME                                                READY          STATUS      RESTARTS         AGE
awx-operator-controller-manager-675865446d-cwvtp     2/2           Running     2 (102m ago)     3h9m
awx-postges-0                                        1/1           Running     0
awx-544f7bf9c4-zhdtt                                 4/4           Running     2 (11m ago)      23m
```
```
root@awx: /home/awx/awx-operator# kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator"
NAME                   READY   STATUS    RESTARTS   AGE
awx-postgres-0         1/1     Running   0          32m
awx-544f7bf9c4-zhdtt   4/4     Running   4          31m
```
```
**kubectl get svc**
root@awx: /home/awx/awx-operator# kubectl get svc-l "app.kubernetes.io/managed-by=awx-operator"
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
awx-postgres           ClusterIP   None            <none>        5432/TCP            63m
awx-service            NodePort    10.43.244.23    <none>        80:31818/TCP        62m
```

### Additional information

I think all the installations are complete. but, when I access [**host IP:31818**] in Firefox, can't access it.

I wonder if it's just me. Is there an error in the version?

Please help me.

**Comment by olinigorov** [comment]
Hello, i am having similliar problem. All seems working fine, but when i try to access on http://host:port, i get blank page. 

While trying curl, i get this. 

`You need to enable JavaScript to run this app.`

I got JavaScript enabled, and i got this problem from several computers..  So next step i took, was checking the logs. 

 k logs -f awx-656b6c86fc-vg6qk awx-web

`2022/05/09 19:50:35 [error] 31#31: *3 open() "/var/lib/awx/public/static//css/main.ca1e253f.css" failed (2: No such file or directory), client: , server: _, request: "GET /static/css/main.ca1e253f.css HTTP/1.1", host: "blablabla:randomport", referrer: "http://blablabla:randomport/"
10.42.0.1 - - [09/May/2022:19:50:35 +0000] "GET /static/css/main.ca1e253f.css HTTP/1.1" 404 146 "http://tawx02.infra.uss:30080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0" "-"`

I am kinda confused, anybody got any idea, what to do now?

**Comment by olinigorov** [comment]
So, after troubleshooting for a while, problem was in a deployment yaml file.

Old deployment file.



```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: static-data-pvc

```

New deploy yaml file.


```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: static-data-pvc
```



I simply deleted 

```
web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public

```
Now it is working like a charm.

Have a nice day,

Oleg
