### ISSUE TITLE
GCP credential not set as env var on execution environment

### ISSUE THREAD

**Issue by fivetran-joliveira** [ansible/awx#12211]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

**TL;DR**
Environment variable `GCP_SERVICE_ACCOUNT_FILE` is not available on the execution environment.
This variable is set in [models/credential/injectors here](https://github.com/ansible/awx/blob/68f214c2bec56af99129c3c8971cb7eaab8bd9ca/awx/main/models/credential/injectors.py#L37) and I can confirm it is available in `awx-task` (`cat /tmp/awx_<job-id>_<hash>/env/envvars`) but not available in execution environment containers.

# What am I trying to accomplish?

I am trying to get AWX working with GCP IAP.
So far the only way I found to get GCP IAP working is by:

1. Setting `ansible_ssh_executable` to[ use a connection wrapper](https://binx.io/blog/2021/03/10/how-to-tell-ansible-to-use-gcp-iap-tunneling/ )
2. Build a custom image to install Google CLI, so `gcloud` command is available

However, as `gcloud` needs to read the credentials (service account file) from `GOOGLE_APPLICATION_CREDENTIALS` environment variable I need to set it with the value of `GCP_SERVICE_ACCOUNT_FILE`  injected by `AWX`, but this one is not being injected.

# Any workaround?
Couldn't find any, I appreciate any suggestion. 

### AWX version

AWX 19.5.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

yes

### Ansible version

2.12.5.post0

### Operating system

CentOS 8

### Web browser

Chrome

### Steps to reproduce

1. Create a credential of type `Google Compute Engine`
2. Create a job template that uses the created `Google Compute Engine` credential, and use ansible playbooks from a source project that contains either a `ansible_ssh_executable` or a playbook that invokes `gcloud`
3. Trigger a job using the created job template

### Expected results

`gcloud` would be successfully executed as the environment variable `GCP_SERVICE_ACCOUNT_FILE` would point to the service account json file with the details of the created `Google Compute Engine` credential

### Actual results

Error:
```
Failed to connect to the host via ssh: WARNING: The private SSH key file for gcloud does not exist.
```

As `gcloud` is not finding a service account file that could be loaded from `GOOGLE_APPLICATION_CREDENTIALS` or `GCP_SERVICE_ACCOUNT_FILE` environment variables it is then trying to connect to the target host using private/public SSH key authentication. As no private key is created in the execution environment, the connection cannot be established.

### Additional information

My `AWX` instance is deployed and managed using  [awx-operator](https://github.com/ansible/awx-operator) and I set a custom execution environment through the [ee_images configuration variable](https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx).

**Comment by TinLe** [comment]
How are you setting your env var?

I am doing something similar and it works for me.   I store my credentials in Hashicorp Vault.   So I grab it from HC Vault, use ansible.builtin.copy to put the value into a file.  Set the env var to that file and everything just works.  I've been using this since AWX v19.0.0 to now running v21.1.0

e.g.
```
  vars:
    - service_account_file: /tmp/sa_file.json
  environment:
    # come from HC Vault KV lookup in AWX
    GOOGLE_APPLICATION_CREDENTIALS: "{{ service_account_file }}"
  tasks:
    - name: Put key content into file for gcloud
      ansible.builtin.copy:
        content: "{{ vaultkv_secret | default('') }}"
        dest: "{{ service_account_file }}"
        owner: 1000
        mode: 0600
```
