### ISSUE TITLE
Could not sync inventory with encrypted vault files

### ISSUE THREAD

**Issue by kathy-lee** [ansible/awx#12234]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In AWX 21.0.0 could not sync inventory with encrypted vault files

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.21.0
* Kubernetes version: 1.22.6
* AWX install method: awx-operator

##### STEPS TO REPRODUCE
Previously I worked an old version AWX 14.1.0 and have my inventory with encrypted vault files. Now I am trying to set up AWX in Azure AKS with awx-operator. The project which contains the inventory files is successfully created in AWX, but when creating inventory from this source project, it got failed with error: "ERROR! Attempting to decrypt but no vault secrets found". I tried to mount the vault password inside the container, but doesn't work.

##### EXPECTED RESULTS
Inventory can sync successfully

##### ACTUAL RESULTS

Logs shown in sync inventory job:
 ```
ansible-inventory [core 2.12.5.post0]
    config file = None
    configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
    ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
    executable location = /usr/local/bin/ansible-inventory
    python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
    jinja version = 2.10.3
    libyaml = True
 No config file found; using defaults
 setting up inventory plugins
 host_list declined parsing /runner/project/inventory.ini as it did not pass its verify_file() method
 script declined parsing /runner/project/inventory.ini as it did not pass its verify_file() method
 auto declined parsing /runner/project/inventory.ini as it did not pass its verify_file() method
 yaml declined parsing /runner/project/inventory.ini as it did not pass its verify_file() method
 Set default localhost to localhost
 Not replacing invalid character(s) "{'-'}" in group name (.....)
 ERROR! Attempting to decrypt but no vault secrets found
```

when I go into the awx-ee container and run "ansible --version" it can show me the config file path correctly:

```
bash-4.4$ ansible --version
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.12.5.post0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

But in sync inventory job, it complained with "No config file found; using defaults". I am not sure if this is the reason. And I don't know if creating an ansible vault type credential with vault password as the vaule will help with this. Can anyone help me please? What is the suggested way to put vault password and let inventory find it when sync?

##### ADDITIONAL INFORMATION
This is my yaml file for awx:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: ClusterIP
  service_annotations: |
    environment: testing
  service_labels: |
    environment: testing

  ee_extra_env: |
    - name: ANSIBLE_VAULT_PASSWORD_FILE
      value: "/home/runner/vault_file"
    - name: ANSIBLE_CONFIG
      value: "/etc/ansible/ansible.cfg"

  extra_volumes: |
    - name: ansible-cfg
      configMap:
        defaultMode: 420
        items:
          - key: ansible.cfg
            path: ansible.cfg
        name: awx-demo-extra-config
  ee_extra_volume_mounts: |
    - name: ansible-cfg
      mountPath: /etc/ansible/ansible.cfg
      subPath: ansible.cfg
```
