### ISSUE TITLE
awx.awx collection: webhook_credential for workflows does not properly work

### ISSUE THREAD

**Issue by Tompage1994** [ansible/awx#12324]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

When using `awx.awx.workflow_job_template` module, the option `webhook_credential` causes the module to fail with the following error message:

```
The requested object could not be found at /api/v2/webhook_credential
```
which is not a valid endpoint.

I have found the offending line [here](https://github.com/ansible/awx/blob/d9f26a411ecd893725372b93b9698b017a40b739/awx_collection/plugins/modules/workflow_job_template.py#L739)

### AWX version

21.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.12.1

### Operating system

RHEL 8

### Steps to reproduce

```
- hosts: controller
  connection: local
  tasks:
    - awx.awx.workflow_job_template:
        name: mywfjt
        webhook_service: gitlab
        webhook_credential: glpat
        state: present
```

### Expected results

Blank workflow with webhook cred created

### Actual results

```
"msg": "The requested object could not be found at /api/v2/webhook_credential/."
```
