### ISSUE TITLE
Support of unified requirements.yml file with roles/collections do not work

### ISSUE THREAD

**Issue by dacofr** [ansible/awx#12364]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Even what is mentioned in this issue : https://github.com/ansible/awx/issues/6270, support of unified requirements.yml at top level do not work.

In file https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L214 
we are looking at the requirements.yml file at the root folder, but we install it with `ansible-galaxy collection install`
(https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml#L204)

### AWX version

20.1

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Linux

### Steps to reproduce

- Create a repository with a requirements.yml at **the root folder** with this content :
```
---
collections:
  - name: community.general
    version: "4.8.1"
  - name: community.hashi_vault
    version: "2.5.0"

roles:
  - src: Datadog.datadog
    name: Datadog.datadog
    version: 4.15.0
```

- Create a projet
- Synchronize it

### Expected results

Collections and roles are installed 

### Actual results

Only collections are installed
