### ISSUE TITLE
ansible_python_interpreter issue since upgrading to 21.2.0

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/awx#12430]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Using version 19.4.0 and setting ansible_python_interpreter in the Inventory to "{{ ansible_playbook_python }}".

`ansible_python_interpreter : "{{ ansible_playbook_python }}"`

Since upgrading ansible_python_interpreter module errors occur. 

### AWX version

21.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

quay.io/ansible/awx-ee:latest

### Operating system

Centos

### Steps to reproduce

```
- name: "get virtual machine facts by tag {{ tag }}"
  azure.azcollection.azure_rm_virtualmachine_info:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    resource_group: "{{ resource_group }}"
    tags:
      - type:{{ tag }}
  register: virtualmachine_facts
  delegate_to: localhost
```

### Expected results

No errors

### Actual results

```
"Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on automation-job-3489-5bgrl's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
```

### Additional information

Attempting to use execution environment quay.io/ansible/awx-ee:0.6.0 also results in an error: 

`This can be caused if the version of ansible-runner in your execution environment is out of date.`
