### ISSUE TITLE
Be able to set Extra Environment Variables at Instance Groups level

### ISSUE THREAD

**Issue by mick1627** [ansible/awx#12449]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature Summary

We started to use Instance Groups to run job in different region (aws EU, Alicloud china).
We set http proxy setting as environnement variable in setting / Jobs settings. Environnement variable set as this level is for all Jobs, inventory update.
We have different proxy per region, so each instance group will need specific proxy.
Today, user needs to unset or overwrite this environnement variable in their playbook running on instance group other then the default one.
Should be a good idea to be able to set environment variable at instance group level for this kind of purpose.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

**Comment by kurokobo** [comment]
As a workaround, you can add environment variables per Container Group by using custom pod spec:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: 'quay.io/ansible/awx-ee:latest'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      env:
        - name: AWX_INSTANCE_GROUP_NAME     👈👈👈
          value: my_custom_instance_group     👈👈👈
        - name: HTTP_PROXY     👈👈👈
          value: proxy.example.com:3128     👈👈👈
        - name: HTTPS_PROXY     👈👈👈
          value: proxy.example.com:3128     👈👈👈
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
```

You can use this environment variable in your playbook:

```yaml
---
- hosts: my_target_hosts
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: "{{ lookup( 'env', 'AWX_INSTANCE_GROUP_NAME' ) }}"
    - ansible.builtin.debug:
        msg: "{{ lookup( 'env', 'HTTP_PROXY' ) }}"
    - ansible.builtin.debug:
        msg: "{{ lookup( 'env', 'HTTPS_PROXY' ) }}"
```

```text
TASK [ansible.builtin.debug] ***************************************************
ok: [host01.example.com] => {
    "msg": "my_custom_instance_group"
}
TASK [ansible.builtin.debug] ***************************************************
ok: [host01.example.com] => {
    "msg": "proxy.example.com:3128"
}
TASK [ansible.builtin.debug] ***************************************************
ok: [host01.example.com] => {
    "msg": "proxy.example.com:3128"
}
```
