### ISSUE TITLE
Automation Jobs Killed

### ISSUE THREAD

**Issue by antwacky** [ansible/awx#12549]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Having migrated AWX operator to a new cluster, jobs are randomly failing with the following:

`Error opening pod stream: Get "https://awx.k3s.net:10250/containerLogs/awx/automation-job-12053-blqxd/worker?follow=true": EOF`

I'm not able to see anything beyond this error. The cluster has plenty of CPU/memory overhead, and I can't see any OOM events or similar.

### AWX Operator version

0.21.0

### AWX version

21.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.7+k3s1

### Modifications

yes

### Steps to reproduce

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  hostname: awx.k3s.net
  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cert-manager-acme-issuer
    traefik.ingress.kubernetes.io/router.middlewares: auth-sysadmin@kubernetescrd
  ingress_tls_secret: awx.k3s.net
  postgres_storage_class: longhorn
```

### Expected results

I expect the jobs to complete successfully.

### Actual results

The pods sometimes fail with the error:

`Error opening pod stream: Get "https://awx.k3s.net:10250/containerLogs/awx/automation-job-12053-blqxd/worker?follow=true": EOF`
