### ISSUE TITLE
Workflow nodes with same unified job template names but different types should be allowed

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#12596]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

If there is a project and inventory source with the same name, the node lookup should use the type to differentiate between the two. for example:
```
- identifier: Inventory Update
  unified_job_template:
    name: Azure
    inventory:
      organization:
        name: Default
    type: inventory_source
- identifier: Project Update
  unified_job_template:
    name: Azure
    type: project
    organization:
      name: Default
```

### AWX version

21.3.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

Run the updated main.yml and it will fail 

### Expected results

It uses the type to find the correct unified job template, as that is a required field in the model

### Actual results

Returns error as multiple objects with the same name
