### ISSUE TITLE
tower_workflow_job_template_node fails on extra_data option

### ISSUE THREAD

**Issue by ronrem** [ansible/awx#12763]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Within `tower_workflow_job_template` we have `ask_variables_on_launch: true` and `extra_vars: awx_hosts: "all"` configured. The workflow need to run on all hosts. Within `tower_workflow_job_template_node:` (Create 1st node) we have `extra_data: awx_hosts: "PaloAltoPanos_Firewall"` configured. We want to run this workflow and a subset of hosts member of this group.

Receiving the following error:

`TASK [Create 1st node] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to create workflow_job_template_node Palo Alto PAN-OS gether facts: {'extra_data': ['Variables awx_hosts are not allowed on launch. Check the Prompt on Launch setting on the Job Template to include Extra Variables.']}"}`

### AWX version

21.4.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.11

### Web browser

Firefox, Chrome, Safari

### Steps to reproduce

```
---
- name: AWX Workflow Playbook
  hosts: localhost
  gather_facts: false

  collections:
    - awx.awx

  tasks:
    - name: Set ci_branch variable
      set_fact:
        workflow_name: "Recommended software check"
        ci_branch: "{{ lookup('env', 'CI_COMMIT_BRANCH') }}"
        cacheable: true

    - name: Assert ci_branch variable is defined
      assert:
        that:
          - ci_branch is defined

    - name: Graceful waiting time before updating workflow
      include_tasks: workflow-graceful-update.yml

    - name: Create AWX workflow [{{ci_branch}}]
      block:
        - name: Create workflow [{{ci_branch}}]
          tower_workflow_job_template:
            name: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            ask_inventory_on_launch: true
            ask_variables_on_launch: true
            survey_enabled: false
            extra_vars:
              awx_hosts: "all"
            # Clean up old schema, resetting all nodes in workflow
            destroy_current_schema: true
          register: result

        - name: Create 1st node
          tower_workflow_job_template_node:
            identifier: "Palo Alto PAN-OS gether facts"
            workflow_job_template: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            unified_job_template: "PAN-OS"
            inventory: "Blank inventory"
            lookup_organization: "Org-SOC-Playbooks"
            extra_data:
              awx_hosts: "PaloAltoPanos_Firewall"

        - name: Create 2nd node
          tower_workflow_job_template_node:
            identifier: "F5 BIG-IP gether facts"
            workflow_job_template: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            unified_job_template: "BIG-IP"
            inventory: "Blank inventory"
            lookup_organization: "Org-SOC-Playbooks"
            extra_data:
              awx_hosts: "F5Bigip_Bigip"

        - name: Create 3th node
          tower_workflow_job_template_node:
            identifier: "Generic Reporting"
            workflow_job_template: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            unified_job_template: "Generic Reporting"
            inventory: "Blank inventory"
            lookup_organization: "Org-SOC-Playbooks"
            job_tags: "eol_report"
            all_parents_must_converge: true

        - name: Link 1st to 3th node
          tower_workflow_job_template_node:
            identifier: "Palo Alto PAN-OS gether facts"
            workflow_job_template: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            success_nodes:
              - "Generic Reporting"

        - name: Link 2nd to 3th node
          tower_workflow_job_template_node:
            identifier: "F5 BIG-IP gether facts"
            workflow_job_template: "{{workflow_name}} workflow"
            organization: "Org-SOC-Workflows"
            success_nodes:
              - "Generic Reporting"

```

### Expected results

```
TASK [Create 1st node] *********************************************************
ok: [localhost]
```

### Actual results

```
TASK [Create 1st node] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to create workflow_job_template_node Palo Alto PAN-OS gether facts: {'extra_data': ['Variables awx_hosts are not allowed on launch. Check the Prompt on Launch setting on the Job Template to include Extra Variables.']}"}
```
