### ISSUE TITLE
Long running ansible playbook jobs on windows hosts are not working properly

### ISSUE THREAD

**Issue by Bchoudhury92** [ansible/awx#12804]
Hi Team,

I have a scenario where I am using Linux7 controller machine to install a patch on an windows 2016 server.
The patch manually takes 3-4 hours to complete. However, whenever I am running the patch from ansible playbook, the execution is not completing.
Similar patches with less runtime (say less than 20-30 mins) are completing successfully but the one with longer execution time is not completing even if I leave it overnight to complete. The log file gets created at the end of patch completion so I am not able to track it either. Below is the code I am running
Please help!

```
  - name: apply patch
    win_shell: 'cmd /c {{comp_installer_loc_dir}}/apply_patch.bat'
    async: 4000000
    poll: 0
    register: async_job
    ignore_errors: yes

  - name: check async job status
    async_status:
       jid: "{{ async_job.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 900
```
