### ISSUE TITLE
[collection] `awx.awx.project` spams `/api/v2/project_updates/<id>/ endpoint` when `wait: True`

### ISSUE THREAD

**Issue by relrod** [ansible/awx#12850]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When creating a new project using the API with `wait: true` (the default), we end up spamming `/api/v2/project_updates/<id>/` way more than is ideal, with no delay at all.

Reproducer playbook is below.

Looking into the module code, I see this:

```python
            if module.is_job_done(result['status']):
                time.sleep(1)
                running = False
```

I'm guessing that really that `sleep()` should be in an `else`, i.e. if the job is *not* done, sleep 1 second and try again, rather than sleeping (for no reason?) when the project *is* done updating.

### AWX version

devel

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Steps to reproduce

```yaml
- hosts: localhost
  tasks:
    - awx.awx.project:
        controller_username: awx
        controller_password: awx
        controller_host: "https://localhost:8043"
        validate_certs: false
        name: test-project
        scm_branch: testinfra
        scm_url: https://github.com/relrod/ansible-sign-demo/
        scm_type: git
```

### Expected results

Not spamming the heck out of AWX :)

### Actual results

![image](https://user-images.githubusercontent.com/43930/189101161-c146f4f5-9c6d-4c04-9e97-8591c92b6af2.png)
