### ISSUE TITLE
Ansible XML Module failing on lxml python library even though it is installed.

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/awx#1286]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

```
Remote system is failing with XML module due to "fatal: [docker1]: FAILED! => {"changed": false, "msg": "The xml ansible module requires the lxml python library installed on the managed machine"}"
```

Even though it is installed:

```
spollock@docker1:~$ pip list
backports.ssl-match-hostname (3.5.0.1)
certifi (2017.11.5)
chardet (3.0.4)
docker (2.7.0)
docker-pycreds (0.2.1)
idna (2.6)
ipaddress (1.0.19)
lxml (4.1.1)  <-----
pip (9.0.1)
requests (2.18.4)
setuptools (20.7.0)
six (1.11.0)
urllib3 (1.22)
websocket-client (0.46.0)
wheel (0.29.0)
```

##### ENVIRONMENT

```
$ ansible --version
ansible 2.5.0
  config file = /Users/spollock/ansible/fs-linux-services/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

* Ansible version:  2.5.0
* Operating System:OSX

##### STEPS TO REPRODUCE

host: docker1 (from above)

Task:
```
- name: Grab version from xml.pom
  xml:
    path: /home/spollock/webui/xxxx-web/pom.xml
    xpath: /project
    content: attribute
    attribute: version
  register: version
  tags: version
```

##### EXPECTED RESULTS

should have parsed the XML and returned the value of the version attribute in the register.

##### ACTUAL RESULTS

```
TASK [dashboard : Grab version from xml.pom] ***********************************
fatal: [docker1]: FAILED! => {"changed": false, "msg": "The xml ansible module requires the lxml python library installed on the managed machine"}
```
