### ISSUE TITLE
AWX Collection Schedule isn't finding 

### ISSUE THREAD

**Issue by IAmAStealer** [ansible/awx#12931]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using the module awx.awx.schedule I have an error saying that either : Organization, inventory or unified_job_templates is not found.

I use the same entries for other modules such as inventory / template / project and never had a problem.
I went to check the code of the module but the method looks similar as other modules.

I test the API with the direct IDs of the inventory/template and it worked correctly.

I tried for a template that doesn't have duplicate names (same name as a project for example)

### AWX version

21.5.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Ansible version

2.10.8

### Operating system

debians

### Steps to reproduce

Have a AWX running.

Have a token for a privileged user

Use the collection awx.awx to update it :

1) Create an organization
2) within this organization create a project for inventory and project for the template
3) create inventory and template
4) try to schedule the template with :

- name: "schedule"
  awx.awx.schedule:
    name: "foo"
    state: "present"
    unified_job_template: "template1"
    rrule: "DTSTART;TZID=Europe/Paris:20220920T103000 RRULE:FREQ=DAILY;COUNT=1;INTERVAL=1"
    enabled: true
    inventory: "inventory1"
    organization: "orga1"
    controller_oauthtoken: "YourToken"
    validate_certs: false

### Expected results

Creation of the schedule for the targeted template

### Actual results

Error :
    "msg": "The requested object could not be found at /api/v2/inventories/."
or
    "msg": "The requested object could not be found at /api/v2/organizations/."
or
    "msg": "The requested object could not be found at /api/v2/unified_job_templates/."

depending whether I removed some parameters to test the creation.

**Comment by fosterseth** [comment]
having trouble reproducing this,
1. created org "sbf"
2. created projects "projA" and "projB"
3. created inventory "InvA" with source based on projB
4. create job template based on projA
5. All of those were assigned to org "sbf"

here is my playbook

```yaml
---
- name: schedule
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    controller_config_file: tower_cli.cfg
  collections:
    - awx.awx

  tasks:
    - name: "schedule"
      awx.awx.schedule:
        name: "foo3"
        state: "present"
        unified_job_template: "jt1"
        rrule: "DTSTART;TZID=Europe/Paris:20220920T103000 RRULE:FREQ=DAILY;COUNT=1;INTERVAL=1"
        enabled: true
        inventory: "invA"
        organization: "sbf"
        validate_certs: false
```

runs fine

```
PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

I'm using the docker based development environment, but I don't expect a difference on minikube for this.

Any suggestions for me to recreate the bug? @IAmAStealer
