### ISSUE TITLE
change authentication URL on docker registry credential

### ISSUE THREAD

**Issue by IAmAStealer** [ansible/awx#13046]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

In API and in awx collection add a new input to change authentication URL for Container Registry credential types and also add this new feature to the documentation.

{
    "name": "foo",
    "credential_type": 17,
    "inputs": {
        "password": "$encrypted$",
        "username": "bar"
        "auth_url": "add this"
    }
}

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Via collection :

- name: "credential | Set up credentials"
  awx.awx.credential:
    name: "foo"
    credential_type: 'Container Registry'
    inputs:
      username: "foo"
      password: "bar"
    controller_host: 'host
    controller_oauthtoken: 'oauth'

### Current results

This will create a Container Registry credential with authentication url equal to quay.io
But some of us have self hosted docker registry. It would be nice to automatically set the url via API and/or collection.

### Sugested feature result

have an additional input to change the authentication url.

### Additional information

I would be glad to help make the pull request but I'm not familiar on how to start

**Comment by sarabrajsingh** [comment]
hey @IAmAStealer,

You can modify the `authentication_url` in the API by modifying the `inputs.host` field.

##### example in the API:
```
{
    "name": <SOME NAME>,
    "description": "",
    "organization": <YOUR ORG ID>,
    "credential_type": <YOUR CREDENTIAL ID>,
    "inputs": {
        "host": <MODIFY HERE>,
        "password": <YOUR PASSWORD>,
        "username": <YOUR USERNAME>,
    }
}
```

could you try and add a `host` field to the call in the collections?

```
name: "credential | Set up credentials"
awx.awx.credential:
  name: "foo"
  credential_type: 'Container Registry'
  inputs:
    username: "foo"
    password: "bar"
    host: <SOME HOST HERE>
  controller_host: 'host
  controller_oauthtoken: 'oauth'
```
