### ISSUE TITLE
AWX unable to find module or collection ?

### ISSUE THREAD

**Issue by craph** [ansible/awx#13051]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

ERROR! couldn't resolve module/action 'archive'. 
This often indicates a misspelling, missing collection, or incorrect module path.

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

I don't know where to find it in AWX

### Web browser

Firefox

### Steps to reproduce

I have create a playbook to archive some files like this : 
```yaml
- name: Backup all docker-compose files
  archive:
    path: /path/to_archive
    dest: /tmp/my_archive_{{ ansible_date_time.weekday }}.tar.gz
    format: gz
  become: yes
  tags: backup_dc
```

When the playbook is run I have this error : 
```
ERROR! couldn't resolve module/action 'archive'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/roles/ar-archive/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Backup all docker-compose files
  ^ here
```

### Expected results

The archive module should work.

### Actual results

Archive module not found and playbook not running.

### Additional information

Where can I find the Ansible version used in AWX 21.7.0 ?
How can I install collection ?
