### ISSUE TITLE
Enable abstract Credential Types 

### ISSUE THREAD

**Issue by philipsd6** [ansible/awx#13070]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

If I have a playbook that needs to talk to 5 different APIs, each requiring separate credentials I must provide 5 different Credential Types, and 5 instances of those Credential Types -- even if all of these APIs are essentially identical:

    host: https:example1.com
    username: joe
    password: s3krit

This is difficult to manage, as Credential Types must be created by an Admin. If the configuration for the Credential Type could be configured to inject dynamic variables instead of hard coded ones, we could have a single "Generic API" credential type with a "prefix" field that could then be used to generate multiple credentials with differently prefixed variables. 

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

For example, if we could do this with the Input for a generic API host:

```yaml
fields:
  - id: host
    label: API Host
  - id: username
    label: Username
  - id: password
    label: Password
    secret: true
  - id: prefix
    label: Prefix for the credential variables
required:
  - host
  - username
  - password
  - prefix
```
And use the prefix like this in the Injector:
```yaml
extravars:
  "{{ prefix }}_host: "{{ host }}"
  "{{ prefix }}_username: "{{ username }}"  
  "{{ prefix }}_password: "{{ password }}"
```

Then we could create credentials for different environments (dev/test/prod) or scopes (internal/external) using the same Credential Type.

### Current results

Currently it is an error to use Jinja2 templating in the key side of an Injector configuration.

### Sugested feature result

With the ability to use Jinja2 templating in the key side of injectors, we can create an abstract/generic Credential Type that can be used for multiple credentials in the same Job Template.
