### ISSUE TITLE
Unable to remove configured instance group with awx.awx.job_template

### ISSUE THREAD

**Issue by MallocArray** [ansible/awx#13098]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

If an Instance Group is configured on a Template, I'm not aware of a way to remove it using the awx.awx.job_template module.  I could change it to a different instance group, but unable to just remove it to go back to having no instance group defined.

On a task, I have the following parameter set:
`instance_groups: "{{ item.instance_groups | default(omit) }}"`

This works to add an instance group if we have one defined, but the default of omitting won't remove it.
I have tried `default('')` which works for string parameters, but does not work for this one.  I'm unaware of another way to remove it, as I get an error that it could not find an empty instance group

### AWX version

21.7.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Ansible version

core 2.13.5

### Web browser

Chrome, Edge

### Steps to reproduce

In the GUI, or with Ansible collection, assign an instance group to an existing template.  In a playbook task that loops through multiple variables with parameters, attempt to remove this assigned instance group by defaulting a variable that no longer exists to  2 quotes or to false and see that an error is presented.  If defaulting to omit, the instance group configuration remains the same and the configured instance group is still present

```yaml
- name: AWX Job Templates
  awx.awx.job_template:
    controller_host: "{{ inventory_hostname }}"
    controller_username: "{{ controller_username | default(omit) }}"
    controller_password: "{{ controller_password | default(omit) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit) }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    ...
    instance_groups: "{{ item.instance_groups | default(omit) }}"
    ...
  loop: "{{ job_templates }}"
  loop_control:
    label: "{{ item.name }}"
  when: job_templates is defined
```

### Expected results

Expect there would be some way to format this parameter so if a variable is present, it will assign the template to use the specified instance group, but if the variable is not present, any configured instance group would be removed from the template

### Actual results

default(omit) does not modify the current instance group configuration as expected, but attempting to use default('') or default(false) results in an error and does not remove the configured instance group

**Comment by john-westcott-iv** [comment]
`default(omit)` prevents the parameter (instance_group) from being passed into the module see https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#making-variables-optional. You were close with `''` but `instance_groups` requires a list, not a string. An empty list looks like `[]`. So to remove instance groups with the module you would do something like:
```yaml
- name: AWX Job Templates
  awx.awx.job_template:
    controller_host: "{{ inventory_hostname }}"
    controller_username: "{{ controller_username | default(omit) }}"
    controller_password: "{{ controller_password | default(omit) }}"
    controller_oauthtoken: "{{ controller_oauthtoken | default(omit) }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    ...
    instance_groups: "{{ item.instance_groups | default([]) }}"
    ...
  loop: "{{ job_templates }}"
  loop_control:
    label: "{{ item.name }}"
  when: job_templates is defined
```

I'm assuming this should resolve your issue so I am going to close this for now. If it does not, please let me know and I can reopen your issue.
