### ISSUE TITLE
Jobs fail to create pods due to kubernetes api-service giving connection refused

### ISSUE THREAD

**Issue by ImNtReal** [ansible/awx#13123]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I suspect that this problem is an underlying infrastructure problem, but I haven't been able to pinpoint the issue, yet. Multiple jobs seem to be failing with the same issue, but inventory updates in particular are always ending with:
```
Error creating pod: Post "https://10.245.0.1:443/api/v1/namespaces/awx/pods": dial tcp 10.245.0.1:443: connect: connection refused
```

I have been troubleshooting connecting to kube-apiserver from inside my cluster. It seems that sometimes the connection succeeds, but other times I get connection refused.

I have an issue open with flannel: https://github.com/flannel-io/flannel/issues/1661

### AWX version

AWX 21.7.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

ansible [core 2.12.5.post0]

### Operating system

k8s running on Clear Linux

### Web browser

Firefox, Chrome, Safari, Edge

### Steps to reproduce

Initiate an inventory updated with a project based inventory.
Project update completes.
Inventory update attempts to start.

### Expected results

Inventory to update

### Actual results

Error creating pod: Post "https://10.245.0.1:443/api/v1/namespaces/awx/pods": dial tcp 10.245.0.1:443: connect: connection refused

### Additional information

The inventory job is set to use a custom execution environment, but I have no problem pulling and running the image using kubectl.

Here is my awx.yaml:
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
  nfs:
    server: nfs.hqsbisilon2.nghs.com
    path: "/ifs/hqsbisilon1/Containers/Kubernetes/awx/"
  claimRef:
    namespace: awx
    name: awx-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-pv-claim
  namespace: awx
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awx-cert
  namespace: awx
spec:
  secretName: awx-crt-secret
  dnsNames:
  - awx.nghs.com
  issuerRef:
    name: smallstep
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: clusterip
  ingress_type: ingress
  hostname: awx.nghs.com
  ingress_tls_secret: awx-cert
  ingress_annotations: |
    kubernetes.io/ingress.class: "nginx"
  ldap_cacert_secret: awx-ldap-ca-cert
  postgres_configuration_secret: awx-postgres-configuration
  extra_volumes: |
    - name: awx-pv-storage
      persistentVolumeClaim:
        claimName: awx-pv-claim
  bundle_cacert_secret: awx-ssl-ca-custom
  web_resource_requirements:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  ee_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  ee_images:
    - name: AWX EE
      image: quay.io/ansible/awx-ee:latest
    - name: NGHS Custom EE
      image: containers.nghs.com/repository/containers/awx-custom-ee:latest
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: ###############
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: awx
stringData:
  secret_key: #################
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: '172.20.213.102'
  port: '6432'
  database: awx
  username: awx
  password: #############
  sslmode: prefer
  type: unmanaged
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-extra-config
  namespace: awx
data:
  ansible.cfg: |
     [defaults]
     interpreter_python = auto
     remote_tmp = /tmp
     library = ./library
     forks = 30
     gathering = smart
     roles_path    = ./roles:/home/runner/project/roles:/runner/project/playbooks/roles:/runner/requirements_roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project/playbooks
     collections_path = ./collections:/home/runner/project/collections:/usr/share/ansible/collections:/etc/ansible/collections/:/runner/project/collections:/runner/requirements_collections
     inventory=./inventory
     jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n
     [ssh_connection]
     ssh_args = -C -o ControlMaster=auto -o ControlPersist=1h -o PreferredAuthentications=publickey
     control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
     pipelining = True
     scp_if_ssh = Smart
  custom.py:  |
      AWX_CLEANUP_PATHS = True
      AWX_TASK_ENV['GIT_SSL_NO_VERIFY'] = True
      GIT_SSL_NO_VERIFY = True
```
