### ISSUE TITLE
BUG - Collection: ansible.controller  and  Module: notification_template Not working Correctly

### ISSUE THREAD

**Issue by tmichett** [ansible/awx#13156]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The module for an e-mail notification should not require a Username/Password 

```
- name: Add email notification
  notification_template:
    name: email notification
    notification_type: email
    notification_configuration:
      username: user
      password: s3cr3t
      sender: controller@example.com
      recipients:
        - user1@example.com
      host: smtp.example.com
      port: 25
      use_tls: no
      use_ssl: no
    state: present
    controller_config_file: "~/tower_cli.cfg"
```

The web interface allows configuring e-mail Notification Template without a Username/Password and this works just fine, in order to use the module without these items, you must leave them as BLANK with **""**.
```

---
- name: Create a Notification Template
  hosts: localhost

  tasks:

    - name: Create Notification Template
      ansible.controller.notification_template:
        name: "DO467 CH5 Demo E-mail Notification"
        notification_type: email
        notification_configuration:
          username: ""
          password: ""
          sender: system@controller.lab.example.com 
          recipients:
            - aap-admins@lab.example.com 
          host: localhost
          port: 25
          use_ssl: no
          use_tls: no
        organization: Red Hat Training
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
```

If something is truly required, it shouldn't be allowed to be blank, and if it is required, it should be required in the WebUI. Based on the demonstrations and functionality in the DO467 classroom, it is clear that a UN/PW are optional.

<img width="975" alt="Screenshot 2022-11-03 at 2 02 52 PM" src="https://user-images.githubusercontent.com/12944787/199799994-f624271c-5b2b-4147-8595-648889bbf49b.png">

### AWX version

Ansible Automation Platform Controller 4.2.0 

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

ansible [core 2.13.0]

### Operating system

RHEL 8.6

### Steps to reproduce

Run the playbook listed here ...

https://github.com/tmichett/DO467_Notes/blob/8c1f1453f58c4887bd414f467cf3d906e331a99b/Demos/CH5/Create_CH5_Notification.yml

Leave out the Username/Password

### Expected results

Notification template created ...

### Actual results

Error message stating username/password required

```
[student@workstation CH5]$ ansible-navigator run Create_CH5_Notification.yml

PLAY [Create a Notification Template] ************************************************

TASK [Gathering Facts] ***************************************************************
ok: [localhost]

TASK [Create Notification Template] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": ["Missing required fields for Notification Configuration: ['username', 'password']."]}

PLAY RECAP ***************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Please review the log for errors.
```

### Additional information

Username and password were given as blank values in the "test" playbook so that the notification template could be automated.
