### ISSUE TITLE
awx.awx collection has job_list module but not workflow_list module

### ISSUE THREAD

**Issue by augustinosusky** [ansible/awx#13175]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

awx.awx collection has job_list module but not workflow_list module. The API syntax is basically the same, jobs have "jobs" endpoint and workflows "workflow_jobs" endpoint so almost everything can be copied over.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

this works:  
```
      job_list:
        controller_host: '{{ lookup("env", "TOWER_HOST") }}'
        controller_username: '{{ lookup("env", "TOWER_USERNAME") }}'
        controller_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
        query: {"id": "{{ job_id }}"}
```

this would be nice:  
```
      workflow_job_list:
        controller_host: '{{ lookup("env", "TOWER_HOST") }}'
        controller_username: '{{ lookup("env", "TOWER_USERNAME") }}'
        controller_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
        query: {"id": "{{ workflow_job_id }}"}
```

the parameters are the same for both API endpoints.

### Current results

workflow_list is not present.

### Sugested feature result

It will allow query workflow jobs.
