### ISSUE TITLE
Execution node fails to parse inventory

### ISSUE THREAD

**Issue by evindunn** [ansible/awx#13195]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'm using the AWX Operator and an external execution node.

```
images:
  - name: quay.io/ansible/awx-operator
    newTag: "1.0.0"
```

```
$ kubectl exec -it awx-demo-5c65d87959-w8pd5 -c awx-demo-web -- awx-manage --version
21.8.0
```

Project is in source control, inventory is a yaml file within the project. However, it looks like the controller node is sending a python script to the executor node? From the job output:

```
Identity added: /runner/artifacts/91/ssh_key_data (/runner/artifacts/91/ssh_key_data)
ansible-playbook 2.9.27.post0
  config file = /runner/project/ansible.cfg
  configured module search path = ['/runner/project/plugins/modules', '/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
Using /runner/project/ansible.cfg as config file
Vault password: 
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
toml declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /runner/inventory/hosts with script plugin:
problem running /runner/inventory/hosts --list ([Errno 13] Permission denied:
'/runner/inventory/hosts')
```

And then it dumps the output when yaml tries to parse it, which is how I know its python:

```
[WARNING]:  * Failed to parse /runner/inventory/hosts with yaml plugin: We were
unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading
YAML.   did not find expected key  The error appears to be in
'/runner/inventory/hosts': line 3, column 534, but may be elsewhere in the file
depending on the exact syntax problem.  The offending line appears to be:  #
-*- coding: utf-8 -*- print('{"all": {"hosts": [], "children":

...
```

As you can see above the python inventory script is missing the executable bit inside the podman container on the execution node. Any suggestions?

### AWX version

21.8.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

minikube

### Modifications

no

### Ansible version

2.9.27

### Operating system

Alma 8

### Steps to reproduce

1. Install awx in minikube via the awx operator
2. Import SCM project
3. Define inventory from a yaml file in the SCM project
4. Add an execution node, download the playbook
5. Run the downloaded playbook against the execution node
6. Wait for the execution node to be ready
7. Attempt to run a job

### Expected results

Job runs playbook against inventory successfully

### Actual results

Job immediately crashes on execution node because inventory is defined as a python script without the executable bit set

**Comment by djyasin** [comment]
Hi @evindunn 
We would like to gather a bit more information from you. Please get back to us with the following information:

How did you set up the execution node?

In your extra_settings, could you try setting `AWX_CLEANUP_PATHS = False` and then rerun that job. 

Check the file permission on the execution node and the controller_node as well.

**Comment by evindunn** [comment]
@djyasin I added the execution node by ip in the web ui
![Screen Shot 2022-11-16 at 12 09 09 PM](https://user-images.githubusercontent.com/19595733/202271510-915dc65a-0718-4296-a997-e3de9a367d75.png)

Then downloaded the "Install Bundle" playbook & ran it against the host

![Screen Shot 2022-11-16 at 12 09 36 PM](https://user-images.githubusercontent.com/19595733/202271577-e3e3d9b1-3ebb-4025-ad17-22b9e97749e0.png)

Permissions look ok on the controller/execution nodes. I'll try `AWX_CLEANUP_PATHS` and report back, thanks.

**Comment by evindunn** [comment]
Looks like the same result after adding `AWX_CLEANUP_PATHS`

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 30080
  secret_key_secret: custom-awx-secret-key
  admin_password_secret: custom-awx-admin-password
  projects_persistence: true
  projects_existing_claim: projects
  extra_settings:
    - setting: AWX_CLEANUP_PATHS
      value: True
```

```
kubectl delete po -l "app.kubernetes.io/managed-by=awx-operator"
```

Run job template:

![Screen Shot 2022-11-16 at 12 23 55 PM](https://user-images.githubusercontent.com/19595733/202274842-1bea8b8a-49d4-4a87-9d14-0c63399527a5.png)

Inventory sync on the controller works just fine btw

**Comment by evindunn** [comment]
Looks like the same result after adding `AWX_CLEANUP_PATHS`

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 30080
  secret_key_secret: custom-awx-secret-key
  admin_password_secret: custom-awx-admin-password
  projects_persistence: true
  projects_existing_claim: projects
  extra_settings:
    - setting: AWX_CLEANUP_PATHS
      value: False
```

```
$ kustomize build . | kubectl apply -f -
namespace/awx unchanged
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com unchanged
serviceaccount/awx-operator-controller-manager unchanged
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role configured
role.rbac.authorization.k8s.io/awx-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding unchanged
configmap/awx-operator-awx-manager-config unchanged
secret/custom-awx-admin-password configured
secret/custom-awx-secret-key configured
service/awx-operator-controller-manager-metrics-service unchanged
persistentvolumeclaim/projects unchanged
deployment.apps/awx-operator-controller-manager configured
awx.awx.ansible.com/awx-demo configured
```

```
kubectl delete po -n awx --all
```

Run job result:

![Screen Shot 2022-11-16 at 12 33 15 PM](https://user-images.githubusercontent.com/19595733/202276715-28889645-4e83-49e6-b399-58265a0abbdf.png)


Inventory sync on the controller works just fine btw
