### ISSUE TITLE
Firewallrules Error in ee container

### ISSUE THREAD

**Issue by OrenAvinoam** [ansible/awx#13300]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When deploying awx, the ee container keeps crashing with the following error showing in logs:

error: error loading config file: field firewallrules not defined for command node: unknown field name firewallrules awx

The relevent part of the configmap is here:
![20221207_155339](https://user-images.githubusercontent.com/103171852/206201623-b6c85a74-1804-4a4c-a277-6c31a1d82604.jpg)

### AWX version

19.5.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

After successfully deploying the awx-operator 0.15.0, deploy awx by using the Makefile and applying the resources. All images are local since we are in an isolated network.

### Expected results

A running awx pod.

### Actual results

The ee container keeps crashing with status CrashLoopBackOff and the previously mentioned error.

**Comment by akus062381** [comment]
@OrenAvinoam can you please provide the details of your custom resource so that one of our engineers can try to reproduce the problem?

**Comment by OrenAvinoam** [comment]
I'm on an air gap environment so I cannot...

**Comment by akus062381** [comment]
Hi @OrenAvinoam,

We would like to help, but we are going to need more details than have been provided here. Can you please copy/paste further details here? If we don't have further details, unfortunately we will not be able to help.

**Comment by codepoke-kk** [comment]
I also have this error. How would I provide the details? The "ConfigMaps" OpenShift object is news to me, but I do have that. 

My error is:
```
1 line
Error: error loading config file: field firewallrules not defined for command node: unknown field name firewallrules
```

I have this in the customized yaml I reference from oc apply:
```
  ee_images:
    - name: mycompany-custom-awx-ee
      image: quay-remote.rtfx.mycompany.com/ansible/awx-ee:0.6.0
  control_plane_ee_image: quay-remote.rtfx.mycompany.com/ansible/awx-ee:0.6.0
```

The image is a direct copy of the publicly available image. 

I have this in the ConfigMap:
```
  receptor_conf: |
    ---
    - log-level: debug
    - local-only: null
    - node:
       firewallrules:
        - action: reject
          tonode: HOSTNAME
          toservice: control
    - control-service:
        service: control
        filename: /var/run/receptor/receptor.sock
        permissions: '0660'
    - work-command:
        worktype: local
        command: ansible-runner
        params: worker
        allowruntimeparams: true
    - work-kubernetes:
        worktype: kubernetes-runtime-auth
        authmethod: runtime
        allowruntimeauth: true
        allowruntimepod: true
        allowruntimeparams: true
    - work-kubernetes:
        worktype: kubernetes-incluster-auth
        authmethod: incluster
        allowruntimeauth: true
        allowruntimepod: true
        allowruntimeparams: true
    - tls-client:
        cert: /etc/receptor/tls/receptor.crt
        key: /etc/receptor/tls/receptor.key
        name: tlsclient
        rootcas: /etc/receptor/tls/ca/receptor-ca.crt
    - work-signing:
        privatekey: /etc/receptor/signing/work-private-key.pem
        tokenexpiration: 1m

```

**Comment by codepoke-kk** [comment]
Fascinating. Based upon this clue, I was able to apply your bare factory yaml and my customized yaml and they create the same ConfigMap, date stamps aside.

**Comment by codepoke-kk** [comment]
I am not sure whether this helps, but this is an excerpt from the POD YAML containing the container definition. 

Here is your running pod, as built from the factory:
```
          'f:containers':
            'k:{"name":"nonprod-network-awx-factory-ee"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/etc/receptor/"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/receptor/receptor-default.conf"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:subPath': {}
                'k:{"mountPath":"/etc/receptor/signing/work-private-key.pem"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/etc/receptor/tls/"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/receptor/tls/ca/receptor-ca.crt"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/var/lib/awx/projects"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/var/run/receptor"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources':
                .: {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
              'f:args': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}

```
Here is mine, with all my customizations:
```
          'f:containers':
            'k:{"name":"nonprod-network-awx-amen-ee"}':
              'f:image': {}
              'f:volumeMounts':
                'k:{"mountPath":"/var/lib/awx/projects"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/receptor/"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/krb5.conf"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:subPath': {}
                .: {}
                'k:{"mountPath":"/etc/receptor/tls/ca/receptor-ca.crt"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/var/run/receptor"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/receptor/receptor-default.conf"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:subPath': {}
                'k:{"mountPath":"/etc/receptor/signing/work-private-key.pem"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/etc/pki/ca-trust/source/anchors/bundle-ca.crt"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
                  'f:subPath': {}
                'k:{"mountPath":"/etc/receptor/tls/"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/etc/pki/ca-trust/extracted"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources':
                .: {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
              'f:args': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:name': {}
```

**Comment by onefourfive** [comment]
I am having the same issue:

### AWX Version

21.9.0

### AWX Operator Version

1.1.1

### Installation Method

k8s

### Other info

We also use local mirrors for `awx-ee`. 

Only the `awx-ee` container is failing:

```
NAME                                               READY   STATUS             RESTARTS         AGE
awx-746dbddb57-krjkc                               3/4     Error              7 (5m16s ago)    11m
```

`k get pod/awx-746dbddb57-krjkc -o json | jq .status.containerStatuses[0]`
```json
{
  "containerID": "docker://2757d126bc5cac2d73510b68823f08f6295c39795889f01ca7c2cedeb7blah",
  "image": "local-repo.com/awx-ee:0.6.0",
  "imageID": "docker-pullable://local-repo.com/awx-ee@sha256:",
  "lastState": {
    "terminated": {
      "containerID": "docker://2757d126bc5cac2d73510b68823f08f6295c39795889f01ca7c2cedeb7blah",
      "exitCode": 1,
      "finishedAt": "2022-12-21T22:31:14Z",
      "reason": "Error",
      "startedAt": "2022-12-21T22:31:14Z"
    }
  },
  "name": "awx-ee",
  "ready": false,
  "restartCount": 7,
  "started": false,
  "state": {
    "waiting": {
      "message": "back-off 5m0s restarting failed container=awx-ee pod=awx-746dbddb57-krjkc_(93a3300c-1322-44eb-96c0-44221ee8d27c)",
      "reason": "CrashLoopBackOff"
    }
  }
}
```

Container logs only state what OP posted above

```
$ k logs pod/awx-746dbddb57-krjkc -c awx-ee
Error: error loading config file: field firewallrules not defined for command node: unknown field name firewallrules
```

From `configmap/awx-awx-configmap`, unchanged from stock and identical to OP:
```yaml
  receptor_conf: |
    ---
    - log-level: debug
    - local-only: null
    - node:
       firewallrules:
        - action: reject
          tonode: HOSTNAME
          toservice: control
```
