### ISSUE TITLE
Testing controller hostname DNS resolution is preventing awx_collection to work with http[s]_proxy

### ISSUE THREAD

**Issue by bagasse** [ansible/awx#13336]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

ControllerApi code check for host resolution via `getaddrinfo` (see https://github.com/ansible/awx/blob/devel/awx_collection/plugins/module_utils/controller_api.py#L146).

This prevent any module to work behind http[s]_proxy.

eg:
```
- name: Ensure organizations are configured
  ansible.controller.organization:
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username | default(omit) }}"
    controller_password: "{{ aap_controller_password | default(omit) }}"
    validate_certs: "{{ aap_controller_validate_certs | default(omit) }}"
    default_environment: "{{ organization.default_environment | default(omit) }}"
    description: "{{ organization.description | default(omit) }}"
    galaxy_credentials: "{{ organization.galaxy_credentials | default(omit) }}"
    instance_groups: "{{ organization.instance_groups | default(omit) }}"
    max_hosts: "{{ organization.max_hosts | default(omit) }}"
    name: "{{ organization.name }}"
    state: "{{ organization.state | default(omit) }}"
  environment:
    https_proxy: http://<http_proxy_host>:3128
```
Fails with `"msg": "Unable to resolve controller_host ([Errno -2] Name or service not known)`

Removing the `try/except` block for `getaddrinfo` make the module works with http proxy

As this modules talks on http(s), it should work with http proxies.

### AWX version

ansible.controller 4.3.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.13

### Operating system

RHEL 8

### Steps to reproduce

* Install awx.awx or downstream ansible.controller collection
* try to use collection modules via an http[s] proxy (see sumary for task example)

### Expected results

Collection's modules works

### Actual results

Fails with `"msg": "Unable to resolve controller_host ([Errno -2] Name or service not known)`
