### ISSUE TITLE
ad_hoc_command module can't specify verbosity level

### ISSUE THREAD

**Issue by OscarBell** [ansible/awx#13377]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

According to the module documentation the verbosity parameter should accept integer values between 0 and 5.
```yaml
verbosity:
      description:
        - Verbosity level for this ad hoc command run
      type: int
      choices: [ 0, 1, 2, 3, 4, 5 ]
```

Providing the value 2 to the module result in a validation error.
```yaml
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of verbosity must be one of: 0, 1, 2, 3, 4, 5, got: 2"}
```

I believe the issue is caused by a wrong definition of the choices option in the module argument specs.
```python
verbosity=dict(type='int', choices=['0', '1', '2', '3', '4', '5']),
```

The correct spec should be a list of integers between 0 and 5 instead of strings to meet the requirement of the parameter. to be an integer.
```python
verbosity=dict(type='int', choices=[0, 1, 2, 3, 4, 5]),
```

### AWX version

Latest

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Below example playbook will result in the validation error.

```yaml
---
- name: Test playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test verbosity for ad_hoc_command awx_test_module
      awx.awx.ad_hoc_command:
        credential: fake_credential
        inventory: fake_inventory
        module_name: shell
        verbosity: 2
```

### Expected results

The module, when using real values for the parameters should be executed and return the result with verbose logging of level 2.

### Actual results

Ansible playbook failure

```yaml
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of verbosity must be one of: 0, 1, 2, 3, 4, 5, got: 2"}
```

### Additional information

If required I could try to create a Pull Request with the suggested change for this module.
