### ISSUE TITLE
WinRM Kerberos Playbook fails in UI but runs in commandline

### ISSUE THREAD

**Issue by r1200gsdave** [ansible/awx#13383]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have a very simple playbook that does win_ping that fails in the UI but runs fine in a shell in the awx-ee container.

I have the following set variables
ansible_connection = winrm
ansible_winrm_port = 5986
ansible_winrm_transport = kerberos
ansible_winrm_server_cert_validation = ignore
ansible_winrm_realm = XXXX.LOCAL
ansible_user = admin_XXXX@XXXX.LOCAL

I have a proper /etc/krb5.conf added in via a config map.

The play succeeds on the command line and I can do other adhoc ansible tasks. 

ansible-playbook -k /var/lib/awx/projects/_9__ad_test/test.yaml

In the UI I have set up a credential, inventory and project and added the same variables in the extra vars.  But I get the error:

'Server not found in Kerberos database'

### AWX version

AWX 21.9.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

ansible [core 2.12.5.post0]

### Operating system

AWS Linux 2

### Steps to reproduce

create play and run

### Expected results

same execution on the command line as in the UI

### Actual results

UI failed and command line succeeded

### Additional information

I have modified the deployment to add in the /etc/krb5.conf configmap as a volume for the awx-ee container.

**Comment by kurokobo** [comment]
`/etc/krb5.conf` has to be mounted on automation job pod for EE where your playbook wil be launched. This is differ from `awx-ee` container in AWX pod.

To achieve this, if you want use configmap, you have to define Container Group with customized pod spec in AWX, and configure your Job Template to use the Container Group, e.g.;

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: 'quay.io/ansible/awx-ee:latest'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
      volumeMounts:
        - name: awx-kerberos-volume
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
  volumes:
    - name: awx-kerberos-volume
      configMap:
        name: awx-kerberos-config
```

Maybe [my unofficial guide to use kerberos](https://github.com/kurokobo/awx-on-k3s/blob/main/tips/use-kerberos.md) can be helpful for you.

If you have any further questions, [ask on mailing list or IRC chat](https://github.com/ansible/awx#get-involved) is preferred way, since here is the place to track bug/RFE and is not for asking usage questions.
