### ISSUE TITLE
AWX doesn't use my Vault credential

### ISSUE THREAD

**Issue by Aohzan** [ansible/awx#13409]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have some Ansible Vault encrypted files in my repo.
I added the Vault credential to the template (otherwise I have the `ERROR! Attempting to decrypt but no vault secrets found` message)
In the first line of the playbook output, I have the line `Vault password: `, like Ansible wait for the password input.
On the first task using a value from a vault file, I have `'vault'  is undefined`

I don't have the issue outside of AWX, ansible decrypt and read the variables

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

7

### Operating system

Debian

### Web browser

Firefox

### Steps to reproduce

![image](https://user-images.githubusercontent.com/2736322/211061106-eb55c2f6-63b9-45a0-935b-7a9e56b9c8e2.png)

![image](https://user-images.githubusercontent.com/2736322/211061296-6b935701-310b-4ce5-bdd4-8a8918278af6.png)

### Expected results

AWX decrypt vault files with the password in the credential

### Actual results

AWX ask the password even if it knows that I add a vault credential, and failed when try to find variables

**Comment by djyasin** [comment]
Hello @Aohzan,
We attempted to reproduce this on our end and we have thus far been unable to duplicate this. 

Do you happen to be using the vault_id feature of anisble-vault? 

Could you possibly provide us the key/value with a dummy value that you have encrypted? That might help us identify what is occurring.

**Comment by Aohzan** [comment]
I tried with a vault id but it didn't changed anything.

Files examples:
`environments/service/group_vars/all/vault.yml`
```yaml
---                                                                                                                 
vault_service:
  gitlab:
    smtp_username: "xxx"
    smtp_password: "yyy"
```
`plays/group_vars/all/vault.yml`
```yaml
---                                                                                                                 
vault_common:
  app:
    token: "zzz"
```
