### ISSUE TITLE
AWXBackup. chown: changing group of '/backups/tower-openshift-backup-blabla/tower.db': Operation not permitted

### ISSUE THREAD

**Issue by anbi-x5** [ansible/awx#13492]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I updated my AWX installation 21.2.0 → 21.10.2 by updating the awx operator from version 0.20.1 to 1.1.3.
Now when I create AWXBackup
```
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-test
  namespace: default
spec:
  backup_pvc: awx-backup-claim
  deployment_name: awx
  no_log: false
```
 I get an error:

`TASK [backup : Set permissions on file for database dump] **********************\r\ntask path: /opt/ansible/roles/backup/tasks/postgres.yml:73\nfatal: [localhost]: FAILED! => {\"changed\": true, \"rc\": 1, \"return_code\": 1, \"stderr\": \"chown: changing group of '/backups/tower-openshift-backup-XXXX-XX-XX-XX:XX:XX/tower.db': Operation not permitted\\n\", \"stderr_lines\": [\"chown: changing group of '/backups/tower-openshift-backup-XXXX-XX-XX-XX:XX:XX/tower.db': Operation not permitted\"]`

Here https://github.com/ansible/awx-operator/pull/1109 there were changes that had already corrected a similar error, but it appeared again.

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

CentOS 8 Stream

### Web browser

Chrome

### Steps to reproduce

1. Deploy awx-operator 1.1.3;
2. Add storage class for PVC;
3. Create a new demo instance AWX:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  control_plane_ee_image: my-proxy-addr/quay.io/ansible/awx-ee:latest
  ee_images:
  - image: my-proxy-addr/quay.io/ansible/awx-ee:latest
    name: AWX EE (latest)
  image: my-proxy-addr/quay.io/ansible/awx
  image_version: 21.10.2
  ingress_type: none
  init_container_image: my-proxy-addr/quay.io/ansible/awx-ee
  init_container_image_version: latest
  loadbalancer_protocol: http
  redis_image: my-proxy-addr/dockerhub/library/redis
  redis_image_version: latest
  service_type: ClusterIP
```
6. Create a AWXBackup:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-test
  namespace: default
spec:
  backup_pvc: awx-backup-claim
  deployment_name: awx-demo
  no_log: false
```
7. Checking pods status and getting a falling pod **awxbackup-test-db-management**:
```
...
awxbackup-test-db-management            1/1     Terminating   0             16s
...
```
8. $ kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager:
`TASK [backup : Set permissions on file for database dump] **********************\r\ntask path: /opt/ansible/roles/backup/tasks/postgres.yml:73\nfatal: [localhost]: FAILED! => {\"changed\": true, \"rc\": 1, \"return_code\": 1, \"stderr\": \"chown: changing group of '/backups/tower-openshift-backup-XXXX-XX-XX-xx:xx:xx/tower.db': Operation not permitted\\n\", \"stderr_lines\": [\"chown: changing group of '/backups/tower-openshift-backup-XXXX-XX-XX-XX:XX:XX/tower.db': Operation not permitted\"], \"stdout\": \"\", \"stdout_lines\": []}\n\r\n`

### Expected results

Сreation of AWXBackup and its successful completion  

### Actual results

Job failed on TASK [backup : Set permissions on file for database dump]
