### ISSUE TITLE
[awx.awx.user] Password is always updated, even with update_secrets: false

### ISSUE THREAD

**Issue by Klaas-** [ansible/awx#13650]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi,
it seems in the awx collection a users password is always updated, even if I set update_secrets: false

### AWX version

21.12.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.13.3

### Operating system

Red Hat Enterprise Linux release 8.7

### Web browser

Firefox

### Steps to reproduce

The simplest reproducer I could come up with is:
```
- name: test
  hosts: all
  tasks:
    - awx.awx.user:
        username: user
        email: no@example.com
        state: present
        is_superuser: true
        organization: Org
        controller_host: https://awx.domain.tld
        controller_username: admin
        controller_password: secret
        password: user
        update_secrets: false
```

Run it twice :)

First run will show:
changed: [awx.domain.tld] => {"changed": true, "id": 12, "name": "user"}

2nd run will show:
ok: [awx.domain.tld] => {"changed": false, "id": 12}

### Expected results

No changes on the AWX side for the 2nd run.

### Actual results

I see a change on the AWX side for the user on the 2nd run:
```
{
  "password": [
    "hidden",
    "hidden"
  ]
}
```

### Additional information

I only noticed this because "changing" the password will log the user out. Meaning on the 2nd run if user is already logged in, the user will be logged out because all sessions are invalidated.

This could be seen as a docs issue if that is expected behavior.
```
true will always change password if user specifies password, even if API gives $encrypted$ for password.
false will only set the password if other values change too.
```
If it's expected behavior the "false" definition should be something like "will not show up as 'changed' in ansible but will update values server side"
