### ISSUE TITLE
export list of objects not working

### ISSUE THREAD

**Issue by pombaer** [ansible/awx#13715]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary
The following Issue should provide the functionallity:
[https://github.com/ansible/awx/pull/13168](https://github.com/ansible/awx/pull/13168)

I try to export a list of inventories, this should work according to awx.awx.module documentation.

- Used awx command line command:

```
awx export --conf.host https://<hostname> --conf.username <user> --conf.password <pwd> -k --inventory ['inv01' ,'inv01'] -f yaml
``` 

- Used playbook task:

``` 
  tasks:
  - name: "AWX | retrieve awx objects"
    awx.awx.export:
      all: false
      controller_host: "https://<hostname>"
      controller_username: "<user>"
      controller_password: "<pwd>"
      projects: ["inv01", "inv02"]
      validate_certs: false
    register: "awx_register_inventories"
``` 

Specifing a string instead of an list works as expectd

Used awxkit version is "21.13.0", 

``` 
ansible-version:

ansible [core 2.12.8]
  config file = /home/maat/bacher/git/dos/collections/bacher-ansible-configmanagement/ansible.cfg
  configured module search path = ['/home/maat/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/pyenv/versions/3.10.2/envs/ansible530/lib/python3.10/site-packages/ansible
  ansible collection location = /home/maat/bacher/git/dos/collections/bacher-ansible-collections/collections/ansible_collections
  executable location = /usr/local/pyenv/versions/ansible530/bin/ansible
  python version = 3.10.2 (main, Sep  1 2022, 11:32:33) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = False
``` 

### AWX version

21.23.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

5.3.0

### Operating system

Debian 11.4

### Steps to reproduce

awx export --conf.host https://<hostname> --conf.username <user> --conf.password <pwd> -k --inventory ['inv01' ,'inv01'] -f yaml

### Expected results

Return the objectd defined in the list

### Actual results

Empty list
