### ISSUE TITLE
Missing instance_groups on cli and awx.awx.role

### ISSUE THREAD

**Issue by tanganellilore** [ansible/awx#13783]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi team,

after this pull request https://github.com/ansible/awx/pull/13584 and publish of AWX 21.14.0, I notice that `awxkit 21.14.0` and `awx.awx collection` not have implemented correctly new instance_groups role.

I will propose a pull request that will fix it.

### AWX version

 21.14.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Firefox, Chrome

### Steps to reproduce

Try to run:

CLI:
`awx teams grant --instance_group your_instance_group --role admin your_team` or `awx users grant --instance_group your_instance_group --role use your_user`

Collection:
```yaml
- name: Add Instace group permission to team
  awx.awx.role:
    role: "{{ item }}"
    instance_groups: 
      - "your_instance_group"
    team: "your_team"
    state: present
```

### Expected results

Permission associated to user/team

### Actual results

No permission associated to user/team
