### ISSUE TITLE
Export objects with `all` option not working

### ISSUE THREAD

**Issue by phildri** [ansible/awx#13801]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The option `all` in the `export` module is not working anymore. @ArtsiomMusin already answered to the corresponding code comment in https://github.com/ansible/awx/commit/c39172f516fdcc28318203e9327fa7758647dfbc and confirmed the bug.

### AWX version

22.0.0

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

As an example, export the workflow templates as follows:
```
- name: Export all workflows
  awx.awx.export:
    workflow_job_templates: 'all'
```

### Expected results

Complete export of all workflow templates

### Actual results

The string `all` is converted to a list and the assets are empty:
```
  assets:
    workflow_job_templates: []
  invocation:
    module_args:
      all: false
      applications: null
      controller_config_file: null
      controller_host: xyz
      controller_oauthtoken: null
      controller_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      controller_username: xyz
      credential_types: null
      credentials: null
      execution_environments: null
      inventory: null
      inventory_sources: null
      job_templates: null
      notification_templates: null
      organizations: null
      projects: null
      schedules: null
      teams: null
      users: null
      validate_certs: null
      workflow_job_templates:
      - all
```
