### ISSUE TITLE
Source control authentication with GitHub App instead of PAT

### ISSUE THREAD

**Issue by OneCyrus** [ansible/awx#13859]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Currently the authentication against a GitHub repository is done through a personal access token (PAT). This token is always associated to a specific user account which is not that great in an enterpise environment.

For server to server communication GitHub recommends GItHub App which uses token exchange for short lived tokens. It would be great to have this as an alternative to PAT.

https://docs.github.com/en/get-started/quickstart/github-glossary#server-to-server-request
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Add a GitHub repro credential. There's only the option for a PAT.

### Current results

a PAT is used which is associated to a specific user

### Sugested feature result

Decouple GitHub access from a user account. This allows also to change permission on GitHub to different repos without generating a new PAT for every change.

**Comment by nikhil-nomula** [comment]
You can use github organization PAT to get around it

**Comment by akingstonlas** [comment]
Hello,

We are also interested GItHub App compatibility as well, as the usage of PAT does not align well with some of our security compliance requirements.

**Comment by sbrile** [comment]
+1  also interested

**Comment by hollebevi** [comment]
+1 Also interested, Personals Access Token are not the recommended way for production usage.

**Comment by chrheg** [comment]
+1 also interested.

**Comment by bmainard** [comment]
+1 also interested.

**Comment by marymerc** [comment]
+1 also interested

**Comment by hrgrigorov** [comment]
+1 also interested

**Comment by bobshinabery** [comment]
+1 I am currently looking for a solution to this as well

**Comment by amalivert** [comment]
+1 looking for something similar

**Comment by flippipe** [comment]
I also would like something more native in AWX, but with AWX features I could solve the issue.

First, develop a credential plugin as documented in
https://github.com/ansible/awx-custom-credential-plugin-example/tree/master

In AWX there are more examples of Plugins
https://github.com/ansible/awx/tree/devel/awx/main/credential_plugins

To build the plugin,
[Example: Using Python to generate a JWT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-python-to-generate-a-jwt)

[Using an installation access token to authenticate as an app installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#using-an-installation-access-token-to-authenticate-as-an-app-installation)

In the end, this credential plugin, just return a token, like a PAT.

Second, it is necessary to link the password of the a "Source Control" Credential with the result of the previous plugin, as explained in [HashiCorp Vault SSH Secrets Engine](https://github.com/ansible/awx/blob/devel/docs/credentials/credential_plugins.md#hashicorp-vault-ssh-secrets-engine)

Different secrets, but same concept.

**Comment by nwaringa** [comment]
I don't have an AWX solution for you all (regrettably). but I put together this quick Golang app that may help in a partial solve. https://github.com/nwaringa/tokenclone. 

_The (theoretical) pattern is essentially a two step workflow:_
- Run job with auth, clone repos down 
- Run your job with repos existing

Internally we are playing with this.

**Comment by E0482204** [comment]
I just wanted to share how I solved this for anyone else that has been stuck on this. It took me entirely too long and it was a bit more complex than I'd like but I'm happy with the result. Thanks to @flippipe for all the links and background.  

Here's what I did:

- Created GitHub App and noted associated private key, App ID, and Installation ID
- Added repos to the GH App
- Created a new Credential Type and Credential in AAP/AWX to house those 3 secrets
- Leveraged the [Github App lookup](https://docs.ansible.com/ansible/latest/collections/community/general/github_app_access_token_lookup.html) in community.general while referencing the new credential type to get short lived token
- Authenticated via the token with `https://x-access-token:{{ token}}@github.com/<org>/<repo>.git`

Here's an example of a playbook leverage a role in a remote, private repository. Because requirements.yml is statically defined, I had to work around this by having some tasks to dynamically create a requirements.yml. 

```
- name: Create Dynamic requirements.yml
  ansible.builtin.copy:
    dest: /tmp/requirements.yml
    content: |
      roles:
        - name: "my_namespace.my_collection.my_role"
          src: git+https://x-access-token:{{ lookup('community.general.github_app_access_token', key_path=key_path, app_id=app_id, installation_id=installation_id) }}@github.com/my-gh-org/my-gh-repo.git
          version: main
  check_mode: false  # Always execute this task

- name: Install collections and roles from requirements.yml
  ansible.builtin.command:
    cmd: "ansible-galaxy install -r /tmp/requirements.yml -vvv"
  check_mode: false  # Always execute this task
```

When referencing the role, I had to use `include role` to dynamically include because roles run before any other plays, and the lookup would not work in the requirements.yml. There may be a way around this, but I am unaware of it. 
```
- name: Configure Something
  hosts: hosts-needing-role
  tasks:
    - name: Apply Role
      ansible.builtin.include_role: # "include_role" here is used because the role needs to be dynamically added
        name: my_namespace.my_collection.my_role`
```
