### ISSUE TITLE
 Bug Report: awx.awx.export all does not work.

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#13853]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

using the all option does not work as noted in the [example](https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/export.py#L111)

It should export everything from that endpoint

I tested this with both the recent pip release of awxkit, and one compiled from dev.

I also tested with the cli directly and it worked using the command
```
awx export --conf.host https://controller --conf.username admin --conf.password 123 --conf.insecure --users --users > users.json
```

### AWX version

22.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.14.4

### Operating system

Fedora

### Steps to reproduce

Run the following playbook
```
---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  environment:
     CONTROLLER_HOST: controller.nas
     CONTROLLER_USERNAME: admin
     CONTROLLER_PASSWORD: secret123
     CONTROLLER_VERIFY_SSL: False

  tasks:
    - name: Export all users
      awx.awx.export:
        users: 'all'
      register: export_results

    - name: Export users to file
      copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: usersa.yaml
...
```
### Expected results
```
---
assets:
  users:
    - username: AWX-Collection-tests-controller_role-user
      first_name: Joe
      last_name: User
      email: joe@example.org
      is_superuser: false
      is_system_auditor: false
      password: controller_password
      related:
        roles:
          - name: Execute
            type: role
            content_object:
              organization:
                name: Default
                type: organization
              name: test-role-workflow
              type: workflow_job_template
      natural_key:
        username: AWX-Collection-tests-controller_role-user
        type: user
    - username: AWX-Collection-tests-controller_role-user-ClPzjxrRTIwcOCvO
      first_name: Joe
      last_name: User
      email: joe@example.org
      is_superuser: false
      is_system_auditor: false
      password: controller_password
      related:
        roles: []
      natural_key:
        username: AWX-Collection-tests-controller_role-user-ClPzjxrRTIwcOCvO
        type: user
changed: false
failed: false
...
```

### Actual results
```
---
assets:
    users: []
changed: false
failed: false
...
```
### Additional information

I asked @TheRealHaoLiu  to test as well to make sure it was not a local problem.
