### ISSUE TITLE
Literal value of ansible variable "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"

### ISSUE THREAD

**Issue by Klaas-** [ansible/awx#13912]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi,
it seems in certain scenarios the literal value of a variable inside ansible code running within awx is "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"

### AWX version

22.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.14.5]

### Operating system

quay.io/ansible/awx-ee c18d73b8295b7 VMs: RHEL8.7

### Web browser

Firefox

### Steps to reproduce

I am using azure keyvault to get a secret, and then write it to a file. 
azure_rm_keyvaultsecret_info is running on localhost (awx-ee), copy is running on the target server
```
- name: get awx service principal client secret in key vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "{{ awx_key_vault_uri }}"
    client_id: "{{ awx_service_principal_application_id }}"
    secret: "{{ awx_service_principal_client_secret }}"
    tenant: "{{ awx_service_principal_tenant }}"
    subscription_id: "{{ awx_key_vault_subscript_id }}"
    name:  "{{ awx_instance_name }}-controller-service-principal-client-secret"
  register: azure_rm_keyvaultsecret_info_controller_service_principal_client_secret
  delegate_to: localhost

- ansible.builtin.copy:
    content: Secret {{ azure_rm_keyvaultsecret_info_controller_service_principal_client_secret.secrets[0].secret }}
    dest: /tmp/test_secret
```

### Expected results

If I run the same code on cli, python 3.9 venv with same ansible-core version I get the right result, the file will show
```
cat /tmp/test_secret
Secret contents_of_secret_in_keyvault
```

### Actual results

Now if I look at /tmp/test_secret on the target it reads:

```
cat /tmp/test_secret
Secret VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
```
