### ISSUE TITLE
Launch scripts don't work as non-root

### ISSUE THREAD

**Issue by ToxicGLaDOS** [ansible/awx#13951]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

In each of the launch scripts ([launch_awx_rsyslog.sh](https://github.com/ansible/awx/blob/devel/tools/ansible/roles/dockerfile/files/launch_awx_rsyslog.sh), [launch_awx_task.sh](https://github.com/ansible/awx/blob/devel/tools/ansible/roles/dockerfile/files/launch_awx_task.sh), [launch_awx_web.sh](https://github.com/ansible/awx/blob/devel/tools/ansible/roles/dockerfile/files/launch_awx_web.sh)), there's this block:

```bash
if [ `id -u` -ge 500 ]; then
    echo "awx:x:`id -u`:`id -g`:,,,:/var/lib/awx:/bin/bash" >> /tmp/passwd
    cat /tmp/passwd > /etc/passwd
    rm /tmp/passwd
fi
```

But the logic doesn't make sense to me. If our UID is greater than 500 then we don't have root privileges so we can't edit `/etc/passwd`. For us this presents as `/usr/bin/launch_awx_task.sh: line 4: /etc/passwd: Permission denied` in the container logs when running as UID = 1000. @rooftopcellist  Could you explain what this block is there to accomplish? It looks like it was added by you in #9289.

### AWX version

22.0.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Deploy AWX with a security context that defines `runAsUser` and `runAsGroup`. Here's a script that deploys awx fresh and shows the issue.

```
#!/usr/bin/env bash

cat << EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.0.1

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.0.1

namespace: awx
EOF

kubectl apply -k .

cat << EOF > awx.yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  image_pull_policy: Always
  service_type: nodeport
  security_context_settings:
    runAsGroup: 1000
    runAsUser: 1000
EOF

kubectl apply -f awx.yaml
```

After the awx-task pod comes up you can see the error in the awx-task, awx-rsyslog and awx-ee containers
```
> k logs -n awx awx-task-5c6d49b7fb-lglgx -c awx-task
/usr/bin/launch_awx_rsyslog.sh: line 4: /etc/passwd: Permission denied
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
...
```

### Expected results

AWX runs properly as a non-root user

### Actual results

3 (awx-ee, awx-task, awx-rsyslog) of the 4 containers in the pod fail to start with similar errors `/usr/bin/launch_awx_task.sh: line 4: /etc/passwd: Permission denied`. The redis container starts up normally.
