### ISSUE TITLE
awx.awx.import module issue importing inventory_sources

### ISSUE THREAD

**Issue by pombaer** [ansible/awx#13967]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am using "awx.awx.import" like:

```
- name: "AWX | create inventory sources"
  awx.awx.import:
    assets: "{{ awx_inventory_sources.assets | to_json }}"
  environment:
    CONTROLLER_VERIFY_SSL: "{{ awx_cli_verify_ssl }}"
    CONTROLLER_HOST: "{{ awx_hostname }}"
    CONTROLLER_USERNAME: "{{ awx_username }}"
    CONTROLLER_PASSWORD: "{{ awx_password }}"
```
To import the following yaml:
```
assets:
  inventory_sources:
  - credential: null
    description: ''
    enabled_value: ''
    enabled_var: ''
    execution_environment:
      name: Custom AWX EE
      type: execution_environment
    host_filter: ''
    inventory:
      name: 'inv: ansible-staging'
      organization:
        name: Default
        type: organization
      type: inventory
    limit: ''
    name: "source inv: ansible-staging"
    natural_key:
      inventory:
        name: 'inv: ansible-staging'
        organization:
          name: Default
          type: organization
        type: inventory
      name: "source inv: ansible-staging"
      type: inventory_source
    overwrite: true
    overwrite_vars: true
    related:
      notification_templates_error: []
      notification_templates_started: []
      notification_templates_success: []
      schedules: []
    scm_branch: ''
    source: scm
    source_path: hosts.yml
    source_project:
      name: "git: inventory-staging"
      organization:
        name: Default
        type: organization
      type: project
    source_vars: '---'
    timeout: 0
    update_cache_timeout: 0
    update_on_launch: true
    verbosity: 1
```
The code workd if there is already an "Source" definition on the inventory, if the inventory does not contain an "Source" definition yet the following error occurs:

```
  msg: |-
    /api/v2/inventory_sources/ "source inv: ansible-staging": Bad Request (400) received - {'inventory': ['This field cannot be blank.']}.
```

### AWX version

22.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.14.5]

### Operating system

Debian 11.4

### Steps to reproduce

Create a Inventory without a Source definition and try to import a inventory_source definition using "awx.awx.import", this should end in an error, after that manually create a Source definition for the inventory and try to import the same inventory_source definition , this time it should work.

The Object can be exported with "awx.awx.export".

### Expected results

The inventory_source definition should be created and synchronized.

### Actual results

Error is :

  msg: |-
    /api/v2/inventory_sources/ "source inv: ansible-staging": Bad Request (400) received - {'inventory': ['This field cannot be blank.']}.
