### ISSUE TITLE
Try to applied credential_admin to team

### ISSUE THREAD

**Issue by nicolaspn** [ansible/awx#13984]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello,

I tried to apply `credential_admin` to a specific team for a credential, but it doesn't apply and I don't get an error running the playbook (also not changed).

thanks for your help

### AWX version

22.1.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Ansible version

ansible [core 2.14.5]

### Operating system

Ubuntu

### Web browser

Chrome

### Steps to reproduce

Execute playbook with this vars and tasks:

```
  vars:
    user: user1
    team: myteam
    organization: myorg
    credentials:
      credential_vault:
        name: "my vault credential"
        credential_type: Vault

  tasks:
    - name: Create organization
      awx.awx.organization:
        name: "{{ organization }}"
        description: "My org test"

    - name: Create teams
      awx.awx.team:
        name: "{{ team }}"
        description: "team"
        organization: "{{ organization }}"

    - name: Create users
      awx.awx.user:
        username: "{{ user }}"
        password: "password"
        update_secrets: false

    - name: Create credentials
      awx.awx.credential:
        name: "{{ item.value.name }}"
        organization: "{{ organization }}"
        description: "{{ item.value.description | default(omit) }}"
        credential_type: "{{ item.value.credential_type | mandatory }}"
        inputs: "{{ item.value.inputs | default(omit) }}"
        state: "{{ item.value.state | default('present') }}"
      loop: "{{ credentials | dict2items }}"
      no_log: true

    - name: Allow team to edit credentials
      awx.awx.role:
        role: credential_admin
        organizations: "{{ organization  }}"
        credentials: "{{ credentials.values() | map(attribute='name') | list }}"
        target_teams: "{{ team }}"

### Expected results

The user in the team: "myteam" can view and modifiy the credential "my vault credential", but it's not.


### Actual results

In the playbook execution no error and no change:
```
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "controller_config_file": null,
            "controller_host": "http://x.x.x.x",
            "controller_oauthtoken": null,
            "controller_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "controller_username": "admin",
            "credential": null,
            "credentials": [
                "my vault credential"
            ],
            "instance_groups": null,
            "inventories": null,
            "inventory": null,
            "job_template": null,
            "job_templates": null,
            "lookup_organization": null,
            "organization": null,
            "organizations": [
                "myorg"
            ],
            "project": null,
            "projects": null,
            "target_team": null,
            "target_teams": [
                "myteam"
            ],
            "team": null,
            "user": null,
            "validate_certs": false,
            "workflow": null,
            "workflows": null
        }
    },
    "role": "credential_admin"
}
```


### Additional information

_No response_

**Comment by AlanCoding** [comment]
Here's are more simple reproducer tasks:

```yaml
- name: Create teams
  awx.awx.team:
    name: ateam
    description: "team"
    organization: "Default"

- name: Create credential
  awx.awx.credential:
    name: acredential
    organization: Default
    credential_type: Machine

- name: Allow team to edit credentials
  awx.awx.role:
    role: credential_admin
    organizations:
      - Default
    credentials:
      - acredential
    target_teams: ateam
```

At first glance I think this looks valid.
