### ISSUE TITLE
awx.awx.import / awx import issue with inventories:

### ISSUE THREAD

**Issue by pombaer** [ansible/awx#13996]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I have an inventory called "empty" without source, very basic, only "localhost" is defined:

```
inventory:
- description: 'empty inv'
  host_filter: null
  kind: ''
  name: empty
  natural_key:
    name: empty
    organization:
      name: Default
      type: organization
    type: inventory
  organization:
    name: Default
    type: organization
  prevent_instance_group_fallback: false
  related:
    groups: []
    hosts:
    - description: ''
      enabled: true
      instance_id: ''
      inventory:
        name: empty
        organization:
          name: Default
          type: organization
        type: inventory
      name: localhost
      natural_key:
        inventory:
          name: empty
          organization:
            name: Default
            type: organization
          type: inventory
        name: localhost
        type: host
      related:
        groups: []
      variables: '---'
    labels: []
  variables: '---'
```

Running following command does not raise an error but also does not import the inventory:

```
awx import -k -f yaml < empty.yml
```
Same behavior with awx.awx.import:
```
- name: "create empty inventory"
  awx.awx.import:
    assets: "{{ empty_inventory }}"
  environment:
    CONTROLLER_VERIFY_SSL: "{{ awx_cli_verify_ssl }}"
    CONTROLLER_HOST: "{{ awx_hostname | default(inventory_hostname) }}"
    CONTROLLER_USERNAME: "{{ awx_username | default(awx_admin_username) }}"
    CONTROLLER_PASSWORD: "{{ awx_password | default(awx_admin_password) }}"
```

This worked on a previous version, dont know which, but it was a recent version 21.x or so.

If i have a clean installation of AWX, only containing Organizations i have to create a dummy project and a dummy inventory before issuing the command, otherwise i get an error:

```
awx import -k -f yaml < empty.yml
Insufficient privileges on /api/v2/inventory_sources/, inferring POST fields from description.
Insufficient privileges on /api/v2/job_templates/, inferring POST fields from description.
```

I think this is also an error but i can work around it, so i can live with it.

May the behavior is intended since newer versions of awx, but cannot imagine.

### AWX version

22.2.0

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Debian 11.4

### Steps to reproduce

Run the commands above.

### Expected results

Inventory should be created

### Actual results

Inventoy is not created, no error occurs, in case of playbook "OK" is returned by the awx.awx.import task.

### Additional information

awxkit: 22.2.0
awx.awx collection: 22.2.0
