### ISSUE TITLE
ad_hoc_command: execution_environment option is ignored

### ISSUE THREAD

**Issue by akira6592** [ansible/awx#14104]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The `execution_environment` option in `ad_hoc_command` module is ignored and runs with the default EE (`AWX EE (latest)`).

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Run with `execution_environment` option in the `awx.awx.ad_hoc_command` module. As in the following Playbook.

```yaml
    - name: Ad Hoc command test
      awx.awx.ad_hoc_command:
        inventory: Demo Inventory
        credential: Demo Credential 
        module_name: command
        module_args: echo I <3 Ansible
        execution_environment: my_ee
        wait: true
````

### Expected results

Runs in the execution environment specified by the execution_environment option.

### Actual results

The execution_environment option is ignored and runs with the default EE (`AWX EE (latest)`).
