### ISSUE TITLE
awx.awx.credential examples for use of external storage systems

### ISSUE THREAD

**Issue by samweisgamdschie** [ansible/awx#14114]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

I want to write a playbook to setup our AWX and need to add a credential which is linked to another credential. Our setup looks like:

HashiCorp Vault: here we have all our credentials, secrets, keys,... 

AWX:
* a credential with type `HashiCorp Vault Secret Lookup`, let's call it `cred-hashicorp`
* many other credentials like a credential with type `Source Control` wich reads the used key from `cred-hashicorp`. Let's call it `cred-git`.

It works when I manually create these credentials. Setting up `cred-hashicorp` works with awx.awx.credential as well.

But there is no documentation nor example (that I found) that describes how I can use ansible awx.awx.credential (or maybe another module?) to create `cred-git`.

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

```
    - name: Cred cred-hashicorp
      awx.awx.credential:
        credential_type: HashiCorp Vault Secret Lookup
        name: cred-hashicorp
        inputs:
          url: https://vault.company.at
          role_id: roleeee
          api_version: v2
          default_auth_path: approle
          secret_id: secretttttt
    - name: Cred cred-git
      awx.awx.credential_input_source:
        credential_type: Source Control
        name: cred-git
        inputs:
          tba: tba
```

### Current results

Not possible to use ansible to create a "linked" credential.

### Sugested feature result

A way to create a "linked" credential via ansible.

**Comment by fosterseth** [comment]
@john-westcott-iv do you know if linking creds is supported in awx collection? maybe work needs to be done to allow this

**Comment by AlanCoding** [comment]
John is actually doing some things of the sort in https://github.com/ansible/awx/pull/14168

This snippet may go out of date, but...

```yaml
- name: Create a HashiCorp Vault Credential
  awx.awx.credential:
    credential_type: HashiCorp Vault Secret Lookup
    name: Vault Lookup Cred
    organization: Default
    inputs:
      api_version: "v1"
      cacert: ""
      default_auth_path: "approle"
      kubernetes_role: ""
      namespace: ""
      role_id: ""
      secret_id: ""
      token: "{{ Initial_Root_Token }}"
      url: "http://tools_vault_1:1234"
  register: vault_cred

- name: Create a custom credential type
  awx.awx.credential_type:
    name: Vault Custom Cred Type
    kind: cloud
    injectors:
      extra_vars:
        the_secret_from_vault: "{{ '{{' }} password {{ '}}' }}"
    inputs:
      fields:
        - type: "string"
          id: "password"
          label: "Password"
          secret: true
  register: custom_vault_cred_type

- name: Create a credential of the custom type
  awx.awx.credential:
    credential_type: "{{ custom_vault_cred_type.id }}"
    name: Credential From Vault
    inputs: {}
    organization: Default
  register: custom_credential

- name: Use the Vault Credential For the new credential
  awx.awx.credential_input_source:
    input_field_name: password
    target_credential: "{{ custom_credential.id }}"
    source_credential: "{{ vault_cred.id }}"
    metadata:
      auth_path: ""
      secret_backend: "my_engine"
      secret_key: "my_key"
      secret_path: "/my_root/my_folder"
      secret_version: ""
```
