### ISSUE TITLE
Improvements to deployments of remote instances via receptor hop when deployed with AWX operator

### ISSUE THREAD

**Issue by whitej6** [ansible/awx#14171]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

When deploying AWX using the operator in an environment where the remote instance (execution) is not reachable from the parent AWX application it is required to deploy a receptor hop instance for the remote instance to connect to. When deploying this we found this to be possibly be not fully supported/documented when using AWX Operator. (Previously this was deployed via docker compose not k8s/operator without any issue).

Example diagram of requirements
<img width="686" alt="image" src="https://github.com/ansible/awx/assets/26559188/6b209d67-fd10-4c3d-9293-4ebc5902f2f7">

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

1. Deploy AWX via operator
2. Deploy receptor hop
3. Connect receptor hop to AWX
4. Deploy remote receptor execution
5. Connect receptor execution to AWX via the receptor hop
6. Trigger a restart of awx_task pod

### Current results

Receptor hop becomes unhealthy and must be reconnected. Appears the receptor control nodes lose the tcp-peer configuration for the receptor hop on restart.

### Sugested feature result

Update the templating of the receptor config to include receptor hop so all instances are able to become healthy without user internvention.

**Comment by whitej6** [comment]
Happy to take this FR, I have identified where the change is needed and have been able to update in a deployment to verify.

**Comment by shanemcd** [comment]
See the work happening in https://github.com/ansible/awx/pull/13904 - you might want to link up with @fosterseth  and see what direction he's heading.

**Comment by fosterseth** [comment]
@whitej6 we don't have plans to deploy a hop node inside of the cluster as part of the operator. Most of my testing for hop nodes has assumed the hop node resides outside of the cluster, in an ec2 instance for example. That is how we envision users deploying a hop node.

It _might_ be possible to deploy a standalone receptor pod in the same cluster as AWX. The main requirements are that the pod
1. can received incoming TCP connections from the control plane nodes and from remote execution nodes (like in your diagram)
2. you have a way to provision or setup receptor to run on that hop node. Ideally you'd be able to use the install bundle playbook that you download from the API, same as setting up an execution node.

**Comment by whitej6** [comment]
In my specific ask/use case I will say the deployment of the receptor hop including exposing ports for comms is out of scope. 

The ask is to patch a receptor task the rebuilds the receptor.conf files to include type of hop node.  What I experienced when deploying AWX via the operator is the receptor.conf file gets destroyed and recreated after a restart of awx_task (and sometimes without a restart). This behavior is not observed when not using the operator to deploy. 

`awx/main/tasks/receptor.py`

```python
@task()
def write_receptor_config():
    lock = FileLock(__RECEPTOR_CONF_LOCKFILE)
    with lock:
        receptor_config = list(RECEPTOR_CONFIG_STARTER)

        this_inst = Instance.objects.me()
        instances = Instance.objects.filter(node_type=Instance.Types.EXECUTION)
        existing_peers = {link.target_id for link in InstanceLink.objects.filter(source=this_inst)}
        new_links = []
        for instance in instances:
            peer = {'tcp-peer': {'address': f'{instance.hostname}:{instance.listener_port}', 'tls': 'tlsclient'}}
            receptor_config.append(peer)
            if instance.id not in existing_peers:
                new_links.append(InstanceLink(source=this_inst, target=instance, link_state=InstanceLink.States.ADDING))

        InstanceLink.objects.bulk_create(new_links)

        ### Proposed changes begin ###
        for instance in Instance.objects.filter(node_type=Instance.Types.HOP):
            receptor_config.append(
                {'tcp-peer': {'address': f'{instance.hostname}:{instance.listener_port}', 'tls': 'tlsclient'}}
            )
        ### Proposed changes end ###

        with open(__RECEPTOR_CONF, 'w') as file:
            yaml.dump(receptor_config, file, default_flow_style=False)
```

I didn't not want to add it to the initial queryset of instances as I was not sure if the `InstanceLink` creation would be applicable. The above update solved my ask in my current deployment.

**Comment by whitej6** [comment]
@fosterseth I have an updated diagram below to better describe the scenario. I hope the example proposed change and this diagram helps describe the issue I ran into and how I solved it. 

<img width="685" alt="image" src="https://github.com/ansible/awx/assets/26559188/f6ecd2fb-dff5-4269-80fe-90146ff03231">

**Comment by fosterseth** [comment]
@whitej6 if you deploy AWX on k8s with
```
image: ghcr.io/ansible/awx
image_version: feature_hop-node
```
You should see the addition of hop node support in the UI and API. We are expecting users to setup a hop node outside of the cluster, and I haven't tested whether it would work with hop node inside of the cluster as you have in your diagram.

How are you starting the receptor sidecar? do you have a podspec example you can share?

**Comment by nniehoff** [comment]
We actually aren't using a sidecar but a separate StatefulSet:

```yaml
---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "receptor-hop"
  labels:
    app.kubernetes.io/name: "awx"
    app.kubernetes.io/component: "receptor"
spec:
  serviceName: "receptor-hop"
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "awx"
      app.kubernetes.io/component: "receptor"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "awx"
        app.kubernetes.io/component: "receptor"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: "awx"
                  app.kubernetes.io/component: "receptor"
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: "awx"
                    app.kubernetes.io/component: "receptor"
                topologyKey: "topology.kubernetes.io/zone"
              weight: 10
      securityContext:
        runAsUser: 1000
      initContainers:
        - command:
            - "/bin/sh"
            - "-c"
            - |
              hostname=$MY_POD_NAME
              receptor --cert-makereq bits=2048 commonname=$hostname dnsname=awx-hop.awx.example.com dnsname=$hostname dnsname=$hostname.receptor-hop.awx.svc.cluster.local dnsname=receptor-hop.awx.svc.cluster.local nodeid=$hostname nodeid=receptor-hop.awx.svc.cluster.local nodeid=$hostname.receptor-hop.awx.svc.cluster.local outreq=/etc/receptor/tls/receptor.req outkey=/etc/receptor/tls/receptor.key
              receptor --cert-signreq req=/etc/receptor/tls/receptor.req cacert=/etc/receptor/tls/ca/receptor-ca.crt cakey=/etc/receptor/tls/ca/receptor-ca.key outcert=/etc/receptor/tls/receptor.crt verify=yes
              cp /etc/receptor/hop-receptor.conf /etc/receptor/receptor.conf
              sed -i "s/HOSTNAME/$HOSTNAME/g" /etc/receptor/receptor.conf
          env:
            - name: "MY_POD_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "metadata.name"
          image: "quay.io/ansible/awx-ee:latest"
          imagePullPolicy: "IfNotPresent"
          name: "init"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "250m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: "/etc/receptor"
              name: "hop-receptor-config"
            - mountPath: "/etc/receptor/tls/ca/receptor-ca.crt"
              name: "awx-receptor-ca"
              readOnly: true
              subPath: "tls.crt"
            - mountPath: "/etc/receptor/tls/ca/receptor-ca.key"
              name: "awx-receptor-ca"
              readOnly: true
              subPath: "tls.key"
            - mountPath: "/etc/receptor/tls/"
              name: "awx-receptor-tls"
            - mountPath: "/etc/receptor/hop-receptor.conf"
              name: "hop-receptor-config-template"
              readOnly: true
              subPath: "hop-receptor.conf"
      containers:
        - name: "receptor"
          command:
            - "receptor"
          args:
            - "--config"
            - "/etc/receptor/receptor.conf"
          env:
            - name: "RECEPTORCTL_SOCKET"
              value: "/tmp/receptor.sock"
            - name: "RECEPTORCTL_CONFIG"
              value: "/etc/receptor/receptor.conf"
            - name: "RECEPTORCTL_TLSCLIENT"
              value: "tlsclient"
          image: "quay.io/ansible/awx-ee:latest"
          ports:
            - containerPort: 5555
              name: "receptor"
          volumeMounts:
            - mountPath: "/etc/receptor"
              name: "hop-receptor-config"
            - mountPath: "/etc/receptor/tls/ca/receptor-ca.crt"
              name: "awx-receptor-ca"
              readOnly: true
              subPath: "tls.crt"
            - mountPath: "/etc/receptor/tls/"
              name: "awx-receptor-tls"
      volumes:
        - name: "hop-receptor-config-template"
          configMap:
            name: "hop-receptor-config"
        - name: "awx-receptor-ca"
          secret:
            defaultMode: 420
            secretName: "awx-receptor-ca"  # pragma: allowlist secret
        - name: "awx-receptor-tls"
          emptyDir: {}
        - name: "hop-receptor-config"
          emptyDir: {}
```
