### ISSUE TITLE
Fix collection module documentation.

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx#14208]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

The collection modules can currently take name or ID for related fields. i.e. in the `inventory` module there is a parameter called `organization`. And the docs state:
```
    organization:
      description:
        - Organization the inventory belongs to.
      required: True
      type: str
```
When ID would also be a valid input in addition to the name.

Additionally, when #14205 merges NAMED_URL will also be supported. The documentation for all modules should be updated to allow for name or ID like in `bulk_host_create`:
```
    inventory:
      description:
        - Inventory name or ID the hosts should be made a member of.
      required: True
      type: str
```

And any items that can support a named URL should have that included as well. For example `bulk_host_create`'s inventory parameter would be updated to:
```
    inventory:
      description:
        - Inventory name, ID or named URL the hosts should be made a member of.
      required: True
      type: str
```

A list of objects support named URL can be found by looking at `api/v2/settings/all/` for the property `NAMED_URL_FORMATS`.

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Steps to reproduce

Run `ansible-doc awx.awx.job_template` look at referenced items and see they just say name. 

### Expected results

All documentation should render correctly and report NAMED URL, ID or Name

### Actual results

Most modules currently just say name.
