### ISSUE TITLE
Job_type for workflows

### ISSUE THREAD

**Issue by Mithur-Niranjan** [ansible/awx#14217]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

The job templates have check_mode. However we can't enable a check_mode for workflows.

If we can have a UI feature for job_type and add check mode there it should automatically run all the job templates inside that workflow in check_mode job_type

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

None. As this is a request for new feature

### Current results

New feature. The workaround is to create a new workflow with dry run. 

### Sugested feature result

Will enable a workflow to be run as a check_mode.

**Comment by sean-m-sullivan** [comment]
Job templates have a check mode, however there is no way to force all nodes of a workflow to run in check mode. 
However if a job template has the ask_job_type_on_launch flag on, a workflow node then prompts for job type in the creation. 
To do this in the collection you have to include it in the workflow node creation. I've created a sample playbook to illustrate
```
---
- name: sample playbook
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    CONTROLLER_HOST: https://controller.nas
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: secret123
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: Create project
      awx.awx.project:
        name: Demo Project
        scm_type: git
        scm_url: https://github.com/ansible/tower-example.git
        scm_branch: master
        scm_clean: true
        description: Test Project 1
        organization: Default
        wait: true
        update_project: true

    - name: Create job template
      awx.awx.job_template:
        name: Hello
        project: Test Project
        job_type: run
        playbook: helloworld.yml
        ask_job_type_on_launch: true
        ask_inventory_on_launch: true

    - name: Create a workflow job template with workflow nodes in template
      awx.awx.workflow_job_template:
        name: check-workflow
        workflow_nodes:
          - identifier: node201
            job_type: check
            inventory:
              name: localhost
              organization:
                name: Default
            unified_job_template:
              name: Hello
              organization:
                name: Default
              type: job_template
...
```
