### ISSUE TITLE
cannot save a file after executing playbook using tower templates

### ISSUE THREAD

**Issue by vshete93** [ansible/awx#14267]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi team,

I have been trying to save some files as a part of ansible playbook that I am executing using templates on tower. Template executes successfully but I cannot locate the files in the respective location. What can be wrong here? 

### AWX version

22.2.0

### Select the relevant components

- [X] UI
- [X] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

- create a playbook that is used to save config files
- create template on awx tower that uses above playbook
- launch the template, it should execute successfully.

### Expected results

tower successfully saves file inside task container in the provided path (var/lib/awx/projects in my case) in the ansible playbook.

### Actual results

cannot save the file and locate it

### Additional information
```
---
- name: Backup Cisco Router or Switch
  hosts: switches
  gather_facts: no
  connection: local

  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable
    dir_name: var/lib/awx/projects/{new_folder}

  tasks:
    - name: IOS CONFIG
      ios_command:
        commands: show run
      register: output_router

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{dir_name}}"
        state: directory
        mode: '0755'

    - name: SAVE IOS CONFIG
      copy:
        content: "{{ output_router.stdout[0] }}"
        dest: "{{dir_name}}/show_run_{{ inventory_hostname }}.txt"
```
