### ISSUE TITLE
Fresh install on GCP: relation "conf_setting" does not exist at character 158, unable to log-in

### ISSUE THREAD

**Issue by kuchynkap** [ansible/awx#14275]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello,

I am getting " relation "conf_setting" does not exist at character 158" on fresh install on GCP GKE, making the AWX UI unaccessible (HTTP 500). After further investigation I also found "relation "django_migrations" does not exist at character 124". I have checked the migrations status and everything looks ok (below is only a portion of output).

```
kubectl exec -it -n awx awx-web-7775596897-whrq5 -c awx-web -- awx-manage showmigrations and all of them have checkmarks - e.g.:
auth
[X] 0001_initial
[X] 0002_alter_permission_name_max_length
[X] 0003_alter_user_email_max_length
[X] 0004_alter_user_username_opts
[X] 0005_alter_user_last_login_null
```

I have tried this multiple times with the same result.

Versions used:

AWX Operator 2.4.0
AWX 22.5.0
Postgres 13

kustomization.yaml:

```
apiVersion: [kustomize.config.k8s.io/v1beta1](http://kustomize.config.k8s.io/v1beta1)
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - [github.com/ansible/awx-operator/config/default?ref=2.4.0](http://github.com/ansible/awx-operator/config/default?ref=2.4.0)
  - awx.yaml
# Set the image tags to match the git version from above
images:
  - name: [quay.io/ansible/awx-operator](http://quay.io/ansible/awx-operator)
    newTag: 2.4.0

# Specify a custom namespace in which to install AWX
namespace: awx

awx.yaml:
```
---
apiVersion: [awx.ansible.com/v1beta1](http://awx.ansible.com/v1beta1)
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport

```

I would like to ask anyone for help. 

Thank you!

### AWX version

22.5.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

AWX Operator 2.4.0; AWX 22.5.0

### Operating system

_No response_

### Web browser

Chrome, Edge

### Steps to reproduce

Create a standard cluster, can be public or private.

Deploy AWX-Operator version 2.4.0, AWX 22.5.0, following standard definitions:

kustomization.yaml:

```
apiVersion: [kustomize.config.k8s.io/v1beta1](http://kustomize.config.k8s.io/v1beta1)
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - [github.com/ansible/awx-operator/config/default?ref=2.4.0](http://github.com/ansible/awx-operator/config/default?ref=2.4.0)
# Set the image tags to match the git version from above
images:
  - name: [quay.io/ansible/awx-operator](http://quay.io/ansible/awx-operator)
    newTag: 2.4.0

# Specify a custom namespace in which to install AWX
namespace: awx

awx.yaml:
```
---
apiVersion: [awx.ansible.com/v1beta1](http://awx.ansible.com/v1beta1)
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport

```

### Expected results

AWX up and running, being able to log in.

### Actual results

Unable to log in to the Web GUI. Errors in postgres container.
