### ISSUE TITLE
awx.awx.inventory deletion doesn't work

### ISSUE THREAD

**Issue by Avilir** [ansible/awx#14419]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Description

When i try to delete inventory in a playbook using this ansible task :

```
- name: "Delete inventory"
  awx.awx.inventory:
    controller_host: "{{ controller_url }}"
    controller_username: "{{ admin_user }}"
    controller_password: "{{ admin_pass }}"
    validate_certs: "no"
    name: "{{ inv_name }}"
    organization: "{{ org }}"
    state: "absent"
```
I am getting 

```
TASK [Delete inventory] ******************************
ok: [localhost] 
```
And the inventory is not deleted.

### AWX version

AWX X-API-Product-Version: 21.10.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.15.3

### Operating system

MacOS 13.5.1

### Web browser

Chrome

### Steps to reproduce

Run a playbook which:

- create an inventory
- delete the inventory

```
tasks:
  - name: "Create an inventory"
    awx.awx.inventory:
      controller_host: "{{ controller_url }}"
      controller_username: "{{ admin_user }}"
      controller_password: "{{ admin_pass }}"
      validate_certs: "no"
      name: "Testing Inventory"
      organization: "TestingOrg"
      state: "present"
    register: "inventory_result"
  
  - name: "Delete the inventory"
  awx.awx.inventory:
    controller_host: "{{ controller_url }}"
    controller_username: "{{ admin_user }}"
    controller_password: "{{ admin_pass }}"
    validate_certs: "no"
    name: "Testing Inventory"
    organization: "TestingOrg"
    state: "absent"
```

### Expected results

The inventory will create and delete

### Actual results

The inventory created and not deleted

**Comment by iDustbin** [comment]
sry but i cant find any inventory with required variables, i feel to stupid to install it. could you please explain it for stupid people ? which playbook should i start ? im hopeless lost, docker also not working for me. is there not a easy install variant available ? docker-compose.yml & ansible directory including inventory, playbook and requirements.txt when a role is required. would be really helpfull when you could give me a hint.

**Comment by Avilir** [comment]
You just need to run AWX as explain in the README, and then run the playbook i put in the **Steps to reproduce**
don't forget to replace the variables with your information

**Comment by iDustbin** [comment]
but heres is the problem, i clone the repo and theres no playbook or inventory existend ? 
Could you share which folder should it be ? 
im super lost :(

**Comment by AlanCoding** [comment]
I can not reproduce this.

```yaml
- name: "Create an inventory"
  awx.awx.inventory:
    name: "Testing Inventory"
    organization: "Default"
    state: "present"
  register: result

- debug: var=result

- name: "Delete the inventory"
  awx.awx.inventory:
    name: "Testing Inventory"
    organization: "Default"
    state: "absent"
```

If I run this, the debug task gives the id. I check it in the API and it's missing after the playbook finishes.

Perhaps you're running this in a playbook and the next task finds the inventory still exists. We have an async task for deleting inventory, because it can take a long time for large inventories. We could add a `wait` parameter if we haven't already.
