### ISSUE TITLE
Job terminated in error after 4 hours

### ISSUE THREAD

**Issue by Mrmel94** [ansible/awx#14457]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi I have a problem already known by this community. The bug of a job that stop after 4 hours of execution with an error.
The principal issue is known there : https://github.com/ansible/awx/issues/11594

The bug is fix with this PR : https://github.com/ansible/receptor/pull/683 and I read the pre-requisites but still doesn't work and problem still there.

I made my installation with this https://github.com/kurokobo/awx-on-k3s and I'm using custom awx-ee

My job for testing is just a sleep for 18000sec (5h), and I enabled the `K8S Ansible Runner Keep-Alive Message Interval` in awx parameters for 1800sec (30min).

Version of my components : 
K3S server  v1.25.12+k3s1

And this is my custom-ee : 
```
---
version: 3

images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.3
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_files:
    - src: ansible.cfg
      dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:v1.4.1 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
  prepend_final:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    user: root
```

I also tried k3s v1.25.4 and add the environment variable `RECEPTOR_KUBE_SUPPORT_RECONNECT` in the file : awx-on-k3s/base/awx.yaml : 

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
{...}
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled
```
and did `kubectl apply -k base` in the folder awx-on-k3s/ but bug still there

What am i doing wrong? Have I forgotten something?

### AWX version

23.0.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Ansible version

ansible-core==2.15.3

### Operating system

quay.io/rockylinux/rockylinux:9

### Steps to reproduce

Launch job test with 5 hours sleep

### Expected results

Job terminated with errors

### Actual results

Job finish in success

**Comment by fosterseth** [comment]
just to rule it out, does your job complete if you run a sleep command on the default awx-ee image (quay.io/ansible/awx-ee:latest)?

**Comment by Mrmel94** [comment]
I just did the test, I have the same issue with awx-ee:latest . So I think the variable RECEPTOR_KUBE_SUPPORT_RECONNECT is not enable by default (I don't know why because my k3s cluster version (1.25.12) is >= v1.25.4).

But even when I tried to enable this variable, I still have the issue (maybe I don't put in the right place ?). I don't how to check what is the value of RECEPTOR_KUBE_SUPPORT_RECONNECT in my deployment.

**Comment by fosterseth** [comment]
We don't enable it by default, so you have to manually set it.

To check the whether the variable is set correctly:

`RECEPTOR_KUBE_SUPPORT_RECONNECT` is passed into the awx-ee container as an environment variable

so you can kubectl exec into the awx-ee container and run "printenv" and you should see this variable set to `enabled`

**Comment by fosterseth** [comment]
Also, there are issues when you have a silent playbook that doesn't emit new messages for long periods of time, i.e. sleep commands. Things tend to timeout when idle

there is a setting in UI Job Settings called `K8S Ansible Runner Keep-Alive Message Interval`

Try setting that to 30

**Comment by Mrmel94** [comment]
Thanks, for the answer I just checked and indeed, when I did printenv in my custom awx-ee the variable `RECEPTOR_KUBE_SUPPORT_RECONNECT` is not set (I can't find it).

Even tough I set it in the awx-on-k3s/base/awx.yaml file like this : 

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
{...}
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled
```

Is this not the way I should do it ?
And as for the parameter `K8S Ansible Runner Keep-Alive Message Interval` is currently set to 1800. I just set it to 30 like you said.
