### ISSUE TITLE
Custom credential type: Injector configuration with awx.awx.credential module

### ISSUE THREAD

**Issue by D1StrX** [ansible/awx#14456]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

For custom credential types:
The field `Input configuration` can be configured with `inputs`, but the documentation doesn't mention a parameter for Injector configuration. Could this be added?

### Select the relevant components

- [ ] UI
- [ ] API
- [X] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

https://docs.ansible.com/ansible/latest/collections/awx/awx/credential_module.html

### Current results

Non existing option

### Sugested feature result

Extend the collection module with the parameter `input_configuration` to satisfy this field corresponding in AWX/Tower.

**Comment by AlanCoding** [comment]
I cannot understand what this is asking for. The module `awx.awx.credential_type` has the fields `inputs` and `injectors`. The `awx.awx.credential` module, and corresponding API model, only has `inputs`. The credential type inputs field configures the expected structure of the credential inputs of that type. The injectors tell what to do with them.

> For custom credential types:
> The field Input configuration can be configured with inputs, but the documentation doesn't mention a parameter for Injector configuration. 

Can you link what you're quoting here?

**Comment by D1StrX** [comment]
I see I missed some documentation, awx.awx.credential_type is the right one for me.
I might have another question regarding the injectors, escaping jinja2 in yaml. I get the error 'tower' is undefined' when specifying it like this (with awx.awx.credential_type I loop over the applicable fields {{ item.name }}):
```yaml
vars:
    custom_credential_types:
      - name: Kubernetes Kubeconfig2
        description: Kubeconfig2
        inputs:
          fields:
            - id: kube_config
              type: string
              label: kubeconfig
              secret: true
              multiline: true
          required:
            - kube_config
        injector_configuration:
          env:
            K8S_AUTH_KUBECONFIG: "{{ '{{' }} tower.filename.kubeconfig {{ '}}' }}"
          file:
            template.kubeconfig: "{{ '{{' }} kube_config {{ '}}' }}"
```
Also "{% raw %}{{ tower.filename.kubeconfig }} {% endraw %}" isn't escaping the var

I worked around it by regex_replace ]] -> {{ but that's not a nice solution.
```yaml
        injector_configuration:
          env:
            K8S_AUTH_KUBECONFIG: "]] tower.filename.kubeconfig }}"
          file:
            template.kubeconfig: "]] kube_config }}"

```

Ansible version 2.15.4

**Comment by AlanCoding** [comment]
It is tricky, yes, but I have seen people figure this out before. Unfortunately we don't have any content in the tests or docs that will get you all the way there. It is expected to see the pattern of `{{ '{{' }}`, since this is needed just to get the brackets in a string to the API.

It would be best if you could consolidate your example to a playbook with a single task, just for this issue, and share it here. I should be fixable, and maybe we could add it as a task to the tests.

**Comment by D1StrX** [comment]
Hereby the consolidated example:
```yaml
- name: Add machine credentials to AWX
  gather_facts: false
  become: false
  hosts: localhost
  vars:
      custom_credential_types:
      - name: Kubernetes Kubeconfig
        description: Kubeconfig
        inputs:
          fields:
            - id: kube_config
              type: string
              label: kubeconfig
              secret: true
              multiline: true
          required:
            - kube_config
        injector_configuration:
          env:
            K8S_AUTH_KUBECONFIG: "{{ tower.filename.kubeconfig }}" # <-- escape var tower.filename.kubeconfig
          file:
            template.kubeconfig: "{{ kube_config }}" # <-- escape var kube_config
  tasks:
    - name: Add Custom credential Kubeconfig credential
      awx.awx.credential_type:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        kind: cloud
        state: present
        controller_config_file: "~/.awx_credentials.cfg"
        inputs: "{{ item.inputs }}"
        injectors: "{{ item.injector_configuration }}"
        validate_certs: true
      loop: "{{ custom_credential_types }}"
      
```

**Comment by AlanCoding** [comment]
Thanks, I can very easily replicate the error your mention.

> 'tower' is undefined.

However, this is a local templating problem. I tried, and I can't solve it! You have my sympathies, but I must raise a flag that problems like these are out of scope for this issue tracker.

With modifications, I can get this to run and correctly create the credential type.

```yaml
---
- name: Add machine credentials to AWX
  gather_facts: false
  connection: local
  hosts: localhost
  tasks:
    - name: Add Custom credential Kubeconfig credential
      awx.awx.credential_type:
        name: Kubernetes Kubeconfig
        description: Kubeconfig
        kind: cloud
        state: present
        inputs:
          fields:
            - id: kube_config
              type: string
              label: kubeconfig
              secret: true
              multiline: true
          required:
            - kube_config
        injectors:
          env:
            K8S_AUTH_KUBECONFIG: "{{ '{{' }} tower.filename.kubeconfig {{ '}}' }}" # <-- escape var tower.filename.kubeconfig
          file:
            template.kubeconfig: "{{ '{{' }} kube_config {{ '}}' }}" # <-- escape var kube_config
```

I agree, you should be able to save the mapping here (which contain strings that _just happen_ to have "{{" in them) and use it in a loop. Ansible core eagerly templates those variables and complicates doing this. Going from my snippet (which works) to your version with the loop in `vars:` would be a good question for the Ansible core mailing list or forum. For our purposes here it looks like the collection credential_type module and the API are working correctly.
