### ISSUE TITLE
Collection: Controller API Lookup plugin causes Ansible worker crash on macOS

### ISSUE THREAD

**Issue by sinuscosinustan** [ansible/awx#14453]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When I try to use the Controller API Lookup plugin on macOS in a `set_fact` task, the Python process / Ansible worker crashes.

```
objc[42687]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[42687]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

### AWX version

23.0.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.3

### Operating system

macOS 13.5.2 with Nix on arm64

### Steps to reproduce

- Run ansible in a venv with Python 3.9.6
- Set the host, username and password via environment variables (`CONTROLLER_HOST`, `CONTROLLER_USERNAME` and `CONTROLLER_PASSWORD`)
- Execute the sample playbook below

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Test lookup task with fact set
      ansible.builtin.set_fact:
        reg_testfact: "{{ lookup('awx.awx.controller_api', 'settings/ui') }}"
```

### Expected results

A registered fact

### Actual results

Ansible/Python crashes with the above mentioned error
