### ISSUE TITLE
awx.awx.host enabled should not be passed by default

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/awx#14461]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary
If I don't pass the enabled option in the module, it should not be set.

Right now default python bool is false, so as is, the module behaves differently then the API.

https://github.com/ansible/awx/blob/f7a2de8a07dacc6384c8ce81b934d442aa14370a/awx_collection/plugins/modules/host.py#L115C8-L115C28

### AWX version

devel

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

N/A

### Operating system

N/A

### Steps to reproduce

Use host module.
```
- name: Add host
  host:
    name: localhost
    description: "Local Host Group"
    inventory: "Local Inventory"
    state: present
    controller_config_file: "~/tower_cli.cfg"
    variables:
      example_var: 123
```

### Expected results

If I don't pass the enabled option in the module, it should not be set. 

Right now default python bool is false, so as is, the module behaves differently then the API.

### Actual results

Host is added but it is not enabled.
