### ISSUE TITLE
awx.awx.execution_environment

### ISSUE THREAD

**Issue by alice-rc** [ansible/awx#14602]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

If the execution environment was setup with an Organization there is no way to remove that and make it 'Globally Available'.

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.15.4

### Steps to reproduce

Setup an execution environment using awx.awx.execution_environment and setting the organization to something.
Then try to remove that organization using awx.awx.execution_environment and setting the organization to:
organization: None
organization: ""
organization: "Globally Available" <-- this gets an error ```"msg": "Request to /api/v2/organizations/?name=Globally+Available returned 0 items, expected 1"```

### Expected results

organiztion would be removed and thus get set to "Globally Available"

### Actual results

``` yml
TASK [execution_environments : Before] ********************
ok: [awx20] => {
    "query_before": [
        {
            "created": "2023-10-20T16:36:26.094111Z",
            "credential": 1,
            "description": "Standard EE v260",
            "id": 3,
            "image": "<REDACTED>/ee-standard:260",
            "managed": false,
            "modified": "2023-10-25T16:43:19.720398Z",
            "name": "ee-standard-260",
            "organization": 2,
            "pull": "missing",
            "related": {
                "activity_stream": "/api/v2/execution_environments/3/activity_stream/",
                "copy": "/api/v2/execution_environments/3/copy/",
                "created_by": "/api/v2/users/1/",
                "credential": "/api/v2/credentials/1/",
                "modified_by": "/api/v2/users/1/",
                "organization": "/api/v2/organizations/2/",
                "unified_job_templates": "/api/v2/execution_environments/3/unified_job_templates/"
            },
            "summary_fields": {
                "created_by": {
                    "first_name": "",
                    "id": 1,
                    "last_name": "",
                    "username": "<REDACTED>"
                },
                "credential": {
                    "cloud": false,
                    "credential_type_id": 17,
                    "description": "",
                    "id": 1,
                    "kind": "registry",
                    "kubernetes": false,
                    "name": "Default Execution Environment Registry Credential"
                },
                "modified_by": {
                    "first_name": "",
                    "id": 1,
                    "last_name": "",
                    "username": "<REDACTED>"
                },
                "organization": {
                    "description": "<REDACTED>",
                    "id": 2,
                    "name": "Org1"
                },
                "user_capabilities": {
                    "copy": true,
                    "delete": true,
                    "edit": true
                }
            },
            "type": "execution_environment",
            "url": "/api/v2/execution_environments/3/"
        }
    ]
}

TASK [execution_environments : Manage AWX Execution Environments] ***
ok: [awx20 -> localhost] => (item=Managing execution environment ee-standard-260 = present) => {
    "_ee_info": {
        "credential": "Default Execution Environment Registry Credential",
        "desc": "Standard EE v260",
        "image": "<REDACTED>/ee-standard:260",
        "name": "ee-standard-260",
        "pull": "missing",
        "state": "present"
    },
    "ansible_loop_var": "_ee_info",
    "changed": false,				<------ Not changing
    "id": 3,
    "invocation": {
        "module_args": {
            "controller_config_file": "/tmp/awx20-controller_config_file",
            "controller_host": null,
            "controller_oauthtoken": null,
            "controller_password": null,
            "controller_username": null,
            "credential": "Default Execution Environment Registry Credential",
            "description": "Standard EE v260",
            "image": "<REDACTED>/ee-standard:260",
            "name": "ee-standard-260",
            "new_name": null,
            "organization": "",			<------ Note it should be setting it to an empty string
            "pull": "missing",
            "request_timeout": null,
            "state": "present",
            "validate_certs": null
        }
    }
}

TASK [execution_environments : After] *********************
ok: [awx20] => {
    "query_after": [
        {
            "created": "2023-10-20T16:36:26.094111Z",
            "credential": 1,
            "description": "Standard EE v260",
            "id": 3,
            "image": "<REDACTED>/ee-standard:260",
            "managed": false,
            "modified": "2023-10-25T16:43:19.720398Z",
            "name": "ee-standard-260",
            "organization": 2,
            "pull": "missing",
            "related": {
                "activity_stream": "/api/v2/execution_environments/3/activity_stream/",
                "copy": "/api/v2/execution_environments/3/copy/",
                "created_by": "/api/v2/users/1/",
                "credential": "/api/v2/credentials/1/",
                "modified_by": "/api/v2/users/1/",
                "organization": "/api/v2/organizations/2/",
                "unified_job_templates": "/api/v2/execution_environments/3/unified_job_templates/"
            },
            "summary_fields": {
                "created_by": {
                    "first_name": "",
                    "id": 1,
                    "last_name": "",
                    "username": "<REDACTED>"
                },
                "credential": {
                    "cloud": false,
                    "credential_type_id": 17,
                    "description": "",
                    "id": 1,
                    "kind": "registry",
                    "kubernetes": false,
                    "name": "Default Execution Environment Registry Credential"
                },
                "modified_by": {
                    "first_name": "",
                    "id": 1,
                    "last_name": "",
                    "username": "<REDACTED>"
                },
                "organization": {
                    "description": "<REDACTED>",
                    "id": 2,
                    "name": "Org1"
                },
                "user_capabilities": {
                    "copy": true,
                    "delete": true,
                    "edit": true
                }
            },
            "type": "execution_environment",
            "url": "/api/v2/execution_environments/3/"
        }
    ]
}
```
