### ISSUE TITLE
awx api request canceling "Enable Concurrent Jobs" on job template

### ISSUE THREAD

**Issue by ghost** [ansible/awx#14616]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Im using awx version 22.3.0 on kubernetes cluster.
I have ansible playbook that is changing the "Variables" content on job template.

API request:
```

  - uri:
      url: "https://awx.123.com/api/v2/workflow_job_templates/12/"
      method: PUT
      user: admin
      password: admin
      body: 
        survey_enabled: True
        name: "Create vm"
        extra_vars : "---\vm: '{{ vm_name }}'"
      force_basic_auth: yes
      validate_certs: no
      return_content: true
      body_format: json
    register: file_search
    failed_when: file_search.status is undefined or file_search.status <= 0
    when: change_name == "yes"

```

This play with api request works fine, the only issue is - it is canceling on the job template the "Enable Concurrent Jobs" (removing the V from the box") and i need to go and manually fix it.
I have checked for an extra var to add to make "Enable Concurrent Jobs" checked again but haven't found a way.
Thanks.

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

5

### Operating system

ubuntu

### Web browser

Chrome

### Steps to reproduce

running the playbook i have added in description

### Expected results

Changing var name without canceling the "Enable Concurrent Jobs" or at least have a way to re-set it to enabled.

### Actual results

Changing var name and the "Enable Concurrent Jobs" getting canceled.
