### ISSUE TITLE
Make awx.awx.role accept a list input like projects

### ISSUE THREAD

**Issue by cthenb** [ansible/awx#14610]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Looking at documentation, `role `is a single value.
We have the use case where we want to give users both read (to see error log in AWX) and execute privileges.

https://docs.ansible.com/ansible/latest/collections/awx/awx/role_module.html#parameter-role

I'd like to see it become able to handle multiple values like what happened with `project`, which got deprecated for `projects`.

Obviously I can loop, so there is a workaround, but it shouldn't be necessary to do 2 api calls and create 2 policies for something so simple.

### Select the relevant components

- [ ] UI
- [X] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

Now:

```
- name: Give team Y read and execute access to X
 awx.awx.tower_role:
   team: "Y"
   tower_host: "{{ awx_server }}"
   validate_certs: false
   tower_oauthtoken: "{{ tower_token }}"
   role: execute
   job_templates: X
   state: present

- name: Give team Y read and execute access to X
 awx.awx.tower_role:
   team: "Y"
   tower_host: "{{ awx_server }}"
   validate_certs: false
   tower_oauthtoken: "{{ tower_token }}"
   role: read
   job_templates: X
   state: present
```

Desired:

```
- name: Give team Y read and execute access to X
 awx.awx.tower_role:
   team: "Y"
   tower_host: "{{ awx_server }}"
   validate_certs: false
   tower_oauthtoken: "{{ tower_token }}"
   roles: [ execute, read ]
   job_templates: X
   state: present
```

### Current results

If user is only assigned execute privilege, it cannot see why the task failed in AWX.

### Sugested feature result

Be able to assign 2 roles with one policy.
