### ISSUE TITLE
awx.awx.instance is not idempotent

### ISSUE THREAD

**Issue by alice-rc** [ansible/awx#14638]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Running awx.awx.instance more than once, with ```node_state: installed```, generates an error

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.5

### Steps to reproduce

``` yaml
- name: create_instance | Manage the execution node instance
  delegate_to: localhost
  awx.awx.instance:
    controller_config_file: "{{ gv_awx_controller_config_file }}"
    hostname: "{{ ansible_host }}"
    managed_by_policy: true
    node_state: installed
    node_type: execution
    capacity_adjustment: "{{ _instance_capacity_adjustment }}"
    enabled: true
```
Run the task more than once

### Expected results

Expected it to just change the capacity adjustment

### Actual results

```FAILED! => {"changed": false, "msg": "Unable to update instance REDACTED see response", "response": {"json": {"node_state": ["Can only change instances to the 'deprovisioning' state."]}, "status_code": 400}}```
