### ISSUE TITLE
ios_command: Max Recursion error when using Custom Credential

### ISSUE THREAD

**Issue by Dustin-Wi** [ansible/awx#14689]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When trying to execute a Job Template with a single task, I am getting the below error.
```
{
  "msg": "Unexpected failure during module execution: maximum recursion depth exceeded while getting the str of an object",
  "exception": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 165, in run
    res = self._execute()
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 608, in _execute
    socket_path = start_connection(self._play_context, options, self._task._uuid)
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 1230, in start_connection
    write_to_file_descriptor(master, options)
  File \"/usr/local/lib/python3.9/site-packages/ansible/module_utils/connection.py\", line 58, in write_to_file_descriptor
    src = cPickle.dumps(obj, protocol=0)
  File \"/usr/lib64/python3.9/copyreg.py\", line 71, in _reduce_ex
    state = base(self)
RecursionError: maximum recursion depth exceeded while getting the str of an object
",
  "stdout": "",
  "_ansible_no_log": false
}
```

### AWX version

23.4.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.15.7rc1

### Operating system

Red Hat Enterprise Linux release 8.8 (Ootpa)

### Steps to reproduce

Create a custom credential.
Create a playbook that sets "ansible_ssh_pass" to the credential.
Execute a task in the playbook that uses cisco.ios.ios_command module.

### Expected results

Ansible Job should connect to the devices in the inventory and run the commands.

### Actual results

```
{
  "msg": "Unexpected failure during module execution: maximum recursion depth exceeded while getting the str of an object",
  "exception": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 165, in run
    res = self._execute()
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 608, in _execute
    socket_path = start_connection(self._play_context, options, self._task._uuid)
  File \"/usr/local/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 1230, in start_connection
    write_to_file_descriptor(master, options)
  File \"/usr/local/lib/python3.9/site-packages/ansible/module_utils/connection.py\", line 58, in write_to_file_descriptor
    src = cPickle.dumps(obj, protocol=0)
  File \"/usr/lib64/python3.9/copyreg.py\", line 71, in _reduce_ex
    state = base(self)
RecursionError: maximum recursion depth exceeded while getting the str of an object
",
  "stdout": "",
  "_ansible_no_log": false
}
```

### Additional information

inventory has two hosts with no variables set.
Custom Credential Input Configuration:
```
fields:
  - id: a10_username
    type: string
    label: Username
  - id: a10_password
    type: string
    label: Password
    secret: true
required:
  - username
  - password
```

Custom Credential Injection Configuration:
```
extra_vars:
  a10_password: '{{ a10_password }}'
  a10_username: '{{ a10_username }}'
```

Playbook:
```
---
- name: PLAYBOOK - TEST VARIOUS FEATURES AND FUNCTIONS OF ANSIBLE
  connection: ansible.netcommon.network_cli
  hosts: all
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ a10_username }}"
    ansible_ssh_pass: "{{ a10_password }}"

  tasks:
    - name: TESTING CREDENTIALS
      cisco.ios.ios_command:
        commands:
          - show version
```
