### ISSUE TITLE
awx.awx.schedule_rrule,awx.awx.schedule_ruleset 'none' selection for frequency but set 'Daily'

### ISSUE THREAD

**Issue by tenpei-on** [ansible/awx#14696]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Title: "Ansible AWX Collection: 'None' Frequency in schedule_rrule and schedule_ruleset Defaults to 'Daily'"

Description:

vbnet
Copy code
**Summary:**
In the Ansible AWX Collection, a bug has been identified in the `awx.awx.schedule_rrule` and `awx.awx.schedule_ruleset` plugins. When the `frequency` parameter is set to `None`, the system erroneously defaults to a 'Daily' frequency.

**Details:**
- **Affected Components**: `awx.awx.schedule_rrule` and `awx.awx.schedule_ruleset` plugins
- **Issue Description**: The expected behavior when setting `frequency` to `None` is for the schedule to none(run once). However, the current implementation defaults to a 'Daily' frequency, which can lead to unexpected scheduling behavior in automation tasks.
- **Location of Issue**: The problematic code is located at [awx_collection/plugins/lookup/schedule_rruleset.py#L153C27-L153C32](https://github.com/ansible/awx/blob/devel/awx_collection/plugins/lookup/schedule_rruleset.py#L153C27-L153C32).

**Impact:**
This bug may cause unintended daily scheduling in automation workflows, potentially leading to operational disruptions or resource misuse.

**Expected Behavior:**
When `frequency` is set to `None`, no default frequency should be applied, or the behavior should be explicitly documented.

**Suggested Action:**
A review and correction of the default behavior when `frequency` is set to `None` is recommended. Alternatively, updating the documentation to reflect the current functionality would also be beneficial.

### AWX version

N/A

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

ansible [core 2.16.0]

### Steps to reproduce

I used this playbook
```
---      
- hosts: localhost
  gather_facts: false
  vars:  
    schedule_name: scheduled_bug
    deadline: '2024-04-17 10:30:45'
  tasks: 
    - name: Create a ruleset 
      set_fact:
        customized_deadline: "{{ query('ansible.controller.schedule_rruleset', rule=rrules, deadline, timezone=timezone) }}"
      vars:
        rrules:
          - frequency: none
        timezone: 'Asia/Tokyo'
         
    - ansible.controller.schedule:
        name: "{{ schedule_name }}"
        unified_job_template: acd 
        rrule: "{{ customized_deadline }}"
```

and after executing it
I made sure it was set to daily.

### Expected results

```
"customized_deadline": "DTSTART;TZID=Asia/Tokyo:20240417T103000 RRULE:INTERVAL=1;COUNT=1;FREQ=MINUTELY"
```
When I use the data I can set None(Run Once)

### Actual results

```
"customized_deadline": "DTSTART;TZID=Asia/Tokyo:20240430T103045 RRULE:FREQ=DAILY;COUNT=1;INTERVAL=1"
```
