### ISSUE TITLE
AWX behind Corporate Proxy

### ISSUE THREAD

**Issue by fahadshery** [ansible/awx#14731]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi,

VM info:
```
cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="9.2"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Oracle Linux Server 9.2"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:9:2:server"
HOME_URL=https://linux.oracle.com/
BUG_REPORT_URL=https://github.com/oracle/oracle-linux
 
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
ORACLE_BUGZILLA_PRODUCT_VERSION=9.2
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=9.2
```

Kubernetes info:
```
k3s --version
k3s version v1.28.4+k3s2 (6ba6c1b6)
go version go1.20.11
 
kubectl version
Client Version: v1.28.4+k3s2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4+k3s2
 
kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443/
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy
```

my `customisation.yaml` looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.9.0
  - awx.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.9.0

# Specify a custom namespace in which to install AWX
namespace: awx
```

my `awx.yaml` looks like this:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 30080
```

I have setup the `/etc/environment` as:
```
HTTP_PROXY=coporateip:8080
HTTP_PROXY=coporateip:8080
NO_PROXY=127.0.0.1,localhost,local_server_ip
```

here is the kubectl output:
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                               READY   STATUS             RESTARTS       AGE
kube-system   local-path-provisioner-84db5d44d9-x776j            1/1     Running            0              115m
kube-system   coredns-6799fbcd5-bg448                            1/1     Running            0              115m
kube-system   helm-install-traefik-crd-2v7kr                     0/1     Completed          0              115m
kube-system   helm-install-traefik-h7xkx                         0/1     Completed          1              115m
kube-system   svclb-traefik-70966721-6j8j2                       2/2     Running            0              115m
kube-system   metrics-server-67c658944b-2d7f4                    1/1     Running            0              115m
kube-system   traefik-f4564c4f4-hm5fd                            1/1     Running            0              115m
awx           awx-operator-controller-manager-759c4cbc74-7h2pk   2/2     Running            0              63m
awx           awx-postgres-13-0                                  1/1     Running            0              32m
awx           awx-task-79bf676f78-9n5lx                          4/4     Running            0              32m
awx           awx-web-c99df8db-jbt42                             2/3     CrashLoopBackOff   10 (80s ago)   30m
```

as you can see `awx-web-c99df8db-jbt42` is in CrashLoopBackOff. 

Any ideas why the other pods are up and running and awx-web is failing?

### AWX version

2.9.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Spin up Oracle Linux 9
Install GitHub 
Install K3S by: `curl -sfL https://get.k3s.io | sh -`
Create `kustomization.yaml` and `awx.yaml` as given.

### Expected results

Should be able to reach the GUI on my VM IP at port 30080

### Actual results

AWX-WEB pod is crashing
