### ISSUE TITLE
Better error message when Basic authentication is disabled

### ISSUE THREAD

**Issue by kk-at-redhat** [ansible/awx#14790]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Show meaningful message when trying to use Basic authentication but unable to authenticate because it's disabled in Controller settings.

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.14.2

### Operating system

Red Hat Enterprise Linux release 9.1 (Plow)

### Web browser

Chrome

### Steps to reproduce

Disable Basic authentication in AAP settings. Try to use one of ansible.controller modules specifying username and password, for example:

```
    - name: Get all credential types from AAP
      ansible.controller.export:
        controller_username: "{{ aap_config_user }}"
        controller_password: "{{ aap_config_pass }}"
        controller_host: "{{ aap_config_host }}"
        credential_types: 'all'
        validate_certs: false
```

### Expected results

Meaningful error message saying "failed to authenticate"  or "incorrect credentials" or "unable to use specified authentication method".

### Actual results

Exception that doesn't help to understand what failed.

```
msg: This endpoint raised an error: /api/v2/credentials
exception:
  File /tmp/ansible_ansible.controller.export_payload_c2dy_i7_/ansible_ansible.controller.export_payload.zip/ansible_collections/ansible/controller/plugins/modules/export.py, line 185, in main
  File /tmp/ansible_ansible.controller.export_payload_c2dy_i7_/ansible_ansible.controller.export_payload.zip/ansible_collections/ansible/controller/plugins/module_utils/controller_api.py, line 282, in exit_jsonn super().exit_json(**kwargs)
  File /tmp/ansible_ansible.controller.export_payload_c2dy_i7_/ansible_ansible.controller.export_payload.zip/ansible/module_utils/basic.py, line 1514, in exit_json sys.exit(0)
```
