### ISSUE TITLE
[BUG?] ERROR: work type did not expect a signature when running health check in AWX with work-kubernetes in Receptor

### ISSUE THREAD

**Issue by x86-39** [ansible/awx#14849]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

When using the `work-kubernetes` type as described in [the documentation](https://ansible.readthedocs.io/projects/receptor/en/latest/user_guide/k8s.html), we get the following error when checking the health of the node from AWX.
```
ERROR 2024/02/07 00:40:42 : work type did not expect a signature
```

![image](https://github.com/ansible/receptor/assets/56408488/9a15cdb1-16c4-42ee-b6b3-441d5ac67dd2)

Does AWX not support the `work-kubernetes` type yet and the health check is not reporting a readable error for this? The error is quite vague and I'm not sure what the issue is. 

Our goal here is to run Receptor in a Kubernetes cluster so we can host execution and/or hop nodes in Kubernetes. I'm not certain whether this is an issue in AWX or in Receptor.

### AWX version

23.7.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 22.04

### Steps to reproduce

The following receptor config is used:

<details><summary> receptor.conf </summary>

```yaml

---
- node:
    id: 192.168.21.54
 
- work-verification:
    publickey: /etc/receptor/work_public_key.pem
 
- log-level: debug
 
- control-service:
    service: control
    filename: /tmp/receptor.sock
    permissions: 0660
    tls: tls_server
- tls-server:
    name: tls_server
    cert: /etc/receptor/tls/receptor.crt
    key: /etc/receptor/tls/receptor.key
    clientcas: /etc/receptor/tls/ca/mesh-CA.crt
    requireclientcert: true
    mintls13: False
 
- tls-client:
    name: tls_client
    cert: /etc/receptor/tls/receptor.crt
    key: /etc/receptor/tls/receptor.key
    rootcas: /etc/receptor/tls/ca/mesh-CA.crt
    insecureskipverify: false
    mintls13: False
- tcp-listener:
    port: 27199
    tls: tls_server
 
- work-kubernetes:
    worktype: kubeit
    authmethod: kubeconfig
    allowruntimeauth: true
    allowruntimepod: true
    allowruntimeparams: true
    verifysignature: true

```
</details>

After starting Receptor and checking the health of the instance, I get the error.

### Expected results

AWX should succeed the health check and use Receptor to run workloads on the Kubernetes cluster with the `kubeit` worktype. 

If this is not a supported usecase yet, I would expect a clearer error message. This error message seems quite arbitrary to me and confused us for days.

### Actual results

We get an error
```
ERROR 2024/02/07 00:40:42 : work type did not expect a signature
```

This does not seem relevant to what we are trying to achieve. I looked through the code to see what causes this and it seems to be related to the health check not using the correct work type (more information later).

### Additional information

It seems this error occurs due to the workType being given as `ansible-runner` instead of `kubeit`. I'm not too familiar with the code at work here, but I added some debug statements in Receptor.

```go
func (c *workceptorCommand) processSignature(workType, signature string, connIsUnix, signWork bool) error {
	shouldVerifySignature := c.w.ShouldVerifySignature(workType, signWork)
	fmt.Print("shouldVerifySignature: ", shouldVerifySignature)
	fmt.Print("workType: ", workType)
	fmt.Print("connIsUnix: ", connIsUnix)

	if !shouldVerifySignature && signature != "" {
		return fmt.Errorf("work type did not expect a signature")
	}
	if shouldVerifySignature && !connIsUnix {
		err := c.w.VerifySignature(signature)
		if err != nil {
			return err
		}
	}

	return nil
```
```
shouldVerifySignature: false
workType: ansible-runner
connIsUnix: false

```

And in ShouldVerifySignature
```go
func (w *Workceptor) ShouldVerifySignature(workType string, signWork bool) bool {
	// if work unit is remote, just get the signWork boolean from the
	// remote extra data field
	if workType == "remote" {
		return signWork
	}
	w.workTypesLock.RLock()
	fmt.Print("w: ", w, " workTypes: ", w.workTypes, "\n")

	wt, ok := w.workTypes[workType]
	w.workTypesLock.RUnlock()
	fmt.Print("w: ", w, " wt: ", wt, " ok: ", ok, "\n")

	if ok && wt.verifySignature {
		return true
	}

	return false
}
```
```
workTypes: map[kubeit:0xc000379e80 remote:0xc000379620]
w: &{0xc0002adb30 0x495fe0 0xc0001ef880 /tmp/receptor/192.168.21.54 0xc0000a74d0 map[kubeit:0xc000379e80 remote:0xc000379620] 0xc0000a74e8 map[]  5m0s /etc/receptor/work_public_key.pem}
wt: <nil>
ok: false

```

Am I correct here in that it seems like it thinks the only valid workTypes are `kubeit` and `remote` here but AWX is sending `ansible-runner` for the health check?
