### ISSUE TITLE
Failed to JSON parse a line from worker stream due to partial ansible-runner event

### ISSUE THREAD

**Issue by pwalters04** [ansible/awx#14859]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

For OCI Dynamic Inventory sourcing,  I have created a custom-ee with the base of awx-ee:lates ( as of 2/7). When I attempt to run the job for syncing the inventory source, after ~5800 lines of stdout, I receive the following errors:
```

Failed to JSON parse a line from worker stream. Error: Extra data: line 1 column 5828 (char 5827) Line with invalid JSON data: b'{"event": "verbose", "uuid": "******************", "counter": 1032, "stdout": "Final inventory for instance ocid1.instance.********* is {\'IP-ADDRESS\': {\'groups\': {\'Prab_US-ASHBURN-AD-1\': {\'children\': []}, \'region_us-ashburn-1\': {\'children\': []}, \'all_hosts\': {\'children\': []}, \'Platform\': {\'children\': []}}, \'vars\': {\'availability_domain\': \'Prab:US-ASHBURN-AD-1\', \'capacity_reservation_id\': None, \'compartment_id\': \'ocid1.compartment.********************', \'dedicated_vm_host_id\': None, \'defined_tags\': {}, \'display_name\': None, \'extended_metadata\': None, \'fault_domain\': None, \'freeform_tags\': {}, \'id\': \'ocid1.instance.oc1.iad.***********************', \'image_id\': None, \'ipxe_script\': None, \'launch_mode\': \'PARAVIRTUALIZED\', \'launch_options\': {\'boot_volume_type\': \'PARAVIRTUALIZED\', \'firmware\': \'BIOS\', \'network_type\': \'PARAVIRTUALIZED'

````

My values file is 
```
  spec:
    no_log: false
    image_pull_policy: always
    task_extra_env: |
      - name: GIT_SSL_NO_VERIFY
        value: "True"

    task_replicas: 1
    task_resource_requirements:
      requests:
        cpu: 500m
        memory: 5Gi
      limits:
        cpu: 2000m
        memory: 10Gi
    # AWX Projects Directory
    projects_persistence: true
    projects_storage_class: awx-storage
    projects_storage_size: 50Gi

    # Postgres Secret
    postgres_configuration_secret: awx-postgres-secret

    # AWX Default User
    admin_user: admin

    # Application Images
    image: harbor-private/platform-infra/awx
    image_version: "23.5.1"
    ee_images:
      - name: awx
        image: harbor-private/platform-infra/awx-ee:latest
    ee_extra_env: |
      - name: RECEPTOR_RELEASE_WORK
        value: "False"
      - name: AWX_CLEANUP_PATHS
        value: "False"
      - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
        value: "Enabled"
    control_plane_ee_image: harbor-private/platform-infra/awx-ee:latest
    redis_image:harbor-private/platform-infra/redis
    redis_image_version: "7"
```

### AWX version

23.5.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

Add source project for inventory source, sync

### Expected results

inventory imported

### Actual results

json parse error
