### ISSUE TITLE
Job stdout blank after reload

### ISSUE THREAD

**Issue by Tfinn92** [ansible/awx#14904]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Since upgrading to 23.8.1 the job output doesn't load after a reload. This seems to be on jobs that have more than 4000 lines, as smaller jobs load their stdout no problem and can be reloaded as well. To be safe, we changed the setting to 8000 rather than the default 4000 but to no avail.
```
    - setting: MAX_UI_JOB_EVENTS
      value: "8000"
``` 

### AWX version

23.8.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

rocky 8.8 (K8s cluster RKE2 v1.26.8+rke2r1)

### Web browser

Firefox, Chrome, Safari

### Steps to reproduce

Run a job that has a stdout of over 4000 lines. This job we are running calls multiple roles against about 40 hosts. Clean installation of AWX through the awx-operator helm chart

### Expected results

Output that can be used for troubleshooting by other teams
![Screenshot 2024-02-20 at 9 44 04 AM](https://github.com/ansible/awx/assets/47154121/8a81687e-09be-45bf-8e69-5cbe3cb07a13)

### Actual results

No output other than hostname is given

![Screenshot 2024-02-15 at 4 01 29 PM](https://github.com/ansible/awx/assets/47154121/ed64fff0-36b8-43df-8947-1af87a8f5d48)
![Screenshot 2024-02-20 at 9 54 12 AM](https://github.com/ansible/awx/assets/47154121/ce1711ed-66e2-4e45-aae2-a0f05d15382c)

### Additional information

Reading through older posts, I found someone was able to temporarily resolve this by running awx-manage run_callback_receiver but my output is as follows if I try
```
sh-5.1# awx-manage run_callback_receiver
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 175, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/management/commands/run_callback_receiver.py", line 30, in handle
    CallbackReceiverMetricsServer().start()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/analytics/subsystem_metrics.py", line 455, in __init__
    registry.register(CustomToPrometheusMetricsCollector(DispatcherMetrics(metrics_have_changed=False)))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/analytics/subsystem_metrics.py", line 440, in collect
    entry = host_metrics.get(metric.field)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by fosterseth** [comment]
`awx-manage run_callback_receiver`

you don't need to run that (in fact better not to)

are you running playbooks with a different ansible strategy other than the default (i.e. are you using "free")

as for now, for really large stdout, you may just need to download the stdout and examine that way

**Comment by Tfinn92** [comment]
Hey fosterseth, no, nothing out of the ordinary in the plays. We use one playbook that calls on about 6 different roles, but that's been the same for about a year. Not using free or anything to that nature. 

Good to know about the `awx-manage run_callback_receiver`, I had seen it on a rather old post and figured I'd give it a whirl.

Downloading the output definitely works however. To put it in perspective, those files are roughly 500 KB, so not huge by any means, just a lot of lines.

**Comment by Tfinn92** [comment]
Just to add a little more to this. I spun up a brand new cluster with Rancher rke2 running version v1.26.13 and added a kubelet arg `container-log-max-size=2560Mi` just to let the logs stretch their legs. Spun up AWX using the latest Operator 2.12.1 and Helm. These are my values:
```
AWX:
  enabled: true
  name: awx
  namespace: awx
  spec:
    ## User creation
    admin_user: admin
    admin_email: email@email

    ## Replica Settings
    web_replicas: 3
    task_replicas: 3

    ## Networking and Ingress
    ingress_type: ingress
    ingress_tls_secret: awx-secret-tls
    hostname: awx-dev.domain
    ingress_path: /
    ingress_path_type: Prefix
    ipv6_disabled: true
    bundle_cacert_secret: cacert-custom-certs

    ## Upgrade Strategy
    auto_upgrade: true

    ## Resource Limitation
    web_resource_requirements:
      requests:
        cpu: 500m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 8Gi
    task_resource_requirements:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
    ee_resource_requirements:
      requests:
        cpu: 500m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 4Gi

    ### Environment Variable configuration
    task_extra_env: |
      - name: LDAPTLS_REQCERT
        value: never

    web_extra_env: |
      - name: LDAPTLS_REQCERT
        value: never

    ee_extra_env: |
      - name: LDAPTLS_REQCERT
        value: never
      - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
        value: disabled

    ## Project Persistence
    projects_persistence: true
    projects_storage_class: longhorn
    projects_storage_size: 30Gi
``` 
Run the same job against the same inventory (about 40 hosts) and I am seeing the exact same behavior
Going through the job in the API I see the following:
```
GET /api/v2/jobs/6/job_events/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
X-API-Node: awx-web-677496f994-smb2m
X-API-Product-Name: AWX
X-API-Product-Version: 23.8.1
X-API-Time: 0.080s
X-UI-Max-Events: 4000

{
    "count": 26183,
``` 

It definitely is a large job with over 26,000 job events. Downloading the output from the gui works no problem, so that work around definitely works for now. I figured maybe adding this context might help! Please let me know if there is anything else I can provide.

*Edit*: One other key note is `GET /api/v2/jobs/6/stdout/ `loads the stdout as expected in the API. So it seems like that transition to the gui isn't happening.  Thanks again
