### ISSUE TITLE
Prompt on launch option for playbook in a job template

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#1491]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

The option 'Prompt on launch' should be available additionally in the configuration of the job template in the 'Playbook' field. Quite reasonably, the to-be-selected playbook should be selectable from the list of the executable playbooks of the project during the execution of the job template.

##### ENVIRONMENT
* AWX version: 1.0.0

**Comment by wenottingham** [comment]
As a workaround, this can be done by passing a playbook file name as an extra variable to a playbook that uses `include` to include it.

**Comment by lucasteinke** [comment]
I created a playbook with just the following:

```yaml
---
- name: "run specific playbook"
  ansible.builtin.import_playbook: "{{ specific_playbook_to_run }}.yml"
```

But AWX, after starting the Job, complains that `ERROR! the playbook: playbooks/specific/test-playbook.yml could not be found`. What am I doing wrong here?
