### ISSUE TITLE
Precedence of playbook group_vars/all vs. inventory group_vars/* vs. inventory host_vars/*

### ISSUE THREAD

**Issue by bsteinb** [ansible/awx#14914]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

AWX seems to handle variable precedence in a way that differs from the Ansible CLI, but also from AWX's own documentation.

### AWX version

23.8.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.16.3

### Steps to reproduce

Our project structure is as follows:

```
test_playbook.yml
test_inventory/
  hosts.yml
  group_vars/
    test_inventory.yml
group_vars/
  all.yml
```

With contents:

`test_playbook.yml`:

```
- hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: "{{ test_variable }}"
```

`test_inventory/hosts.yml`:

```
test_inventory:
  children:
    test_group:
      hosts:
        localhost:
          ansible_connection: local
```

`test_inventory/group_vars/test_inventory.yml`:

```
test_variable: "from inventory group_vars/test_inventory"
```

`group_vars/all.yml`:

```
test_variable: "from playbook group_vars/all"
```

We import the project into AWX from Git and run `test_playbook.yml` against inventory `test_inventory` and compare the output with running `ansible-playbook -i test_inventory test_playbook.yml`.

### Expected results

According to [AWX's documentation](https://ansible.readthedocs.io/projects/awx/en/latest/userguide/job_templates.html#extra-variables) (see table "AWX Variable Precedence Hierarchy") we learn that any kind of playbook group_var has higher precedence than any inventory  group_vars and would expect both AWX and Ansible to print:

```
ok: [localhost] => 
  msg: from playbook group_vars/all
```

### Actual results

And that is indeed what is printed by AWX, however, [Ansible's own documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence) contradicts AWX's description of what Ansible does by going into more detail and giving inventory group_vars/* higher precedence than playbook group_vars/all and in fact Ansible prints:

```
ok: [localhost] => 
  msg: from inventory group_vars/test_inventory
```

Thus AWX's behavior differs significantly from that of Ansible while the AWX documentation suggests both should behave the same way.

### Additional information

Additionally, AWX's behavior contradicts its own documentation. If we add `test_inventory/host_vars/localhost.yml` with contents as follows:

```
test_variable: "from inventory host_vars/localhost"
```

We would still expect the output to remain the same, since the playbook group_vars should have higher precedence, but in fact the inventory host_vars win and now AWX prints

```
ok: [localhost] => 
  msg: from inventory host_vars/localhost
```

which matches `ansible-playbook`.

**Comment by kzinas-adv** [comment]
Something similar only with inventory vars vars_files overwrite.  ansible cli (version 2.15, 2.16, 2.17) - OK, I may not have some_var in vars.yaml, but with awx in this simply ignores overwrite and stays with   interfaces: "default".
I should put some_var in playbook/vars.yaml for awx to work it through.
AWX 24.6.1  

```
playbook/deploy.yaml
- hosts: "{{ hosts  }}"
  vars_files:
     vars.yaml
   
playbook/vars.yaml:
interfaces: "new_iface"
#awx needs this: 
#some_var:
#   smth: "{{ interfaces }}"


inventory/prod/group_vars/all.yaml 
interfaces: "default" 
some_var:
   smth: "{{ interfaces }}"
```
