### ISSUE TITLE
variables and source_vars expect dictionary but apply as yaml (multiple modules)

### ISSUE THREAD

**Issue by kk-at-redhat** [ansible/awx#14918]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Dictionary with provided variables seems to be applying as yaml:
 - inventories: variables
 - hosts: variables
 - groups: variables
 - inventory sources: source_vars

Also, see https://github.com/ansible/awx/issues/14842

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.14.2

### Operating system

Red Hat Enterprise Linux release 9.1 (Plow)

### Web browser

Chrome

### Steps to reproduce
```
- ansible.controller.inventory:
    name: "Dynamic A"
    organization: "A"
    variables: {tt: tt}

- ansible.controller.host:
    name: "Host A"
    inventory: "Static A"
    variables: {tt: tt}

- ansible.controller.group:
    name: "Group A"
    inventory: "Static A"
    variables: {tt: tt}

- ansible.controller.inventory_source:
    name: "A"
    inventory: "Dynamic A"
    source_vars: {tt: tt}
```
### Expected results
```
YAML:
---
tt: tt
```
### Actual results
```
YAML:
{"tt": "tt"}
```
