### ISSUE TITLE
No ability to specify null values for source_project (ansible.controller.inventory_source)

### ISSUE THREAD

**Issue by kk-at-redhat** [ansible/awx#14921]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Depending on the source, source_project value is either defined or null. However, there is no way to specify null value source_project in a playbook.  A workaround would be to have a different playbook for each source type (project, Satellite etc.) which is not scalable.

### AWX version

23.2.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.14.2

### Operating system

Red Hat Enterprise Linux release 9.1 (Plow)

### Web browser

Chrome

### Steps to reproduce

```
- ansible.controller.inventory_source:
    name: "Sat"
    inventory: "Dynamic A"
    source_project: ""

- ansible.controller.inventory_source:
    name: "Sat"
    inventory: "Dynamic A"
    source_project: None
```

### Expected results

```
ok: [localhost] ...

ok: [localhost] ...
```

### Actual results

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/projects/ returned 6 items, expected 1"

fatal: [localhost]: FAILED! => {"changed": false, "msg": "The specified source project, {}, was not found."}
```
