### ISSUE TITLE
Error on project update since 23.9.0 ("No file was found when using first_found." on "Fetch galaxy roles and collections from requirements")

### ISSUE THREAD

**Issue by 2and3makes23** [ansible/awx#14953]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

PR [#14065](https://github.com/ansible/awx/pull/14065/files) seems to have introduced a bug. Project update fails with "No file was found when using first_found." from task "Fetch galaxy roles and collections from requirements".

### AWX version

23.9.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

openshift

### Modifications

no

### Ansible version

core 2.16.4

### Operating system

CentOS9 Stream

### Web browser

Firefox

### Steps to reproduce

Attempt to run a project update for a project that has no requirements.yml for roles and collections (but the same problem should occur on the similar preceding/subsequent tasks)

### Expected results

If there is no respective (roles/collections) requirements.yml, skip the step of resolving requirements from respective requirements.yml without failing

### Actual results

```yaml
msg: >
  The conditional check 'req_file' failed. The error was: An unhandled exception
  occurred while templating '{{ lookup('ansible.builtin.first_found',
  req_candidates, skip=True) }}'. Error was a <class
  'ansible.errors.AnsibleLookupError'>, original message: No file was found when
  using first_found.


  The error appears to be in
  '/tmp/awx_70571_iq73bn0q/project/project_update.yml': line 252, column 11, but
  may

  be elsewhere in the file depending on the exact syntax problem.


  The offending line appears to be:


          - name: Fetch galaxy roles and collections from requirements.(yml/yaml)
            ^ here
_ansible_no_log: false

```

### Additional information

Might be an easy fix to change the three tasks´ conditionals to something like:
```yaml
when:
  - roles_enabled | bool
  - req_file is defined
  - req_file | stat | isfile
```

**Comment by 2and3makes23** [comment]
I tried what happens if I provide an empty `/requirements.yml` (contains only `---\n`) for combined roles and collections.

In this case, another error occurs:
```yaml
changed: true
stdout: ''
stderr: >-
  [DEPRECATION WARNING]: ANSIBLE_COLLECTIONS_PATHS option, does not fit var 

  naming standard, use the singular form ANSIBLE_COLLECTIONS_PATH instead. This 

  feature will be removed from ansible-core in version 2.19. Deprecation
  warnings
   can be disabled by setting deprecation_warnings=False in ansible.cfg.
  ERROR! No requirements found in file
  '/var/lib/awx/projects/_376__awxtesting/requirements.yml'
rc: 1
cmd:
  - ansible-galaxy
  - install
  - '-r'
  - /var/lib/awx/projects/_376__awxtesting/requirements.yml
start: '2024-03-06 08:12:38.378667'
end: '2024-03-06 08:12:40.390555'
delta: '0:00:02.011888'
msg: non-zero return code
invocation:
  module_args:
    chdir: /var/lib/awx/projects/_376__awxtesting
    _raw_params: >-
      ansible-galaxy install -r
      /var/lib/awx/projects/_376__awxtesting/requirements.yml 
    _uses_shell: false
    expand_argument_vars: true
    stdin_add_newline: true
    strip_empty_ends: true
    argv: null
    executable: null
    creates: null
    removes: null
    stdin: null
stdout_lines: []
stderr_lines:
  - '[DEPRECATION WARNING]: ANSIBLE_COLLECTIONS_PATHS option, does not fit var '
  - >-
    naming standard, use the singular form ANSIBLE_COLLECTIONS_PATH instead.
    This 
  - >-
    feature will be removed from ansible-core in version 2.19. Deprecation
    warnings
  - ' can be disabled by setting deprecation_warnings=False in ansible.cfg.'
  - >-
    ERROR! No requirements found in file
    '/var/lib/awx/projects/_376__awxtesting/requirements.yml'
_ansible_no_log: false
```

Adding some random role entry solves this. So (unless this is the intended reaction to empty requirements.yml files) in addition to the conditional mentioned above, there needs to be added an additional check to prevent this from happening as well.

**Comment by kurokobo** [comment]
@2and3makes23 
Hi, I can't reproduce this issue on 23.9.0 on K3s. Could you please clarify that the issue exists or not with following demo project?

1. Add new project with URL <https://github.com/ansible/ansible-tower-samples>
   - Add new project anyway even if you already have "Demo Project" 
3. Gather job output

If you've faced issue with demo project, could you please provide:

- Full job output
- Output from `kubectl -n <namespace> describe deployment/<instance-name>-task`
- Output from `kubectl -n <namespace> exec deployment/<instance-name>-task -c <instance-name>-ee -- ansible --version`

Technically, since `skip=True` is specified for `ansible.builtin.first_found` lookup plugin, `req_file` will be an empty list if there is no requirements file. So I don't know why `No file was found when using first_found` is ocurred.

**Comment by 2and3makes23** [comment]
@kurokobo 
Thank you for your quick reply.

To reproduce I recommend a simplified copy of e.g. [this task](https://github.com/ansible/awx/blob/e1e32c971cbc30363abf213dae785a937756d3fe/awx/playbooks/project_update.yml#L217-L231) from `project_update.yml`:
```yaml
# removed irrelevant parts for testing
    - name: Test behavior of task
      debug:
        msg: 'I am able to run'
      vars:
        req_file: "{{ lookup('ansible.builtin.first_found', req_candidates, skip=True) }}"
        req_candidates:
          - "roles/requirements.yml"
          - "roles/requirements.yaml"
      when:
        - req_file
```
For me locally, like in AWX, this produces:
```yaml
PLAY [test play] ***********************************************************************************************************************************************************************************************************************************************************************

TASK [Test behavior of task] ***********************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'req_file' failed. The error was: An unhandled exception occurred while running the lookup plugin 'ansible.builtin.first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found\n\nThe error appears to be in 'testplay.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Test behavior of task\n      ^ here\n"}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

As to your point regarding the [first_found_lookup documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/first_found_lookup.html#parameter-skip):

> 
> This is useful when used with with_first_found, as an empty list return to with_ calls causes the calling task to be skipped.
> 
> When used as a template via lookup or query, setting [skip=True](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/first_found_lookup.html#ansible-collections-ansible-builtin-first-found-lookup-parameter-skip) will *not* cause the task to skip. Tasks must handle the empty list return from the template.

I am inclined to believe that the second cited line from documentation applies in this case, using `lookup('ansible.builtin.first_found'`. What do you think?

It´s been a long work day and I have to log off. Please consider checking out above proposed test task - thanks so much!

**Comment by kurokobo** [comment]
@2and3makes23 
Okay, it's related to: https://github.com/ansible/ansible/issues/81503

As a workaround, use latest Ansible 2.15.x instead.

The reason why I can't reproduce the issue is the Ansible version in default `awx-ee` image is 2.15.9. I believe you are using customized (or old) EE images that contains newer (or older) Ansible for your control plane.

Applicable fix is passing list of files as a keyword param instead of positional param. However it is a difficult decision as to which is safer, as some versions of Ansible will not work unless it is a positional param, and some will not work unless it is a keyword param.

```yaml
    - name: Test behavior of task
      debug:
        var: lookup('first_found', req_candidates, skip=True)
      vars:
        # Not works on 2.16
        #req_file: "{{ lookup('ansible.builtin.first_found', req_candidates, skip=True) }}"
        # Works on 2.16
        req_file: "{{ lookup('ansible.builtin.first_found', files=req_candidates, skip=True) }}"
        req_candidates:
          - "sitea.yml"
      when:
        - req_file
```

@bcoca @fosterseth 
F.Y.I.
I think this should be fixed in upstream Ansible in https://github.com/ansible/ansible/issues/81503 since [following example snippet on the doc](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/first_found_lookup.html) no longer works on the latest Ansible 2.16.x.

```yaml
- name: Set _found_file to the first existing file, or an empty list if no files found
  ansible.builtin.set_fact:
    _found_file: "{{ lookup('ansible.builtin.first_found', files, paths=['/extra/path'], skip=True) }}"
  vars:
    files:
      - /path/to/foo.txt
      - /path/to/bar.txt
```

As an AWX side, to be safer, shoud we use keyword param instead, or keep this as-is? I vote for keeping this as-is, but I'm not particular about it.
