### ISSUE TITLE
Job Output does not automatically get updates, requires manual refresh

### ISSUE THREAD

**Issue by syahrul-aiman** [ansible/awx#15049]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

After executing any jobs, output doesn't get updated, and seems hang. However, after click refresh, output shows update, but still hangs. Probably issue with websocket?

<img width="1172" alt="image" src="https://github.com/ansible/awx/assets/17613060/e534ea2d-fc9a-4e19-bbb7-32c385426d3a">

Sample Job Output URL:
```
http://localhost:30080/#/jobs/playbook/21/output
```

### AWX version

24.1.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

yes

### Operating system

MacOS 14.4

### Web browser

Chrome

### Steps to reproduce

After executing any jobs, output doesn't get updated, and seems hang. However, after click refresh, output shows update, but still hangs. Probably issue with websocket? I'm using nofusscomputing/awx image, which has arm64.

awx.yaml:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: ansible-awx
spec:
  service_type: nodeport
  nodeport_port: 30080
  image: nofusscomputing/awx
  image_version: 24.1.0
  image_pull_policy: Always
```

### Expected results

Job Output should always retrieve the latest update and doesn't require any manual refresh

### Actual results

Job Output only retrieve the latest update after refresh. And requires manual refresh to get updates.
