### ISSUE TITLE
Ansible awx.awx collection tasks altering configuration for a pre-existing inventory should be organization scope aware

### ISSUE THREAD

**Issue by absynth76** [ansible/awx#15117]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

 collection version 24.2.0
AWX version 23.9.0

If (at least) 2 inventories with the same name exist, the awx.awx.host task is looping with an error:
    "msg": "Request to /api/v2/inventories/?name=<duplicated_name> returned 2 items, expected 1",
    
there is indeed the same <duplicated_name> inventory name on 2 different organizations

### AWX version

 23.9.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.16.2]

### Operating system

wsl - fedoraremix

### Steps to reproduce

create 2 inventories with the same name on 2 different organization, example:
```
- name: Create duplicated inventory
  awx.awx.inventory:
      name: "DuplicatedInventoryName"
      description: "duplicate name inventory"
      organization: "{{ item }}"
      state: present
  loop:
    - 'org1'
    - 'org2'
```
and try to add host to one of them
```
- name: Add host to inventory
  awx.awx.host:
      name: "localhost"
      inventory: "DuplicatedInventoryName"
      state: present
```

will result in the error mentioned in the description of this issue

### Expected results

mutltiple choices here:
- alter all inventories with the same name if organization is not specified, mentioning the amount of inventory altered in the msg result
- alter the target inventory at the condition 'organization' (TBD variable name) filter is provided to the task

### Actual results

failing with the message mentioned in the description
