### ISSUE TITLE
AWX task fail with AnsibleUnsafeBytes for yaml collapsed string

### ISSUE THREAD

**Issue by jon-nfc** [ansible/awx#15161]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

A yaml collapsed string with jinja fails with error `AnsibleUnsafeBytes.__format__. unsupported format string passed to  AnsibleUnsafeBytes.__format__` when it should not have for a string. this task does not fail when run via CLI.

### AWX version

23.9.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.16.1

### Operating system

k3s 1.29

### Steps to reproduce

use the foollowing task in play:
``` yaml
- name: Download K3s Binary
  ansible.builtin.uri:
    url: |-
      https://github.com/k3s-io/k3s/releases/download/
        {{- node_k3s.desired_version | urlencode -}}
      /k3s
      {%- if cpu_arch.key == 'aarch64' -%}
      -arm64
      {%- endif %}
    method: GET
    return_content: false
    status_code:
      - 200
      - 304
    dest: "/tmp/k3s.{{ cpu_arch.key }}"
    mode: "744"
  changed_when: not ansible_check_mode
  check_mode: false
  delay: 10
  retries: 3
  register: k3s_download_files
  delegate_to: localhost
  failed_when: >
    (lookup('ansible.builtin.file', '/tmp/k3s.' + cpu_arch.key) | hash('sha256') | string) != node_k3s.desired_hash
      and
    (
      k3s_download_files.status | int != 200
        or
      k3s_download_files.status | int != 304
    )
  run_once: true
  when: ansible_os_family == 'Debian'
  loop: "{{ nfc_kubernetes_install_architectures | dict2items }}"
  loop_control:
    loop_var: cpu_arch
  vars:
    ansible_connection: local
```

where:
``` yaml
cpu_arch:
  key: aarch64
```

### Expected results

A yaml collapsed string `|-` or `>-`  by never return error `AnsibleUnsafeBytes.__format__. unsupported`. when the type is clearly a yaml string

### Actual results

error:

``` yaml

msg: >-
  Unexpected templating type error occurred on
  (https://github.com/k3s-io/k3s/releases/download/
    {{- node_k3s.desired_version | urlencode -}}
  /k3s

  {%- if cpu_arch.key == 'aarch64' -%}

  -arm64

  {%- endif %}): unsupported format string passed to
  AnsibleUnsafeBytes.__format__. unsupported format string passed to
  AnsibleUnsafeBytes.__format__

```
