### ISSUE TITLE
task check_mode=false ignored by awx job template - Playbook Check

### ISSUE THREAD

**Issue by jon-nfc** [ansible/awx#15162]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

when running a job template with job type `Playbook Check`, tasks with `check_mode: false` do not run as intended when on the cli they do.

### AWX version

23.9.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

23.9.0

### Operating system

k3s 1.29

### Steps to reproduce

add the following task

``` yaml
- name: Get Hostname
  ansible.builtin.command:
    cmd: hostname
  changed_when: false
  check_mode: false
  register: hostname_to_check
  tags:
    - always

```
and run the playbook in "check" mode from awx. the task fails to run

### Expected results

that a task with `check_mode: false` runs when the play is run in "check mode". This is what already occurs when the cli is used, i.e. `ansible-playboook my-playbook-name.yaml --check`.

### Actual results

``` yaml

skipping: [<truncated>] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "cmd": [
        "hostname"
    ],
    "delta": null,
    "end": null,
    "invocation": {
        "module_args": {
            "_raw_params": "hostname",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "expand_argument_vars": true,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true
        }
    },
    "msg": "Command would have run if not in check mode",
  …

```
