### ISSUE TITLE
Collection 24.3.1 displays warning claiming 0.0.1-devel

### ISSUE THREAD

**Issue by MallocArray** [ansible/awx#15172]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Similar to #12060 after upgrading to Collection 24.3.0 or 24.3.1, I get a warning when running a task
`[WARNING]: You are running collection version 0.0.1-devel but connecting to AWX version 24.1.0`

Installed using `ansible-galaxy collection install awx.awx --force`

### AWX version

 24.1.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

openshift

### Modifications

no

### Ansible version

2.16.6

### Operating system

quay.io/centos/centos:stream9

### Steps to reproduce

Seeing the message with my first task in a playbook

```yaml
    - name: Generate Token for Authentication
      awx.awx.token:
        controller_host: "{{ inventory_hostname }}"
        controller_username: "{{ controller_username | default(omit) }}"
        controller_password: "{{ controller_password | default(omit) }}"
        controller_oauthtoken: "{{ controller_oauthtoken | default(omit) }}"
        validate_certs: "{{ validate_certs | default(yes) }}"
        scope: write
        state: present
      register: token_result
      check_mode: false
      tags:
        - always
```

### Expected results

Task completes without warning

### Actual results

Warning message is display, but task completes as expected
