### ISSUE TITLE
Feature Wants: kubectel delete -k . should only delete all the awx resources, but not the entire namespace

### ISSUE THREAD

**Issue by wangzhihaocom** [ansible/awx#15173]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Currently., when I deploy the awx in the existing namespace, I use kustomization.yaml
`kubectl apply -k .` command ,

but when I want to delete all the resources, I use kubectl delete -k .

It will terminate all the resources, as well as the entire existing namespace( including our other existing pod in the namespace), which is not good.

Is there a better to just delete all the awx resource but not to delete the entire namespace? 

This is my kustomization.yaml

```
kind: Kustomization
namespace: devops

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=<host>
      - port=<port>
      - database=<db>
      - username=<user>
      - password=<password>
      - type=unmanaged
      - sslmode=prefer

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=admin

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1
```

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

kubectl apply -k .
kubectl delete -k .

### Current results

When run kubectl delete -k ., it delete the entire existing namespace deletes

### Sugested feature result

Should only delete the awx resources , not delete the entire namespace

### Additional information

N/A
