### ISSUE TITLE
Restore is not working as expected | need restore docs

### ISSUE THREAD

**Issue by dhivinp-maersk** [ansible/awx#15239]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [x] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

AWX restore not working as expected when restoring to new k8's cluster.
failed at , creating new psql container to restore.

pv were backup is located.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-backup-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  storageClassName: local-storage
  hostPath:
    path: /mnt/awx_backup
```

PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-backup-pv
  namespace: awx-poc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

restore :
```
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: restore1
  namespace: awx-poc
spec:
  deployment_name: restore-awx
  backup_pvc_namespace: 'awx-poc'
  backup_dir: '/backups/tower-openshift-backup-2024-05-30-090908'
  backup_pvc: 'static-backup-pv'

```

### AWX version

24.4.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes with helm awx operator

### Modifications

no

### Ansible version

24.4.0

### Operating system

20.04

### Web browser

Chrome

### Steps to reproduce

1. take backup from awx on k8'scluster.
2.  create backup pv on another k8s with host path were backup is placed.
3. restore using the backup

### Expected results

1. backup should restore

### Actual results

1.  restore is failing in an loop 

error: failed at "Restore database dump to the new postgresql container"
