### ISSUE TITLE
ansible.controller.workflow_launch tries to access /api/controller/v2/organizations/ when I believe it should be /api/v2/organizations/ 

### ISSUE THREAD

**Issue by matthieup** [ansible/awx#15622]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I am try to use ansible.controller.workflow_launch with the following parameters:

```yaml
    - name: "Run on  {{ target }}"
      ansible.controller.workflow_launch:
        #controller_config_file: config_automation.txt
        controller_host: https://automation_host
        validate_certs: false
        name: Workflow-Template-A
        organization: ORGANIZATION_A
        extra_vars:
          target: "{{ target }}"
        wait: true
        controller_username: "user_aap"
        controller_password: "{{ aap_password }}"
```

However I keep on getting the message from the task:
```
The requested object could not be found at /api/controller/v2/organizations/
```
or 
```
The requested object could not be found at /api/controller/v2/workflow_job_templates/.
```

Trying to access the URL on the controller, it fails, but /api/v2/organizations/ or /api/v2/workflow_job_templates/ ( without the "controller" part) succeeds.
So I do believe the URL is wrong.

### AWX version

4.5.6

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

2.15.12

### Operating system

Linux

### Web browser

Firefox

### Steps to reproduce

```yaml
    - name: "Run on  {{ target }}"
      ansible.controller.workflow_launch:
        #controller_config_file: config_automation.txt
        controller_host: https://automation_host
        validate_certs: false
        name: Workflow-Template-A
        organization: ORGANIZATION_A
        extra_vars:
          target: "{{ target }}"
        wait: true
        controller_username: "user_aap"
        controller_password: "{{ aap_password }}"
```

### Expected results

It should start the workflow I passed in the name: Workflow-Template-A

### Actual results

Getting the message:
```
The requested object could not be found at /api/controller/v2/organizations/
```
