### ISSUE TITLE
CrashLoopBackOff by awx-web and cannot install AWX

### ISSUE THREAD

**Issue by ghost** [ansible/awx#15686]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello
I am not good at English. Sorry if my English is strange.

I am having a lot of trouble starting awx-web.
CrashLoopBackOff by awx-web and cannot install AWX

kubectl get all -n awx
```
NAME                                                  READY   STATUS             RESTARTS        AGE
pod/awx-operator-controller-manager-dfd7f7bdf-b7rn9   2/2     Running            0               12m
pod/awx-postgres-15-0                                 1/1     Running            0               11m
pod/awx-task-767c894fd9-z4m4j                         0/4     Init:0/2           0               11m
pod/awx-web-7c67c8bff6-mqc6f                          2/3     CrashLoopBackOff   6 (2m27s ago)   11m
```

kubectl logs pod/awx-operator-controller-manager-xxxxxxxx   -n awx -c awx-manager
```
{"level":"error","ts":"2024-12-05T01:03:39Z","msg":"Reconciler error","controller":"awx-controller","object":{"name":"awx","namespace":"awx"},"namespace":"aw
x","name":"awx","reconcileID":"03ea3be2-fb61-4960-8325-e7e2f58b3e07","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/intern
al/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsig
s.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/i
nternal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.
io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}

```

cat awx-demo.yaml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ipv6_disabled: true
  
  service_type: nodeport

  postgres_data_volume_init: true
  postgres_init_container_commands: |
    chown 26:0 /var/lib/pgsql/data
    chmod 700 /var/lib/pgsql/data
 
  postgres_configuration_secret: awx-postgres-configuration
  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 2Gi
```

### AWX version

24.6.0

### Select the relevant components

- [ ] UI
- [X] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

I referred to the AWX-operator manual

### Expected results

Nodes should be deployed successfully (status = Running).

### Actual results

Deployment fails:

```
NAME                                                  READY   STATUS             RESTARTS        AGE
pod/awx-operator-controller-manager-dfd7f7bdf-b7rn9   2/2     Running            0               12m
pod/awx-postgres-15-0                                 1/1     Running            0               11m
pod/awx-task-767c894fd9-z4m4j                         0/4     Init:0/2           0               11m
pod/awx-web-7c67c8bff6-mqc6f                          2/3     CrashLoopBackOff   6 (2m27s ago)   11m
```
