### ISSUE TITLE
Unable to install AWX on Docker.

### ISSUE THREAD

**Issue by bhargavtejad** [ansible/awx#15730]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

I am trying to install AWX on Docker. I have created a Docker Compose file with Redis and PostgreSQL configured with proper networking. While Redis and PostgreSQL are running successfully, AWX fails to deploy, showing the following error:
`awx | Usage: dumb-init [option] program [args]`
`awx | Try dumb-init --help for full usage. `
`awx exited with code 1.`

### AWX version

24.6.1

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [ ] API
- [x] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.18.0

### Operating system

Mac OS 15.1.1

### Web browser

Chrome

### Steps to reproduce

**docker-composer.yml**
```
services:
  awx:
    image: quay.io/ansible/awx:24.6.1
    container_name: awx
    ports:
      - "8052:8052"
    environment:
      SECRET_KEY: "test_secret_key_12345" 
      DATABASE_USER: "awx_user"
      DATABASE_PASSWORD: "awx_test_pass"
      DATABASE_NAME: "awx_test_db"
      DATABASE_HOST: "postgres"
      REDIS_HOST: "redis"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "test_admin_pass"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: awx_postgres
    environment:
      POSTGRES_USER: "awx_user"
      POSTGRES_PASSWORD: "awx_test_pass"
      POSTGRES_DB: "awx_test_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: awx_redis

volumes:
  postgres_data:
```

Command used: `docker-compose up`

### Expected results

Ansible tower up and running with proper connections and able to run UI on browser.

### Actual results

tower$ docker compose up
```
WARN[0000] /tower/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 3/0
✔ Container awx_redis     Created                                                                                                                  0.0s
✔ Container awx_postgres  Created                                                                                                                  0.0s
✔ Container awx           Created                                                                                                                  0.0s
Attaching to awx, awx_postgres, awx_redis
awx_postgres  |
awx_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
awx_postgres  |
awx_redis     | 1:C 02 Jan 2025 07:41:25.123 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
awx_redis     | 1:C 02 Jan 2025 07:41:25.123 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
awx_redis     | 1:C 02 Jan 2025 07:41:25.123 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
awx_redis     | 1:M 02 Jan 2025 07:41:25.123 * monotonic clock: POSIX clock_gettime
awx_redis     | 1:M 02 Jan 2025 07:41:25.125 * Running mode=standalone, port=6379.
awx_redis     | 1:M 02 Jan 2025 07:41:25.127 * Server initialized
awx_redis     | 1:M 02 Jan 2025 07:41:25.127 * Ready to accept connections tcp
awx_postgres  | 2025-01-02 07:41:25.159 UTC [1] LOG:  starting PostgreSQL 13.18 (Debian 13.18-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
awx_postgres  | 2025-01-02 07:41:25.159 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
awx_postgres  | 2025-01-02 07:41:25.159 UTC [1] LOG:  listening on IPv6 address "::", port 5432
awx_postgres  | 2025-01-02 07:41:25.164 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
awx_postgres  | 2025-01-02 07:41:25.168 UTC [26] LOG:  database system was shut down at 2024-12-31 09:34:01 UTC
awx_postgres  | 2025-01-02 07:41:25.175 UTC [1] LOG:  database system is ready to accept connections
awx           | Usage: dumb-init [option] program [args]
awx           | Try dumb-init --help for full usage.
awx exited with code 1
```
