### ISSUE TITLE
Lack of documentation for custom *credential* plugins

### ISSUE THREAD

**Issue by chrisdola** [ansible/awx#15755]
There is a severe lack of documentation on how to include custom credential plugins in the newer versions of AWX now that things have shifted over to being operator based. 

All documentation I've found points to using the typical `ansible-galaxy collection ...` commands to build a collection and then including that collection in the requirements.yml file when building the new ee. However, unless I'm mistaken credential plugins are not the same as the [module plugins](https://docs.ansible.com/ansible-core/2.18/plugins/plugins.html) that this is meant for. 

Is the only way to include custom credential plugins to build the awx project from scratch and include the new cred plugin alongside the others as outlined in [this](https://groups.google.com/g/awx-project/c/jQg_QZ00tDQ) post? I'm having a hard time believe that's the correct way to do this, but nothing else I've found makes any sense..

**Comment by tvo318** [comment]
The credential plugins have been moved to another repo and site. Please update your bookmarks to point to: https://awx-plugins-core.readthedocs.io/en/latest/

Thanks!

**Comment by chrisdola** [comment]
Hey @tvo318, I don't see any documentation there either about how to actually build the plugins into AWX. Can you please share where that information is documented or outlined? 

Thanks!

**Comment by chrisdola** [comment]
I've managed to get the awx devel branch building, but the plugins are installed in the image and then never actually present in the API/UI... So there is some sort of disconnect between the development docs on the AWX side and what is actually required to develop cred plugins.

**Comment by EyesIce** [comment]
I found this very useful:
https://www.linkedin.com/pulse/how-create-use-custom-credential-types-awx-ansible-david-henderson-ebe1e

On top of these, within Injector configuration it's possible to use env instead of extra_variables, thus it's possible to retrive credentials from environment variable for example in a python script as dynamic inventory by icluding os library.

Example:
```
Input configuration:
---
fields:
  - id: api_user
    type: string
    label: API User
    help_text: Use this field to set user API
    secret: false
  - id: api_token
    type: string
    label: API Token
    help_text: Set API Token
    secret: true

Injector configuration:
env:
  API_USER_VARIABLE: "{{ api_user }}"
  API_TOKEN: "{{ api_token }}"

python:
include os
token = os.getenv("API_TOKEN")
user = os.getenv("API_USER_VARIABLE")
```
