### ISSUE TITLE
Create construced inventory with API don't work

### ISSUE THREAD

**Issue by akqopensystems** [ansible/awx#15945]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [x] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [x] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

It seems as if it is not possible to create
a constructed inventory with for example with a limit, useing the API with awx.awx.inventory and awx.awx.inventory_source modules.

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [x] API
- [x] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Use for example this little demo code
```yml
- hosts: localhost
  gather_facts: false
  vars:
    awx_url: "https://awx.example.com"
    awx_user: admin
    awx_password: admin
    awx_validate_certs: false
  tasks:
    - name: Create constructed inventory
      awx.awx.inventory:
        controller_host: "{{ awx_url }}"
        controller_username: "{{ awx_user }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ awx_validate_certs }}"

        name: "My constructed"
        organization: default
        kind: "constructed"
        input_inventories:
          - "my basic inventory"

    - name: Edit the constructed inventory source
      awx.awx.inventory_source:
        controller_host: "{{ awx_url }}"
        controller_username: "{{ awx_user }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ awx_validate_certs }}"
        name: "some name here"
        inventory: "My contructed"
        source: controller
        limit: host3,host4,host6
```

### Expected results

Create a costructed inventory with name "My constructed" and "my basic inventory" as inventory and a limit of "host3,host4,host6" in AWX

### Actual results

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to create inventory source My constructed: {'inventory': {'detail': 'Cannot create Inventory Source for Smart or Constructed Inventories'}}"}
```

### Additional information

- Our AWX and the awx.awx collection are both 24.6.1
- Its a easy task to create this kind of construced inventory over the WebUI

Also the documentation of [awx.awx.inventory](https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html) and [awx.awx.inventory_source](https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_source_module.html) seems to be not up to date.
awx.awx.inventory_source has in the examples the creation of a constructed inventory, but it does not work. If you use like in the example you run in a python error `The error was: KeyError: 'source'` which mean it only work when awx.awx.inventory_source module has a `source` option set.

Another Problem is that it looks a bit like it shouldn't work at all.
See [serializers.py](https://github.com/ansible/awx/blob/24.6.1-docs/awx/api/serializers.py#L2474-L2477)
```
    def validate_inventory(self, value):
        if value and value.kind in ('constructed', 'smart'):
            raise serializers.ValidationError({"detail": _("Cannot create Inventory Source for Smart or Constructed Inventories")})
        return value
```
It check if constructed or smart and raise an error if so.

Which brings me to the question, is it even possible to create a constructed inventory over api like it is possible over the WebUI

**Comment by fosterseth** [comment]
tried running the example from https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html

(modified the names a bit)

```yaml
- name: generic stuff
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx

  tasks:
  - name: Add inventory
    inventory:
      name: "Foo Inventory"
      description: "Our Foo Cloud Servers"
      organization: "Default"
      state: present

  - name: Copy inventory
    inventory:
      name: Copy Foo Inventory
      copy_from: Demo Inventory
      description: "Our Foo Cloud Servers"
      organization: "Default"
      state: present

  # You can create and modify constructed inventories by creating an inventory
  # of kind "constructed" and then editing the automatically generated inventory
  # source for that inventory.
  - name: Add constructed inventory with two existing input inventories
    inventory:
      name: My Constructed Inventory
      organization: Default
      kind: constructed
      input_inventories:
        - "Foo Inventory"
        - "Copy Foo Inventory"

  - name: Edit the constructed inventory source
    inventory_source:
      # The constructed inventory source will always be in the format:
      # "Auto-created source for: <constructed inventory name>"
      name: "Auto-created source for: My Constructed Inventory"
      inventory: My Constructed Inventory
      limit: host3,host4,host6
      source_vars:
        plugin: constructed
        strict: true
        use_vars_plugins: true
        groups:
          shutdown: resolved_state == "shutdown"
          shutdown_in_product_dev: resolved_state == "shutdown" and account_alias == "product_dev"
        compose:
          resolved_state: state | default("running")
```

against my local development environment and it succeeded!

```
PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored
```
