### ISSUE TITLE
[AWXMeshIngress] adding possibility to define replica count

### ISSUE THREAD

**Issue by mengmann** [ansible/awx#15961]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [x] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Currently AWXMeshIngress (hop nodes) instances are controlled by replicasets which are limited to a replica count of 1. 
The AWXMeshIngress CRD does not have a replica property.
To minimize downtimes and improve availability of hop nodes we would like to have a possibility to define replica count.
I'm not sure if AWX Operator is already able to distribute and handle executions on different hop nodes. So this might be a requirement.
If this possible then it would be great to update the AWXMeshIngress CRDs.

### Select the relevant components

- [ ] UI
- [x] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

It can't be reproduced yet. But it could be reproduced by using something like this (just a proposal):

```yaml
apiVersion: awx.ansible.com/v1alpha1
kind: AWXMeshIngress
metadata:
  name: my-hopnode
spec:
  deployment_name: awx
  ingress_type: none
  external_hostname: hopnode.example.org
  affinity: {}
  replicas: 3
```

### Current results

NA

### Sugested feature result

A hop node deployment and replicaset with a replica count defined in AWXMeshIngress.

### Additional information

NA
