### ISSUE TITLE
Vmware inventory source : guest.gueststate do not disable host in inventory

### ISSUE THREAD

**Issue by Kronk74** [ansible/awx#16000]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [x] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [x] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hi,

I'm trying to create an dynamic inventory using VMware vCenter source.
I found [here](https://groups.google.com/g/awx-project/c/SCjREu9P9pk) that it is possible the synchronize all hosts but disable those which are not running.

Based on [default awx params](https://github.com/ansible/awx/blob/devel/awx/settings/defaults.py#L598), I added the property _**guest.gueststate**_ to let the plugin enable or not the host. But it doesn't work and I don't know why :/

I saw also that inside the [vmware inventory plugin](https://github.com/ansible-collections/community.vmware/blob/main/plugins/inventory/vmware_vm_inventory.py#L101) the var is name a bit different : _guest.guest**S**tate_. 

I tried a trick like this but it doesn't work : 

```yaml
...
compose:
  guest.gueststate: guest.guestState
...
```

Does anyone already had this use case ?

Regards,

Thomas

### AWX version

24.6.1

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [x] Other

### Installation method

openshift

### Modifications

yes

### Ansible version

core 2.18.2

### Operating system

fedora

### Steps to reproduce

Try to get hosts via these params : 

```yaml
---
plugin: community.vmware.vmware_vm_inventory
hostnames:
  - 'config.name'
with_nested_properties: true
with_tags: true
compose:
  guest.gueststate: guest.guestState
properties:
  - 'config.name'
  - 'config.guestId'
  - 'guest.ipAddress'
  - 'guest.net'
  - 'guest.guestState'
  - 'guest.guestId'
  - 'guest.guestFamily'
  - 'summary.runtime.powerState'`
```

### Expected results

In  AWX interface, you should see all host and some disabled in function of guest.guestState variable result.

### Actual results

All hosts are enabled.

### Additional information

I tried multiple execution environments with different version but with no success.
