### ISSUE TITLE
No cached facts for some hosts

### ISSUE THREAD

**Issue by iyurev** [ansible/awx#1791]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

No cached facts for some hosts,  facts not exist iether API or web UI .

##### ENVIRONMENT
* AWX version: 1.0.3.0  
* AWX install method:  docker on linux
* Ansible version: 2.4.3.0 
* Operating System: CentOS 7

##### STEPS TO REPRODUCE
1. Configure AWX according to gude http://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html#ug-fact-caching
2. Configure and run job for fact gathering,  job playbook 
 ```
- name: Gather node facts
  become: yes
  become_user: root
  hosts: "{{ host_list }}"
  gather_facts: True
  tasks:

```
3.  Run  job with certain  invertory ( for all invertory hosts )

##### EXPECTED RESULTS

Can use cached facts for smart inventory filters and view them in AWX UI or via API .

##### ACTUAL RESULTS
For some host facts not cached , but  gathering job end with successfull status for them .
