### ISSUE TITLE
Not able to integrate containerized awx ansible tower with LDAP

### ISSUE THREAD

**Issue by rehanch178** [ansible/awx#1900]
Hi Team,

I am running Ansible tower docker version.

I configured LDAP authentication in the UI setting section of LDAP, but it is not working.

Wanted to know , does docker version of ansible tower support AD integration.

If yes, I am not sure, if I am making any mistake while configuring LDAP.

**Comment by joshuacherry** [comment]
It's working for me, the only issue I've run into was TLS. I had to set the server uri to `ldap://fqdn:389` and disable Start TLS.

**Comment by tumbl3w33d** [comment]
For the original question - yeah it works, at least with OpenLDAP so I would imagine AD should work as well. I've done that a while ago but as far as I remember, I followed the [tower doc](https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html) and it worked.

After the installation, when the containers are already running, I executed some commands using `docker exec` to `curl/wget` my CA from a webserver and `update-ca-trust` to get it active so STARTTLS would work with my self-signed cert as well.
``` yaml
  - name: trust CA in awx containers
    shell: docker exec -i {{ item }} bash -c 'curl http://someintranethttpd/static/myintranetca.crt > /etc/pki/ca-trust/source/anchors/myintranetca.crt && update-ca-trust extract'
    with_items:
      - awx_web
      - awx_task
```
and I think you need to restart the containers afterwards. Instead of downloading the CA you could also use `docker cp` to get it in, of course.
