### ISSUE TITLE
Custom credentials injector does not support hash result, only flat

### ISSUE THREAD

**Issue by miha-plesko** [ansible/awx#1965]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- API

##### SUMMARY
When defining custom credential type, I'm not able to inject fields as a dictionary, only flat string values seem to be accepted.

##### ENVIRONMENT
* AWX version: 1.0.6.15
* AWX install method: docker on linux
* Ansible version:  2.5.4
* Operating System: Ubuntu 16.04
* Web Browser: chromium

##### STEPS TO REPRODUCE

Navigate to **CREDENTIAL TYPES -> Create a new credential type** and input following data:

- name: "My Custom Credential"
- input configuration:

```yaml
---
fields:
  - id: userid
    type: string
    label: Username
  - id: password
    type: string
    label: Password
```

- injector configuration:

```yaml
---
extra_vars:
  auth:
    api_username: '{{ userid }}'
    api_password: '{{ password }}'
```

Then click **SAVE**.

##### EXPECTED RESULTS

Credential type should be saved with no problems.

##### ACTUAL RESULTS

Following error appears:

```
OrderedDict provided in relative path ['extra_vars', u'auth'], expected string
```

![capture](https://user-images.githubusercontent.com/8102426/41024247-000379ac-696f-11e8-8dda-5f9265519850.PNG)

##### ADDITIONAL INFORMATION

The result I'm trying to achieve is that when I later use such credentials type, following variable is available to my playbook:

```yaml
---
auth:
  api_username: myusername
  api_password: mypassword
```

ATM this seems not to be possible and I'm only able to pass flat values like this:

```yaml
---
auth_api_username: myusername
auth_api_password: mypassword
```

but then I need to modify all my playbooks that depend on `auth` variable only because I run them via AWX instead ansible directly...
