### ISSUE TITLE
Access host variables from dynamic inventory?

### ISSUE THREAD

**Issue by t-readyroc** [ansible/awx#2054]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

I've got an AWS dynamic inventory established. Each host shows all of the "ec2_" variables listed on this page if you look at its page in the UI (Inventories > Hosts > <hostname> > Details > Variables listing). Do I need to write a specific "include" statement in my playbook in order to access these variables?

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker
* Ansible version:  2.5.2
* Operating System: CentOS 7
* Web Browser: Various

##### STEPS TO REPRODUCE

code:
```
    - name: Get our instance info
      ec2_instance_facts:
        filters:
          instance-id: "{{ ec2_id }}"
      register: instance_info
```
##### EXPECTED RESULTS

Expected ec2_id variable to be populated in playbook run.

##### ACTUAL RESULTS

Results in this error:

```
ERROR! Syntax Error while loading YAML.
  did not find expected key
The error appears to have been in '/var/lib/awx/projects/_13__snapshot_testing/standalone/snapshot.yml': line 21, column 8, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
          instance-id: ""
       register: instance_info
       ^ here
```

##### ADDITIONAL INFORMATION

Seems to suggest that the variable isn't getting set. Had posted this over in the Google Group, but have only got a single view & no responses.
