### ISSUE TITLE
"Invalid search term entered. GET returned: -1" when clicking job.

### ISSUE THREAD

**Issue by verwilst** [ansible/awx#2061]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

"Invalid search term entered. GET returned: -1" when clicking on a job title on http://.../#/jobs?job_search=page_size:20;order_by:-finished;not__launch_type:sync

##### ENVIRONMENT
* AWX version: latest docker image, according to https://hub.docker.com/r/ansible/awx_task/tags/, it's version 1.0.6.25.
* AWX install method: docker on linux
* Ansible version:  -
* Operating System: Debian Stretch
* Web Browser: Firefox 60.0.0.2

##### STEPS TO REPRODUCE

- docker-compose up
- Create job template and launch it
- Go to http://.../#/jobs?job_search=page_size:20;order_by:-finished;not__launch_type:sync
- click on one of the listed jobs

##### EXPECTED RESULTS

Show detailed information about the job.

##### ACTUAL RESULTS

Error message "Invalid search term entered. GET returned: -1"

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/2114993/42556786-0851130a-84ed-11e8-8979-a8be21bbb1d1.png)

```
version: '3'
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /data/postgres/pgdata:/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: "memcached:alpine"

  awx_web:
    image: "ansible/awx_web:latest"
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  awx_task:
    image: "ansible/awx_task:latest"
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

```
