### ISSUE TITLE
with_lines fires before when

### ISSUE THREAD

**Issue by grb247** [ansible/awx#2101]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

---
- hosts: localhost
  tasks:
    - action: debug msg={{ foo }}
      when: foo is defined
      with_lines:
        - cat /this/doesnt/exist

Output:

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug msg={{foo}}] ***************************************************** 
cat: /this/doesnt/exist: No such file or directory
fatal: [localhost] => lookup_plugin.lines(cat /this/doesnt/exist) returned 1

FATAL: all hosts have already failed -- aborting

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

**Comment by ryanpetrello** [comment]
Hey @grb247,

This issue isn't unique to AWX itself, as I'm able to reproduce it with plain old `ansible-playbook`.

```yaml
~ cat test.yml
- hosts: localhost
  tasks:
    - action: debug msg={{ foo }}
      when: foo is defined
      with_lines:
        - cat /this/doesnt/exist
~ ansible-playbook -i localhost, -e ansible_connection=local test.yml

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************************************************************
cat: /this/doesnt/exist: No such file or directory
fatal: [localhost]: FAILED! => {"msg": "lookup_plugin.lines(cat /this/doesnt/exist) returned 1"}
	to retry, use: --limit @/home/ryanpetrello/venvs/tmp-13485fb2a1c7b7c0/test.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

You might consider asking on the Ansible mailing list (
https://groups.google.com/d/forum/ansible-project) or IRC room (#ansible on Freenode) if you need additional assistance with Ansible.
