### ISSUE TITLE
OpenShift authentication failed on TLS verification

### ISSUE THREAD

**Issue by dnguyen9** [ansible/awx#2114]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The ansible task 'OpenShift authentication failed on TLS verification]' will always fail if the authentication method to Openshift is token and not username/password.

##### ENVIRONMENT
* AWX version: 1.0.6
* AWX install method: openshift
* Ansible version: 2.5.3 
* Operating System: Linux RHEL 7
* Web Browser: n/a

##### STEPS TO REPRODUCE

Execute the install playbook and configure the inventory file to point to an openshift environment - fill in the below variables:
openshift_project=awx
openshift_user=myusername
openshift_skip_tls_verify=False
openshift_pg_emptydir=True
openshift_token=xxx

##### EXPECTED RESULTS

the playbook continue to run and log into openshift via token.
##### ACTUAL RESULTS

TASK [kubernetes : fail] *****************************************************************
skipping: [localhost]

TASK [kubernetes : Set kubernetes base path] *********************************************
ok: [localhost]

TASK [kubernetes : include_tasks] ********************************************************
included: /root/ansible-awx/installer/roles/kubernetes/tasks/openshift.yml for localhost

TASK [kubernetes : include_vars] *********************************************************
ok: [localhost]

TASK [kubernetes : Set kubernetes_namespace] *********************************************
ok: [localhost]

TASK [kubernetes : Ensure workspace directories exist] ***********************************
ok: [localhost] => (item=/tmp/awx-config)
ok: [localhost] => (item=/tmp/awx-config/.kube)

TASK [kubernetes : Authenticate with OpenShift via user and password] ********************
skipping: [localhost]

TASK [kubernetes : OpenShift authentication failed on TLS verification] ******************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'openshift_auth_result.rc != 0' failed. The error was: error while evaluating conditional (openshift_auth_result.rc != 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/root/ansible-awx/installer/roles/kubernetes/tasks/openshift.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: OpenShift authentication failed on TLS verification\n  ^ here\n"}
        to retry, use: --limit @/root/ansible-awx/installer/install.retry

PLAY RECAP *******************************************************************************
localhost                  : ok=17   changed=1    unreachable=0    failed=1

##### ADDITIONAL INFORMATION

- name: OpenShift authentication failed on TLS verification
  fail:
    msg: "Failed to verify TLS, consider settings openshift_skip_tls_verify=True {{ openshift_auth_result.stderr }}"
  when:
    - openshift_skip_tls_verify is not defined or not openshift_skip_tls_verify
    - openshift_auth_result.rc != 0
    - openshift_auth_result.stderr | search("certificate that does not match its hostname")

the error handling for TLS validation  assumes that the previous task will run and the result variable (openshift_auth_result) is defined with 'rc' key exist. instead what we get is this since the previous task was skipped.

ok: [localhost] => {
    "msg": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

**Comment by dnguyen9** [comment]
to fix this:

we just add in  openshift_auth_result.rc is defined and openshift_auth_result.rc != 0 in this task:

```
- name: OpenShift authentication failed on TLS verification
  fail:
    msg: "Failed to verify TLS, consider settings openshift_skip_tls_verify=True {{ openshift_auth_result.stderr }}"
  when:
    - openshift_skip_tls_verify is not defined or not openshift_skip_tls_verify
    -  openshift_auth_result.rc is defined  and openshift_auth_result.rc != 0
    - openshift_auth_result.stderr | search("certificate that does not match its hostname")

- name: OpenShift authentication failed
  fail:
    msg: "{{ openshift_auth_result.stderr }}"
  when: openshift_auth_result.rc is defined and openshift_auth_result.rc != 0


```
