### ISSUE TITLE
Injectors for Red Hat Satellite 6 within playbook job runs

### ISSUE THREAD

**Issue by drewburr** [ansible/awx#2192]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### SUMMARY

It would be useful to be able to manage Satellite via playbook tasks. AWX currently does not include injectors for the Satellite 6 credential, meaning they are not usable in a playbook. 

When creating a custom credential, these are the injectors used:
```yaml
injectors:
      extra_vars:
        satellite_username: "{{ '{{ \"{{username}}\" }}'}}"
        satellite_password: "{{ '{{ \"{{password}}\" }}'}}"
        satellite_host: "{{ '{{ \"{{host}}\" }}'}}"
```
