### ISSUE TITLE
Creating tar archive fails with error "Error writing image archive /tmp/awx_web_<version>.tar - write() argument must be str, not bytes"

### ISSUE THREAD

**Issue by moenka** [ansible/awx#222]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Trying to deploy awx to a remote docker host ansible fails when trying to create the tar archive.
```
TASK [local_docker : Export Docker web image if it isnt local and there isnt a registry defined] **********************************************************************************************
fatal: [docker1.<domain removed> -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error writing image archive /tmp/awx_web_1.0.0.503.tar - write() argument must be str, not bytes"}
	to retry, use: --limit @/home/monk/Forge/awx/installer/install.retry
```

##### ENVIRONMENT
* AWX version: 1.0.0.503
* Ansible version:  2.3.2.0 (also tested with 2.3.0.0, older versions will fail due to the `block` statement using the `name` attribute)
* Operating System: Ubuntu 16.04 local, CentOS 7 on the docker host

##### STEPS TO REPRODUCE

1. clone repository
2. cd into installer directory
3. comment localhost in the inventory file and replace with remote docker host (without the rest of the line after `ansible_connection=local` - so just the hostname)
4. run `ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

awx is installed and running on the docker host

##### ACTUAL RESULTS

See error message in section SUMMARY.
Repeating the run with the --limit argument wont help.

##### ADDITIONAL INFORMATION

Images are there when running `docker image ls` local.
```
awx_task                          1.0.0.503           720f343a102d        About an hour ago   998MB
awx_web                           1.0.0.503           b8c9610543c6        About an hour ago   971MB
awx_sdist_builder                 1.0.0.503           fa3d30a3e8a4        About an hour ago   683MB
```

Also the `installer/local_docker/tasks/main.yml` contains this task twice:

```
---
- name: Export Docker web image if it isnt local and there isnt a registry defined
  docker_image:
    name: "{{ awx_web_image }}"
    tag: "{{ awx_version }}"
    archive_path: "{{ awx_local_base_config_path|default('/tmp') }}/{{ awx_web_image }}_{{ awx_version }}.tar"
  when: inventory_hostname != "localhost" and docker_registry is not defined
  delegate_to: localhost

- name: Export Docker task image if it isnt local and there isnt a registry defined
  docker_image:
    name: "{{ awx_task_image }}"
    tag: "{{ awx_version }}"
    archive_path: "{{ awx_local_base_config_path|default('/tmp') }}/{{ awx_task_image }}_{{ awx_version }}.tar"
  when: inventory_hostname != "localhost" and docker_registry is not defined
  delegate_to: localhost

...
```
Uncommenting one task also wont help.
