### ISSUE TITLE
AWX does not perform SSH host key check

### ISSUE THREAD

**Issue by ccremer** [ansible/awx#2282]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Even if "forced" by using the configuration files, the SSH host keys are explicitly not checked

##### ENVIRONMENT
* AWX version: 1.0.7.2
* AWX install method: openshift
* Ansible version:  2.6.2
* Web Browser: Firefox 62.0

##### STEPS TO REPRODUCE
- Create a playbook repo with ansible.cfg as shown below and import in AWX
- Run it on a target host

##### EXPECTED RESULTS
```
SSH: EXEC ssh -vvv -F sshop_config1 -o StrictHostKeyChecking=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible_test -o ConnectTimeout=10 redacted-target-host '/bin/sh -c '"'"'echo ~ansible_test && sleep 0'"'"''
```

##### ACTUAL RESULTS
```
SSH: EXEC ssh -vvv -F sshop_config1 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible_test -o ConnectTimeout=10 redacted-target-host '/bin/sh -c '"'"'echo ~ansible_test && sleep 0'"'"''
```
--> notice StrictHostKeyChecking parameter. For some reason it does get added, which overrides the one defined in ansible.cfg and sshop_config1 file.

File ansible.cfg:
```yaml
[ssh_connection]
ssh_args = -F sshop_config1
host_key_checking = True
```
File sshop_config1:
```
Host redacted-target-host
    User ansible_test
    StrictHostKeyChecking yes
    UserKnownHostsFile {{ known_hosts_file }}
    ProxyCommand ssh ansible_test@redacted-jump-host -W redacted-target-host:22
    ControlMaster auto
Host redacted-jump-host
    User ansible_test
    StrictHostKeyChecking yes
    UserKnownHostsFile {{ known_hosts_file }}
    Port 22
    ControlMaster auto
```
sshop_known_hosts1 file:
```
redacted-target-host ssh-ed25519 AAAAC3...
redacted-jump-host,aaa.bbb.ccc.ddd,2a06:c0<snip> ssh-ed25519 AAAAC3N
```
Playbook:
```yaml
- hosts: localhost
  connection: local
  vars:
    known_hosts_file: sshop_known_hosts1
    ssh_config_file: sshop_config1
  tasks:
    - name: Create ssh config
      delegate_to: localhost
      connection: local
      template:
        src: templates/sshop_config.j2
        dest: "{{ ssh_config_file }}"
        mode: 0644
    - name: Create known_hosts
      delegate_to: localhost
      connection: local
      template:
        src: templates/sshop_known_hosts.j2
        dest: "{{ known_hosts_file }}"
        mode: 0644

- hosts: all
  tasks:
    - debug:
        var: ansible_user_id
    - debug:
        var: ansible_ssh_common_args
```
##### ADDITIONAL INFORMATION

The output is somewhat formatted for better readability
```
<redacted-target-host> SSH: EXEC ssh -vvv -F sshop_config1 -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible_test -o ConnectTimeout=10 redacted-target-host '/bin/sh -c '"'"'echo ~ansible_test && sleep 0'"'"''
he authenticity of host 'redacted-jump-host (redacted-ipv4)' can't be established.
ED25519 key fingerprint is SHA256:CCpaTtY3o<snip>.
ED25519 key fingerprint is MD5:a7:bb:ff:a6:5a:82:a<snip>.
Are you sure you want to continue connecting (yes/no)? 
<redacted-target-host> (255, '', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data sshop_config1
debug1: sshop_config1 line 1: Applying options for redacted-target-host
debug1: Executing proxy command: exec ssh ansible_test@redacted-jump-host -W redacted-target-host:22
debug3: timeout: 10000 ms remain after connect
debug1: permanently_drop_suid: 1005720000
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/awx/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/awx/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/awx/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/awx/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /var/lib/awx/.ssh/id_ecdsa type -1
deb…
<cut-off by AWX>
```
Then the playbook fails with
```
fatal: [redacted-target-host]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: <see error above, beginning with "OpenSSH...">
```
* The SSH key file for both hosts is the same.
* No variables are set on inventory, group or host
