### ISSUE TITLE
Scheduled Tasks don't fire after a day or two of overall awx_task container runtime

### ISSUE THREAD

**Issue by jstewart612** [ansible/awx#2407]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

We notice that, every day or so, we're having to bounce our AWX instance for it to run scheduled jobs again.
##### ENVIRONMENT
* AWX version: 2.0.0
* AWX install method: docker on linux
* Ansible version:  2.6
* Operating System:  Scientific Linux 7
* Web Browser:  Chrome

##### STEPS TO REPRODUCE

Start AWX using following compose file (passwords masked obviously)
```
version: '3'
services:

  web:
    image: ansible/awx_web:2.0.0
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "/var/lib/awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: xxxxxxxx
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: xxx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: xxx
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: xxx
      AWX_ADMIN_PASSWORD: xxx
      LDAPTLS_REQCERT: "never"
    command: /bin/sh -c '/bin/curl https://releases.hashicorp.com/envconsul/0.7.3/envconsul_0.7.3_linux_amd64.tgz --output envconsul_0.7.3_linux_amd64.tgz && /bin/tar zxvfp envconsul_0.7.3_linux_amd64.tgz -C /usr/bin/ && /bin/yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && /bin/yum -y install docker-ce && /bin/pip install --upgrade pip && /bin/pip install github3.py docker docker-compose && /usr/bin/launch_awx.sh'

  task:
    image: ansible/awx_task:2.0.0
    depends_on:
      - web
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "/var/lib/awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SECRET_KEY: xxxxxxxx
      DATABASE_NAME: awx
      DATABASE_USER: awx
      DATABASE_PASSWORD: xxx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: xxx
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      AWX_ADMIN_USER: xxx
      AWX_ADMIN_PASSWORD: xxx
      LDAPTLS_REQCERT: "never"
    command: /bin/sh -c '/bin/curl https://releases.hashicorp.com/envconsul/0.7.3/envconsul_0.7.3_linux_amd64.tgz --output envconsul_0.7.3_linux_amd64.tgz && /bin/tar zxvfp envconsul_0.7.3_linux_amd64.tgz -C /usr/bin/ && /bin/yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && /bin/yum -y install docker-ce && /bin/pip install --upgrade pip && /bin/pip install github3.py docker docker-compose && /usr/bin/launch_awx_task.sh'

  rabbitmq:
    image: ansible/awx_rabbitmq:latest
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: awx
      RABBITMQ_ERLANG_COOKIE: cookiemonster

  memcached:
    image: memcached:alpine
    restart: unless-stopped

  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    hostname: postgres
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: awx
    command: -c 'max_connections=4096' -c 'shared_buffers=1024MB'
```

##### EXPECTED RESULTS

AWX just keeps running and reliably runs Scheduled Tasks that are configured over multiple days of runs.
##### ACTUAL RESULTS

It runs for about a day or two before stopping dead and we have to restart all containers
##### ADDITIONAL INFORMATION

Container logs attached.
[awx.logs.zip](https://github.com/ansible/awx/files/2469546/awx.logs.zip)
