### ISSUE TITLE
changes in inventory are ignored

### ISSUE THREAD

**Issue by hudecof** [ansible/awx#246]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
template job did not relect changes in invenotry
 - hosts
 - groups
 - hostvars

##### ENVIRONMENT
* AWX version: e6777577b6b75e1f3e1b064c12432af3101c1f53
* Ansible version:  2.4.0
* Operating System: CentOS 7
* Web Browser: Firefox

##### STEPS TO REPRODUCE
- create inventory
- add 1 host (v1)
- create template
- run template (should be OK)
- add host  into inventory(v2)
- run template

##### EXPECTED RESULTS
The template should run on all hosts in modified inventory (v2) , but it stll run only on old one (v1).
The same behaviour is when ediing variables or even added project as source toinventory.

##### ACTUAL RESULTS
The template is ignoring any changes in the inventory since it was created. It somehow remembers the old inventory.

##### ADDITIONAL INFORMATION
None

**Comment by matburt** [comment]
I can't reproduce this. I followed your steps and launching the job template again after adding another host will show it run against both hosts.

Are you sure your playbook is not targeting only one host?

**Comment by hudecof** [comment]
very simple playbook
```
---
- hosts: all
  gather_facts: yes
  become: no
  vars:
    skip_hosts: []
  tasks:
  - group_by: key={{ ansible_os_family }}
    when: "inventory_hostname not in skip_hosts"

- hosts: RedHat
  gather_facts: no
  become: yes
  become_user: root
  tasks:
  - name: update for RedHat
    yum :
      name: '*'
      state: latest

- hosts: Debian
  gather_facts: no
  become: yes
  become_user: root
  tasks:
  - name: update for Debian
    apt:
      upgrade: yes
      update_cache: yes
      allow_unauthenticated: yes
      cache_valid_time: 3600
```
