### ISSUE TITLE
Missing Python module openshift in image ansible/awx_task:latest

### ISSUE THREAD

**Issue by devops-42** [ansible/awx#2471]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Installer

##### SUMMARY
I played around with the k8s plugin in Ansible and set up an according project on AWX. The playbook contains a task for creating an OpenShift namespace. My configured job aborted with an error:

`"msg": "This module requires the OpenShift Python client. Try pip install openshift"`

Due to user restrictions in OpenShift I'm not able to install the Python module manually.

##### ENVIRONMENT
* AWX version: 2.0.1
* AWX install method: openshift/minishift
* Ansible version:  2.7.0
* Operating System: macOS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Install AWX on OpenShift/MiniShift
- Create an ansible git project containing this task:

```
- name: Create a k8s namespace
  k8s:
    host: <OPENSHIFT_HOST_IP>
    username: <OPENSHIFT_USER>
    password: <OPENSHIFT_PASSWORD>
    name: sampleproject
    api_version: v1
    kind: Namespace
    state: present
```

- Set up project, inventory
- Create and run job

##### EXPECTED RESULTS

- AWX interacts with my OpenShift/MiniShift environment, i.e. the k8s plugin is fully usable.

##### ACTUAL RESULTS

- Job aborts with error:
`"msg": "This module requires the OpenShift Python client. Try pip install openshift"`
