### ISSUE TITLE
Allow another logging driver such as journald/syslog/splunk

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/awx#2637]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
By default, the logging driver is ```json-file``` and destroying a container will also remove logs. 
Changing it to ```journald``` for instance would allow us to access the logs of destroyed containers, on top of everything that is already possible with the default logging driver. In particular, the ```docker logs``` command remains available with ```journald``` (and only that one).
This feature can be made **optional** in ```installer/inventory``` with an option within the ```[all:vars]``` section:
```
logging_driver=journald
```
The user could even choose another logging driver such as ```syslog``` or ```splunk``` (the whole list of supported logging drivers is available [here](https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers)), if the user is notified somewhere that the ```docker logs``` command does NOT remain available for any other logging driver than ```journald```.

##### ADDITIONAL INFORMATION
This feature is enabled in the ```docker-compose.yml``` file for ```journald``` for instance with:
```
  web:
    logging:
        driver: journald
...
  task:
    logging:
        driver: journald
...
  rabbitmq:
    logging:
        driver: journald
...
  memcached:
    logging:
        driver: journald
...
  postgres:
    logging:
        driver: journald
...
```
The last entry depends on whether postgresql server is internal or external.
