### ISSUE TITLE
VMware: Missing Customvalue in inventories

### ISSUE THREAD

**Issue by 3kami3** [ansible/awx#2679]
VMware: Missing Customvalue in inventories

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

Missing Customvalue in inventories hosts details.

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.1
* Operating System: Red Hat Enterprise Linux Server release 7.5 (Maipo)
* Web Browser: Chrome 70.0.3538.102(Official Build) (64 bit)
```
# docker exec -it awx_task ansible --version
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### STEPS TO REPRODUCE

1. Add a new VMware Inventory item
1. Create a new Inventory Source
1. Add new Source Variables and include a properties YAML dictionary:
    ```
    ---
    validate_certs: False
    groupby_custom_field: True
    properties:
      prop01: name
      prop02: guest.ipAddress
      prop03: guest.guestId
      prop04: customvalue
    ```
1. Start a new inventory scan

##### EXPECTED RESULTS

```
<snip>
customvalue:
  - value: staging
    key: 46
  - value: sogi
    key: 47
<snip>
summary:
  customvalue:
    - value: staging
      key: 46
    - value: sogi
      key: 47
<snip>
```

##### ACTUAL RESULTS

1. Show Hosts Details

- INVENTORIES/test/HOSTS/mikami_ansible_XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX  
    - HOST NAME: mikami_ansible_XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX  
    - VARIABLES: 
    ```
    resourcepool:
      _moId: resgroup-8
      name: Resources
    alarmactionsenabled: true
    configissue: []
    tag: []
    <snip>
    customvalue: []    <-----*** result empty ***
    permission: []
    parentvapp: null
    recenttask: []
    availablefield: []
    overallstatus: green
    ansible_host: 10.128.32.100
    guest:
      hostname: mikamiansible
      toolsversionstatus: guestToolsUnmanaged
      generationinfo: []
      disk: []
      guestoperationsready: true
      guestfullname: CentOS 7 (64-bit)
      toolsversion: '10309'
      appstate: none
      guestfamily: linuxGuest
      toolsrunningstatus: guestToolsRunning
      toolsversionstatus2: guestToolsUnmanaged
      guestid: centos7_64Guest
      net: []
      appheartbeatstatus: appStatusGray
      guestkernelcrashed: false
      dynamictype: null
      screen: {}
      dynamicproperty: []
      toolsstatus: toolsOk
      powerpolicy: null
      ipaddress: 10.128.32.100
      gueststate: running
      toolsinstalltype: guestToolsTypeOpenVMTools
      interactiveguestoperationsready: false
      ipstack: []
      gueststatechangesupported: true
      toolsupdatestatus: null
    guestheartbeatstatus: green
    name: mikami_ansible
    rootsnapshot: []
    configstatus: green
    value: []
    summary:
      customvalue: []     <-----*** result empty ***
      guest: {}
      dynamictype: null
      config: {}
      dynamicproperty: []
      storage: {}
      vm: {}
      quickstats: {}
      runtime: {}
      overallstatus: green
    capability:
    <snip>
    ```

##### ADDITIONAL INFORMATION

$ cat vmware_inventory.ini | grep -v "^#" | grep -v "^$"
```
[vmware]
server = <vcenter>
username = <username>
password = <password>
validate_certs = False
cache_max_age = 0
groupby_custom_field = True
[properties]
prop01=name
prop02=guest.ipAddress
prop03=guest.guestId
prop04=customValue
```
$ ./vmware_inventory.py
```
{
  "all": {
    "hosts": [
      "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX"
    ]
  },
  "_meta": {
    "hostvars": {
      "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX": {
        "customvalue": [
          {
            "value": "staging",
            "key": 46
          },
          {
            "value": "sogi",
            "key": 47
          }
        ],
        "name": "mikami_ansible",
        "ansible_uuid": "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX",
        "guest": {
          "guestid": "centos7_64Guest",
          "ipaddress": "10.128.32.100"
        }
      }
    }
  },
  "vmware_tag_Department_sogi": {
    "hosts": [
      "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX"
    ]
  },
  "centos7_64Guest": {
    "hosts": [
      "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX"
    ]
  },
  "vmware_tag_Environment_staging": {
    "hosts": [
      "XXXXXXXX-XXXX-4XXX-8XXX-XXXXXXXXXXXX"
    ]
  }
}
```
![awx_cav](https://user-images.githubusercontent.com/12627100/48471241-ccffe300-e836-11e8-9a5d-1667967a03af.png)
