### ISSUE TITLE
Openstack Inventory Sources - source variables do not overwrite openstack.yaml variables 

### ISSUE THREAD

**Issue by mohclips** [ansible/awx#268]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Openstack Inventory Sources - source variables do not overwrite openstack.yaml variables as created and refered to in OS_CLIENT_CONFIG_FILE environment vars

##### ENVIRONMENT
* AWX version: 1.0.0.358

##### STEPS TO REPRODUCE

Create openstack credentials
create inventory
create inventory source
add source variables
```
---
clouds:
  devstack:
    auth:
      identity_api_version: 3
      region_name: uk-1
      project_id: fdfde7587dc647d287946d06a060aa4a
      user_domain_name: MyCoolDom
      project_name: overwrite_proj
```
save souce
sync source

login to awx task docker container
cd /tmp
;display the openstack.yml config file created by the sync task
cat awx_*/tmp*

##### EXPECTED RESULTS

```
[root@awx tmp]# cat awx_36_o3JY_P/tmpCZRY8S   
cache:
  path: /tmp/awx_36_o3JY_P/openstack_cacheRLFnNE
clouds:
  devstack:
    auth:
      auth_url: https://identity.cloud.global.dom.com/v3
      domain_name: some_dom
      identity_api_version: 3
      password: mypass
      project_id: fdfde7587dc647d287946d06a060aa4a
      project_name: overwrite_proj
      region_name: uk-1
      user_domain_name: MyCoolDom
      username: myuser
    private: true
```

##### ACTUAL RESULTS

```
[root@awx tmp]# cat awx_36_o3JY_P/tmpCZRY8S   
cache:
  path: /tmp/awx_36_o3JY_P/openstack_cacheRLFnNE
clouds:
  devstack:
    auth:
      auth_url: https://identity.cloud.global.dom.com/v3
      domain_name: some_dom
      password: mypass
      project_name: someproj
      username: myuser
    private: true
```

**Comment by matburt** [comment]
It looks like right now we just support a limited view of the vars that can be exposed to the client configuration: https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1639-L1680

I think we could definitely be more flexible here, and I'm totally fine receiving pull requests :)

I think the ones that we *specifically* include are the ones that we know to be required. We should be able to pick up any extra ones for use in the `auth` object on this data structure. The question is how to do that in a sensible way. As you can see, the source vars are pretty well strictly used for ansible inventory control variables.

**Comment by zeroware** [comment]
Hello,

I may be wrong but the `region_name` parameter is outside the `auth` object. At least this is what I can see in the example config : https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.yml
Being able to specify the region is really important for some provider like OVH Public Cloud

**Comment by mohclips** [comment]
@zeroware yes region_name  is outside auth (my mistake in the example i provided), but this still function needs to add source variables where ever they are required.   

Having looked at the code @matburt mentioned above (thanks for that), there does not seem to be any code that takes in cloud['devstack'] and below vars provided by the user and overwrites them to end up in the /tmp/awx_ temp file used to access the remote Openstack platform.  (I might be wrong but it certainly looks like there isn't).
I'll take a look at trying to shoehorn something in, but no promises, i can write a bit of python, but i'm no developer. :)

**Comment by mohclips** [comment]
Looking at this I can't seem to be able to manipulate the clouds dict.  If i add `region_name` to the `openstack_data` on lines https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L966 or https://github.com/ansible/awx/blob/devel/awx/main/tasks.py#L1658  these changes are not seen in the temp file created.   After adding quite a bit of logging into the tasks.py file, i'm not even sure its calling the functions (or its not logging).

So if someone could point me in the right direction, i'll take another stab at it.

thanks.

**Comment by AlanCoding** [comment]
The logic for this has been moved around (not changed), and with Ansible 2.8, we switch to running the inventory plugin. I want to follow through on this conversation, and be clear about what's possible.

`project_name` and `project_id` parameters, as well as some others, are defined by the openstack credential used by the inventory source.

The API version is accounted by the fact that we have an `openstack_v2` and `openstack_v2` credential type, with and without the domain. So if we let that be specified by the user, it would only break things.

The parameters we allow customization in source variables are:

 - use_hostnames
 - expand_hostvars
 - fail_on_errors

https://github.com/ansible/awx/blob/aaeb2d6fb98681bf7b530e3c769a1d25380bfd8f/awx/main/models/inventory.py#L2481-L2490

> Being able to specify the region is really important for some provider like OVH Public Cloud

I completely agree. If we support region filtering, then it should be done via the `source_regions` field, not by allowing arbitrary data from the user in source variables.

Feel free to open up an issue for that, if you'd like, and any information about where the parameter should go or how to get region options that would be helpful.

**Comment by rchaud** [comment]
Howdy,

I have come to my own solution using Custom Script and Credential Types since AWX developer have not added this to AWX, even after a couple of years of people reporting this. I created the following script which is my updated version of the official openstack script, this allow the env we need.

```
#!/usr/bin/env python

import argparse
import collections
import os
import sys
import time
from distutils.version import StrictVersion
from io import StringIO

import json
import yaml

import openstack as sdk
from openstack.cloud import inventory as sdk_inventory
from openstack.config import loader as cloud_config

import time

CONFIG_FILES = []


def get_groups_from_server(server_vars, namegroup=True):
    groups = []

    region = server_vars['region']
    cloud = server_vars['cloud']
    metadata = server_vars.get('metadata', {})

    # Create a group for the cloud
    groups.append(cloud)

    # Create a group on region
    if region:
        groups.append(region)

    # And one by cloud_region
    groups.append("%s_%s" % (cloud, region))

    # Check if group metadata key in servers' metadata
    if 'group' in metadata:
        groups.append(metadata['group'])

    for extra_group in metadata.get('groups', '').split(','):
        if extra_group:
            groups.append(extra_group.strip())

    groups.append('instance-%s' % server_vars['id'])
    if namegroup:
        groups.append(server_vars['name'])

    for key in ('flavor', 'image'):
        if 'name' in server_vars[key]:
            groups.append('%s-%s' % (key, server_vars[key]['name']))

    for key, value in iter(metadata.items()):
        groups.append('meta-%s_%s' % (key, value))

    az = server_vars.get('az', None)
    if az:
        # Make groups for az, region_az and cloud_region_az
        groups.append(az)
        groups.append('%s_%s' % (region, az))
        groups.append('%s_%s_%s' % (cloud, region, az))
    return groups


def get_host_groups(inventory, refresh=False, cloud=None):
    (cache_file, cache_expiration_time) = get_cache_settings(cloud)
    if is_cache_stale(cache_file, cache_expiration_time, refresh=refresh):
        groups = to_json(get_host_groups_from_cloud(inventory))
        with open(cache_file, 'w') as f:
            f.write(groups)
    else:
        with open(cache_file, 'r') as f:
            groups = f.read()
    return groups


def append_hostvars(hostvars, groups, key, server, namegroup=False):
    hostvars[key] = dict(
        ansible_ssh_host=server['interface_ip'],
        ansible_host=server['interface_ip'],
        openstack=server)

    metadata = server.get('metadata', {})
    if 'ansible_user' in metadata:
        hostvars[key]['ansible_user'] = metadata['ansible_user']

    for group in get_groups_from_server(server, namegroup=namegroup):
        groups[group].append(key)


def get_host_groups_from_cloud(inventory):
    groups = collections.defaultdict(list)
    firstpass = collections.defaultdict(list)
    hostvars = {}
    list_args = {}
    if hasattr(inventory, 'extra_config'):
        use_hostnames = inventory.extra_config['use_hostnames']
        list_args['expand'] = inventory.extra_config['expand_hostvars']
        if StrictVersion(sdk.version.__version__) >= StrictVersion("0.13.0"):
            list_args['fail_on_cloud_config'] = \
                inventory.extra_config['fail_on_errors']
    else:
        use_hostnames = False

    for server in inventory.list_hosts(**list_args):

        if 'interface_ip' not in server:
            continue
        firstpass[server['name']].append(server)
    for name, servers in firstpass.items():
        if len(servers) == 1 and use_hostnames:
            append_hostvars(hostvars, groups, name, servers[0])
        else:
            server_ids = set()
            # Trap for duplicate results
            for server in servers:
                server_ids.add(server['id'])
            if len(server_ids) == 1 and use_hostnames:
                append_hostvars(hostvars, groups, name, servers[0])
            else:
                for server in servers:
                    append_hostvars(
                        hostvars, groups, server['id'], server,
                        namegroup=True)
    groups['_meta'] = {'hostvars': hostvars}
    return groups


def is_cache_stale(cache_file, cache_expiration_time, refresh=False):
    ''' Determines if cache file has expired, or if it is still valid '''
    if refresh:
        return True
    if os.path.isfile(cache_file) and os.path.getsize(cache_file) > 0:
        mod_time = os.path.getmtime(cache_file)
        current_time = time.time()
        if (mod_time + cache_expiration_time) > current_time:
            return False
    return True


def get_cache_settings(cloud=None):
    config_files = cloud_config.CONFIG_FILES + CONFIG_FILES
    if cloud:
        config = cloud_config.OpenStackConfig(
            config_files=config_files).get_one(cloud=cloud)
    else:
        config = cloud_config.OpenStackConfig(
            config_files=config_files).get_all()[0]
    # For inventory-wide caching
    cache_expiration_time = config.get_cache_expiration_time()
    cache_path = config.get_cache_path()
    if cloud:
        cache_path = '{0}_{1}'.format(cache_path, cloud)
    if not os.path.exists(cache_path):
        os.makedirs(cache_path)
    cache_file = os.path.join(cache_path, 'ansible-inventory.cache')
    return (cache_file, cache_expiration_time)


def to_json(in_dict):
    return json.dumps(in_dict, sort_keys=True, indent=2)


def parse_args():
    parser = argparse.ArgumentParser(description='OpenStack Inventory Module')
    # parser.add_argument('--cloud', default=os.environ.get('OS_CLOUD'),
    #                     help='Cloud name (default: None')
    parser.add_argument('--private',
                        action='store_true',
                        help='Use private address for ansible host')
    parser.add_argument('--refresh', action='store_true',
                        help='Refresh cached information')
    parser.add_argument('--debug', action='store_true', default=False,
                        help='Enable debug output')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--list', action='store_true',
                       help='List active servers')
    group.add_argument('--host', help='List details about the specific host')

    return parser.parse_args()


def main():
    cloud_env = """clouds:
    devstack:
        auth:
            username: %s
            password: %s
            auth_url: %s
            project_name: %s
            domain_name: %s
            user_domain_name: %s
        private: true
        verify: %s
    """ % (os.environ.get('OS_USERNAME'),
        os.environ.get('OS_PASSWORD'),
        os.environ.get('OS_AUTH_URL'),
        os.environ.get('OS_PROJECT_NAME'),
        os.environ.get('OS_DOMAIN_NAME'),
        os.environ.get('OS_USER_DOMAIN_NAME'),
        os.environ.get('OS_VERIFY_SSL', 'true')
        )

    with open('clouds.yml', 'w') as file_clouds_new:
        yaml.dump(yaml.load(cloud_env, Loader=yaml.FullLoader), file_clouds_new, default_flow_style=False)

    args = parse_args()
    try:
        # openstacksdk library may write to stdout, so redirect this
        sys.stdout = StringIO()
        config_files = cloud_config.CONFIG_FILES + CONFIG_FILES + ['./clouds.yml']
        sdk.enable_logging(debug=args.debug)
        inventory_args = dict(
            refresh=args.refresh,
            config_files=config_files,
            private=args.private,
            cloud='devstack',
        )
        if hasattr(sdk_inventory.OpenStackInventory, 'extra_config'):
            inventory_args.update(dict(
                config_key='ansible',
                config_defaults={
                    'use_hostnames': os.environ.get('use_hostnames', False),
                    'expand_hostvars': os.environ.get('expand_hostvars', True),
                    'fail_on_errors': os.environ.get('fail_on_errors', True),
                }
            ))

        inventory = sdk_inventory.OpenStackInventory(**inventory_args)

        sys.stdout = sys.__stdout__
        if args.list:
            output = get_host_groups(inventory, refresh=args.refresh, cloud='devstack')
        elif args.host:
            output = to_json(inventory.get_host(args.host))
        print(output)
    except sdk.exceptions.OpenStackCloudException as e:
        sys.stderr.write('%s\n' % e.message)
        sys.exit(1)
    sys.exit(0)


if __name__ == '__main__':
    main()
```
  
And here is the Custom Credential.

```
Name: OpenStack Multi Cloud

INPUT CONFIGURATION:
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: auth_url
    type: string
    label: Authentication URL
  - id: project_name
    type: string
    label: Project (Tenant Name)
  - id: domain_name
    type: string
    label: Domain Name
  - id: user_domain_name
    type: string
    label: User Domain Name
  - id: verify
    type: boolean
    label: Verify SSL
    default: true
required:
  - username
  - password
  - auth_url
  - domain_name
  - project_name
  - user_domain_name

INJETOR CONFIGURATION:
env:
  OS_AUTH_URL: '{{auth_url}}'
  OS_DOMAIN_NAME: '{{domain_name}}'
  OS_PASSWORD: '{{password}}'
  OS_PROJECT_NAME: '{{project_name}}'
  OS_USERNAME: '{{username}}'
  OS_USER_DOMAIN_NAME: '{{user_domain_name}}'
  OS_VERIFY_SSL: '{{verify}}'
```
  
Use this credential type along with the custom script in a Source for a inventory should get your hosts from OpenStack:
You can also add the followings in extra variables for the source to change their settings.
```
use_hostnames: True  -> False is default
expand_hostvars: True -> True is default
fail_on_errors: True -> True is default
```
