### ISSUE TITLE
Feature: Support deploying on Kubernetes with Istio Service Mesh

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/awx#2714]
##### ISSUE TYPE
 - Feature Idea
Support deploying AWX on a Kubernetes cluster running an Istio Service Mesh with Sidecar Injection.

##### COMPONENT NAME
 - Installer

##### SUMMARY

As the installer stands today, the AWX pod will not start on a Kubernetes cluster running an Istio Service Mesh that automatically deploys sidecars with each deployed pod.
There are two parts to this: 
1. Getting an AWX pod running with an Istio sidecar injected
2. Ability to cluster multiple AWX pods (with or without MutualTLS enabled)

**Getting AWX pod running with an Istio sidecar injected**
Currently, when AWX deploys on Kubernetes with Istio sidecar injection enabled, the AWX pod will not fully support as the RabbitMQ container enters an endless crash cycle. By design, Istio only allows traffic on ports defined in a Kubernetes service. Erlang utilizes ports `4369` and `25672` to discover services and for cluster communication. The current service deployed by the installer does not expose ports `4369` and `25672`.

```yaml
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ kubernetes_namespace }}
  name: rabbitmq
  labels:
    app: {{ kubernetes_deployment_name }}
    type: LoadBalancer
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: {{ kubernetes_deployment_name }}
```

The changes mentioned above to the service allows the AWX pod to fully start on Kubernetes, however, trying to scale the AWX deployment past 1 pod will result in multiple AWX pods where RabbitMQ can not connect to the other discovered RabbitMQ instances.

**Ability to cluster multiple AWX pods**
Supporting clustering requires a few more changes. The current method AWX uses to discover other running RabbitMQ containers from other AWX pods is through rabbitmq_peer_discovery_k8s plugin and currently uses IP.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ kubernetes_namespace }}
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
      default_user = {{ rabbitmq_user }}
      default_pass = {{ rabbitmq_password }}
      default_vhost = awx

      ## Clustering
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc
      cluster_formation.k8s.address_type = ip
      cluster_formation.node_cleanup.interval = 10
      cluster_formation.node_cleanup.only_log_warning = false
      cluster_partition_handling = autoheal
      ## queue master locator
      queue_master_locator=min-masters
      ## enable guest user
      loopback_users.guest = false
```
By design, Istio prevents pod to pod communication by pod IP. The method of discovery above returns the pod IPs, and clustering fails since the pod to pod traffic is blocked. There is a workaround though. The workaround involves changes to the RabbitMQ service, the ConfigMap passed to the RabbitMQ container, the servicename the statefulset is tied to, adding additional environmental variables in the RabbitMQ container, and some Istio configurations. 

The change to the RabbitMQ service requires configuring the service as a headless service. This allows the pods to be discovered at `<pod_name>.awx-rabbitmq.<namespace>.svc`
```yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ kubernetes_namespace }}
  name: awx-rabbitmq
  labels:
    app: {{ kubernetes_deployment_name }}
    type: LoadBalancer
spec:
  type: ClusterIP
  clusterIP: None
  ports:
   - name: epmd
     protocol: TCP
     port: 4369
     targetPort: 4369
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
   - name: http-api
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: inter-node
     protocol: TCP
     port: 25672
     targetPort: 25672
  selector:
    app: {{ kubernetes_deployment_name }}
```

The AWX statefulset then needs to be tied to the RabbitMQ headless service. This allows the API call made by the rabbitmq_peer_discovery_k8s plugin to retrieve the pod information for the service.
```yaml
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ kubernetes_deployment_name }}
  namespace: {{ kubernetes_namespace }}
spec:
#  serviceName: {{ kubernetes_deployment_name }}
  serviceName: awx-rabbitmq
```

The RabbitMQ ConfigMap needs to be updated to use hostname instead of IP for discovery, and `cluster_formation.k8s.hostname_suffix` needs to be set if `RABBITMQ_USE_LONGNAME` is set to true.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ kubernetes_namespace }}
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
      default_user = {{ rabbitmq_user }}
      default_pass = {{ rabbitmq_password }}
      default_vhost = awx

      ## Clustering
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default
      cluster_formation.k8s.address_type = hostname
      cluster_formation.k8s.hostname_suffix = .awx-rabbitmq.{{ kubernetes_namespace }}.svc.cluster.local
      cluster_formation.node_cleanup.interval = 10
      cluster_formation.node_cleanup.only_log_warning = false
      cluster_partition_handling = autoheal
      ## queue master locator
      queue_master_locator=min-masters
      ## enable guest user
      loopback_users.guest = false
```

Along with the ConfigMap changes, additional environment variables are needed for the RabbitMQ pod.
```yaml
env:
    - name: MY_POD_NAME
      valueFrom:
         fieldRef:
           fieldPath: metadata.name
    - name: RABBITMQ_NODENAME
      value: "rabbit@$(MY_POD_NAME).awx-rabbitmq.{{ kubernetes_namespace }}.svc.cluster.local"
```

At this point AWX is deployed in a manner that supports clustering on Istio. The only remaining changes are configurations to Istio. If MutualTLS is disabled, then one ServiceEntry can be created to allow access. This is part of why I consider this a workaround because this does not automatically scale as the AWX pods are scaled. It's something that would need to be created or updated before scaling the pods. If MutualTLS is enabled, then a Policy along with a DestinationRule per host needs to be created.

MutualTLS Disabled
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rmq
  namespace: <namespace>
spec:
  hosts:
  - awx-0.awx-rabbitmq.<namespace>.svc.cluster.local
  - awx-1.awx-rabbitmq.<namespace>.svc.cluster.local
  - awx-2.awx-rabbitmq.<namespace>.svc.cluster.local
  ports:
  - number: 4369
    name: epmd
    protocol: TCP
  - number: 5672
    name: amqp
    protocol: TCP
  - number: 15672
    name: http
    protocol: HTTP
  - number: 25672
    name: inter-node
    protocol: TCP
```

MutualTLS Enabled (requires DestinationRule per host)
```yaml
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: awx-rabbitmq
  namespace: <namespace>
spec:
  targets:
  - name: awx-0
  - name: awx-1
  - name: awx-2
  peers:
  - mtls: {}

---
apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: awx-0
  namespace: <namespace>
spec:
  host: awx-0.awx-rabbitmq.<namespace>.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
    portLevelSettings:
    - port:
        number: 5672
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 15672
      tls:
        mode: ISTIO_MUTUAL
    - port:
        number: 25672
      tls:
        mode: ISTIO_MUTUAL
```
