### ISSUE TITLE
Add region or EC2_URL option to Amazon Web Services credential type

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#2804]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
Cannot use Amazon AWS / EC2 credential to take actions with modules in Ansible

##### ADDITIONAL INFORMATION

Create an AWS credential with all fields filled out, all valid data.

Run the playbook

```yaml

---
- name: Test use of credentials with cloud module, taken from Ansible docs
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances (credential_type=aws)
      ec2:
         state: "{{ state | default('absent') }}"
         instance_ids: ["8ut0o26a1g"]  # should not match anything
      tags:

```

Expected: successful, not changed

Actual:

> Either region or ec2_url must be specified

This issue is to add a parameter to the AWS credentials so that it can be used with the modules without additional hacking.
