### ISSUE TITLE
Feature: enhanced workflows

### ISSUE THREAD

**Issue by wenottingham** [ansible/awx#284]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY

Based on feedback, there are areas Workflows can be enhanced (outside of other areas with existing tickets):
- ~~Allow use of `always` nodes in combination with `success` and `failure` nodes~~ https://github.com/ansible/awx/issues/2255
- ~~Have a convergence step that tracks the completion of multiple workflow jobs before continuing~~ https://github.com/ansible/awx/issues/2254
- Allow ad-hoc commands in workflows https://github.com/ansible/awx/issues/2253
- ~~Allow workflows within workflows~~ https://github.com/ansible/awx/issues/2252
- ~~Add an 'allow_simultaneous' flag for workflows (that overrides the setting on nodes)~~ (already exists)

**Comment by hemskgren** [comment]
I like to see a workflow summary/end job option when there is parallel workflow jobs.

**Comment by chrismeyersfsu** [comment]
Initial design here comments welcome https://drive.google.com/open?id=1Uxndde44a0NFe7NbUR5WTFbkgPeJOTAUkzKqPRse0o8

**Comment by AlanCoding** [comment]
Heads up that #264 looks like it's becoming a new workflow feature as well.

**Comment by gdubicki** [comment]
In our setup we care only about "Convergence nodes". It's one of the missing features that blocks us from migrating some pipeline from Jenkins.

Can you please consider splitting this task into implementing "Convergence nodes" and "always" separately, and doing the former as first?

**Comment by wenottingham** [comment]
If we're going to spend a release tackling workflows, we'd want to do as much of this as possible, not a series of changes across multiple releases in a one-off fashion.

**Comment by gdubicki** [comment]
Thanks for a quick reply @wenottingham ! Do you have any ETA for this?

**Comment by wenottingham** [comment]
Barring contributions from the community at large, not in the next few months.

**Comment by livelace** [comment]
"convergence step" is absolutely necessary :)

At the moment I use such construction of Openstack Mistral::

```
tasks:
    task1:
        workflow: flow1
        on-complete:
            - fixate
    task2:
        workflow: flow2
        on-complete:
            - fixate

    fixate:
        join: all
        action: std.echo
        input:
            output: 'just echo'
        on-complete:
            - stop
```

task "stop" will be executed only if "task1" and "task2" will be completed.
