### ISSUE TITLE
'PyVmomiHelper' object has no attribute 'module' - Not able to run playbooks that use vmware_guest

### ISSUE THREAD

**Issue by daniel-lynch** [ansible/awx#2915]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI
 - Core

##### SUMMARY
When running a playbook that uses the vmware_guest Ansible module to create Virtual Machines the Web UI stdout is blank as well as the the API shows no activity for that job. The job runs indefinitely and cannot be killed through the web. When running the playbook on the awx_task container command line Ansible raises an exception.

##### ENVIRONMENT
* AWX version: 2.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.4
* Operating System: Ubuntu 18.04.1 LTS running Docker
* Web Browser: Chrome 70.0.3538.77

##### STEPS TO REPRODUCE

Web UI
Run the playbook in the additional information section with all variables filled out (We use tower's survey function) and launch the job. The playbook uses localhost.

Task container
source venv/ansible/bin/activate
ansible-playbook playbook.yml
Fill out the prompts

##### EXPECTED RESULTS

The playbook should run and reach out to our vcenter server and create a new Virtual Machine

##### ACTUAL RESULTS

Web UI/API
No output and the job cannot be canceled

Task Container
```
PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************************

TASK [Create virtual machine from template] ************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'PyVmomiHelper' object has no attribute 'module'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1544629992.04-214556431882032/AnsiballZ_vmware_guest.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1544629992.04-214556431882032/AnsiballZ_vmware_guest.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1544629992.04-214556431882032/AnsiballZ_vmware_guest.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vmware_guest_payload_zozjLJ/__main__.py\", line 2396, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_zozjLJ/__main__.py\", line 2322, in main\n  File \"/tmp/ansible_vmware_guest_payload_zozjLJ/__main__.py\", line 798, in __init__\n  File \"/tmp/ansible_vmware_guest_payload_zozjLJ/ansible_vmware_guest_payload.zip/ansible/module_utils/vmware.py\", line 777, in __init__\nAttributeError: 'PyVmomiHelper' object has no attribute 'module'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/var/lib/awx/test.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
``` 

##### ADDITIONAL INFORMATION

Here is a stripped down version of the playbook we are running

```
---
- hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: vcenter_hostname
      prompt: "vCenter Host"
      private: no

    - name: vcenter_username
      prompt: "vCenter Username"
      private: no

    - name: vcenter_password
      prompt: "vCenter Password"
      private: yes

    - name: vm_name
      prompt: "Virtual Machine Name"
      private: no

    - name: vm_template
      prompt: "Virtul Machine Template"
      private: no

    - name: vm_folder
      prompt: "Virtual Machine Location Folder (sys.inf, sys.qa, datayard.local, sys.svc)"
      private: no

    - name: vm_memory
      prompt: "Virtual Machine Memory"
      private: no

    - name: vm_cpus
      prompt: "Virtual Machine CPU(s)"
      private: no

    - name: vm_datastore
      prompt: "Virtual Machine Datastore"
      private: no

    - name: vm_disksize
      prompt: "Virtual Machine Disk Size (GB)"
      private: no

    - name: vm_network
      prompt: "Virtual Machine Primary Network"
      private: no

    - name: vm_billingid
      prompt: "Billing ID"
      private: no

  tasks:
    - name: Create virtual machine from template
      vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          datacenter: Redacted
          esxi_hostname: Redacted
          folder: /Redacted/vm/{{ vm_folder }}
          name: "{{ vm_name }}"
          state: poweredon
          template: "{{ vm_template }}"
          customvalues: [
            {
              "key": "BillingID",
              "value": "{{ vm_billingid }}"
            }
          ]
          disk:
          - size_gb: "{{ vm_disksize }}"
            type: thin
            datastore: '[{{ vm_datastore }}]'
          hardware:
            memory_mb: "{{ vm_memory }}"
            num_cpus: "{{ vm_cpus }}"
            num_cpu_cores_per_socket: 1
            scsi: paravirtual
          networks:
            - name: "{{ vm_network }}"
              type: dhcp
              start_connected: true
          wait_for_ip_address: yes
      delegate_to: localhost
```

This playbook is working on a couple different systems, I've created a fresh ubuntu install with ansible 2.7.4, python 2.7.12, and pyvmomi 6.7.1 and experience no errors.

To experience this issue you do not need an active vcenter server, you'll get the error even if you put incorrect information in the variables 

pyvmomi version on awx is 6.5, we've tried upgrading this as well just as a test then reverted.

Any help would be greatly appreciated.
Thanks!
