### ISSUE TITLE
ansible not loading library configuration from ansible.cfg

### ISSUE THREAD

**Issue by AerialRoots** [ansible/awx#2973]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - Ansible

##### SUMMARY
According to the logs in AWX the ansible.cfg for our project is being picked up and read, 
but it is not loaded some of the defined configuration values like library or module_utils

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: openshift
* Ansible version: 2.7.4 
* Operating System: centos7
* Web Browser: Firefox 64

##### STEPS TO REPRODUCE

1. Place a custom configuration file (ansible.cfg) at the root of the project with values for library and module_utils
2. Execute a playbook from this project with a high level debug
3. Check the "configured module search path" and "config file" values from the output.

##### EXPECTED RESULTS

I expected the ansible run to pickup the values from the ansible.cfg file and display them in the "configured module search path" and "config file". This currently works in an older version of AWX on 1.0.7.

##### ACTUAL RESULTS

When you check the debug output from the playbook the "configured module search path" and "config file" they appear to match the standard values as if the configuration file hadn't been read.
Here is what ends up getting listed:
configured module search path = [u'/usr/lib/python2.7/site-packages/awx/plugins/library']
ansible python module location = /usr/lib/python2.7/site-packages/ansible

##### ADDITIONAL INFORMATION

ansible.cfg
```
[defaults]
roles_path          = /etc/ansible/roles:/opt/custom_roles/roles
library             = /opt/custom_modules
internal_poll_interval = 0.05
gather_timeout = 20
module_utils = module_utils/

[ssh_connection]
retries = 45
````

Ansible output
```
ansible-playbook 2.7.4
  config file = /var/lib/awx/projects/_15__middleware/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/awx/plugins/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /var/lib/awx/projects/_15__middleware/ansible.cfg as config file
/tmp/awx_19_qw6j0f/tmpsUrZM7 did not meet host_list requirements, check plugin documentation if this is unexpected
Parsed /tmp/awx_19_qw6j0f/tmpsUrZM7 inventory source with script plugin
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/_15__middleware/playbooks/build_managedservers.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Write out our current tower job id to etcd
      ^ here

```

Playbook snippet (showing our module from custom_modules)
```
---
- name: Write out our current tower job id to etcd
  etcd_key:
    etcd_fqdn: "{{etcd_fqdn}}"
    key_path: "/environments/{{env}}/inventory/applications/{{app_name}}/components/{{component_name}}/most_recent_awx_job"
    username: "{{global_vars.awx_etcd_username}}"
    action: update
    data: "https://{{awx.hostname}}/#/jobs/playbook/{{tower_job_id}}"

- name: pull in the corresponding DNA file from our repo
  include_vars: "{{etcd_dna_file_path}}"

- name: import the base_component role
  import_role:
    name: base_component

- name: add host(s) to group 'ManagedServers'
  add_host:
    name: "{{item}}"
    groups: ManagedServers
  with_items: "{{valid_server_names}}"

```
