### ISSUE TITLE
AWX secret_key in K8s should be treated as a secret

### ISSUE THREAD

**Issue by grahamn-gr** [ansible/awx#2976]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
The SECRET_KEY used for postgres encryption/decryption is stored and comes from a configMap rather than a secret.

##### ENVIRONMENT
* AWX version: 2.1.2
* AWX install method: openshift
* Ansible version:  2.7.2
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

As seen here: https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/configmap.yml.j2#L7
the SECRET_KEY is part of a configMap file and doesn't come from K8s secret management.

The SECRET_KEY can be mounted on a volume mount and pulled from K8s as a secret by changing the deployment.yml file to include the following which applies to the celery, web containers and the management container.

Remove the secret_key entry from the configmap.yml.j2:

configmap.yml.j2
```
data:
#  secret_key: {{ secret_key }}
```

Apply these changes:

secret.yml.j2
```
data:
  secret_key: "{{ secret_key | b64encode }}"
```

deployment.yml.j2
```
          volumeMounts:
            - name: {{ kubernetes_deployment_name }}-application-config
              mountPath: "/etc/tower/settings.py"
              subPath: settings.py
              readOnly: true

            - name: {{ kubernetes_deployment_name }}-secret-key
              mountPath: "/etc/tower/SECRET_KEY"
              subPath: SECRET_KEY
              readOnly: true

      volumes:
        - name: {{ kubernetes_deployment_name }}-application-config
          configMap:
            name: {{ kubernetes_deployment_name }}-config
            items:
              - key: {{ kubernetes_deployment_name }}_settings
                path: settings.py

        - name: {{ kubernetes_deployment_name }}-secret-key
          secret:
            secretName: "{{ kubernetes_deployment_name }}-secrets"
            items:
              - key: secret_key
                path: SECRET_KEY
```

management-pod.yml.j2
```
      volumeMounts:
        - name: {{ kubernetes_deployment_name }}-application-config
          mountPath: "/etc/tower/settings.py"
          subPath: settings.py
          readOnly: true

        - name: {{ kubernetes_deployment_name }}-secret-key
          mountPath: "/etc/tower/SECRET_KEY"
          subPath: SECRET_KEY
          readOnly: true

  volumes:
    - name: {{ kubernetes_deployment_name }}-application-config
      configMap:
        name: {{ kubernetes_deployment_name }}-config
        items:
          - key: {{ kubernetes_deployment_name }}_settings
            path: settings.py

    - name: {{ kubernetes_deployment_name }}-secret-key
      secret:
        secretName: "{{ kubernetes_deployment_name }}-secrets"
        items:
            - key: secret_key
              path: SECRET_KEY
```

##### EXPECTED RESULTS

All secrets come from K8s built-in secret management.

##### ACTUAL RESULTS

SECRET_KEY stored in a configMap
