### ISSUE TITLE
ca_trust_dir only works for awx_web container and not awx_task container

### ISSUE THREAD

**Issue by lparkes** [ansible/awx#3010]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY

The installer at installer/roles/local_docker/tasks/standalone.yml creates volume mounts for ca_trust_dir in both the awx_web and awx_task containers, but the tasks clearly only run /usr/bin/update-ca-trust in the awx_web container. This results in the updated CA cert not being available for jobs run by AWX.

Skip to the end for the TL;DR.

##### ENVIRONMENT
* AWX version: 2.1.2.0
* AWX install method: docker on linux (playbook run on RHEL, docker is on Red Hat Atomic)
* Ansible version:  2.7.4
* Operating System: RHEL7
* Web Browser: Firefox

##### STEPS TO REPRODUCE

1) Configure up somewhere to put your CA certs on your docker server

```yaml
    - name: Create exportable trust anchor dierctory
      file:
        state: directory
        dest: /var/trust-anchors
        owner: root
        group: root
        mode: 0755
        setype: container_file_t

    - name: Export corporate CA cert for docker
      copy:
        src: certs/ca-root.cer
        dest: /var/trust-anchors/ca-root.cer
        owner: root
        group: root
        mode: 0644
        setype: container_file_t
```

2) Set ca_trust_dir=/var/trust-anchors in installer/inventory and and deploy AWX with ``ansible-playbook -i inventory -k install.yml``. 

3) In AWX try and use a corporate Git repository that uses HTTPS. A quicker test is to run ``docker exec awx_web curl https://corporate.web.server.com/`` and ``docker exec awx_web curl https://corporate.web.server.com/`` on the docker host.

##### EXPECTED RESULTS

I expect AWX to be able to access the corporate GIT repository via HTTPS and I expect the two curl commands to display some sort of web page.

##### ACTUAL RESULTS

The git pull fails with certificate errors as does the curl command run in the awx_task container. The curl command run in the awx_web container works fine.

##### ADDITIONAL INFORMATION

The task called "Update CA trust in awx_web container" has no counterpart for the awx_task container. (standalone.yml). 

I ran /usr/bin/update-ca-trust in the awx_task container and then I got my expected results.
