### ISSUE TITLE
Kubernetes is unable to execute from Ansible AWX 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3145]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

*  Ansible AWX Kubernetes Jobs/yaml is unable to execute. 

##### ENVIRONMENT
* AWX version: Ansible 2.7.4
* AWX install method: docker on linux 
* Ansible version:  2.7.4
* Operating System: 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

* Web Browser: Safari Web Browser from MacOS 

##### STEPS TO REPRODUCE

```
kylix3511 >>>> cat fetch_all_services.yaml 

---
- hosts: localhost
  connection: local
  vars:
      ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - python_requirements_facts:
         dependencies:
            - openshift
            - requests

    - name: Get a list of all service objects
      k8s_facts:
        api_version: v1
        kind: Service
        namespace: "kylix3511"
      register: service_list
kylix3511 >>>> 

```

##### EXPECTED RESULTS

Show return all the services in the namespace "kylix3511" 

##### ACTUAL RESULTS

 

[job_38.txt](https://github.com/ansible/awx/files/2826105/job_38.txt)

##### ADDITIONAL INFORMATION

open shift is already installed already still I'm getting that the openshit is missing. 

kylix3511 >>>> sudo pip freeze 
adal==1.2.1
asn1crypto==0.24.0
cachetools==3.1.0
certifi==2018.11.29
chardet==3.0.4
cryptography==2.1.4
dictdiffer==0.7.1
enum34==1.1.6
google-auth==1.6.2
idna==2.6
ipaddress==1.0.17
Jinja2==2.10
keyring==10.6.0
keyrings.alt==3.0
kubernetes==8.0.1
MarkupSafe==1.1.0
oauthlib==3.0.1
**openshift==0.8.4**
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.7.1
python-dateutil==2.7.5
python-string-utils==0.6.0
pyxdg==0.25
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.87
SecretStorage==2.3.1
six==1.11.0
urllib3==1.24.1
vboxapi==1.0
websocket-client==0.54.0
kylix3511 >>>>
