### ISSUE TITLE
A simple kubernetes k8s module is unable to execute from Ansible AWX. 

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3248]
@AlanCoding @ryanpetrello @willthames @chouseknecht @fabianvf 

##### ISSUE TYPE
 - Bug Report

Related to Issue : https://github.com/ansible/awx/issues/3208 

##### COMPONENT NAME

 - UI

##### SUMMARY

Ansible AWX Kubernetes Jobs/yaml is unable to execute.

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on linux
* Ansible version:  Ansible 2.7.7
* Operating System:
  NAME="Ubuntu"
  VERSION="18.04.1 LTS (Bionic Beaver)"
* Web Browser: Safari Web Browser from MacOS

##### STEPS TO REPRODUCE

```
kylix3511 >>>> cat fetch_all_services.yaml 

---
- hosts: localhost
  connection: local
  vars:
      ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - python_requirements_facts:
         dependencies:
            - openshift
            - requests

#    - name: Get a list of all service objects
 #     k8s_facts:
   #     api_version: v1
     #   kind: Service
        # namespace: "kylix3511"
      #register: service_list

   - name: Get a list of all service objects
      k8s:
        api_version: v1
        kind: Service
        namespace: "kylix3511"
      register: service_list

kylix3511 >>>>

```
##### EXPECTED RESULTS

Show return all the services in the namespace "kylix3511"

##### ACTUAL RESULTS

[job_44.txt](https://github.com/ansible/awx/files/2871395/job_44.txt)

##### ADDITIONAL INFORMATION

I follow the https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#preparing-a-new-custom-virtualenv to install openshift in the ***docker awx-task container*** still I have same issue and same error ...  ***seems more direction or documentation needed for AWX on Docker virtual env. ***

```

[root@awx .kube]# hostname
awx
[root@awx .kube]# pip search kubernetes  | grep -i installed
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  INSTALLED: 8.0.1 (latest)
[root@awx .kube]# pip search openshift  | grep -i installed
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  INSTALLED: 0.8.6 (latest)
[root@awx .kube]# 
[root@awx .kube]# pip show openshift
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: openshift
Version: 0.8.6
Summary: OpenShift python client
Home-page: https://github.com/openshift/openshift-restclient-python
Author: OpenShift
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /usr/lib/python2.7/site-packages
Requires: kubernetes, python-string-utils, ruamel.yaml, jinja2, dictdiffer, six
Required-by: 
[root@awx .kube]# 
[root@awx .kube]# 
[root@awx .kube]# pip show kubernetes
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: kubernetes
Version: 8.0.1
Summary: Kubernetes python client
Home-page: https://github.com/kubernetes-client/python
Author: Kubernetes
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /usr/lib/python2.7/site-packages
Requires: ipaddress, websocket-client, setuptools, certifi, pyyaml, requests-oauthlib, six, adal, requests, python-dateutil, google-auth, urllib3
Required-by: openshift
[root@awx .kube]# 
[root@awx .kube]# pwd
/var/lib/awx/.kube
[root@awx .kube]# ls -lrt config
-rw------- 1 root root 13918 Feb 16 00:13 config
[root@awx .kube]# 

```

**Related to this bug ... there is also also quick question: 

/var/lib/awx/.kube is a container image/space. I believe the config should be either outside of the container or just keep it in persistence volume ? Is there any solution for this issue ? 

I believe the SSL handshake is not happening due to the fact the .kube/config is in the container and not able to communicate with kubernetes cluster/context.**
