### ISSUE TITLE
RFE: Hide artifacts values in workflow job

### ISSUE THREAD

**Issue by saito-hideki** [ansible/awx#3249]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Using workflow job template, user wants to pass secret values with set_stats, but `artifacts` and `extra_vars` are not able to mask those values.
For the security reason, users want to mask these variables from the `artifacts` and `extra_vars` in the UI / API if necessary.

##### ADDITIONAL INFORMATION

1. Create a workflow job template: JOB1(test1.yml) --"RUN: on succee" --> JOB2(test2.yml)
2. We will see `SECRET VALUE` as a plain text in `artifacts` of JOB1 and `extra_vars` in JOB2 as well, even if we use no_log: True in both of playbooks

- test1.yml

```
---
- hosts: localhost
  no_log: True

  tasks:
    - set_stats:
        data:
          message: "SECRET VALUE"
```

- test2.yml

```
---
- hosts: localhost
  no_log: True

  tasks:
    - debug:
        msg: "{{ message }}"
```

**Comment by AlanCoding** [comment]
Have you tried changing the first playbook to use `no_log`, like

```yaml
---
- hosts: localhost
  no_log: True

  tasks:
    - set_stats:
        data:
          message: "SECRET VALUE"
      no_log: true
```

I'm trying to find where that was documented, but looks like it might have been a notable omissions in the docs.

EDIT: or, maybe this was the original design and it was eventually dropped due to some problems with how we got the data, I don't remember at the moment
