### ISSUE TITLE
Allow additional directory mounts for local docker setup

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/awx#3252]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - Installer

##### SUMMARY

In my AWX jobs, which include regular backups and other kind of directory synchronizations, I'd like to access NFS shares directly instead of using a third server that mounts them for me. In a container I cannot mount the volume directly without adding privileges on container launch time.
The [elegant solution since docker 17.06](https://stackoverflow.com/a/45911186/10429943) is [creating a named volume](https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options) ahead of awx container launch that can then be added to the awx_task container.

Of course, this is neither limited to NFS nor named volumes. You could also mount the NFS share on the docker host and use a simple bind mount.

##### ADDITIONAL INFORMATION
I tested this with awkward replacement logic in my automated AWX deployment so in case this feature gets rejected or not merged in the near future, here is your workaround in case you're doing something similar:
``` yaml
[...]
- name: add custom volumes to inventory
    lineinfile:
      path: /root/awx/installer/inventory
      line: "additional_task_volumes=['mynamedvolume:/mnt/mynamedvolume:z']"
  - name: bind volumes to task container
    lineinfile:
      path: /root/awx/installer/roles/local_docker/tasks/standalone.yml
      insertafter: "^.*\\(\\[project_data_dir \\+ ':/var/lib/awx/projects:z'\\] if project_data_dir is defined else \\[\\]\\)"
      line: "        + (additional_task_volumes if additional_task_volumes is defined else [])"
  - name: launch awx installer
    shell: ansible-playbook -i inventory install.yml
[...]
```
I will create a PR for this.
