### ISSUE TITLE
syntax error executing junos_command module from source control

### ISSUE THREAD

**Issue by cdeniro** [ansible/awx#3301]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
When using playbooks from git containing juniper_junos_command module there is always a syntax error on the first task

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker
* Ansible version:  2.7.7
* Operating System: ubuntu 18.04
* Web Browser: firefox

##### STEPS TO REPRODUCE

Connect to any playbook containing juniper_junos_command via git

##### EXPECTED RESULTS

playbook to run without error

##### ACTUAL RESULTS

SSH password: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/_11__backup/Playbooks/get_config.yml': line 16, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: get configuration in set on device
    ^ here

##### ADDITIONAL INFORMATION

If i run the exact same playbook via awx cli or manual project it works fine

**Comment by cdeniro** [comment]
This is the playbook being executed

```
- name: get_config
  hosts: all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars:
    provider_info:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        user: ##
        password: ##
  tasks:
  - name: get configuration in set on device
    juniper_junos_command:
      provider: "{{ provider_info }}"
      command: 'show configuration | display set'
      dest: "./configs/juniper_configs/{{ inventory_hostname }}.conf"
```
