### ISSUE TITLE
Implement a system for allowing a user to load dependencies

### ISSUE THREAD

**Issue by matburt** [ansible/awx#332]
This is likely to be done as part of container configuration. It needs to support both standalone Docker deployments and container cluster style deployments. This also needs to be dynamic so it can be reconfigured in the application without needing to regenerate the containers. This also allows for easy propogation across the cluster in the same way we perform some other cluster-wide operations.

**Comment by jamestutton** [comment]
Don't we already have this via playbooks themselves:  For example I have something like this playbook to ensure the container running the job has all the bits it needs:

```
- name: Prepare ansible environment
  hosts: 127.0.0.1
  connection: local
  environment:
    http_proxy: http://myproxy:8080
    https_proxy: http://myproxy:8080
  tasks:
    # Install (zabbix-api) python package.
    - name: Install Python Modules
      pip:
        name: "{{ item }}"
      with_items:
        - zabbix-api
        - pysphere
```

If your in no rush you can run this at the start of the job or my preference I have it as a separate template that runs on demand as should only need to be run if the container is new or recreated.
