### ISSUE TITLE
Associating AWS credential to job template is not idempotent 

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#3383]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API

##### SUMMARY
the [tower_job_template](https://docs.ansible.com/ansible/latest/modules/tower_job_template_module.html) module today does not have the ability to use any credential type, and I need to be able to use AWS.

I register the result from the tower_credential module and I register the result from the tower_job_template module to get the id for the credential and job template, I then use the URI module to associate the AWS module to the correct job template.  This works, but only works one time, if I re-run the Playbook the tower API is not happy, it doesn't see it already has a matching credential in there.  The full Playbook is [located here](https://gist.github.com/IPvSean/6074d7a77ee2e39cd180f6fb0be5b4a6)

##### ADDITIONAL INFORMATION
task that will fail

```
    - name: ASSOCIATE AWS CREDENTIAL TO JOB TEMPLATE
      uri:
        url: "https://{{host}}/api/v2/job_templates/{{create_first_job.id}}/credentials/"
        user: "{{username}}"
        password: "{{password}}"
        method: POST
        validate_certs: False
        force_basic_auth: yes
        body_format: json
        body: ' {"id": {{credential.id}}}'
        status_code:
          - 200
          - 204
```

first time works!

2nd time does this->
```    error: Cannot assign multiple Amazon Web Services credentials.```

rull error is here->
```
TASK [ASSOCIATE AWS CREDENTIAL TO JOB TEMPLATE] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  allow: GET, POST, HEAD, OPTIONS
  connection: close
  content: '{"error":"Cannot assign multiple Amazon Web Services credentials."}'
  content_language: en
  content_length: '67'
  content_type: application/json
  date: Thu, 07 Mar 2019 15:27:45 GMT
  json:
    error: Cannot assign multiple Amazon Web Services credentials.
  msg: 'Status code was 400 and not [200, 204]: HTTP Error 400: Bad Request'
  redirected: false
  server: nginx/1.12.2
  status: 400
  url: https://ansible.rhdemo.io/api/v2/job_templates/75/credentials/
  vary: Accept, Accept-Language, Cookie
  x_api_node: localhost
  x_api_time: 0.083s
  x_api_total_time: 0.101s
	to retry, use: --limit @/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/tests/setup_tower.retry
```
