### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED ansible AWX

### ISSUE THREAD

**Issue by L1ghtman2k** [ansible/awx#3397]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

panos_zone module, included using library

##### SUMMARY
When attempting to run module that is making a request to a host with self-signed cert, the module fails.

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method:docker
* Ansible version:  Ansible 2.7.7 
* Operating System: CENTOS 7

##### STEPS TO REPRODUCE

1) include panos_zone.py in playbook's library folder
2) install pan-python, and pandevice using virtualenv ansible on aws
3) Run the follwing code

```
    - name: create outside zone on a firewall
      panos_zone:
        ip_address: "192.168.1.1"
        username: 'admin'
        password: 'admin'
        zone: 'outside'
        mode: 'layer3'
```

##### EXPECTED RESULTS

Zone outside created on PANOS

##### ACTUAL RESULTS

When using panos_zone, I am getting the following error:
```
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "log_setting": null,
            "zone": "outside",
            "vsys": "vsys1",
            "include_acl": null,
            "zone_profile": null,
            "exclude_acl": null,
            "state": "present",
            "mode": "layer3",
            "template": null,
            "enable_userid": false,
            "interface": null,
            "api_key": null,
            "ip_address": "192.168.1.1"
        }
    },
    "changed": false,
    "msg": "URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)"
}
```

I have tried to set PYTHONHTTPSVERIFY=0 in awx_task, however that still did not help
