### ISSUE TITLE
Dynamic Inventory in AWX Using Azure Resource Manager as a Source

### ISSUE THREAD

**Issue by akamalov** [ansible/awx#3430]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 
##### SUMMARY

Trying to configure Dynamic Inventory in AWX against Azure environment

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: docker on linux
* Ansible version:  2.7.8
* Operating System: CentOS7.4
* Web Browser: Chrome 70.0.x
* cURL: 7.63.0

##### STEPS TO REPRODUCE

1. Create Azure Credentials
2. Create Inventory sourcing Azure Resource Manager
3. Verify that Azure resources have been discovered
4. Create variables in Inventory to contain settings (like in azure_rm.ini):

{
 "resource_groups": "mygroup1",
 "tags": "zookeepernodes, zookeeper_id: zkid",
 "group_by_resource_group": yes,
 "group_by_location": yes,
 "group_by_security_group": yes,
 "group_by_tag": yes,
 "use_private_ip": yes,
 "location": "eastus2",
 "include_powerstate": yes
}

##### EXPECTED RESULTS

I expected the inventory would be populated based on settings provided (narrowed down to Resource group: "mygroup1", which hosts defined in tag: "zookeepernodes"

If possible, can I pass bool ```use_private_ip``` to it ? 

##### ACTUAL RESULTS

AWX is still displaying all hosts in the inventory as well as all groups!!!

##### ADDITIONAL INFORMATION

null

**Comment by AlanCoding** [comment]
I have tested the group_by, the resource group filter, and using the private IP. All of these work by my testing.

> "group_by_location": yes,

This looks like a hybrid of the config file format (`group_by_location=yes`) and JSON (`"group_by_location": true`). My best shot at troubleshooting your problem would be to assure that the server displays your inventory source source_vars in the latter format. In the UI, you should be in the SOURCES tab for the inventory, and looking at the text box with source variables.

**Comment by akamalov** [comment]
Thanks Alan. I will hive it a try.

**Comment by akamalov** [comment]
Hey @AlanCoding , thanks yet again for your reply. Tried it first thing today. 

Extra Variables:
```
{
	"ansible_user": "XXXXXXXXXXX",
	"zookeeper_password": "XXXXXXXXX",
	"AZURE_GROUP_BY_LOCATION": true,
	"AZURE_GROUP_BY_RESOURCE_GROUP": true,
	"AZURE_GROUP_BY_SECURITY_GROUP": true,
	"AZURE_GROUP_BY_TAG": true,
	"AZURE_LOCATIONS": "eastus2",
	"AZURE_TAGS": {
		"zookeepernodes": "hosts",
		"zookeeper_id": "zkid"
	},
	"AZURE_RESOURCE_GROUPS": "mygroup1"
}
```
For some reason, Ansible not detecting a tag (already created on each VM instance) - ```zkid```. I am pretty assigning key/value for zookeeper_id. The tag ```zkid``` is defined with VM instance.

```
 "tags": {
    "displayName": "dev-zookeeper VM Creation",
    "name": "zookeeper - default",
    "ssh_ip": "192.168.2.9",
    "ssh_user": "XXXXXXXXX",
    "zkid": "1",
    "zookeepernodes": "zk1"
  },
  "type": "Microsoft.Compute/virtualMachines",
  "vmId": "XXXXXXXXX-3319-4508-9097-d80a079eacde",
  "zones": null
```

However, when my playbook executes, it has to initialize zookeeper where it references ```zookeeper_id```:
```
---

  # Initializing `myid` File for Zookeeper.
  - name: Initializing `myid` File for Zookeeper.
    become: true
    become_method: sudo
    become_user: "{{ zookeeper_user }}"
    command: creates={{ zookeeper_data_store }}/myid {{ common['soft_link_base_path'] }}/zookeeper/bin/zkServer-initialize.sh --myid={{ zookeeper_id }} --force
    tags:
      - zookeeper_init_file

```
Unfortunately it exits with an error:

```
failed: [zk3] (item=zoo.cfg) => {"changed": false, "item": "zoo.cfg", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'zookeeper_id'"}
failed: [zk1] (item=zoo.cfg) => {"changed": false, "item": "zoo.cfg", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'zookeeper_id'"}
failed: [zk2] (item=zoo.cfg) => {"changed": false, "item": "zoo.cfg", "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'zookeeper_id'"}
```

Any pointers would be tremendously appreciated!!!

**Comment by AlanCoding** [comment]
This isn't quite `devel`, but only a checkbox is different:

![Screen Shot 2019-03-18 at 11 17 10 AM](https://user-images.githubusercontent.com/1385596/54559546-a72a4c80-4996-11e9-8574-8dcdfbc6bc08.png)

It looks like you're trying to set this up for a _job_ run, which will not work right. AWX is designed so that you run an inventory import (by creating an inventory source and updating it), which pulls in the host, and then those will be used in the playbook run. You can set the inventory source to update on launch if you want it to run in advance of a job run.

**Comment by akamalov** [comment]
Thanks so much @AlanCoding  for quick response. I actually have a source setup with variables defined and 'update-on-launch' configured:

![image](https://user-images.githubusercontent.com/7885257/54560445-c0cc9380-4998-11e9-934f-1b4e361a8645.png)

Again, it correctly identifies resource group,  ```zookeepernodes``` does everything it supposed to do, except, the tag assignment for ```zookeeper_id``` does not read tag value defined in ```zkid```  (i.e., ```zookeeper_id: zkid```) which is defined during VM instance creation.  Under a script version of ```azure_rm.py```, I would define azure_rm.ini as such:

```
# Control which tags are included. Set tags to a comma separated list of keys or key:value pairs
tags=zookeepernodes:hosts,kafkanodes:hosts,zookeeper_id:zkid,kafka_broker_id:broker_id,kafka_port:kafka_port
```
...and it would pick up ```zookeeper_id``` off  ```zkid```, however under AWX it seems to be failing...

**Comment by AlanCoding** [comment]
The closest thing we have to documentation for what you're trying to do would be at:

https://github.com/ansible/awx/blob/358ad05e51ac16124e7c960bcf7ceb0a52e0b011/awx/plugins/inventory/azure_rm.ini.example#L9-L10

If you compare to my example:

https://github.com/ansible/awx/blob/358ad05e51ac16124e7c960bcf7ceb0a52e0b011/awx/plugins/inventory/azure_rm.ini.example#L19

```yaml
group_by_resource_group: true
```

I'm using the same key-value content in SOURCE VARIABLES as in the example .ini file (aside from format / representations). If I were to apply that same criteria to the tags filter that you're trying to use, I would expect to see the yaml version of the vars as

```yaml
tags: zookeeper_id:zkid
```

(you might need quotes for "zookeeper_id:zkid", not sure)

Prefixing the keys with AZURE_ doesn't match up with anything I know of.

I'm not saying that any of this was obvious, I fully understand how we require different source_vars syntax for different sources, which is terrible and I am trying to get rid of. Azure_rm, however, does a dumb dump of those variables to the config file (under `[azure]` section).

**Comment by akamalov** [comment]
Thanks for your response @AlanCoding. Unfortunately, it's not picking up tags. Here are the details:

In AWX, under source, I've defined the following source vars:

```
group_by_location: true
group_by_resource_group: true
group_by_security_group: true
group_by_tag: true
locations: eastus2
resource_groups: mygroup1
tags:
  "zookeeper_id: zkid"

```

In job template, the following variables have been defined:

```
ansible_user: XXXXXXXXX
tags: "zookeeper_id:zkid"
zookeeper_password: XXXXXXXX
```

My ZooKeeper init.yml file contains the following:

```
---

  # Initializing `myid` File for Zookeeper.
  - name: Initializing `myid` File for Zookeeper.
    become: true
    become_method: sudo
    become_user: "{{ zookeeper_user }}"
    command: creates={{ zookeeper_data_store }}/myid {{ common['soft_link_base_path'] }}/zookeeper/bin/zkServer-initialize.sh --myid={{ zookeeper_id }} --force
    tags:
      - zookeeper_init_file

```
Next, running the script yields the following error:

```
TASK [zookeepernodes : Initializing `myid` File for Zookeeper.] ****************
fatal: [zk1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'zookeeper_id' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_13__zookeeper_nodes/roles/zookeepernodes/tasks/init.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Initializing `myid` File for Zookeeper.\n  - name: Initializing `myid` File for Zookeeper.\n    ^ here\n"}
fatal: [zk2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'zookeeper_id' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_13__zookeeper_nodes/roles/zookeepernodes/tasks/init.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Initializing `myid` File for Zookeeper.\n  - name: Initializing `myid` File for Zookeeper.\n    ^ here\n"}
fatal: [zk3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'zookeeper_id' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_13__zookeeper_nodes/roles/zookeepernodes/tasks/init.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Initializing `myid` File for Zookeeper.\n  - name: Initializing `myid` File for Zookeeper.\n    ^ here\n"}
```

Regarding prefixing with ```AZURE_```, I got it off the following URL documentation for Ansible: https://docs.ansible.com/ansible/2.3/guide_azure.html

**Comment by AlanCoding** [comment]
You should be able to view the hostvars for one of the imported hosts. Why can't you remove `tags: "zookeeper_id:zkid"` from the job template (it confuses the issue) and reference `{{ tags['zookeeper_id'] }}` in the playbook?

Because I can do test imports, I am quite sure of the data structure in hostvars, which is `"tags": {"zookeeper_id": "value"}`. If what you need from this is "value", then that should be available within the namespace as your are within a particular task for an Azure host that this applies to.

If you need a host pattern to obtain all the zookeeper hosts, then I'd expect `zookeeper_id` to be a valid group name constructed by the inventory import.

The use of "tags" in the Azure inventory config, IIRC, is for _filtering_ by tags. You shouldn't need to do anything special if you just need to _reference_ a tag in a playbook.

**Comment by akamalov** [comment]
@AlanCoding . You were absolutely right! I had to remove that ```tags: "zookeeper_id:zkid"``` completely and just simply reference it as you told (i.e., ```{{ tags['zookeeper_id'] }}```. 

Thank You So Much for helping me troubleshoot it!! You rock!!!

**Comment by raidlman** [comment]
Hi @AlanCoding. Could you please clarifiy how the tags work?
I have multiple hosts in my resource group `my_rg`. One is tagged with `key=ansible,value=test`.
I thought specifying the following SOURCE VARIABLES would filter all hosts by this tag.

```
group_by_location: true
group_by_resource_group: true
group_by_security_group: true
group_by_tag: true
resource_groups: my_rg
tags: "ansible:test"
```

But instead of returning just the one host, no host is returened at all. If I remove `tags: "ansible:test"` all hosts in the resource group are returned and the correct tag is listed in the hostvars:

```
 "tags": {
  "ansible": "test"
 }
```

I was quick enough to get the `azure_rm.yml` from the Docker container while it was refreshing the host. But I'm not sure if the `exclude_host_filters` is correct or not for tags.

```
conditional_groups:
  azure: true
default_host_filters: []
exclude_host_filters:
- resource_group not in ['my_rg']
- tags not in ['ansible:test']
fail_on_template_errors: false
hostvar_expressions:
  computer_name: name
  private_ip: private_ipv4_addresses[0] if private_ipv4_addresses else None
  provisioning_state: provisioning_state | title
  public_ip: public_ipv4_addresses[0] if public_ipv4_addresses else None
  public_ip_id: public_ip_id if public_ip_id is defined else None
  public_ip_name: public_ip_name if public_ip_name is defined else None
  tags: tags if tags else None
  type: resource_type
keyed_groups:
- key: location
  prefix: ''
  separator: ''
- key: tags.keys() | list if tags else []
  prefix: ''
  separator: ''
- key: security_group
  prefix: ''
  separator: ''
- key: resource_group
  prefix: ''
  separator: ''
- key: os_disk.operating_system_type
  prefix: ''
  separator: ''
- key: dict(tags.keys() | map("regex_replace", "^(.*)$", "\1_") | list | zip(tags.values() | list)) if tags else []
  prefix: ''
  separator: ''
plain_host_names: true
plugin: azure_rm
use_contrib_script_compatible_sanitization: true
```

What's going on here? I'm running awx 7.0.0 btw.
