### ISSUE TITLE
Custom module fails in async mode succeeds in non-async

### ISSUE THREAD

**Issue by pkaramol** [ansible/awx#3456]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

When running a task in `async` mode it fails with `504` __Gateway Timeout__ error. The same task without `async`, finishes normally.

##### ENVIRONMENT
* AWX version: 3.0.1.0
* AWX install method: docker on linux
* Ansible version:  2.7.7
* Operating System: Ubuntu 16.04.6 LTS
* Web Browser: N/A

##### STEPS TO REPRODUCE

I have developed an extremeley simple custom `ansible` module which more or less goes as follows:

(just posting the `main` here)

    try:
        resp = requests.post(_update_endpoint, data=json.dumps(PAYLOAD), headers=HEADERS, verify=False, timeout=50000)
        if resp.status_code != 200:
            module.fail_json(msg=resp.text)
    except Exception as ansibleException:
        module.fail_json(msg=result)

    result = json.loads(resp.text)
    module.log(str(result))

    while (result['status'] != 'succeeded') and (result['status'] != 'failed'):
        pass

    if result['status'] != 'succeeded' :         
        module.fail_json(msg=result)
    else:
        module.exit_json(changed=True, msg=result)

When I try to invode it without `async`, everything is ok.

However the following `async` invocation fails:

```
      - name:  "Updating custom packs"
        my_custom_module:
          var1: "{{ item.key }}"
          var2: "{{ item.value.revision }}"
          api_key: "{{ response2['json']['key'] }}"
          endpoint: https://{{ inventory_hostname }}:8080/api/v2/sync_execution
          ca_cert_path: "/etc/ssl/certs/ca-certificates.crt"
        with_dict: "{{ my_dict }}"
        async: 10000
        poll: 0
        register: async_results


      - name: " Await async"
        async_status:
          jid: "{{ async_result_item.ansible_job_id }}"
        loop: "{{ async_results.results }}"
        loop_control:
          loop_var: "async_result_item"
        register: async_poll_results
        until: async_poll_results.finished
        retries: 300
```
