### ISSUE TITLE
set_stats not working with per_host parameter (needs descriptive error)

### ISSUE THREAD

**Issue by bamason14** [ansible/awx#3556]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - API
 - UI

##### SUMMARY

I am trying to set and reference set_stats in a workflow. It does not appear that the variable is being set and am unable to reference variable in same and next playbook with the per_host parameter set.

Am I miss understanding on how set_stats is suppose to work or is there a bug or installation issue?

##### ENVIRONMENT
* AWX version: 4.0.0.17-1 back to 2.1.2.59-1
* AWX install method: rpm install via awx-build/awx-dev
* Ansible version:  2.7.6
* Operating System: RHEL 7.6
* Web Browser: Chrome

##### STEPS TO REPRODUCE

  - name: yum update
    yum:
      name: '*'
      state: latest
    register: yum_update
    when: (ansible_distribution_major_version >= "6")
    
  - debug:
      msg: '{{ yum_update }}'
    
  - name: set stats
    set_stats:
      data:
        patching_result: '{{ yum_update.changed }}'
      per_host: yes

  - debug:
      msg: "{{ patching_result }}"

Second playbook:

Reference variable via a when statement.
`when: (facter_is_virtual|bool  == true) and (patching_result == false)`

##### ACTUAL RESULTS

Unable to reference variable in first or second playbook. Error is undefined variable. Also get the following warning in playbook that is setting the set_stats.
CUSTOM STATS: ******************************************************************
 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
(<display_callback.module.AWXDefaultCallbackModule object at 0x7f936ae682b0>):
'<' not supported between instances of 'Host' and 'Host'

Output:
TASK [set stats] ***************************************************************
task path: /var/lib/awx/projects/_6__rhel/fake_rhel_patching.yml:38
ok: [mmdadml04.dev.mig.corp] => {"ansible_stats": {"aggregate": true, "data": {"patching_result": false}, "per_host": true}, "changed": false}
ok: [mmpspkidxl04.mmi.mig.corp] => {"ansible_stats": {"aggregate": true, "data": {"patching_result": false}, "per_host": true}, "changed": false}
TASK [debug] *******************************************************************
task path: /var/lib/awx/projects/_6__rhel/fake_rhel_patching.yml:45
fatal: [mmdadml04.dev.mig.corp]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'patching_result' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_6__rhel/fake_rhel_patching.yml': line 45, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - debug:\n    ^ here\n"}
fatal: [mmpspkidxl04.mmi.mig.corp]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'patching_result' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_6__rhel/fake_rhel_patching.yml': line 45, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - debug:\n    ^ here\n"}
PLAY RECAP *********************************************************************
mmdadml04.dev.mig.corp     : ok=8    changed=1    unreachable=0    failed=1   
mmpspkidxl04.mmi.mig.corp  : ok=8    changed=1    unreachable=0    failed=1   
CUSTOM STATS: ******************************************************************
 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
(<display_callback.module.AWXDefaultCallbackModule object at 0x7f936ae682b0>):
'<' not supported between instances of 'Host' and 'Host'

CUSTOM STATS: ******************************************************************
[WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
(<display_callback.module.AWXDefaultCallbackModule object at 0x7ffb8f9602b0>):
'<' not supported between instances of 'Host' and 'Host'

##### ADDITIONAL INFORMATION

Note if only one host is in the inventory file, CUSTOM STATS shows properly but still unable to reference variable.

CUSTOM STATS: ******************************************************************
        mmdadml04.dev.mig.corp: { "patching_result": false}

**Comment by AlanCoding** [comment]
This is documented to not be allowed, see:

https://github.com/ansible/awx/blob/devel/docs/workflow.md

> Note that the default set_stats parameters are the correct ones to work with Tower (i.e. per_host: no).

also

https://docs.ansible.com/ansible-tower/latest/html/userguide/workflows.html

The issue is that these will be re-used in `--extra-vars` for the next workflow job run. There's no per-host keying of data in Ansible extra vars, so the expectations would be unclear in this case.

You probably want something more like fact caching.

ping @chrismeyersfsu

**Comment by wenottingham** [comment]
reopening, we should at least fix it so:
```
[WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin
(<display_callback.module.AWXDefaultCallbackModule object at 0x7f936ae682b0>):
'<' not supported between instances of 'Host' and 'Host'
```
either doesn't happen, or is replaced by a more useful message.

**Comment by sugitk** [comment]
From the customer, I received a case about this issue.

They found the good solution but I think it is very complex, for example like this:
```
    - name: set fact
      set_fact:
        infoblox: "{{ infoblox | default({}) | combine({ item: { 'changed': true, 'ipv4': host[item].ipv4addrs[0].ipv4addr}}) }}"
      with_items: "{{ groups['all'] }}"
      run_once: true
      when: host_record.status is defined and host_record.status == 201
```

The workflow function is very useful of AWX/Tower, so I think it should be more easier to pass variable between playbooks in a workflow.

Is there any good alternative idea?

**Comment by bamason14** [comment]
Am I missing something? From the documentation you provided it appears that set_stats should be able to be set and passed to the next job template in a workflow. Also set_facts is documented as having a per_host option. I'm just really confused on how I am supposed to set a variable in one job template and pass it to the next in a workflow on a per host basis.

"If you use the set_stats module in your playbook, you can produce results that can be consumed downstream by another job, for example, notify users as to the success or failure of an integration run."

"This module allows setting/accumulating stats on the current ansible run, either per host or for all hosts in the run."

**Comment by AlanCoding** [comment]
> I'm just really confused on how I am supposed to set a variable in one job template and pass it to the next in a workflow on a per host basis.

We don't have a concrete use case for per-host stats in workflows.

The point of `set_stats` in workflows is to have a vehicle to pass data via `--extra-vars` to the next job template. If you set a stat for a host, then what how would you reference that in the subsequent playbook? What would the specific jinja2 template syntax be in such a case, given the variable name and the host name, and what would the `--extra-vars` form of the data for `ansible-playbook` invocation look like?

**Comment by bamason14** [comment]
Documentation implies a per_host is supported. Maybe documentation needs to be clarified.

I don't want to get stuck on set_stats but I just need a vehicle that can pass a fact on a per host basis. Maybe this is a feature request. My thought would be if I can set a fact/variable on a host then be able to pass it to the next template in the workflow and reference it via hostvars[inventory_hostname][fact that I create] or something along those lines.

**Comment by AlanCoding** [comment]
related https://github.com/ansible/ansible/pull/54725

**Comment by ryanpetrello** [comment]
@bamason14,

I think the `Failure using method (v2_playbook_on_stats) in callback plugin` message is actually an ansible bug in py3 (which should be addressed in 2.8):

ansible/ansible#49895

**Comment by chrismeyersfsu** [comment]
@bamason14 you can construct a dict where the key is your hostname and the value is the value of what you want to pass along.

**Comment by bamason14** [comment]
How would I pass that to the next job template in the workflow?

Sent from my iPhone

On Apr 3, 2019, at 8:14 AM, Chris Meyers <notifications@github.com<mailto:notifications@github.com>> wrote:


@bamason14<https://github.com/bamason14> you can construct a dict where the key is your hostname and the value is the value of what you want to pass along.

**Comment by walterrowe** [comment]
There is a work-around that I figured out with some help from other online articles. It involves creating dictionaries in real-time.
```yaml
    - name: Create and Add items to dictionary
      set_stats: 
        data:
          my_dict: "{{ my_dict | default({}) | combine ({ item.key : item.value }) }}"
      with_items:
        - { "key": "{{ inventory_hostname_short }}" , "value": {
              "var_a" : "{{ var_a_val }}",
              "var_b" : "{{ var_b_val }}",
              "var_c" : "{{ var_c_val }}"
            }
          }
```

This results in a dictionary that is passed back to ansible tower as an artifact. Downstream templates in the workflow will receive it in extra\_vars.

```yaml
my_dict:
  host1:
    var_a: host1_var_a_val
    var_b: host1_var_b_val
    var_c: host1_var_c_val
  host2:
    var_a: host2_var_a_val
    var_b: host2_var_b_val
    var_c: host2_var_c_val
  hostN:
    var_a: host3_var_a_val
    var_b: host3_var_b_val
    var_c: host3_var_c_val
```

Downstream templates can access this data as follows:

```yaml
my_dict[inventory_hostname_short].var_a
my_dict[inventory_hostname_short].var_b
my_dict[inventory_hostname_short].var_c
```
