### ISSUE TITLE
Allow for Explanation of Required Inputs on Custom Credentials

### ISSUE THREAD

**Issue by mrmibrown** [ansible/awx#3562]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Allow for explanation/description of required inputs on Custom Credentials.

**Comment by wenottingham** [comment]
@mrmibrown is this for custom creds, or something else?

**Comment by mrmibrown** [comment]
My apologies @wenottingham.  That is correct.  The RFE has been updated to reflect this change.

**Comment by ryanpetrello** [comment]
Is specifying `help_text` on the credential type definition for the appropriate fields enough to accomplish this?

**Comment by kfattig** [comment]
We have custom credential types injecting extra & env vars, and we need some way to display to users the name of the injected values.

We've tried using labels for this purpose, but they are capitalized by the UI.

This definition:
```yaml
fields:
  - type: string
    id: demo_user
    label: username
  - secret: true
    type: string
    id: demo_pass
    label: password
required:
  - demo_pass
  - demo_user

```

```yaml
extra_vars:
  password: '{{ demo_pass }}'
  username: '{{ demo_user }}'
```

Leads to this in the UI:
![image](https://user-images.githubusercontent.com/23063964/55825833-61136500-5acc-11e9-9844-65f9e575e48a.png)

Allowing for a description in the input configuration, and surfacing that as help_text would solve our problem as long as case is preserved.  We could also get by using just labels as shown above if their case was preserved.

**Comment by ryanpetrello** [comment]
@kfattig,

Is this what you're looking for?

```yaml
fields:
  - id: demo_user
    type: string
    label: username
    help_text: This field will set -e demo_user
  - id: demo_pass
    type: string
    label: password
    secret: true
    help_text: This field will set -e demo_pass
required:
  - demo_pass
  - demo_user
```

![image](https://user-images.githubusercontent.com/214912/55826906-fca9d300-5ad6-11e9-801b-198299a79987.png)
