### ISSUE TITLE
Web performance regression since 4.0.0

### ISSUE THREAD

**Issue by kakawait** [ansible/awx#3719]
##### ISSUE TYPE

- bug report

##### SUMMARY

On same installation with empty database (so empty project) when using 4.0.0 I got 10sec for 

```
[pid: 159|app: 0|req: 28/90] 172.28.0.17 () {62 vars in 2732 bytes} [Tue Apr 16 07:33:24 2019] GET / => generated 11339 bytes in 10838 msecs (HTTP/1.1 200) 7 headers in 321 bytes (1 switches on core 0) web_1        |
[pid: 158|app: 0|req: 13/91] 172.28.0.17 () {64 vars in 2707 bytes} [Tue Apr 16 07:33:36 2019] GET /api/ => generated 6859 bytes in 10263 msecs (HTTP/1.1 200) 11 headers in 481 bytes (1 switches on core 0)
```

<img width="1017" alt="Screen Shot 2019-04-16 at 10 08 27" src="https://user-images.githubusercontent.com/275609/56216323-84f12080-6061-11e9-863d-61281cc5a8da.png">

Keep in mind that those calls tooks always **10sec or few ms (like in `3.0.1`)**, but never 5sec or more than 10sec. That constant timing execution 10sec is really strange, like a timeout or something like that.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  bundle inside ansible:awx_task and ansible:awx_web
* Operating System: Centos
* Web Browser: Firefox 66 (but same issue on Chrome)

##### STEPS TO REPRODUCE

```
version: '2'
services:
  web:
    image: ansible/awx_web:4.0.0
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    networks:
      - default
      - nginx_default
    environment:
      # nginx variable
      - VIRTUAL_HOST=awx.foo.com
      - VIRTUAL_PORT=8052
    volumes:
      - ./conf/SECRET_KEY:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py

  task:
    image: ansible/awx_task:4.0.0
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./conf/SECRET_KEY:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    restart: unless-stopped
    networks:
      - default
    environment:
      - RABBITMQ_DEFAULT_VHOST=awx
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=awxpass
      - RABBITMQ_ERLANG_COOKIE=cookiemonster

  memcached:
    image: memcached:alpine
    restart: unless-stopped
    networks:
      - default

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=awx
      - POSTGRES_PASSWORD=awxpass
      - POSTGRES_DB=awx
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  default:
  nginx_default:
    external: true
```

with `environment.sh`

```
DATABASE_USER=awx
DATABASE_NAME=awx
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_PASSWORD=awxpass
MEMCACHED_HOST=memcached
RABBITMQ_HOST=rabbitmq
AWX_ADMIN_USER=admin
AWX_ADMIN_PASSWORD=password
```

and `credentials.py`

```
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "awxpass",
        'HOST': "postgres",
        'PORT': "5432",
    }
}
BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
    "guest",
    "awxpass",
    "rabbitmq",
    "5672",
    "awx")

CHANNEL_LAYERS = {
    'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                'ROUTING': 'awx.main.routing.channel_routing',
                'CONFIG': {'url': BROKER_URL}}
}
```
##### EXPECTED RESULTS

`/`, `/api`, `/api/v2`, etc... should not stuck on 10sec executions like on `3.0.1`

##### ACTUAL RESULTS

`/`, `/api`, `/api/v2`, etc... takes to much time to be computed.

Keep in mind that those calls tooks always **10sec or few ms (like in `3.0.1`)**, but never 5sec or more than 10sec. That constant timing execution 10sec is really strange, like a timeout or something like that.

##### ADDITIONAL INFORMATION

I just edited few line of `docker-compose.yml` to be connected to our reverse proxy. But I tested with and without our reverse proxy to be sure that is not responsible of that regression.

I don't see any error on logs, except `access log` of the request that take 10sec

**Comment by lijok** [comment]
I've been looking into this for the last two days
Can you do: `sudo docker exec -it awx_web bash -c "echo \"127.0.0.1 None\" >> /etc/hosts"`
go into the web ui and see if it removes the delay

**Comment by kakawait** [comment]
@lijok Nice that work! Way better. You saved my day 😽 

I just update my `docker-compose.yml` (to persist the tricks)

```
version: '2'
services:
  web:
    image: ansible/awx_web:4.0.0
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    networks:
      - default
      - nginx_default
    command:
      - /bin/bash
      - -c
      - |
        echo "127.0.0.1 None" >> /etc/hosts
        /usr/bin/launch_awx.sh
    environment:
      # nginx variable
      - VIRTUAL_HOST=awx.foo.com
      - VIRTUAL_PORT=8052
    volumes:
      - ./conf/SECRET_KEY:/etc/tower/SECRET_KEY:ro
      - ./conf/environment.sh:/etc/tower/conf.d/environment.sh
      - ./conf/credentials.py:/etc/tower/conf.d/credentials.py
...
```

--- 

But this is still an `AWX` issue? I mean should I keep the issue open or close it?
