### ISSUE TITLE
task not executing 

### ISSUE THREAD

**Issue by sinu** [ansible/awx#3771]
##### ISSUE TYPE
 - help wanted

##### SUMMARY
team i am trying to launch a template with list of variable_value but  task is getting executed only in one target host 

sample request 

`curl -H "Content-Type: application/json" -X POST -s -u admin:admin123 -d '{ "extra_vars": { "domain": "dom-cn-1", "targets": "dev-cn-c1", "targets": "dev-cn-c2", "fwcmd": "fw sam -v  -J src  192.168.10.10" }}' -k https://172.16.102.4/api/v2/job_templates/10/launch/`

this is working as expected when i run via cli playbook.

##vars file snip

domain: dom-cn-1
targets: 
    - dev-cn-c1
    - dev-cn-c2

###Playbook file
```
    - name: "Create output file"
      check_point_mgmt:
        command: run-script
        parameters:
          script-name: "Create output file"
          script: "fw sam -v  -J src  192.168.10.10"
          targets: "{{ targets }}"
        session-data: "{{login_response}}"
```

 

##### ENVIRONMENT
* AWX version: 4.0
* AWX install method: docker on linux
* Ansible version: 2.8
* Operating System:
* Web Browser:

##### EXPECTED RESULTS

task should run on both target hosts, as per the about request it is getting executed only on dev-cn-c2 
targets: 
    - dev-cn-c1
    - dev-cn-c2
