### ISSUE TITLE
AWX parser of JT : playbook syntax fail

### ISSUE THREAD

**Issue by louisfrancoisSO** [ansible/awx#3881]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Hello,
My playbook is working fine on Ansible but fails on AWX.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.10
* Operating System: Ubuntu 18.04
* Web Browser: FF

##### STEPS TO REPRODUCE
My playbook:
```
---
- hosts: switch1
  tasks:
    - name: Create VLAN 300
      arubaoss_vlan:
        vlan_id: 300
        name: "vlan300"
        config: "create"
        command: config_vlan
        use_ssl: True
        api_version: v6.0
```
This is from the module aruba_switch_module

And my inventory
```
all:
  hosts:
    switch1:
      ansible_host: 172.17.104.13
      ansible_user: ...
      ansible_password: ...
      ansible_connection: local  # Do not change
      ansible_network_os: arubaoss  # Do not change
```

##### EXPECTED RESULTS
It should work as it is working on Ansible when doing
`ansible-playbook vlan.yml -i switch.yml `

##### ACTUAL RESULTS
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/_7__aruba_test/vlan.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Create VLAN 300
      ^ here
```
##### ADDITIONAL INFORMATION
The helloworld demo is working fine.
My guess is that it has troubles to parse the yml and the error is misleading.
