### ISSUE TITLE
Failed to update project: 4. PUT status: 400

### ISSUE THREAD

**Issue by ghost** [ansible/awx#3939]
EDIT: I have uncomment this line like it's said and relaunch install and I have the exact same issue
`#project_data_dir=/var/lib/awx/projects`
##### ISSUE TYPE
Cannot save project
##### SUMMARY

I have done what it is explained on issue 857 but it doesn't work

##### ENVIRONMENT
* Ubuntu bionic
* AWX install method:  docker on linux
* Ansible version: ansible 2.8.0
* Operating System:  Ubuntu 18.04.2 LTS
* Web Browser: Chrome

##### STEPS TO REPRODUCE

I have added line like said in issue reported : 857 but after reinstall web GUI doesn't work. 
I have added lines in local_docker/main.yml

```
- import_tasks: set_image.yml
- import_tasks: compose.yml

- name: Activate AWX Web Container
  docker_container:
    name: awx_web
    state: started
    restart_policy: unless-stopped
    image: "{{ awx_web_docker_actual_image }}"
    volumes: "{{ project_data_dir }}:/var/lib/awx/projects:rw"

- name: Activate AWX Task Container
  docker_container:
    name: awx_task
    state: started
    restart_policy: unless-stopped
    image: "{{ awx_task_docker_actual_image }}"
    volumes: "{{ project_data_dir }}:/var/lib/awx/projects:rw"
```

When I comment line and reinstall it's work fine.

I have added in inventory But I have still the issue.
`project_data_dir=/opt/awx_projects `

I can see folder created test folder in /opt/awx_projects  
```
ls /opt/awx_projects/
_6__demo_project145956  _6__demo_project145956.lock  test  test2
```
But I cannot save the project after selected one When I click on save I have the issue : Failed to update project: 6. PUT status: 400

I have change rigth to 777 for awx_project folder

```
/opt$ ls -lrt
total 12
drwxr-xr-x 3 root root 4096 May 16 16:51 snow
drwx--x--x 4 root root 4096 May 17 16:38 containerd
drwxrwxrwx 6 root root 4096 May 21 17:04 awx_projects
```

##### EXPECTED RESULTS

Create manual project

##### ACTUAL RESULTS

Mount volume and web GUI page not found
