### ISSUE TITLE
local_action Unable to connect to port 22 on 127.0.0.1 or ::1

### ISSUE THREAD

**Issue by adpavlov** [ansible/awx#3955]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

It seems that local_action ignores ansible_connection=local varible and tries to ssh localhost.
At the same time ad-hoc command to localhost works fine.

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker on linux
* Ansible version:  2.7.9
* Operating System: RHEL 7.4
* Web Browser: any

##### STEPS TO REPRODUCE

```
  - name: Prepare AIX servers
    hosts: aix
    gather_facts: no
    order: sorted
    remote_user: root
    ignore_unreachable: yes
    tasks:

    - name: Upload rpm fileset to AIX hosts
      local_action: shell sshpass -p {{aix_root_pass}} scp -r -o 'StrictHostKeyChecking no' "{{ dep_packages_aix }}"/yum_bundle.* root@{{ hostvars[inventory_hostname].ansible_host }}:/tmp


```

##### EXPECTED RESULTS

AWX to use local connection instead of ssh as it's done for ad-hoc command:

```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python2.7 && sleep 0'
localhost | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": "pong"
        }
    }, 
    "ping": "pong"
}

```
##### ACTUAL RESULTS

```
<localhost> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: root on PORT 22 TO localhost

TASK [aix : Upload rpm fileset to AIX hosts] *****************************************************************************************************************
fatal: [aix1]: UNREACHABLE! => {
    "changed": false, 
    "msg": "[Errno None] Unable to connect to port 22 on 127.0.0.1 or ::1", 
    "unreachable": true
}


```
