### ISSUE TITLE
Ansible-playbook keeps pushing LogConfig even though I've deleted it on my tasks/main

### ISSUE THREAD

**Issue by ry1015** [ansible/awx#4035]
Hi All,

For some reason, ever since I've added syslog to my docker_container configuration, ansible refuses to delete this configuration even if it's been removed from my main.yml file.

Log:
```
{"ansible_facts": {"docker_container": {"AppArmorProfile": "docker-default", "Args": ["-c", "/opt/mimidae/mimidae.json"], "Config": {"ArgsEscaped": true, "AttachStderr": false, "AttachStdin": false, "AttachStdout": false, "Cmd": ["-c", "/opt/mimidae/mimidae.json"], "Domainname": "", "Entrypoint": ["mimidae"], "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"], "Hostname": "baaa69810a13", "Image": "registry.corp.capellaspace.com/groundsoftware/mimidae:test-mimidae-elk", "Labels": {}, "OnBuild": null, "OpenStdin": false, "StdinOnce": false, "Tty": false, "User": "", "Volumes": {"/opt/dicts": {}, "/opt/mimidae": {}, "/var/logs/mimidae": {}}, "WorkingDir": "/src"}, "Created": "2019-06-10T19:46:38.975518437Z", "Driver": "aufs", "ExecIDs": null, "GraphDriver": {"Data": null, "Name": "aufs"}, "HostConfig": {"AutoRemove": false, "Binds": ["/opt/mimidae:/opt/mimidae:rw", "/opt/dicts:/opt/dicts:rw", "/var/logs/mimidae:/var/logs/mimidae:rw"], "BlkioDeviceReadBps": null, "BlkioDeviceReadIOps": null, "BlkioDeviceWriteBps": null, "BlkioDeviceWriteIOps": null, "BlkioWeight": 0, "BlkioWeightDevice": null, "CapAdd": null, "CapDrop": null, "Cgroup": "", "CgroupParent": "", "ConsoleSize": [0, 0], "ContainerIDFile": "", "CpuCount": 0, "CpuPercent": 0, "CpuPeriod": 0, "CpuQuota": 0, "CpuRealtimePeriod": 0, "CpuRealtimeRuntime": 0, "CpuShares": 0, "CpusetCpus": "", "CpusetMems": "", "DeviceCgroupRules": null, "Devices": null, "DiskQuota": 0, "Dns": [], "DnsOptions": [], "DnsSearch": [], "ExtraHosts": null, "GroupAdd": null, "IOMaximumBandwidth": 0, "IOMaximumIOps": 0, "IpcMode": "shareable", "Isolation": "", "KernelMemory": 0, "Links": null, "LogConfig": {"Config": {"syslog-address": "udp://:5141", "syslog-facility": "daemon", "tag": "mimidae-syslog-test"}, "Type": "syslog"}, "MaskedPaths": ["/proc/asound", "/proc/acpi", "/proc/kcore", "/proc/keys", "/proc/latency_stats", "/proc/timer_list", "/proc/timer_stats", "/proc/sched_debug", "/proc/scsi", "/sys/firmware"], "Memory": 0, "MemoryReservation": 0, "MemorySwap": 0, "MemorySwappiness": null, "NanoCpus": 0, "NetworkMode": "default", "OomKillDisable": false, "OomScoreAdj": 0, "PidMode": "", "PidsLimit": 0, "PortBindings": null, "Privileged": false, "PublishAllPorts": false, "ReadonlyPaths": ["/proc/bus", "/proc/fs", "/proc/irq", "/proc/sys", "/proc/sysrq-trigger"], "ReadonlyRootfs": false, "RestartPolicy": {"MaximumRetryCount": 0, "Name": "unless-stopped"}, "Runtime": "runc", "SecurityOpt": null, "ShmSize": 67108864, "UTSMode": "", "Ulimits": null, "UsernsMode": "", "VolumeDriver": "", "VolumesFrom": null}, "HostnamePath": "/var/lib/docker/containers/baaa69810a130accbffe26d739a135c1095d3266e1366f284d888dabf17a3029/hostname", "HostsPath": "/var/lib/docker/containers/baaa69810a130accbffe26d739a135c1095d3266e1366f284d888dabf17a3029/hosts", "Id": "baaa69810a130accbffe26d739a135c1095d3266e1366f284d888dabf17a3029", "Image": "sha256:8a5744d66bb4b5c21be814ee9700909ab3e555c146b3362f9e1d2db88133bbfe", "LogPath": "", "MountLabel": "", "Mounts": [{"Destination": "/opt/dicts", "Mode": "rw", "Propagation": "rprivate", "RW": true, "Source": "/opt/dicts", "Type": "bind"}, {"Destination": "/opt/mimidae", "Mode": "rw", "Propagation": "rprivate", "RW": true, "Source": "/opt/mimidae", "Type": "bind"}, {"Destination": "/var/logs/mimidae", "Mode": "rw", "Propagation": "rprivate", "RW": true, "Source": "/var/logs/mimidae", "Type": "bind"}], "Name": "/mimidae", "NetworkSettings": {"Bridge": "", "EndpointID": "de2fde3879682f106f26eb192fcfffcc413d5aadc536fb5fd54f836274ab594e", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "HairpinMode": false, "IPAddress": "172.17.0.17", "IPPrefixLen": 16, "IPv6Gateway": "", "LinkLocalIPv6Address": "", "LinkLocalIPv6PrefixLen": 0, "MacAddress": "02:42:ac:11:00:11", "Networks": {"bridge": {"Aliases": null, "DriverOpts": null, "EndpointID": "de2fde3879682f106f26eb192fcfffcc413d5aadc536fb5fd54f836274ab594e", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "172.17.0.17", "IPPrefixLen": 16, "IPv6Gateway": "", "Links": null, "MacAddress": "02:42:ac:11:00:11", "NetworkID": "02a02278c6cf64dfbb2717c6832db9d018bee2bfbb0344642aebeff339a6012a"}, "elk-network": {"Aliases": ["mimidae-maybe", "baaa69810a13"], "DriverOpts": null, "EndpointID": "e9c0aa3255cd6b774be46c85d4faad9472afc62c489080f158a9f8f2ecb12d11", "Gateway": "172.20.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "172.20.0.5", "IPPrefixLen": 16, "IPv6Gateway": "", "Links": null, "MacAddress": "02:42:ac:14:00:05", "NetworkID": "8ba53ec347565e7d116951e054fdef84ec2f4950fca16fba1f4a9c2c298a393b"}}, "Ports": {}, "SandboxID": "ecb96c499a10e99a3adf75cb8688375262ea22338ead7b3f8fca04188d42433b", "SandboxKey": "/var/run/docker/netns/ecb96c499a10", "SecondaryIPAddresses": null, "SecondaryIPv6Addresses": null}, "Path": "mimidae", "Platform": "linux", "ProcessLabel": "", "ResolvConfPath": "/var/lib/docker/containers/baaa69810a130accbffe26d739a135c1095d3266e1366f284d888dabf17a3029/resolv.conf", "RestartCount": 0, "State": {"Dead": false, "Error": "", "ExitCode": 0, "FinishedAt": "2019-06-10T20:16:31.610213129Z", "OOMKilled": false, "Paused": false, "Pid": 5657, "Restarting": false, "Running": true, "StartedAt": "2019-06-10T20:16:33.18957592Z", "Status": "running"}}}, "changed": true}
```

main.yml
```
- name: start app
  become: true
  docker_container:
    name: app
    image: "{{ app_image }}:{{ app_image_tag }}"
    state: started
    restart: yes
    volumes:
      - /opt/app:/opt/app
      - /opt/dicts:/opt/dicts
      - /var/logs/app:/var/logs/app
    restart_policy: unless-stopped
    networks:
      - name: elk-network
        aliases:
          - app
```

previous main.yml
```
- name: start app
  become: true
  docker_container:
    name: app
    image: "{{ app_image }}:{{ app_image_tag }}"
    log_driver: syslog
    log_options:
      syslog-address: tcp://:514
      syslog-facility: daemon
    state: started
    restart: yes
    volumes:
      - /opt/mimidae:/opt/app
      - /opt/dicts:/opt/dicts
      - /var/logs/app:/var/logs/app
    restart_policy: unless-stopped
    networks:
      - name: elk-network
        aliases:
          - app
```

Why is Ansible forcing my previous config file when I've deleted it from my code? Also, I noticed that I can change the port and other config changes but Ansible will never remove the log_driver and log_options.

Please help

Thanks,
Ryan
