### ISSUE TITLE
Error When Running Playbook in AWX vs localhost for vsphere_guest Creation

### ISSUE THREAD

**Issue by aguynamedjoetoo** [ansible/awx#410]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
When running a playbook locally I get a different result from running a playbook from AWX. When running locally, the vsphere_guest task returns as 'changed' with a proper object (`vm`) to iterate on. When running from AWX, I get an 'ok' and the following returned on the task:

```
{
    "_ansible_parsed": true,
    "changed": false,
    "_ansible_no_log": false,
    "failed": false,
    "_ansible_item_result": true,
    "item": {
        "vm_name": "ansible-test-deleteme",
        "esxi_host": "REDACTED",
        "num_cpus": 2,
        "memory": 2048,
        "datastore": "REDACTED",
        "storage_gb": 20
    },
    "invocation": {
        "module_args": ""
    },
    "msg": "vm ansible-test-deleteme not present"
}
```

Notably the `msg` field reporting back that the vm isn't present, resulting in the `vm` object being invalid for the rest of my play.

##### ENVIRONMENT
* AWX version: 1.0.1
* AWX install method: Docker on Linux
* Ansible version:  2.3.0
* Operating System: Ubuntu 16.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Run the task included below.

On AWX, have a prompt for extra variables, input and object such as:

```
vms:
  - vm_name: "ansible-test-deleteme"
    storage_gb: 20
    memory: 2048
    num_cpus: 2
    datastore: "REDACTED"
    esxi_host: "REDACTED"
```

and a survey for the following:

```
ad_password
ad_username
```

##### EXPECTED RESULTS

The VM object should register as "changed" and register an object 'vm' to consume

##### ACTUAL RESULTS

The above is returned from the task, and then when trying to grab `vm.ansible_facts.hw_eth0.ipaddresses` the entire play fails since `vm` does not exist:

```
{
    "msg": "The conditional check 'vm.ansible_facts.hw_eth0.ipaddresses' failed. The error was: error while evaluating conditional (vm.ansible_facts.hw_eth0.ipaddresses): 'dict object' has no attribute 'ansible_facts'",
    "failed": true
}
```

##### ADDITIONAL INFORMATION

vsphere_guest task example:

```
- name: Create the VM instance
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username: REDACTED\{{ ad_username }}
    password: "{{ ad_password }}"
    guest: "{{ item.vm_name }}"
    state: powered_on
    vm_disk:
      disk1:
        size_gb: "{{ item.storage_gb }}"
        type: thin
        datastore: "{{ item.datastore }}"
        folder: REDACTED
    vm_nic:
      nic1:
        type: e1000
        network: "PG-VM"
        network_type: dvs
    vm_hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.num_cpus }}"
      osid: ubuntu64Guest
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "REDACTED"
    vm_hw_version: vmx-08
    esxi:
      datacenter: REDACTED
      hostname: "{{ item.esxi_host }}"
    validate_certs: no
  with_items:
    - "{{ vms }}"
```

Example extra variables that was generated:

```
vms:
  - vm_name: "ansible-test-deleteme"
    storage_gb: 20
    memory: 2048
    num_cpus: 2
    datastore: "REDACTED"
    esxi_host: "REDACTED"

ad_username: $encrypted$
ad_password: $encrypted$
```
