### ISSUE TITLE
API parameter vault_credential being ignored for job_template

### ISSUE THREAD

**Issue by devops-42** [ansible/awx#4148]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Tried to create a job template via API using the template mentioned below. The parameter `vault_credential` will not applied after creation. When reviewing the job template in the GUI the according field is empty, but I'm able to add the credential manually in the GUI.
In the official API documentation for Ansible tower the parameter `vault_credential` is marked deprecated. How to use job templates for which a vault credential is necessary?

##### ENVIRONMENT
* AWX version: 5.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.0
* Operating System: CentOS 7.5
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Create a project and an inventory
- Create a vault credential named "example_vault"
- Run Ansible task for creating job template:
```
- name: Create job template 
  uri:
    url: "{{ tower_uri }}/api/v2/job_templates/"
    user: "{{ api_user }}"
    password: "{{ api_password }}"
    force_basic_auth: yes
    method: POST
    status_code: 201
    body_format: json
    body:
      name: "example_job"
      job_type: "run"
      inventory: "{{ inventory_id }}"
      project: "{{ project_id }}"
      playbook: "site.yml"
      vault_credential: "example_vault"
```
- Ansible returns 201, the job has been created
- Log into AWX GUI, navigate to "Templates" and select created "example_job"

##### EXPECTED RESULTS

The given vault credential should be applied to the job template

##### ACTUAL RESULTS

The credential field is empty, when running the job an error occurs:

`ERROR! Attempting to decrypt but no vault secrets found`

##### ADDITIONAL INFORMATION

none
