### ISSUE TITLE
Allow cloning from non-head git refs (like PR references)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#4258]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
With git projects currently, you can checkout a branch, tag, commit hash, or generally any ref that is listed under the git heads.

If you give a ref that is not a head, additional syntax is needed to clone it via the git module. For example:

```yaml
- hosts: all
  gather_facts: false
  connection: local
  vars:
    repo_dir: "/tmp/foo_dir"
  tasks:
    - name: update project using git
      git:
        dest: "{{ repo_dir }}"
        repo: "https://github.com/ansible/test-playbooks.git"
        version: "pull/62/head"
        refspec: +refs/pull/62/head:refs/remotes/origin/pull/62/head  # works
```

Another valid way:

```yaml
- hosts: all
  gather_facts: false
  connection: local
  vars:
    repo_dir: "/tmp/foo_dir"
  tasks:
    - name: update project using git
      git:
        dest: "{{ repo_dir }}"
        repo: "https://github.com/ansible/test-playbooks.git"
        refspec: refs/pull/62/head
```

This means that the contract between AWX and Ansible changes, and it's probable that the contract with the user changes.

Note that the dual parameters `refspec` and `version` are documented to exist so that you can clone a commit hash of a non-head ref. For example, say I have a PR with 5 commits, I want to clone the 3rd commit of the PR. This has to involve an additional `git fetch` command, which is what `refspec` allows you to do, and this is a use case we need to support (in part because the git module supports it).

It's still possible that we add this as an enhancement to the git module. Proposal for that:

 - when resolving the version, add additional `elif` block if it's not in branches or tags, only if it does not fit a valid SHA-1 hash
 - in this case, automatically add a `refspec` parameter
 - add `refs/` to the start of the refspec if it does not already have it

This issue is to replace https://github.com/ansible/ansible/issues/57497, because the module is still in compliance with its own documentation, so I'm closing that. The solution could be in either repo, but it the use case is AWX-centric.

Part of features https://github.com/ansible/awx/issues/282 and https://github.com/ansible/awx/issues/2862
