### ISSUE TITLE
ec2_transit_gateway fails in AWX but not in ansible

### ISSUE THREAD

**Issue by dvntstph** [ansible/awx#4642]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to manage an AWS Transit Gateway from AWX, the job fails with "msg": "transit gateway module requires boto3 >= 1.9.52"
However if I run the same playbook from the same AWX host on the command line the job is successful.
Strangely the first task in the playbook is succesfull. It uses the 'sts_assume_role' Ansible module to get an STS access token which I register and pass into the ec2_transit_gateway task. 
Both Ansible modules "sts_assume_role" and "ec2_transit_gateway" use boto3.

##### ENVIRONMENT
* AWX version: 6.1.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.2
* Operating System: Ubuntu 18.04.3
* Web Browser: Chrome 76.0.3809.132

##### STEPS TO REPRODUCE

Ran the same playbook interactively on the command line

##### EXPECTED RESULTS

Second task in the playbook should've failed.

##### ACTUAL RESULTS

Complete playbook run was successful

##### ADDITIONAL INFORMATION

Sanitised code:

```
---
- name: Workflow to ultimately manage Transit Gateway in the XXX AWS Account
  hosts: localhost
  
  tasks:

  - name: Create variable for desired region
    set_fact: 
      defined_region: us-east-1

  - name: Assume role and obtain STS token
    sts_assume_role:
     region: "{{ defined_region }}"
     role_arn: arn:aws:iam::123456789123:role/My-AWS-Automation-Role-Name
     role_session_name: "AWS-Automation-session"
    register: assumed_role

  - name: Manage Transit Gateway for XXX AWS Account
    ec2_transit_gateway:
     aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
     aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
     security_token: "{{ assumed_role.sts_creds.session_token }}"
     description: "My Awesome TGW"
     state: present
     #asn: 
     auto_associate: no
     auto_attach: yes 
     auto_propagate: no
     dns_support: yes
     vpn_ecmp_support: yes
     region: "{{ defined_region }}"
     tags:
      Name: my-awesome-tgw
      module: ec2_transit_gateway
      my-tag: heck-yeah



```
