### ISSUE TITLE
Add prompting for extra_vars to Workflow JTs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#478]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Workflow job templates do not allow arbitrary extra_vars entry on launch.

##### STEPS TO REPRODUCE
Edit a workflow job template.

##### EXPECTED RESULTS
Ability to prompt for variables on launch.

##### ACTUAL RESULTS
It has survey option (which go into extra_vars), but no ability to prompt for variables on launch like you can with a JT, which allows for arbitrary extra_vars entry on launch.

##### ADDITIONAL INFORMATION

Field `ask_variables_on_launch` on JT:

https://github.com/ansible/awx/blob/764356bf477f339dfa933dce7eb825940c3fc2fd/awx/main/models/jobs.py#L248-L251

**Comment by MichalTaratuta** [comment]
Any idea on the ETA for this feature, without it Workflow is useless.

**Comment by wenottingham** [comment]
@MichalTaratuta this is easily worked around by adding a survey for the vars in question.

**Comment by MichalTaratuta** [comment]
@wenottingham I'm using iterations of tasks in the plays, thus I don't know if surveys will work with with that i.e.:
```
auth_key: qwqgere
address: 10.0.0.1
params:
  - esx_hostname: HOST01ESX01
    iqn: iqn.1998-01.com.vmware:host01esx01-2aasad839
    volume_name: Hello-World
    capacity: 1G
    pool_name: RAID1-POOL-B
    server_name: LAB01ESX01
    volume: "Hello-World"
    lun: 0
  - esx_hostname: HOST09ESX13
    iqn: iqn.1998-01.com.vmware:host09ESX13-538agg3e
    volume_name: force
    capacity: 1G
    pool_name: RAID1-POOL-B
```

At least the API is working fine.
