### ISSUE TITLE
After SAML Authentication, it redirects to /login

### ISSUE THREAD

**Issue by abdul-jabbar01** [ansible/awx#4814]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I've integrated the SML Authentication with AWX. It redirects to my IDP (I get 200 OK). Authenticate it there. And then redirects back to the http://localhost:8052/sso/complete/saml/ (here I get 302 Found) But after this, it redirects to the http://localhost:8052/sso/error/ (And here I get 301 Moved Permanently) and then to http://localhost:8052/#/login . I'm unable to login into the AWX by SAML. Please resolve the issue. 

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker for mac
* Operating System: MacOS
* Web Browser: Chrome, Brave, Safari

##### STEPS TO REPRODUCE

Install AWX with following docker-compose file: 
```yaml
version: '3'
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: "memcached:alpine"

  awx_web:
    #image: "geerlingguy/awx_web:latest"
    image: "ansible/awx_web:latest"
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8052:8052"
    hostname: awxweb
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    volumes:
      - ./SECRET_KEY:/etc/tower/SECRET_KEY

  awx_task:
    #image: "geerlingguy/awx_task:latest"
    image: "ansible/awx_task:latest"
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    environment:
      SECRET_KEY: aabbcc
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: awx
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    volumes:
      - ./SECRET_KEY:/etc/tower/SECRET_KEY
```
Then Navigate to Settings => Authentication > SAML

And I had following configurations for IDP:
```json
{
 "cas": {
  "x509cert": "MIIDBzCCAe+gAwIBAgIJAP+Iolzz6C3mM....................................................",
  "attr_last_name": "last_name",
  "attr_username": "User.Username",
  "entity_id": "http://cas.real-dev.de/saml/metadata",
  "attr_email": "User.Email",
  "attr_user_permanent_id": "User.Username",
  "attr_first_name": "first_name",
  "url": "http://cas.real-dev.de/saml/sso"
 }
}
```

##### EXPECTED RESULTS

It should login into the AWX after getting response from the IDP.

##### ACTUAL RESULTS

It redirects to http://localhost:8052/#/login 

##### ADDITIONAL INFORMATION

This is what I'm getting from SAML Tracer. 

**Sending Request to IDP**

<img width="753" alt="Screenshot 2019-09-24 at 17 32 59" src="https://user-images.githubusercontent.com/22825645/65526533-87e61c00-def1-11e9-89e7-5eae4f1004c1.png">
<img width="751" alt="Screenshot 2019-09-24 at 17 33 09" src="https://user-images.githubusercontent.com/22825645/65526538-8ae10c80-def1-11e9-98b4-3787c4dcc940.png">

**Response of IDP**

<img width="751" alt="Screenshot 2019-09-24 at 17 35 24" src="https://user-images.githubusercontent.com/22825645/65526666-c5e34000-def1-11e9-9688-54db282c28f2.png">
<img width="752" alt="Screenshot 2019-09-24 at 17 35 35" src="https://user-images.githubusercontent.com/22825645/65526673-c8459a00-def1-11e9-9c3c-972cb9d90db8.png">
<img width="767" alt="Screenshot 2019-09-24 at 17 35 43" src="https://user-images.githubusercontent.com/22825645/65526680-cb408a80-def1-11e9-9cc4-0879c7bb9ebb.png">

And here I'm getting **301 Moved Permanently**
<img width="757" alt="Screenshot 2019-09-24 at 17 36 47" src="https://user-images.githubusercontent.com/22825645/65526798-f32fee00-def1-11e9-984b-c9e3b19c3ab4.png">
