### ISSUE TITLE
Module tower_credential parameter organization should not be required

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5045]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
the module `tower_organization` has a parameter `organization` which is required.

It should not be required, and the user can alternatively specify either user or team.

The module should either enforce that the user supplies 1 of the 3, or correctly surface API error messages to this effect.

##### ENVIRONMENT
* AWX version: 7.0.0
* AWX install method: docker for mac
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

See docs on `tower_organization` Ansible module.

##### EXPECTED RESULTS

Expect usage to work like

```yaml
- name: Add tower credential
  tower_credential:
    name: Team Name
    description: Team Description
    team: test-team
    kind: ssh
    state: present
    tower_config_file: "~/tower_cli.cfg"
```

##### ACTUAL RESULTS

The organization field is required and no user/team options are available

##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible/latest/modules/tower_credential_module.html

https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_credential.py
