### ISSUE TITLE
Module tower_project has no means of waiting for update to finish

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5166]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
There is no way to use `tower_project` in a playbook and have it poll until the project finishes updating.

So to create a job template this is necessary:

https://github.com/ansible/test-playbooks/blob/d4b39fe0c010cf8dc9c4e6e60113664cd4bf1bbd/tower_modules/tower_job_template/tasks/main.yml#L17

```yaml
- name: Wait for the project to be status=successful
  uri:
    url: "{{ tower_host }}/api/v2/projects/{{ result.id }}/"
    method: GET
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: false
    force_basic_auth: true
    return_content: true
  register: result
  until: result.json.summary_fields.last_update is defined and result.json.summary_fields.last_update.status == "successful"
  retries: 60
  delay: 1
```

A simple parameter like `wait: True` should be sufficient.

**Comment by wenottingham** [comment]
https://github.com/ansible/ansible/pull/51302 ?

**Comment by AlanCoding** [comment]
I don't know if the associated test is the only way to use it, but that gave 2 tasks for doing this

```yaml
- name: Create project TestProject
  tower_project:
    name: TestProject
    organization: TestOrg1
    scm_type: git
    scm_url: "https://github.com/ansible/ansible"
    scm_credential: TestCred1

- name: Update project
  tower_project:
    name: TestProject
    state: updated
```

I also don't know concretely if this creates an _additional_ update, which would certainly be unwanted. It could be that passing `state: updated` to the fist task with that diff will work correctly, but I don't know.

That PR also breaks the precedent set by https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_job_launch.py. Maybe treating JTs and projects as special cases will be the most sensible thing here...

Also, projects are unique here. They automatically create an update when creating the project. They even create a new update on certain parameter changes. We don't even _need_ to change the contract. We could just do this automatically in all cases without asking.

It's just one of the many old pull requests which I don't quite know what to do with.
