### ISSUE TITLE
Support multiple credentials in tower_job_template

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5171]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The AWX collection module `tower_job_template` should take a list in parameter `credentials` to allow for use of multiple credentials.

**Comment by ture-karlsson** [comment]
Hello! 

I have run into a problem regarding the tower_job_template module and credentials. Since 3.6.0, credentials are not populated at all with tower_job_template. I can easily replicate this problem by running the following task on a fresh Tower install:

```bash
  - name: "create Demo Job Template 2"
    tower_job_template:
      tower_username: "admin"
      tower_password: "password"
      name: "Demo Job Template 2"
      job_type: "run"
      inventory: "Demo Inventory"
      project: "Demo Project"
      playbook: "hello_world.yml"
      credential: "Demo Credential"
```

The credentials field is configured properly on an old 3.5.3 installation, but not on 3.6.0.

I suspect it is related to the following changes from the 3.6.0 release notes [1]:

"Removed the following API endpoints:

        Job template credential field (in either v1 or v2)
        Corresponding credential field on workflow job template nodes"

Do you want me to create a separate issue for this or leave it here?

[1] https://docs.ansible.com/ansible-tower/3.6.0/html/release-notes/relnotes.html

**Comment by AlanCoding** [comment]
That was supposed to be fixed with https://github.com/ansible/tower-cli/pull/741, are you using tower-cli 3.3.7?

**Comment by ture-karlsson** [comment]
No I use python2-ansible-tower-cli-3.3.0-2.el7.noarch.rpm

It is the latest version available as RPM through EPEL: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python2-ansible-tower-cli-3.3.0-2.el7.noarch.rpm

Is 3.3.7 available as RPM somewhere else?

**Comment by AlanCoding** [comment]
No, it's only on PyPI

**Comment by ture-karlsson** [comment]
Do you know how often the RPM available in EPEL is updated?

**Comment by AlanCoding** [comment]
The pipelines that were in place for automatically building this probably cannot be revived, but the actual target to build it should still be functional. Someone can still manually build and upload it.

**Comment by Elyytscha** [comment]
How do i set credentials with tower_job_template on awx version: <  AWX 9.0.1.0 ?

its not working, i think because of the change mentioned in 3.6.0

have to do a really ugly workaround which is id based, so i have to know the id of the credential:

```
## Workaround for not beeing able to set creds via module above
- name: Update credentials for jobs templates
  uri:
    url: "https://{{ inventory_hostname }}:8053/api/v2/job_templates/{{ item.project }}-{{ item.name }}-deploy-int/credentials/"
    return_content: yes
    user: "{{ docker_compose_env_yaml.AWX_ADMIN_USER }}"
    password: "{{ docker_compose_env_yaml.AWX_ADMIN_PASS }}"
    force_basic_auth: yes
    status_code: "204,200,400"
    body_format: json
    method: POST
    body: 
      id: 6
  delegate_to: localhost
  run_once: true
  register: notifications
  loop: "{{ awx_test_projects }}"
  changed_when: 204 == notifications.status
```
