### ISSUE TITLE
Add ability to add host to groups and groups as children via AWX collection

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5177]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Replacing old issue https://github.com/ansible/ansible/issues/29149

The modules provide the ability to create groups, hosts, and inventories, but there's no way to add hosts to groups. It's pointless to have `tower_group` if you cannot actually group hosts inside of it.

got 11 👍 in old issue, so putting priority high.

There might have been some prior attempt at this before, but the code was lost somehow.

I'd suggest a `groups` parameter to `tower_host`, or `hosts` for `tower_group`, something along those lines, not involving a new module.

**Comment by leonrado** [comment]
Some update for this ?

**Comment by JonTheNiceGuy** [comment]
If you've been bitten by this one too, consider this workaround (yes, it's messy, but yes, it appears to work)

```
  - name: Messy workaround for missing ability to add children groups to an inventory group
    raw: |
      awx-cli config host {{ ansible_fqdn }} && \
      awx-cli login admin --password "{{ admin_password }}" && \
      awx-cli group create -n "{{ item.group }}" -d "{{ item.group_description | default('imported') }}" --parent "{{ item.parent }}" -i "{{ item.inventory }}"
    when: item.group is defined and item.parent is defined and item.inventory is defined
    loop:
    - group: mygroup
      parent: someparent
      inventory: my_inventory
    - group: aGroup
      group_description: A Group
      parent: aParent
      inventory: anInventory
    loop_control:
      label: "{{ item.inventory }} -> {{ item.parent }} -> {{ item.group }}"
```

**Comment by AlanCoding** [comment]
> or `hosts` for `tower_group`

This is my current leaning, because that's more similar to how it works in both the script inventory file format, and the conventional ini inventory file type.

It's also easier to mentally grok the dependency chain. I would rather create hosts and then groups, as opposed to create groups and then hosts. I don't want to consider in-loop creation of related resources, because that goes way out of scope.

**Comment by AlanCoding** [comment]
demo

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:
    - name: delete the inventory
      tower_inventory:
        name: example-inventory
        organization: Default
        state: absent

    - name: create the inventory
      tower_inventory:
        name: example-inventory
        organization: Default
        state: present

    - name: add hosts
      tower_host:
        name: "{{ item }}"
        inventory: example-inventory
      loop:
        - host1
        - host2
        - host3

    - name: add mid level group
      tower_group:
        name: child
        inventory: example-inventory
        hosts:
          - host3

    - name: add top group
      tower_group:
        name: parent
        inventory: example-inventory
        hosts:
          - host1
          - host2
        children:
          - child
```

hit a bug with it, will put up new patch

**Comment by AlanCoding** [comment]
This is now fully finished, that that demo playbook should run fine.

**Comment by squidboylan** [comment]
https://github.com/ansible/awx/pull/6505 adds the demo playbook to our integration tests

**Comment by mtward** [comment]
The functionality of adding hosts to groups is really needed.  Can this be re-opened?

**Comment by AlanCoding** [comment]
This was added, try this syntax from the tests:

https://github.com/ansible/awx/blob/devel/awx_collection/tests/integration/targets/tower_group/tasks/main.yml

```yaml
- name: add top group
  tower_group:
    name: "{{ group_name3 }}"
    inventory: "{{ inv_name }}"
    hosts:
      - "{{ host_name1 }}"
      - "{{ host_name2 }}"
    children:
      - "{{ group_name2 }}"
```
