### ISSUE TITLE
Newlines for multi-line variables are not preserved when using '|' modifier

### ISSUE THREAD

**Issue by terra-nova** [ansible/awx#525]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Specifying multi-line host variables in the AWX UI and in a YAML file in a Git repository gives different results.

The host variables are the same in AWX UI and in the YAML file:

```
sudo_config_ubiquity:
  file: ubiquity
  rules: |
    # humpty dumpty sat on a wall
    # humpty dumpty had a bad fall
```

According to Ansible docs, the `|` token should preserve newlines: `Spanning multiple lines using a | will include the newlines` (http://docs.ansible.com/ansible/latest/YAMLSyntax.html).

My Jinja template looks like this:

```
# {{ ansible_managed }}

{% for line in all_sudo_files[item] %}
{{ line }}
{% endfor %}
```

However, using AWX GUI I get this:

```
# Ansible managed

# humpty dumpty sat on a wall # humpty dumpty had a bad fall
```

Using a YAML file, I get this:

```
# Ansible managed

# humpty dumpty sat on a wall
# humpty dumpty had a bad fall
```

##### ENVIRONMENT
* AWX version: AWX 1.0.1.81
* AWX install method: docker on linux
* Ansible version:  2.4.0.0
* Operating System: CentOS 7.4 x64
* Web Browser: Mozilla Firefox 53

##### STEPS TO REPRODUCE

1. Define multi-line host variables using AWX
2. Watch in horror as playbook fails
3. Define multi-line host variables using YAML files
4. Playbook succeeds

##### EXPECTED RESULTS

Newlines should have been preserved when using the `|` modifier, according to Ansible YAML syntax documentation.

##### ACTUAL RESULTS

Newlines are not preserved when using the `|` modifier.

**Comment by temazelikin** [comment]
Confirm the same bug.

AWX: 1.0.1.93
Ansible: 2.4.0.0
Operating System: CentOS 7.4 x64

AWX deployed using docker containers.

**Comment by ryanpetrello** [comment]
@terra-nova @temazelikin I'm having trouble reproducing this on the latest version of awx - are you all still seeing this issue on `awx 1.0.5+`?

**Comment by ryanpetrello** [comment]
If so, could you visit any host at: `https://awx.example.org/api/v2/hosts/N/` and share the `variables` data?  This is what I have when I fill out YAML hostvars in the UI:

```json
{
    "variables": "ansible_connection: local\nfoo: |\n    # bar\n    # spam\n    # eggs"
}
```

<img width="352" alt="screen shot 2018-04-06 at 2 58 55 pm" src="https://user-images.githubusercontent.com/214912/38439274-0d479c2c-39ab-11e8-8a73-d25d4fd1db0f.png">

**Comment by ryanpetrello** [comment]
Here's the inventory file that will be written by awx for `ansible-playbook` to actually _use_ in my example:

```python
print Inventory.objects.get(pk=1).get_script_data(hostvars=True)
{'all': {'hosts': [u'localhost']}, '_meta': {'hostvars': {u'localhost': {'foo': '# bar\n# spam\n# eggs', 'ansible_connection': 'local'}}}}
```

I'm pretty sure this is equivalent to what your YAML-based hostvars should be doing.

Specifically, _this_ is the inventory file that was generated by awx in this example:

```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-
print '{"all": {"hosts": ["localhost"]}, "_meta": {"hostvars": {"localhost": {"foo": "# bar\\n# spam\\n# eggs", "ansible_connection": "local"}}}}'
```

**Comment by ryanpetrello** [comment]
Here's what I get if I run an example playbook + template w/ the JSON inventory version:

```yaml
[root@awx /]# cat debug_template.yml && cat templates/lines.j2 && cat json
---

- hosts: all
  gather_facts: false
  tasks:
    - template: src=lines.j2 dest=/tmp/multiline

{% for line in foo.splitlines() %}
{{ line }}
{% endfor %}

#! /usr/bin/env python
# -*- coding: utf-8 -*-
print '{"all": {"hosts": ["localhost"]}, "_meta": {"hostvars": {"localhost": {"foo": "# bar\\n# spam\\n# eggs", "ansible_connection": "local"}}}}'

[root@awx /]# ansible-playbook debug_template.yml -i json

PLAY [all] *********************************************************************

TASK [template] ****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

```
[root@awx /]# cat /tmp/multiline
# bar
# spam
# eggs
```

**Comment by ryanpetrello** [comment]
Here's an equivalent YAML version:

```yaml
[root@awx /]# cat debug_template.yml && cat templates/lines.j2 && cat host_vars/localhost
---

- hosts: all
  gather_facts: false
  tasks:
    - template: src=lines.j2 dest=/tmp/multiline

{% for line in foo.splitlines() %}
{{ line }}
{% endfor %}

ansible_connection: local
foo: |
     # bar
     # spam
     # eggs

[root@awx /]# ansible-playbook debug_template.yml -i localhost,

PLAY [all] *********************************************************************

TASK [template] ****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

```
[root@awx /]# cat /tmp/multiline
# bar
# spam
# eggs
```
