### ISSUE TITLE
tower_credential_type gives incorrect changed status

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5321]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The module `tower_credential_type` appears to be useless for any practical playbook, because `state: present` will fail every time if the credential type already exists and a credential that uses the credential type is present (which is, after all, the point of credential types).

##### ENVIRONMENT
* AWX version: 9.0.1
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Run this twice

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - awx.awx.tower_organization:
      name: demo

  - awx.awx.tower_credential_type:
      name: single_env_var
      kind: cloud
      inputs:
        fields:
          - id: env_value
            label: Value to set this environment variable to
            default: foo
      injectors:
        env:
          TEST_ENV_VAR: !unsafe "{{ env_value }}"

  - awx.awx.tower_credential:
      name: demo_custom
      credential_type: single_env_var
      organization: demo
      inputs:
        env_value: "use of custom input is confirmed"
```

From https://github.com/ansible/awx/pull/5210

##### EXPECTED RESULTS

It runs and does not error both times.

##### ACTUAL RESULTS

runs the 1st time, but errors the 2nd time.

##### ADDITIONAL INFORMATION

It's fairly obvious that it is attempting to obtain the data (in terms of inputs / injectors) that already exists.

Either tower-cli needs to correctly assess that this is a no-op, or the API needs to not throw 400 errors in the case that inputs / injectors are not _actually_ changing.

Really, both of these two things should be fixed.
