### ISSUE TITLE
[AWX collection] Handling of extra_vars is still inconsistent with job launch

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#5558]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Following up from https://github.com/ansible/ansible/pull/65949

For job templates and other cases, extra_vars is a dict. Launching a job, it is declared as a list. However, the example that worked:

```yaml
- name: Launch a job template with Extra Vars on remote tower instance
  tower_job_launch:
    job_template: "My Job Template"
    extra_vars: >
      var1: "My First Variable",
      var2: "My Second Variable",
      var3: "My Third Variable"
    tower_host: "{{ my_tower_host }}"
    tower_username: "{{ my_tower_username }}"
    tower_password: "{{ my_tower_password }}"
    job_type: run
```

seems to be using a string.

In the old tests https://github.com/ansible/test-playbooks/blob/d4b39fe0c010cf8dc9c4e6e60113664cd4bf1bbd/tower_modules, this parameter was never used at all.

this is subject to discussion, but it should probably be a dict
