### ISSUE TITLE
Job remains in pending

### ISSUE THREAD

**Issue by beatsandpics** [ansible/awx#5617]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
Job remains in pending, In the log I see a lot of "awx.main.tasks Not running scheduler, another task holds lock" 

There are some closed issues regarding this one, but didn't find any solution.

Randomly AWX get stuck where all jobs remain in "pending"

In the logs I see 
`task_1       | 2020-01-09 16:08:59,344 DEBUG    awx.main.dispatch task a1c42d7f-17b2-4590-b013-b82f76105f0c starting awx.main.scheduler.tasks.run_task_manager(*[])
task_1       | 2020-01-09 16:08:59,347 DEBUG    awx.main.scheduler Running Tower task manager.
task_1       | 2020-01-09 16:08:59,359 DEBUG    awx.main.scheduler Not running scheduler, another task holds lock
task_1       | 2020-01-09 16:08:59,360 DEBUG    awx.main.dispatch task a1c42d7f-17b2-4590-b013-b82f76105f0c is finished`

After a lot of time (this time 16min) it suddenly starts to execute the task

`task_1       | 2020-01-09 16:24:19,814 DEBUG    awx.main.dispatch task b832fea9-c31f-4cfb-8ce3-fda16a1ac5cb starting awx.main.scheduler.tasks.run_task_manager(*[])
task_1       | 2020-01-09 16:24:19,816 DEBUG    awx.main.scheduler Running Tower task manager.
task_1       | 2020-01-09 16:24:19,827 DEBUG    awx.main.scheduler Not running scheduler, another task holds lock
task_1       | 2020-01-09 16:24:19,828 DEBUG    awx.main.dispatch task b832fea9-c31f-4cfb-8ce3-fda16a1ac5cb is finished
task_1       | 2020-01-09 16:24:38,979 DEBUG    awx.main.dispatch publish awx.main.tasks.cluster_node_heartbeat(aacec6cc-b438-4cb7-b3f8-2a9ba0b3f399, queue=awx)
task_1       | [2020-01-09 16:24:38,979: DEBUG/Process-1] publish awx.main.tasks.cluster_node_heartbeat(aacec6cc-b438-4cb7-b3f8-2a9ba0b3f399, queue=awx)
rabbitmq_1   | 2020-01-09 16:24:38.989 [info] <0.3775.0> accepting AMQP connection <0.3775.0> (172.19.0.5:48346 -> 172.19.0.3:5672)
rabbitmq_1   | 2020-01-09 16:24:38.991 [info] <0.3775.0> connection <0.3775.0> (172.19.0.5:48346 -> 172.19.0.3:5672): user 'guest' authenticated and granted access to vhost 'awx'
rabbitmq_1   | 2020-01-09 16:24:38.996 [info] <0.3775.0> closing AMQP connection <0.3775.0> (172.19.0.5:48346 -> 172.19.0.3:5672, vhost: 'awx', user: 'guest')
task_1       | 2020-01-09 16:24:39,003 DEBUG    awx.main.dispatch delivered aacec6cc-b438-4cb7-b3f8-2a9ba0b3f399 to worker[178] qsize 0
task_1       | 2020-01-09 16:24:39,005 DEBUG    awx.main.dispatch task aacec6cc-b438-4cb7-b3f8-2a9ba0b3f399 starting awx.main.tasks.cluster_node_heartbeat(*[])
task_1       | 2020-01-09 16:24:39,008 DEBUG    awx.main.tasks Cluster node heartbeat task.
task_1       | 2020-01-09 16:24:39,020 DEBUG    awx.main.dispatch task aacec6cc-b438-4cb7-b3f8-2a9ba0b3f399 is finished
task_1       | 2020-01-09 16:24:39,090 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_k8s_reaper(e33c3d96-163b-487f-8101-00dd80f101a7, queue=awx)
task_1       | [2020-01-09 16:24:39,090: DEBUG/Process-1] publish awx.main.tasks.awx_k8s_reaper(e33c3d96-163b-487f-8101-00dd80f101a7, queue=awx)
rabbitmq_1   | 2020-01-09 16:24:39.100 [info] <0.3788.0> accepting AMQP connection <0.3788.0> (172.19.0.5:48350 -> 172.19.0.3:5672)
rabbitmq_1   | 2020-01-09 16:24:39.102 [info] <0.3788.0> connection <0.3788.0> (172.19.0.5:48350 -> 172.19.0.3:5672): user 'guest' authenticated and granted access to vhost 'awx'
rabbitmq_1   | 2020-01-09 16:24:39.104 [info] <0.3788.0> closing AMQP connection <0.3788.0> (172.19.0.5:48350 -> 172.19.0.3:5672, vhost: 'awx', user: 'guest')
task_1       | 2020-01-09 16:24:39,105 DEBUG    awx.main.dispatch delivered e33c3d96-163b-487f-8101-00dd80f101a7 to worker[178] qsize 0
task_1       | 2020-01-09 16:24:39,108 DEBUG    awx.main.dispatch task e33c3d96-163b-487f-8101-00dd80f101a7 starting awx.main.tasks.awx_k8s_reaper(*[])
task_1       | 2020-01-09 16:24:39,117 DEBUG    awx.main.dispatch task e33c3d96-163b-487f-8101-00dd80f101a7 is finished
task_1       | 2020-01-09 16:24:39,344 DEBUG    awx.main.dispatch publish awx.main.tasks.awx_periodic_scheduler(97554fd6-f2c2-4b5f-a25d-bf09743b9105, queue=awx_private_queue)
task_1       | [2020-01-09 16:24:39,344: DEBUG/Process-1] publish awx.main.tasks.awx_periodic_scheduler(97554fd6-f2c2-4b5f-a25d-bf09743b9105, queue=awx_private_queue)
rabbitmq_1   | 2020-01-09 16:24:39.354 [info] <0.3801.0> accepting AMQP connection <0.3801.0> (172.19.0.5:48354 -> 172.19.0.3:5672)
rabbitmq_1   | 2020-01-09 16:24:39.356 [info] <0.3801.0> connection <0.3801.0> (172.19.0.5:48354 -> 172.19.0.3:5672): user 'guest' authenticated and granted access to vhost 'awx'
task_1       | 2020-01-09 16:24:39,359 DEBUG    awx.main.dispatch delivered 97554fd6-f2c2-4b5f-a25d-bf09743b9105 to worker[178] qsize 0
rabbitmq_1   | 2020-01-09 16:24:39.359 [info] <0.3801.0> closing AMQP connection <0.3801.0> (172.19.0.5:48354 -> 172.19.0.3:5672, vhost: 'awx', user: 'guest')
task_1       | 2020-01-09 16:24:39,361 DEBUG    awx.main.dispatch task 97554fd6-f2c2-4b5f-a25d-bf09743b9105 starting awx.main.tasks.awx_periodic_scheduler(*[])
task_1       | 2020-01-09 16:24:39,377 DEBUG    awx.main.tasks Starting periodic scheduler
task_1       | 2020-01-09 16:24:39,380 DEBUG    awx.main.tasks Last scheduler run was: 2020-01-09 16:05:39.310989+00:00
task_1       | 2020-01-09 16:24:39,390 DEBUG    awx.main.dispatch task 97554fd6-f2c2-4b5f-a25d-bf09743b9105 is finished`

Is there a way to know which other task blocks the scheduler?

##### ENVIRONMENT
* AWX version: 9.1.0
* AWX install method: docker on linux
* Operating System: Centos 7

**Comment by beatsandpics** [comment]
what infos do you need?

**Comment by wenottingham** [comment]
What sort of deployment do you have - what is the topology?

If this is in kubernetes, what is your pod status?

**Comment by beatsandpics** [comment]
I'm using docker-compose with an external Postgres DB.
It's a AWX 3.x version (where we had the same issue) which I upgraded to 9.x 

```
version: '2'
services:

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - "~/docker_projects/awx/nginx_ssl.conf:/etc/nginx/nginx.conf:ro"
      - "~/docker_projects/awx/cert/:/etc/nginx/certs/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    image: ansible/awx_web:9.1.0
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
    ports:
      - "8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "~/docker_projects/awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "~/docker_projects/awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "~/docker_projects/awx/credentials.py:/etc/tower/conf.d/credentials.py"
      - "~/docker_projects/awx/nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:


  task:
    image: ansible/awx_task:9.1.0
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "~/docker_projects/awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "~/docker_projects/awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "~/docker_projects/awx/credentials.py:/etc/tower/conf.d/credentials.py"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: awx_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "awxpass"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy:
      https_proxy:
      no_proxy:

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
```
