### ISSUE TITLE
ovirtsdk4 version 4.3.0 or higher is required for this module

### ISSUE THREAD

**Issue by preguenga** [ansible/awx#5623]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
ovirtsdk4 4.3.0 is installed by default but this error message still appears...
I even created a custom venv with no luck.. 

##### ENVIRONMENT
* AWX version: 9.1.0.0  
* AWX install method: docker on linux
* Ansible version:  2.8.5(default venv) and 2.9.2(custom venv)

##### STEPS TO REPRODUCE
1. use any ovirt module
for example : 

```
  - name: Obtain SSO token using username/password creds.
    ovirt_auth:
      url: https://rhvm.com/ovirt-engine/api
      username: admin@internal
      ca_file: ../pki-resource.cer
      password: "{{ ovirt_password }}"
```
 

##### EXPECTED RESULTS

Get token

##### ACTUAL RESULTS
error msg: ovirtsdk4 version 4.3.0 or higher is required for this module

##### ADDITIONAL INFORMATION
Default venv
```
(ansible) bash-4.4# pip freeze | grep ovirt.
ovirt-engine-sdk-python==4.3.0
```

Custom venv
```
(py36) bash-4.4# pip freeze | grep ovirt
ovirt-engine-sdk-python==4.4.0
``
