### ISSUE TITLE
Mattermost notification failed because of custom CA

### ISSUE THREAD

**Issue by craph** [ansible/awx#5704]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm unable to use Mattermost notification because my custom CA is not trusted

##### ENVIRONMENT
* AWX version: 9.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Windows
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a notification for Mattermost (Mattermost must have custom CA)
Test the notification

##### EXPECTED RESULTS

Notification have to work with custom CA

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/14820052/72713506-6fb79e00-3b6d-11ea-8e3f-c4c2bd988b86.png)

**Comment by wenottingham** [comment]
Have you passed the CA as a volume mount with the installer?

**Comment by craph** [comment]
Hello @wenottingham ,

Can you provide me the link where this is explain. Should I have to pass the ROOT CA only or the ROOT CA + the intermediate CA too ? 

If both, should I concatenate them in one file ?

Should restart the installation steps to do that ?

Thank you very much for your help.

Best regards,

**Comment by wenottingham** [comment]
See the section in the installer inventory:
```

# CA Trust directory. If you need to provide custom CA certificates, supplying
# this variable causes this directory on the host to be bind mounted over
# /etc/pki/ca-trust in the awx_task and awx_web containers.
#ca_trust_dir=/etc/pki/ca-trust/source/anchors
```

**Comment by craph** [comment]
Hello @wenottingham ,

This doesn't work for me. 

Here is what I have :
![image](https://user-images.githubusercontent.com/14820052/74514054-26f4ca00-4f0c-11ea-8a65-394025003e51.png)

Here is my docker-compose.yml :
```yaml
# cat docker-compose.yml
version: '2'
services:

  web:
    image: ansible/awx_web:9.2.0
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "443:8053"
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "/srv/dockerdata/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/srv/dockerdata/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/srv/dockerdata/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/srv/dockerdata//awx/awxcompose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/root/certpki:/etc/pki/ca-trust/source/anchors:ro"
      - "/root/awx-ssl/awx-bundled-key.crt:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx_task:9.2.0
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "/srv/dockerdata/awx/awxcompose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/srv/dockerdata/awx/awxcompose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/srv/dockerdata/awx/awxcompose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/root/certpki:/etc/pki/ca-trust/source/anchors:ro"
      - "/root/awx-ssl/awx-bundled-key.crt:/etc/nginx/awxweb.pem:ro"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: awx_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guestxxx"
      RABBITMQ_DEFAULT_PASS: "xxxx"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy:
      https_proxy:
      no_proxy:

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /srv/dockerdata/awx/pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy:
      https_proxy:
      no_proxy:

```

The folder `/root/certpki` contains my custom CA (ROOT and intermediate CA) + a pem file that contains the merge of ROOT and intermediate.

```bash
# ll /root/certpki/
total 16
-rwxrwxrwx 1 root root 2886 Jan 26  2017 subCA Base 64.cer
-rw-r--r-- 1 root root 4984 Nov 12 16:35 pki_chain.pem
-rwxrwxrwx 1 root root 2098 Jan 26  2017 Root CA Base 64.cer
```

Here is the log :
```bash
awx_task     | 2020-02-14 08:32:49,194 ERROR    awx.main.tasks Send Notification Failed HTTPSConnectionPool(host='mattermost.mydomain.com', port=4434): Max retries exceeded with url: /hooks/whojkstuu7ybi8ckdqjee95gxc (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))
awx_task     | Traceback (most recent call last):
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
awx_task     |     chunked=chunked,
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
awx_task     |     self._validate_conn(conn)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
awx_task     |     conn.connect()
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
awx_task     |     ssl_context=context,
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
awx_task     |     return context.wrap_socket(sock, server_hostname=server_hostname)
awx_task     |   File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
awx_task     |     _context=self, _session=session)
awx_task     |   File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
awx_task     |     self.do_handshake()
awx_task     |   File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
awx_task     |     self._sslobj.do_handshake()
awx_task     |   File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
awx_task     |     self._sslobj.do_handshake()
awx_task     | ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
awx_task     |
awx_task     | During handling of the above exception, another exception occurred:
awx_task     |
awx_task     | Traceback (most recent call last):
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
awx_task     |     timeout=timeout
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
awx_task     |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
awx_task     |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
awx_task     | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mattermost.mydomain.com', port=4434): Max retries exceeded with url: /hooks/whojkstuu7ybi8ckdqjee95gxc (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))
awx_task     |
awx_task     | During handling of the above exception, another exception occurred:
awx_task     |
awx_task     | Traceback (most recent call last):
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py", line 324, in send_notifications
awx_task     |     sent = notification.notification_template.send(notification.subject, notification.body)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/models/notifications.py", line 196, in send
awx_task     |     return backend_obj.send_messages([notification_obj])
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/notifications/mattermost_backend.py", line 48, in send_messages
awx_task     |     data=json.dumps(payload), verify=(not self.mattermost_no_verify_ssl))
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/api.py", line 116, in post
awx_task     |     return request('post', url, data=data, json=json, **kwargs)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/api.py", line 60, in request
awx_task     |     return session.request(method=method, url=url, **kwargs)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
awx_task     |     resp = self.send(prep, **send_kwargs)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
awx_task     |     r = adapter.send(request, **kwargs)
awx_task     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
awx_task     |     raise SSLError(e, request=request)
awx_task     | requests.exceptions.SSLError: HTTPSConnectionPool(host='mattermost.mydomain.com', port=4434): Max retries exceeded with url: /hooks/whojkstuu7ybi8ckdqjee95gxc (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))

```

And in the container : 
```bash
# docker exec -ti b3ee68360bf3 bash
bash-4.4#
bash-4.4#
bash-4.4# cd /etc/pki/ca-trust/source/anchors
bash-4.4# ls
'subCA Base 64.cer'   pki_chain.pem  'Root CA Base 64.cer'
```

**Comment by craph** [comment]
I have done some other tests. 

Inside the awx_web container : 
```bash
openssl s_client -connect mattermost.mydomain.com:4434
...
SSL handshake has read 3204 bytes and written 432 bytes
Verification: OK
...
Verify return code: 0 (ok)
Extended master secret: yes
```
I was unable to do the same in awx_task container because openssl wasn't installed. After installing it with `dnf install openssl` I got the same result : 
```bash
openssl s_client -connect mattermost.mydomain.com:4434
...
SSL handshake has read 3204 bytes and written 432 bytes
Verification: OK
...
Verify return code: 0 (ok)
Extended master secret: yes
```

So I don't understand why it's not OK and I got this error message

**Comment by craph** [comment]
After installing python requests module, I have try to do : 
`python3 -c 'import requests; requests.get("https://mattermost.mydomain.com/")'`

And I got the same error
`(Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))`

**Comment by craph** [comment]
@wenottingham, @ryanpetrello, any news about custom CA  and CA trust dir issue ?

May be something like that should help : https://incognitjoe.github.io/adding-certs-to-requests.html

After reading some documentation, I found that by default, the Python ssl module uses the system CA certificate bundle - /etc/pki/tls/certs/ca-bundle.crt - shipped as part of the ca-certificates package.

Here is the link : https://access.redhat.com/articles/2039753#troubleshooting-certificate-verification-8

Nevertheless, if I launch (in awx_task and awx_web) after installing `requests` in the default user : 
```python
python3 -c "import requests; print(requests.certs.where())"
/usr/local/lib/python3.6/site-packages/certifi/cacert.pem
```

I can see that `certifi `is used and the default CA certificated trusted, used and bundled are here : `/usr/local/lib/python3.6/site-packages/certifi/cacert.pem` but this location doesn't use the `ca_trust_dir` refered during the installation step.

So I think here Python is not using `/etc/pki/tls/certs/ca-bundle.crt` where the custom CA should be placed after the `/usr/bin/update-ca-trust`

Possible solutions : 

1. Add the custom CA to the certifi bundle file ? (NOT BEST I THINK)

1. Remove `certifi` to be able to use the system CA certificate bundle

1. Use environment variable `REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`

With the environment variable I have no error in CLI : 
`REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt python3 -c 'import requests; requests.get("https://mattermost.mydomain.com/")'`

So the simplyest way should to use the env variable.

What I propose is to define the environment variable in the docker compose file if ca-trust-dir is set like this (I can make a PR for that 😃 ) : 
```yaml
environment:
      http_proxy: {{ http_proxy | default('') }}
      https_proxy: {{ https_proxy | default('') }}
      no_proxy: {{ no_proxy | default('') }}
{% if ca_trust_dir is defined %}
      REQUESTS_CA_BUNDLE: /etc/pki/tls/certs/ca-bundle.crt
{% endif %}
```

What do you think about that ?

Thank you.

Best regards,
