### ISSUE TITLE
tower_job_launch does not set credential against AWX 9.1.1

### ISSUE THREAD

**Issue by ephracis** [ansible/awx#5834]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When using the module `awx.awx.tower_job_launch` using the collection `awx.awx:9.1.1` against AWX 9.1.1 the job does not get the correct credential. This worked previously in AWX 3.

This bug report was originally reported as ansible/ansible#67098 but since the tower/awx modules are moving, I am opening up a new bug report here.

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker on linux
* Ansible version:  2.9.4
* awx.awx collection version: 9.1.1
* Operating System (AWX server): CentOS 8.1 and CentOS 7.7
* Operating System (Ansible control): macOS Catalina and CentOS 7.7

##### STEPS TO REPRODUCE

Deploy AWX and configure it with a template, an inventory and a credential. The template has the property `ask_credential` and `ask_inventory` set.

Verify that the AWX template can be launched via the web interface when selecting the proper inventory and credential.

```yaml
# example from https://docs.ansible.com/ansible/latest/modules/tower_job_launch_module.html
- name: Launch a job with inventory and credential
  tower_job_launch:
    job_template: "My Job Template"
    inventory: "My Inventory"
    credential: "My Credential"
```

##### EXPECTED RESULTS

The job is launched with the credential `My Credential`.

##### ACTUAL RESULTS

The job is launched without any credential.

##### ADDITIONAL INFORMATION

When launching the job manually using the GUI a dialog is asking for both inventory and credential, selecting these and running the template results in a successful job.

I have triple checked the name of the credential. Pretty sure this is not the issue. Also, when running the exact same playbook against AWX 3 it works without issue. There seem to be a mismatch in the AWX 3 API and the awx.awx 9.1.1 modules.
