### ISSUE TITLE
Unable to connect to postgres with pgadmin

### ISSUE THREAD

**Issue by craph** [ansible/awx#5873]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to connect to postgres (docker container) with pgadmin

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker
* Ansible version:  2.8.5
* Operating System: CentOS 7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Install pgadmin on your laptop and then try to connect to the docker postgres.

##### EXPECTED RESULTS

I want to be able to connect to the postgres with pgadmin.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/14820052/74221978-9de35600-4cb3-11ea-9087-4e9e65f01ab8.png)

##### ADDITIONAL INFORMATION

Here is the info from my docker ps :
`36b1032bc28b        postgres:10                  "docker-entrypoint.s…"   3 weeks ago         Up 8 days              5432/tcp                                                awx_postgres
`

I'm using the defaut config from AWX for postgres

If I use the IPV4 of my container I have a timeout :
```yaml
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8aa7aa174e1b4a725b859d1010c27dbc1e54fc1e5d9e070993ed097c8c94583c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5432/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/8aa7aa174e1b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "awxcompose_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "postgres",
                        "36b1032bc28b"
                    ],
                    "NetworkID": "90c2977e02a1d16a7a207c4cf91daaa1aa59737f1ad922efe49f80add0c259de",
                    "EndpointID": "82a6df0808a2c2a33ebdb102d0e9c834fa402eb990e2cf5c510fe9bc233ea2a5",
                    "Gateway": "172.23.0.1",
                    "IPAddress": "172.23.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:17:00:03",
                    "DriverOpts": null
                }
            }
        }

```
![image](https://user-images.githubusercontent.com/14820052/74222689-5a89e700-4cb5-11ea-99d2-28fa2516f1cd.png)

Thank you very much for your help.
