### ISSUE TITLE
Allow multiple instances of the same custom credential

### ISSUE THREAD

**Issue by philipsd6** [ansible/awx#5911]
##### ISSUE TYPE
 - Allow multiple instances of the same custom credential to be used in the same playbook
##### SUMMARY
Currently, if we create a generic custom credential named "REST API Credential" that injects `api_username` and `api_password` and `api_base_url` into the extravars and/or environment, we can only use that to deal with _one_ API, because there can be only one extravar of `api_username`, etc.

For example, I cannot use such a custom credential type to create credentials for ServiceOne and ServiceTwo _and_ work with both in the same playbook. So the only way to manage this is to create a custom credential for ServiceOne and another for ServiceTwo. But then, what if I want to create two ServiceOne credentials for two accounts? Back to the original problem. 

We should be able to create multiple credentials of the same custom type, and use each of them in the playbooks. Obviously there must be a way to distinguish between them then. I'm sure there is more than one way to model this, but what I wanted to do was this:

**Input Configuration**
```yaml
fields:
  - type: string
    id: api_username
    label: Username
  - secret: true
    type: string
    id: api_password
    label: Password
  - type: string
    id: api_baseurl
    label: Base URL
  - type: string
    id: prefix
    label: Credential Prefix
required:
  - api_username
  - api_password
  - api_baseurl
```
**Injector Configuration**
```yaml
extra_vars:
  "{{ [prefix, 'api_username'] | join('_') }}": "{{ api_username }}"
  "{{ [prefix, 'api_password'] | join('_') }}": "{{ api_password }}"
  "{{ [prefix, 'api_baseurl'] | join('_') }}": "{{ api_baseurl }}"
```
With a prefix of "one", I'd expect to be able to use `one_api_username`, etc... in my playbooks. But of course I can't do that, because injector keys are not evaluated as Jinja2. Or is there a better way to achieve my goals with Credentials?
