### ISSUE TITLE
Using delegate_to on remote docker host 

### ISSUE THREAD

**Issue by jorgv** [ansible/awx#593]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

##### SUMMARY

I am trying to deploy a playbook on a remote host, deploying some docker containers like Mysql for example, but when using delegate_to: mysql to create DB inside the container it gives me:

```
docker: executable file not found in PATH
```

Because docker is not present on awx-task container. 
Is it possible to use docker remote host to deploy the playbook on the remote host and then use delegate_to to get inside the container host.

Or to install docker inside awx-task so it can use it to delegate_to: directly on the remote container host.

##### ENVIRONMENT
* AWX version:1.0.1.153 
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: Ubuntu Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Deploy the following playbook

```
- hosts: all
  become: yes
  gather_facts: False
  vars:
   - ansible_python_interpreter: /usr/bin/python2.7
   - ansible_sudo_pass:
  tasks:
    - name: Mysql docker container UP
      docker_container:
        name: db
        image: mysql:latest
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: 

    - name: add Mysql container to inventory
      add_host:
        name: db
        ansible_connection: docker
        ansible_user: root
        ansible_docker_extra_args: "-H=tcp://remotehost:2375"
      changed_when: False

    - name: install DB
      delegate_to: db
      gather_facts: False
      mysql_db:
        name: test
        state: present

```

##### EXPECTED RESULTS

To install DB on remote docker container

##### ACTUAL RESULTS

```
docker: executable file not found in PATH
```

##### ADDITIONAL INFORMATION

Tried to install docker on awx-task docker container and it will not show the following error anymore:
```
docker: executable file not found in PATH
```

But instead shows that the docker daemon is not active.
