### ISSUE TITLE
command module has not applied the become: true flag

### ISSUE THREAD

**Issue by dojones1** [ansible/awx#5959]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Become flag on playbook and task does not appear to take effect. Command is run without sudo privileges

##### ENVIRONMENT
* AWX version: 9.2.0 (also seen on 9.1.0)
* AWX install method: docker on linux
* Ansible version:  2.9.3
* Operating System: Centos
* Web Browser: Chrome 80.0.3987.106

##### STEPS TO REPRODUCE

playbook.yml:
```
---
- name: Check that this is only run once
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Have we run before
      when: _deploy_common_has_run is not defined
      import_role:
        name: role_ansible_prereqs
      
- name: install Docker based Oracle
  hosts: all
  become: true
  tasks:
    - name: Have we run before
      when: _deploy_common_has_run is not defined
      block:
        - import_role:
            name: role_ca_certificates
```

role_ca_certificates/tasks/linux.yml
```
---
- name: Load OS Family specific defaults
  include_vars: "defaults-{{ ansible_os_family }}.yml"

- name: Install CA Certificates package
  become: true
  package:
    name: ca-certificates
    state: present

- name: Enable Cert Management (RHEL 6)
  when:
    - ansible_os_family | lower == 'redhat'
    - ansible_distribution_major_version | int == 6 or ansible_distribution_major_version | int == 7
  block:
    - name: "Check CA Trust Expansion state"
      become: true
      command: "/usr/bin/update-ca-trust check"
      check_mode: false
      changed_when: false
      register: result
...
```

User has been created with:
PRIVILEGE ESCALATION METHOD: sudo
PRIVILEGE ESCALATION USERNAME: <set>
PRIVILEGE ESCALATION PASSWORD: <set>

Target VM is a Centos7 based machine.

##### EXPECTED RESULTS

/usr/bin/update-ca-trust check should operate without issue.

##### ACTUAL RESULTS

The Check CA Trust Expansion state stage fails due to permission denied. There is no evidence that the stage was run with escalated privileges.
```
{
    "changed": false,
    "end": "2020-02-17 17:12:16.558452",
    "stdout": "",
    "cmd": [
        "/usr/bin/update-ca-trust",
        "check"
    ],
    "delta": "0:00:00.746504",
    "stderr": "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt: Permission denied\np11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: Permission denied\np11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem: Permission denied\np11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem: Permission denied\np11-kit: couldn't create file: /etc/pki/ca-trust/extracted/java/cacerts: Permission denied",
    "rc": 1,
    "invocation": {
        "module_args": {
            "creates": null,
            "executable": null,
            "_uses_shell": false,
            "strip_empty_ends": true,
            "_raw_params": "/usr/bin/update-ca-trust check",
            "removes": null,
            "argv": null,
            "warn": true,
            "chdir": null,
            "stdin_add_newline": true,
            "stdin": null
        }
    },
    "start": "2020-02-17 17:12:15.811948",
    "msg": "non-zero return code",
    "stdout_lines": [],
    "stderr_lines": [
        "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt: Permission denied",
        "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: Permission denied",
        "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem: Permission denied",
        "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem: Permission denied",
        "p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/java/cacerts: Permission denied"
    ],
    "_ansible_no_log": false
}
```

I know that I can run the command with sudo and it will work:
```
[dev@jm5_vm1 ~]$ /usr/bin/update-ca-trust check
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt: Permission denied
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: Permission denied
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem: Permission denied
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem: Permission denied
p11-kit: couldn't create file: /etc/pki/ca-trust/extracted/java/cacerts: Permission denied
[dev@jm5_vm1 ~]$ sudo /usr/bin/update-ca-trust check
[sudo] password for dev:
[dev@jm5_vm1 ~]$
```

So why does AWX not run command and obey the become: true flag
