### ISSUE TITLE
Using workflow within another workflow, results in `Deleted` Node - when using tower_workflow_template ansible module

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#6168]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Using a workflow within another workflow, results in `Deleted` Node - when using tower_workflow_template ansible module to create workflows on Ansible Tower.

##### ENVIRONMENT

* Tower version: 3.6.2
* AWX install method: linux using bundle
* Ansible version: 2.9.1 on Tower, 2.9.2 on my local system from where I run the playbook
* Operating System: not relevant I believe
* Web Browser: N/A

##### STEPS TO REPRODUCE

Use tower_workflow_template ansible module to create workflow and pass it following data:
```
tower_workflows:
  - name: Test workflow
    description: created by Ansible Playbook
    organization: Default
    survey_enabled: false
    allow_simultaneous: no
    schema:
      - job_template: Demo Job Template
        failure_nodes:
          - job_template: bherring-MR
        success_nodes:
          - workflow_template: Satellite SNAP Build  
            always_nodes:
              - job_template:  Deploy base RHEL 7 box
```

##### EXPECTED RESULTS

See screenshot below. I ended up with Deleted node in workflow. 

##### ACTUAL RESULTS

`Deleted` Node in my workflow. 

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/8180469/75922718-9128cc80-5e31-11ea-9aa1-8ffc5f11f7fe.png)
