### ISSUE TITLE
tower_notifications forces to set username and password for email/irc notifications

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#6218]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using `tower_notification` modules in my ansible playbooks, to create notification of `kind` - `email` or `irc`, it forces you to pass `username:''` and `password:''` for `email` and `password:''` for `irc`. This is inconsistent with what UI needs you to add.

##### ENVIRONMENT
* Tower version: 3.6.2
*AWX install method: linux using bundle
* Ansible version: 2.9.1 on Tower, 2.9.2 on my local system from where I run the playbook
* Operating System: not relevant I believe
* Web Browser: N/A

##### STEPS TO REPRODUCE

use following code to create a notifiction in Ansible tower using `tower_notification` ansible core module:
```
tower_notifications:
  - name: irc-satqe-chat-notification
    description: Notify us on job in IRC!
    organization: Default
    notification_type: irc
    nickname: Ansible-Tower-Stage-Bot-01
    port: 6667
    server: irc.com
    targets:
      - 'kkulkarni'
    password: ''  # this is required even if there's no password
  - name: Email notification
    description: Send out emails for tower jobs
    organization: Default
    notification_type: email
    host: smtp.redhat.com
    recipients:
      - kk@example.com
    sender: admin@example.com
    port: 25
    username: '' # this is required even if there's no username
    password: '' # this is required even if there's no password
    state: present
```

##### EXPECTED RESULTS

No need to pass username/password to the module, making it optional. 

##### ACTUAL RESULTS

Module fails as it thinks username and password are required. 

##### ADDITIONAL INFORMATION
Do not have any atm. but can provide if needed.
