### ISSUE TITLE
tower_role not idempotent

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#6324]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Granting a user a role with the AWX collection twice gives changed twice

##### ENVIRONMENT
* AWX version: 9.3.0

##### STEPS TO REPRODUCE

```yaml
- name: Add Joe to workflow execute role
  tower_role:
    user: joe
    role: execute
    workflow: test-role-workflow
    state: present
  register: result

- assert:
    that:
      - "result is changed"

- name: Add Joe from the workflow execute role, no-op
  tower_role:
    user: joe
    role: execute
    workflow: test-role-workflow
    state: present
  register: result

- assert:
    that:
      - "result is not changed"
```

##### EXPECTED RESULTS

passes

##### ACTUAL RESULTS

fails, both tasks report changed

##### ADDITIONAL INFORMATION

this is being refactored anyway, test again then

https://github.com/ansible/awx/pull/6304
