### ISSUE TITLE
tower_settings module "value" field does not accept comma

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/awx#6355]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Supplying a comma in the value field for tower_settings causes the module to fail with "Not a valid string."

The issue is only seen in the new AWX Collection module: https://galaxy.ansible.com/awx/awx

This is a regression from the old Tower-CLI module located at
`/site-packages/ansible/modules/web_infrastructure/ansible_tower/tower_settings.py`, which works as expected.

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.2
* Operating System: MacOS 10.15.3
* Web Browser:

##### STEPS TO REPRODUCE

1. Install latest AWX collection from Ansible Galaxy
`ansible-galaxy collection install awx.awx`

2. Create a Playbook that updates an AWX setting
```YAML
---
- hosts: localhost
  gather_facts: false
  collections:
    - awx.awx
  tasks:
  - name: Set LDAP Bind DN
    tower_settings:
      name: AUTH_LDAP_BIND_DN
      value: "CN=service_account,OU=ServiceAccounts,DC=domain,DC=company,DC=org"
      tower_username: admin
      tower_password: password
      tower_host: https://awx.domain.company.org/
      tower_verify_ssl: false
```
3. Execute the Playbook

##### EXPECTED RESULTS

The task completes successfully (shown here using old Tower-CLI module)
```JSON
changed: [localhost] => {
    "changed": true,
    "id": "AUTH_LDAP_BIND_DN",
    "invocation": {
        "module_args": {
            "name": "AUTH_LDAP_BIND_DN",
            "value": "CN=service_account,OU=ServiceAccounts,DC=domain,DC=company,DC=org"
        }
    },
    "value": "CN=service_account,OU=ServiceAccounts,DC=domain,DC=company,DC=org"
}
```

##### ACTUAL RESULTS

New `tower_settings` module in AWX collection will always fail if there is a comma in the `value` field. This is unacceptable for LDAP settings such as AUTH_LDAP_BIND_DN, which require commas to denote the path to an Active Directory object.

```JSON
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/7f/cd1nvl050nd5zpjjtk_407_8xsjm6q/T/ansible_tower_settings_payload_2eardS/ansible_tower_settings_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_settings.py", line 111, in main
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "AUTH_LDAP_BIND_DN",
            "settings": null,
            "tower_config_file": null,
            "tower_host": "https://awx.domain.company.org/",
            "tower_oauthtoken": null,
            "tower_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tower_username": "admin",
            "tower_verify_ssl": false,
            "validate_certs": false,
            "value": "CN=service_account,OU=ServiceAccounts,DC=domain,DC=company,DC=org"
        }
    },
    "msg": "Unable to update settings, see response",
    "response": {
        "json": {
            "AUTH_LDAP_BIND_DN": [
                "Not a valid string."
            ]
        },
        "status_code": 400
    }
}
```

##### ADDITIONAL INFORMATION

If you don't include a comma in the `value` field, the operation completes successfully.

```JSON
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "name": "AUTH_LDAP_BIND_DN",
            "settings": null,
            "tower_config_file": null,
            "tower_host": "https://awx.domain.company.org/",
            "tower_oauthtoken": null,
            "tower_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tower_username": "admin",
            "tower_verify_ssl": false,
            "validate_certs": false,
            "value": "CN=service_account"
        }
    },
    "old_values": {
        "AUTH_LDAP_BIND_DN": ""
    },
    "value": "CN=service_account"
}
```

**Comment by kedark3** [comment]
Interesting, I do not see the same issue. I haven't switched to Collections yet. But I am able to setup LDAP using tower_settings module just fine.

**Comment by RylandDeGregory** [comment]
> Interesting, I do not see the same issue. I haven't switched to Collections yet. But I am able to setup LDAP using tower_settings module just fine.

It works fine using the built-in modules. I can configure every LDAP setting properly with them. The issue is the Collection.

**Comment by AlanCoding** [comment]
Could you test this workaround and report back

```yaml
  - name: Set LDAP Bind DN
    tower_settings:
      settings:
        AUTH_LDAP_BIND_DN: "CN=service_account,OU=ServiceAccounts,DC=domain,DC=company,DC=org"
```

thanks!
