### ISSUE TITLE
Cannot create user with tower_user from AWX collection

### ISSUE THREAD

**Issue by mooky31** [ansible/awx#6437]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Cannot create user with tower_user from AWX collection

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Debian Buster
* Web Browser: Firefox

##### STEPS TO REPRODUCE

```
root@TWIN-SV-BSDANS01:~/ansible# cat play-testAPI.yml
---
- name: Configure host for ansible/AWX
  hosts: localhost
  collections:
    - awx.awx

  tasks:
    - name: Users AWX
      tower_user:
        username: test
        first_name: FirstName
        last_name: LastName
        email: email@example.com
        password: changeme
```

##### EXPECTED RESULTS

User created

##### ACTUAL RESULTS
```

TASK [Users AWX] **********************************************************************************************************************************************************
[WARNING]: Module did not set no_log for password
[WARNING]: Failed to release tower token 3: HTTP Error 400: Bad Request
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an unknown error when trying to connect to http://localhost:8080/api/v2/users/?username=test: TypeErrorsendall() argument 1 must be string or buffer, not dict"}
```

##### ADDITIONAL INFORMATION
Dump of faulty transaction :
```
16:58:52.038188 IP 127.0.0.1.52340 > 127.0.0.1.8080: Flags [P.], seq 1:210, ack 1, win 512, options [nop,nop,TS val 3270014390 ecr 3270014390], length 209: HTTP: DELETE /api/v2/tokens/4/?username=test HTTP/1.1
E...._@.@............t..K7K&\.gT...........
..u...u.DELETE /api/v2/tokens/4/?username=test HTTP/1.1
Accept-Encoding: identity
Host: localhost:8080
Connection: close
Authorization: Basic YWRtaW46bUJXZ0JBb3QyVE16UklUbVEzWEE=
User-Agent: Python-urllib/2.7
16:58:52.183425 IP 127.0.0.1.8080 > 127.0.0.1.52340: Flags [P.], seq 1:391, ack 210, win 512, options [nop,nop,TS val 3270014536 ecr 3270014390], length 390: HTTP: HTTP/1.1 400 Bad Request
E.....@.@..&...........t\.gTK7K............
..vH..u.HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 26 Mar 2020 15:58:52 GMT
Content-Type: application/json
Content-Length: 60
Connection: close
Vary: Accept, Accept-Language, Origin, Cookie
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
X-API-Node: awx
X-API-Time: 0.117s
Content-Language: en
X-API-Total-Time: 0.143s

{"detail":"OAuth2AccessToken has no field named 'username'"}
```

**Comment by AlanCoding** [comment]
How did you configure authentication to the server? Environment variables (like `TOWER_HOST`, etc.), or the tower_cli.cfg file? And did this auth use token or username/password?

**Comment by mooky31** [comment]
I use tower_cli.cfg with user/pass :

```
root@TWIN-SV-BSDANS01:~# cat .tower_cli.cfg
[general]
host = http://localhost:8080
username = admin
password = password
use_token = false
```

**Comment by mooky31** [comment]
I also tried with this playbook:
```
root@TWIN-SV-BSDANS01:~/ansible# cat play-testAPI.yml
---
- name: Configure host for ansible/AWX
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx

  tasks:
    - name: Users AWX
      tower_user:
        username: test
        first_name: FirstName
        last_name: LastName
        email: email@example.com
        password: changeme
        tower_host: http://localhost:8080
        tower_username: admin
        tower_password: password
```

Same error

**Comment by mooky31** [comment]
Interesting fact: 
I have AWX listening on localhost:8080. It is accessed remotely through a NGINX reverse proxy on port 443 (which also does the SSL part). Ports look like this (port 80 is for gitweb):
```
root@TWIN-SV-BSDANS01:~/ansible# netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1001/nginx: worker
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      26701/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      548/sshd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1001/nginx: worker
tcp6       0      0 :::22                   :::*                    LISTEN      548/sshd
```


This playbook works:
```
root@TWIN-SV-BSDANS01:~/ansible# cat play-testAPI.yml
---
- name: Configure host for ansible/AWX
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx

  tasks:
    - name: Users AWX
      tower_user:
        username: test
        first_name: FirstName
        last_name: LastName
        email: email@example.com
        password: changeme
        #tower_host: http://localhost:8080
        tower_host: https://localhost
        tower_username: admin
        tower_password: password
        validate_certs: False
```
