### ISSUE TITLE
tower_workflow_template does not respect tower workflow survey_spec

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#6483]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the tower_workflow_template module passing the survey_spec does not get correctly used. 

##### ENVIRONMENT
* AWX version: 3.6.2
* AWX install method: setup_bundle tar ball deploying on a RHEL VM 
* Ansible version:  2.9.6
* Operating System: RHEL
* Web Browser: not relevant

##### STEPS TO REPRODUCE
```
name: Test workflow 1
    description: created by Ansible Playbook
    organization: Satellite
    survey_enabled: false
    allow_simultaneous: no
    schema:
      - job_template: Demo Job Template
    survey_spec:
      name: ''
      description: ''
      spec:
      - question_name: Test-survey
        question_description: ''
        required: true
        type: text
        variable: Test
        min: 0
        max: 1024
        default: ''
        choices: ''
        new_question: true
    survey_enabled: true

```

##### EXPECTED RESULTS

Survey is added to workflow

##### ACTUAL RESULTS
Survey not being added to the workflow even though ansible playbook execution output shows "Changed"

##### ADDITIONAL INFORMATION

Using collections awx.awx version 9.3.0 as well as `tower_workflow_template.py` from the devel.
