### ISSUE TITLE
AWX collection v10.0.0: tower_* modules lack consistent auth parameters

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/awx#6552]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some modules have a `tower_oauthtoken` parameter, and others don't, within the same version of the collection.

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: MacOS Catalina 10.15.3
* Web Browser: Google Chrome 80.0.3987.149 (Official Build) (64-bit)

##### STEPS TO REPRODUCE

Install the latest version of the collection from Ansible Galaxy

```Shell
ansible-galaxy collection install awx.awx:10.0.0 --force-with-deps
```

Execute the following module, `tower_project`

```YAML
---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
   - name: Ensure Project exists
      tower_project:
        name: "{{ branch.split('/')[-1] | default(branch) }}"
        organization: myOrg
        scm_branch: "{{ branch | default(master) }}"
        scm_update_on_launch: yes
        scm_type: git
        scm_url: https://github.com/ansible/awx.git
        state: present
        tower_host: https://towerserver.company.org/
        tower_oauthtoken: "ABCDEFGHIKL1234567"
        tower_verify_ssl: false
```

Then execute the following module, `tower_job_template`

```YAML
---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  tasks:
  - name: Ensure Template exists
     tower_job_template:
      name: A Job Template
      description: My test Job Template
      job_type: run
      inventory: localhost
      project: master
      playbook: myPlaybook.yml
      state: present
      tower_host: https://towerserver.company.org/
      tower_oauthtoken: "ABCDEFGHIKL1234567"
      tower_verify_ssl: false
      survey_enabled: no
```

##### EXPECTED RESULTS

tower_project

```Text
ok: [localhost]
```

tower_job_template

```Text
ok: [localhost]
```

##### ACTUAL RESULTS

tower_project

```Text
ok: [localhost]
```

tower_job_template

```Text
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (tower_job_template) module: tower_oauthtoken Supported parameters include: ask_credential, ask_diff_mode, ask_extra_vars, ask_inventory, ask_job_type, ask_limit, ask_skip_tags, ask_tags, ask_verbosity, become_enabled, concurrent_jobs_enabled, credential, credentials, custom_virtualenv, description, diff_mode_enabled, extra_vars, extra_vars_path, fact_caching_enabled, force_handlers_enabled, forks, host_config_key, inventory, job_tags, job_type, limit, name, playbook, project, skip_tags, start_at_task, state, survey_enabled, survey_spec, timeout, tower_config_file, tower_host, tower_password, tower_username, validate_certs, vault_credential, verbosity"}
```

##### ADDITIONAL INFORMATION

I haven't gone through testing which of the `tower_*` modules are affected, but if it's one, it's likely multiple.
