### ISSUE TITLE
The tower_workflow_job_template module inventory option does not work

### ISSUE THREAD

**Issue by akira6592** [ansible/awx#6586]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The tower_workflow_job_template module inventory option does not work.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.6
* Operating System: macOS
* Web Browser: Chrome 80

##### STEPS TO REPRODUCE

task
```yaml
    - name: create workflow templates
      awx.awx.tower_workflow_job_template:
        tower_host: "https://{{ ansible_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: no
        name: wfjt01
        inventory: test_inventory   # existing inventory
```

`test_inventory` exists, as shown below.
```json
GET /api/v2/inventories/

{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
        (omit)
            "name": "test_inventory",
            "description": "",
            "organization": 5,
        (omit)
        }
    ]
}
```

##### EXPECTED RESULTS

```
TASK [create workflow templates] *************************************************************************************
changed: [awx1]
```

##### ACTUAL RESULTS

```
TASK [create workflow templates] *************************************************************************************
[WARNING]: Failed to release tower token 1289: HTTP Error 400: Bad Request
fatal: [awx1]: FAILED! => {"changed": false, "msg": "The requested object could not be found at /api/v2/inventory/."}
```

##### ADDITIONAL INFORMATION

The first argument of `resolve_name_to_id` seems to be `inventories`, not `inventory`.
So it looks like can not find inventory ID by name.

https://github.com/ansible/awx/blob/077461a3ef99390dbfcec2d1f2e5490caf35e232/awx_collection/plugins/modules/tower_workflow_job_template.py#L195
