### ISSUE TITLE
Machine credentials are refused by tower_job_template

### ISSUE THREAD

**Issue by mooky31** [ansible/awx#6653]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Can't create job template with tower_job_template because of credentials.
Machine credentials (SSH) are refused.

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.5
* Operating System: Debian Buster
* Web Browser: Firefox
* AWX collection: 10.0.0

##### STEPS TO REPRODUCE
```
    - name: Creation templates
      tower_job_template:
        name: "{{ item.name }}"
        playbook: "{{ item.playbook }}"
        inventory: "{{ awx_inventory }}"
        project: "{{ awx_inventory }}"
        credentials:
          - "ssh-root-key"
        survey_enabled: yes
        survey_spec:
          name: "survey {{ item.name }}"
          description: ""
          spec: "{{ item.survey_spec }}"
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: False
      with_items: "{{ awx_job_templates }}"
      loop_control:
        label: "{{ item.name }}"
      tags: templates
```

##### EXPECTED RESULTS

Template created

##### ACTUAL RESULTS
```
{

    "ansible_loop_var":"item",
    "changed":false,
    "item":{
        "job_type":"run",
        "name":"Provisionning TWIN",
        "playbook":"play-provisioning_twin.yml",
    },
    "msg":"Failed to add credential to job template: The Tower server claims it was sent a bad request.\n\nPOST https://localhost/api/v2/job_templates/9/extra_credentials/\nParams: None\nData: {\"id\": 3, \"associate\": true}\n\nResponse: {\"error\":\"Extra credentials must be network or cloud.\"}"

}
```

##### ADDITIONAL INFORMATION

`credential: "ssh-root-key"` kinda works, but according to the documentation it is deprecated.
And when I go into the web interface, the credentials field is empty.
