### ISSUE TITLE
Use awx docker-compose on another server

### ISSUE THREAD

**Issue by sinahamedheidari** [ansible/awx#6674]
I created an AWX instance in docker. The docker-compose.yml file and all other necessary files are stored in ```/tmp/awxcompose/``` and database files are stored in ```/tmp/pgdocker/10/data/```. If I do docker-compose up and down on my local machine everything is fine. But if I copy the ```/tmp/awxcompose/``` and change the volume for postgres, I get the database related errors! absent relations and so on.
```
postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
            #- /tmp/pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
      - ./volume/pgdocker/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy:
      https_proxy:
      no_proxy:
```
But If i copy the content of ```/tmp/pgdocker/10/data/``` to the new volume, everything gets fine! I thing the awxweb or awxtask does not create the database schema if the postgres volume is empty! Am I right?
