### ISSUE TITLE
The tower_project module scm_allow_override option does not work

### ISSUE THREAD

**Issue by akira6592** [ansible/awx#6748]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The tower_project module scm_allow_override option does not work.

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker for mac
* Ansible version:  2.9.6
* Operating System: macOS
* Web Browser: Chrome 80

##### STEPS TO REPRODUCE

task
```yaml
    - name: create projects
      awx.awx.tower_project:
        tower_host: "http://{{ ansible_host }}"
        tower_username: "{{ conn.tower_username }}"
        tower_password: "{{ conn.tower_password }}"
        validate_certs: no
        name: test_project
        organization: test_org
        scm_type: git
        scm_url: https://github.com/akira6592/tower-sample-nw.git
        scm_branch: master
        scm_allow_override: true    # here
```

```
ansible-playbook -i inventory.ini create_pj.yml
```

##### EXPECTED RESULTS

```
TASK [create projects] 
changed: [awx1]
```

![image](https://user-images.githubusercontent.com/16851744/79631877-cd707c00-8196-11ea-9024-62e529d9804d.png)

##### ACTUAL RESULTS

```
TASK [create projects] *********************************************************************************************
[WARNING]: The field scm_allow_override of project 18 has encrypted data and may inaccurately report task is changed
changed: [awx1]
```
![image](https://user-images.githubusercontent.com/16851744/79631872-c3e71400-8196-11ea-9aa1-5a7998ab3d4d.png)

##### ADDITIONAL INFORMATION

The API specification corresponding to `scm_allow_override` option is `allow_override`, not `scm_allow_override`.

But in `tower_project` module, it's set to `scm_allow_override`.

https://github.com/ansible/awx/blob/b90a296d4196ccccf99a1ba9bfb00ee9de796edb/awx_collection/plugins/modules/tower_project.py#L257
