### ISSUE TITLE
[RFE] A method to bubble set_stats up to parent workflows/jobs

### ISSUE THREAD

**Issue by JacobCallahan** [ansible/awx#6806]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Ansible Tower API RFE

Background:
Our team uses nested workflows. Each of which passes down information from 
the other using set_stats. At the end of the execution flows, the information 
is accumulated and formatted in our desired format. Our usage of Ansible Tower API is almost entirely for identifying and executing workflows.
This is expected to be at a high level, with most workflows having nested 
workflows and/or templates.

Problem:
With the current implementation of AT's API, set_stats can only flow down.
This means that, after the entire flow has finished executing, we need to 
find the last job that ran and pull the stats from it.

Desired Solution:
Implement a way to flow information back up to parent jobs and workflows. 
This way an API user can kick off a workflow or job execution and get all 
generated information from it once all child processes have completed.

Possible implementation:

Because workflows in general have arbitrary number of leaf nodes and we can not anticipate what will be the leaf nodes (for example,  some paths may not be taken depending on what happens at run time),  and it would be impossible to guess the preference of how to merge the different sets of artifacts and with what preference, as a first approach we propose setting the artifacts set by a job of a workflow node on the workflow node itself.

E.g. if a child job of a workflow job node has the `artifacts` property, set that on the workflow node.

As a second step, on the workflow, if workflow nodes in the workflow have the `artifacts` property set, save this on the workflow job itself in the form of a dictionary, where the key is some identifier for the workflow node, and the value is the artifacts set on that workflow node.

One possible configuration option would be to set the behavior for merging multiple branches. Options could include:

- Overwrite with latest (whatever is the last to run overwrites previous values)
- Branch (split each branch into a new key on the returned dictionary)
- Minimal branch (only branch if there is a conflict)

Possible example:
```yaml
{
    "id": 20,
    "type": "workflow_job",
    "url": "/api/v2/workflow_jobs/20/",
    "related": {
        "created_by": "/api/v2/users/1/",
        "modified_by": "/api/v2/users/1/",
        "unified_job_template": "/api/v2/workflow_job_templates/7/",
        "workflow_job_template": "/api/v2/workflow_job_templates/7/",
        "notifications": "/api/v2/workflow_jobs/20/notifications/",
        "workflow_nodes": "/api/v2/workflow_jobs/20/workflow_nodes/",
        "labels": "/api/v2/workflow_jobs/20/labels/",
        "activity_stream": "/api/v2/workflow_jobs/20/activity_stream/",
        "relaunch": "/api/v2/workflow_jobs/20/relaunch/",
        "cancel": "/api/v2/workflow_jobs/20/cancel/"
    },
    "summary_fields": {
        "workflow_job_template": {
            "id": 7,
            "name": "baz",
            "description": ""
        },
        "unified_job_template": {
            "id": 7,
            "name": "baz",
            "description": "",
            "unified_job_type": "workflow_job"
        },
        "created_by": {
            "id": 1,
            "username": "foobar",
            "first_name": "",
            "last_name": ""
        },
        "modified_by": {
            "id": 1,
            "username": "foobar",
            "first_name": "",
            "last_name": ""
        },
        "user_capabilities": {
            "delete": true,
            "start": true
        },
        "labels": {
            "count": 0,
            "results": []
        }
        "artifacts": { <SOME KEY THAT LETS ME KNOW WHAT NODE IT CAME FROM>: {"string": "abc",
                          "integer": 123,
                          "float": 1.0,
                          "unicode": "竳䙭韽",
                          "boolean": true,
                          "none": null},
                       <SOME KEY THAT LETS ME KNOW WHAT NODE IT CAME FROM>: {"string": "abc",
                          "integer": 123,
                          "float": 1.0,
                          "unicode": "竳䙭韽",
                          "boolean": true,
                          "none": null},
                     }
    },
    "created": "2020-04-22T16:11:49.120399Z",
    "modified": "2020-04-22T16:11:49.633559Z",
    "name": "grandma",
    "description": "",
    "unified_job_template": 7,
    "launch_type": "manual",
    "status": "running",
    "failed": false,
    "started": "2020-04-22T16:11:49.623267Z",
    "finished": null,
    "canceled_on": null,
    "elapsed": 11.223614,
    "job_args": "",
    "job_cwd": "",
    "job_env": {},
    "job_explanation": "",
    "result_traceback": "",
    "workflow_job_template": 7,
    "extra_vars": "{}",
    "allow_simultaneous": false,
    "job_template": null,
    "is_sliced_job": false,
    "inventory": null,
    "limit": null,
    "scm_branch": null,
    "webhook_service": "",
    "webhook_credential": null,
    "webhook_guid": ""
}
```
