### ISSUE TITLE
if awx_server != localhost in local_docker role, db upgrade fails ( not adjusted for non_local )

### ISSUE THREAD

**Issue by i4o** [ansible/awx#6813]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Installer suggest to update awx_server from localhost to remote server, if you want to install to remote server. This is how I installed previous ( 7 ) version of AWX.
Now when Upgrading to 10+ it wants to upgrade postgres db.

Problem is, file lookup and db upgrade tasks are looking for **local** files, even if you change inventory to be non-local. 

##### ENVIRONMENT
* AWX version: latest github repo
* AWX install method: docker on linux, role local_docker
* Ansible version:  2.9.6
* Operating System: Ubuntu 18.04 
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Change `awx_server` to external server, not localhost

##### EXPECTED RESULTS

It will fail in lookup for old postgres version ( searching locally, not remotely ). 
And continue to fail if you just manually set variable:

```
- name: Determine whether to upgrade postgres
  set_fact:
    upgrade_postgres: yes
```

because it's still working on local directories during db migration, not remote directories.

**Comment by i4o** [comment]
```
- name: Copy old pg_hba.conf
  copy:
    src: "{{ postgres_data_dir + '/pgdata/pg_hba.conf' }}"
    dest: "{{ postgres_data_dir + '/10/data/' }}"
    remote_src: yes <<< needed if not localhost
  when: upgrade_postgres | bool
```
