### ISSUE TITLE
awx.awx.tower_job_template fails when project does not exist on tower

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#6819]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx.awx.tower_job_template fails when project does not exist on tower.  I am using `state: absent` so in my opinion I should not even have to specify the project or other parameters... I should be able to just delete the job template by name with `state: absent`

##### ENVIRONMENT
* <  Tower 3.6.3  >
* RHEL 8.1 AWS instance 
* Ansible version:  2.9.5
* Operating System:RHEL 8.1
* Web Browser: N/A

##### STEPS TO REPRODUCE

Ansible Playbook like this->

```
---
- hosts: localhost
  gather_facts: false
  vars:
    admin_password: ansible1234
    tower_host: "{{ansible_host}}"
  tasks:



  - name: delete demo job template
    awx.awx.tower_job_template:
      name: "Demo Job Template"
      job_type: "run"
      project: "Demo Project"
      playbook: "hello_world.yml"
      state: absent
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
```
##### EXPECTED RESULTS

pass, with changed: 0 because it is not there

##### ACTUAL RESULTS

```
TASK [delete demo job template] **************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: The projects Demo Project was not found on the Tower server
```

##### ADDITIONAL INFORMATION

Red Hat employee, this is for ansible automation workshops

**Comment by AlanCoding** [comment]
I think this should have a short-term specific solution, and a long-term general solution.

For the general solution, I can see it becoming a part of https://github.com/ansible/awx/pull/6430. The related objects should not even be obtained if state=absent, unless it's one of the identity objects.

Since the project is not used to _look up_ the job template, we should do a GET for that project when deleting the job template. If the `organization` is provided, and we use this to look up an object (like inventory), then failing to get that _may_ justify a module failure.

**Comment by john-westcott-iv** [comment]
@AlanCoding 100% agree with the long term.
@IPvSean can you see what happens if you just do:
```
  - name: delete demo job template
    awx.awx.tower_job_template:
      name: "Demo Job Template"
      state: absent
      tower_username: admin
      tower_password: "{{ admin_password }}"
      tower_host: "{{ ansible_host }}"
      tower_verify_ssl: false
```
If the project is not specified it should not attempt to look it up.
