### ISSUE TITLE
Keystone v3 support for OpenStack Credential

### ISSUE THREAD

**Issue by lewisface** [ansible/awx#6831]
##### ISSUE TYPE
 - Enhancement 

##### SUMMARY
Keystone v3 requires project_domain_name to authenticate, but AWX openstack credential doesn't provide / request those in the credential templating.

Currently when the cloud.yml file is generated it is populated with:

```
clouds:
  devstack:
    auth:
      auth_url: 
      domain_name: 
      password:
      project_name:
      username:
```

Instead for v3 this should include "project_domain_name"

```
clouds:
  devstack:
    auth:
      auth_url: 
      domain_name:
      password:
      project_domain_name: 
      project_name:
      username: 
```
