### ISSUE TITLE
awx_task python3 interpreter not discovered with delegate_to: localhost

### ISSUE THREAD

**Issue by vin-c** [ansible/awx#6835]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx_task python3 interpreter not discovered with delegate_to: localhost

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.5
* Operating System: debian/stretch

##### STEPS TO REPRODUCE

We've got a task like that
```
    - name: Plop
      uri:
        url: http://{{ somehost }}/and/some/path
        method: POST
        return_content: yes
        body:
          some: "{{ and }}"
          keys: "{{ values }}"
        body_format: json
      become: no
      delegate_to: localhost
```

##### EXPECTED RESULTS

Regarding this information : https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html

I would expect that the python3 interpreter of the container awx_task would be found

##### ACTUAL RESULTS

```
fatal: [myhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

##### ADDITIONAL INFORMATION
Will try a workaround adding some logic like that
```
(...)
      delegate_to: localhost
      vars:
        ansible_python_interpreter: /usr/bin/python3
```
