### ISSUE TITLE
reuse of local built images

### ISSUE THREAD

**Issue by vin-c** [ansible/awx#6890]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
We deploy awx via ansible here and run the installer each time to adapt it to our needs.

When using the official images, the installer reuse the images downloaded earlier and the process is somehow fast.
But when we need to build images, the process always rebuilt images.

It could be good to have an option to reuse the built images if any.

We made a local hack to be able to do so but.. it's a hack:
```
    - name: Customize role/tasks to use local images (hack)
      blockinfile:
        path: "{{ awx_build_dir }}/awx/installer/roles/local_docker/tasks/main.yml"
        insertafter: "- import_tasks: set_image.yml"
        block: |
          - name: Set Local Image Paths
            set_fact:
              awx_web_docker_actual_image: awx_web:latest
              awx_task_docker_actual_image: awx_task:latest
      when: awx_build_local_image and not awx_upgrade_needed
```
Feel free to add your thought about it, I'm already thinking of a "good way" to do it...

Regards,
