### ISSUE TITLE
Dynamic Inventory of hosts from OpenStack: ansible_ssh_host is private IP and not floating

### ISSUE THREAD

**Issue by mareckis** [ansible/awx#6892]
##### ISSUE TYPE
 - Documentation
##### COMPONENT NAME
 - API
##### SUMMARY
Hi,
I'm during the synchronization of OpenStack and AWX. I made a dynamic inventory of hosts that are deployed on my OpenStack cloud using the appriopriate credentials. The hosts are detected correctly, and doing job templates manually works, but I will be in need of making an API callbacks and SSH using floating ips of the virtual machines. So, right now I can see in AWX, in the host variables that these parameters are the private-networks IPs:
ansible_host: 192.168.100.11
ansible_ssh_host: 192.168.100.11
I can see that both IPs are discovered:
addresses:
    private:
      - 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:19:9f:fb'
        'OS-EXT-IPS:type': fixed
        addr: 192.168.100.11
        version: 4
      - 'OS-EXT-IPS-MAC:mac_addr': 'fa:16:3e:19:9f:fb'
        'OS-EXT-IPS:type': floating
        addr: 10.0.0.147
        version: 4

For this inventory job I use the venv: /var/lib/awx/venv/ansible
I can't find out in the docs, how I can change the script to take the floating IPs from an inventory as an assible_ssh_host parameter.. In this case 10.0.0.147

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker
* Ansible version:  2.9.5
* Operating System: CentOS7

##### EXPECTED RESULTS

ansible_ssh_host: 10.0.0.147 <-- floating ip from OpenStack

##### ACTUAL RESULTS

ansible_ssh_host: 192.168.100.11 <-- right now i collect private ip from OpenStack

**Comment by ryanpetrello** [comment]
@mareckis,

Any chance you could give this a shot on the latest version of AWX, 11.2.0?

We recently merged in a change that moves us to the _newer_ openstack collection (https://galaxy.ansible.com/openstack/cloud) for inventory syncs, and I'm wondering if there's a change there that might address what you're seeing.

@emonty you have any pointers here that might help?  I'm not super familiar with how this inventory plugin is configured.

**Comment by emonty** [comment]
The inventory plugin should be using server.interface_ip for the ansible_ssh_host setting unless private: true has been specified. Can you tell me the values of public_v4, private_v4 and interface_ip on the server record?

**Comment by ryanpetrello** [comment]
https://github.com/ansible/awx/blob/devel/awx/main/models/inventory.py#L2406

@mareckis 

Have you tried specifying `private: false` in the inventory source definition?

<img width="414" alt="image" src="https://user-images.githubusercontent.com/214912/80739649-cf1a3800-8ae4-11ea-898b-3795ecc9e6f5.png">

```yaml
bash-4.4$ cat /tmp/awx_638_5gygj0xf/tmp6rl5wtxs
clouds:
  devstack:
    auth:
      auth_url: http://example.org
      domain_name: Domain Name!
      password: password
      project_domain_name: Project Domain Name!
      project_name: Tenant!
      username: user
    private: false
    verify: true
```
