### ISSUE TITLE
Assert Evaluating False, Should be True

### ISSUE THREAD

**Issue by bandwiches** [ansible/awx#6970]
##### ISSUE TYPE
 - Assert module evaluating incorrectly.

##### SUMMARY

```yaml
---
  - hosts: REMOVED
    gather_facts: no
    tasks:
      - name: Run show version
        ios_command:
          commands:
            - show version
        register: showversion
      - name: Debug show version
        debug:
          var: showversion.stdout
          verbosity: 0
      - name: Check for 3560
        assert:
          that:
            - "'C3560E' in showversion.stdout"
          success_msg: "This is a 3560."
          fail_msg: "{{ showversion.stdout }}"
```

##### ENVIRONMENT
* AWX version: 10.0.0
* AWX install method: docker
* Ansible version:  2.9
* Operating System: Ubuntu/Docker
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Register variable
2. Use assert module
3. See error

##### EXPECTED RESULTS

Expected the assert module to evaluate to true.

##### ACTUAL RESULTS

Assert module evaluated to false.

##### ADDITIONAL INFORMATION

Including image of the failed module.  You can see the variable clearly has the text within it but the module is still evaluating false.  I have actually printed the showversion.stdout inside the failed message of the module to show that the text is there.

![image](https://user-images.githubusercontent.com/16140382/81414990-6d258800-910d-11ea-8880-88f9f293ab7e.png)
