### ISSUE TITLE
awx.awx.tower_host trouble use from NOT awx server (where pyyaml not installed)

### ISSUE THREAD

**Issue by dolgovas** [ansible/awx#6983]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

awx.awx collection does not work correctly
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: macos
* Web Browser: Firefox

##### STEPS TO REPRODUCE

add hosts via playbook through awx.awx.tower_host
tower_cli config
```
cat ~/tower_cli.cfg
[general]
host = https://awx.local.lan
verify_ssl = false
oauth_token = OBaCofjahsdlfkjhalsdjfELUHomaCxRWfnNM
```
inventory
```
ansible -m debug -a 'var=ansible_host' awx
awx-docker1 | SUCCESS => {
    "ansible_host": "192.168.10.10"
}
```
playbook adding hosts
```
---
- name: Playbook for Using a Variety of Tower Modules
  hosts: awx
  gather_facts: false
  become: false
  collections:
    - awx.awx

  tasks:
  - name: Create a Host
    tower_host:
      name: "New Host"
      inventory: "New inventory"
      state: present
      variables:
         ansible_host: 10.10.10.10
```
##### EXPECTED RESULTS
add host into awx

##### ACTUAL RESULTS
```
ansible-playbook awx_add_hosts.yml
PLAY [Playbook for Using a Variety of Tower Modules] ****************************************************************************************************************************************

TASK [Create a Host] ************************************************************************************************************************************************************************
Monday 11 May 2020  10:38:32 +0300 (0:00:00.235)       0:00:00.235 ************
[WARNING]: Failed to release tower token None: hostname '127.0.0.1' doesn't match either of 'local.lan', '*.local.lan'
fatal: [awx-docker1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false
}

MSG:

There was an unknown error when trying to connect to https://127.0.0.1/api/v2/inventories/?name=New+inventory: CertificateError hostname '127.0.0.1' doesn't match either of 'local.lan', '*.local.lan'
	to retry, use: --limit @.ansible-retry/awx_add_hosts.retry

PLAY RECAP **********************************************************************************************************************************************************************************
awx-docker1                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Monday 11 May 2020  10:38:34 +0300 (0:00:01.298)       0:00:01.534 ************
===============================================================================
Create a Host ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 1.30s
```

**Comment by AlanCoding** [comment]
> hosts: awx

When you ran the command `cat ~/tower_cli.cfg`, where did you run that? From your own machine, or from the "awx" server?

From the looks of what you're doing, maybe the task should be `delegate_to: localhost`. That makes sense if your networking allows your computer access to the server via the normal ports for the API and UI to work.

The config is read from wherever the task is ran. It looks like, since the task ran on the server, there was no config file and it fell back to default values.

Environment vars (set in `ansible-playbook` context) & config file don't work to specify auth parameters if not ran from localhost. I'm all for improving the docs on this, but it needs to be said that it's a problem shared with other cloud modules, and is very often confusing. I'd like to see some examples of it done right.

**Comment by dolgovas** [comment]
>When you ran the command cat ~/tower_cli.cfg, where did you run that? From your own machine, or from the "awx" server?

from my own machine, which has tcp access to awx server

some later i'll try play this things again with `local_action`

**Comment by dolgovas** [comment]
> some later i'll try play this things again with `local_action`

file on my machine
```
cat ~/tower_cli.cfg
[general]
host = https://awx.local.lan
verify_ssl = false
oauth_token = OBaCofMWWfnNM
```
playbook
```
---
- name: Playbook for Using a Variety of Tower Modules
  hosts: localhost
  gather_facts: false
  become: false
  collections:
    - awx.awx

  tasks:
  - name: Create a Host
    tower_host:
      name: "New Host"
      inventory: "New inventory"
      state: present
      variables:
         ansible_host: 10.10.10.10
```
result
```
PLAY [Playbook for Using a Variety of Tower Modules] ****************************************************************************************************************************************

TASK [Create a Host] ************************************************************************************************************************************************************************
Monday 11 May 2020  16:20:45 +0300 (0:00:00.232)       0:00:00.232 ************
[WARNING]: Failed to release tower token None: <urlopen error [Errno 61] Connection refused>
[WARNING]: Platform darwin on host localhost is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false
}

MSG:

There was an unknown error when trying to connect to https://127.0.0.1/api/v2/inventories/?name=New+inventory: URLError <urlopen error [Errno 61] Connection refused>
	to retry, use: --limit @.ansible-retry/test.awx.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Monday 11 May 2020  16:20:46 +0300 (0:00:00.402)       0:00:00.634 ************
===============================================================================
Create a Host ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.40s
```
