### ISSUE TITLE
awx collection tower_group: append to existing host list

### ISSUE THREAD

**Issue by fxmick** [ansible/awx#7010]
**SUMMARY**
When using hosts parameter to add hosts to a group, all existing hosts are deleted.

**ISSUE TYPE**
Enhancement

**COMPONENT NAME**
tower_group

**ADDITIONAL INFORMATION**
Add an overwrite parameter to prevent deletion of existing hosts.

**Comment by ryanpetrello** [comment]
@AlanCoding is this always how the old module worked, or is this a regression in the new collection?

**Comment by AlanCoding** [comment]
the old module never supported group hosts at all. This is all new territory. We need to take our time and carefully discuss any implications of the interface design. My initial feeling is that we should allow "magic" words in the list like:

```yaml
tower_group:
  name: foo
  hosts:
    - "<existing>"
    - hostB
```

That would still be idempotent, so I'm not against the general concept.

This would incur a some validation burden, but I would prefer it to new parameters. The number of modules & parameters is too high, it's difficult to manage.

**Comment by fxmick** [comment]
This "magic" word trick would be great !
I currently managed this with a mix of api calls to get the the current list of hosts and add new one(s) with the collection.

**Comment by john-westcott-iv** [comment]
Will this "existing" pattern apply to all parameters that accept multiple things? i.e. `extra vars` in job_templates, notification fields, labels, etc. (I'd like to think yes)

From an implementation perspective it might be easier to have a a flag like `keep_existing_hosts: True` otherwise we will have to modify any resolution loops which are attempting to lookup IDs by name to handle the case of our keyword.

**Comment by AlanCoding** [comment]
> i.e. `extra vars` in job_templates, notification fields, labels, etc. (I'd like to think yes)

There are many problems with dict-like fields. The API inconsistently accepts YAML strings, JSON strings, or dict objects. Right now the collection only has to worry about the type that it _gives to_ the API, and if you added logic to combine with existing, then you would have to worry about the type that the API _gives back_.

> otherwise we will have to modify any resolution loops which are attempting to lookup IDs by name to handle the case of our keyword.

Not every string is a valid hostname, see #3384. Provided that the keyword has at least 1 character that would make it unusable as an _actual_ Ansible hostname, conflicts should not be a reasonable concern for this particular case.

However, I see this as being implemented generally for all many-to-many relationships, so it may be a valid concern in other cases. I still think the benefits outweigh the risks.

**Comment by planeturban** [comment]
Wouldn't another state be an approach?  `state: update` or something like that? Since it could (should?) be used in other modules (I'm looking at you `tower_host`.)?

**Comment by planeturban** [comment]
Come to think about it.. `state: present` wiping everything else is kinda.. dumb.. Compare with `lineinfile` setting a line as present does not clear the everything in the file. 

So it ought to be the other way around: use `state: absent` to clear your the unwanted hosts (or extra_vars). And/Or a parameter `wipe: yes` (`no` default) to clear whatever one is working with at the moment (as @john-westcott-iv suggested, but for any and all tower elements).

**Comment by AlanCoding** [comment]
By that logic, we should merge, and not write, dict fields (of which there are many). You could go even further, dict-type fields that have sub-dicts and sub-lists shouldn't overwrite, but merge. It's not impossible to do this, but to document it and implement it consistently in all cases would be more effort than we could manage.

**Comment by planeturban** [comment]
There are, in my eyes, a few solutions..

1. Leave as is and document how to write a playbook that stores all hosts in a variable and then adds the new one(s). **bad**
2. Go all in and support any and all variations for `present`, `absent` plus `keep_existing`. **worse**
3. Add support for updating top level of dicts/lists only. **less bad**
4. Add support for updating to the most commonly used modules. _group, _host amongst others. **bad**


Full disclosure: I'm not at all familiar with the sub-dicts and others that you're talking about @AlanCoding. So this could be plain gibberish as well. :)

**Comment by AlanCoding** [comment]
Yeah, I think that (3) is what the conversation was already trending towards. There needs to be a way for user to control merge/overwrite, and I still don't see any problem with the `<existing>` syntax, which would be a fast one-off patch solving the problem for all similar cases.

**Comment by planeturban** [comment]
<existing> as quick and dirty fix is fine. But it opens up a Pandora’s can of worms (!) if someone forgets it in a production system and wipes all hosts from an inventory...

Come to think of it, how would one go about when using ‘with_items’ in conjunction with <existing>?

**Comment by AlanCoding** [comment]
you can't use with_items, this is a parameter of the list type. If you have a list, you can just pass it to the parameter.

**Comment by sean-m-sullivan** [comment]
With the advent of the tower_api lookup module, is this still a feature we want to implement, or rely on users doing the smart thing and using the lookup module to resolve things like this.

**Comment by planeturban** [comment]
But even with `tower_api` it doesn't solve the problem? It's like I said when comparing with `lineinfile`; the whole file but the line souldn't be wiped.

**Comment by sean-m-sullivan** [comment]
Right now extra vars, survey, all of those are wiped when a competing field is introduced, its the way the api currently works, it doesn't merge, We could either make the API do a merge, or figure it out in the module, Was saying the tower_api lookup would allow you to merge a list with a given list to Then feed the module the newly merged data.

**Comment by john-westcott-iv** [comment]
@planeturban while I see your point on the `lineinfile` with `state: present` I personally don't think it is a good comparison in this situration. This module is `tower_group` which describes a group in its entirety like how the `copy` module would describe a file in its entirety. And there is no good way to add a single line in a file from the `copy` module. `lineinfile` would be a better comparison to a module like `tower_host_in_group`(which does not exist). I like @sean-m-sullivan idea of grabbing the existing items with `tower_api` as an interim solution to the problem.

**Comment by planeturban** [comment]
In that case it's just a matter of documentation for the collection. I'm fine with either. 

I'm Switzerland in this question. :)

**Comment by sean-m-sullivan** [comment]
A 3rd way would be if this feature were ever developed #7008 , where you essentially copied from itself and we added merge on some fields. It would essentially be like using the tower_api module, but would require the merge by default. Either way, its using api to grab existing info and merging.

**Comment by sean-m-sullivan** [comment]
Was checking up on this, This has been solved by the above merge.

**Comment by AlanCoding** [comment]
I started on some quick verification work:

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:
    - tower_inventory:
        name: inventory_m2m_test
        organization: Default
        state: absent

    - tower_inventory:
        name: inventory_m2m_test
        organization: Default

    - tower_group:
        name: group_a
        inventory: inventory_m2m_test

    - tower_group:
        name: group_b
        inventory: inventory_m2m_test

    - tower_group:
        name: group_c
        inventory: inventory_m2m_test
        children:
          - group_a

    - name: Setup group children initially
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        children:
          - group_a
          - group_b

    - tower_host:
        name: host_a
        inventory: inventory_m2m_test

    - tower_host:
        name: host_b
        inventory: inventory_m2m_test

    - name: Setup group hosts initially
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        hosts:
          - host_a
          - host_b
      register: result

    - name: This should not be changed (group hosts test)
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        preserve_existing_hosts: true
        hosts:
          - host_b

    - name: "Show number of hosts of group_c"
      debug:
        msg: >
          group {{result.id}} number of hosts: {{ lookup('awx.awx.tower_api', 'groups/{{result.id}}/all_hosts/', wantlist=True) | length }}
          names of hosts: {{ lookup('awx.awx.tower_api', 'groups/{{result.id}}/all_hosts/', wantlist=True) | map(attribute='name') }}

    - name: Repeat the preserve_existing_hosts (should still not be changed)
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        preserve_existing_hosts: true
        hosts:
          - host_b

    - name: This should not be changed (group children test)
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        preserve_existing_children: true
        children:
          - group_b
      register: result

    - name: "Show number of children of group_c"
      debug:
        msg: >
          group {{result.id}} number of children: {{ lookup('awx.awx.tower_api', 'groups/{{result.id}}/children/', wantlist=True) | length }}
          names of children: {{ lookup('awx.awx.tower_api', 'groups/{{result.id}}/children/', wantlist=True) | map(attribute='name') }}

    - name: Repeat of prior task, this should not be changed
      tower_group:
        name: group_c
        inventory: inventory_m2m_test
        preserve_existing_children: true
        children:
          - group_b

```

output:

```
TASK [tower_inventory] ***********************************************************************************************
changed: [localhost]

TASK [tower_inventory] ***********************************************************************************************
changed: [localhost]

TASK [tower_group] ***************************************************************************************************
changed: [localhost]

TASK [tower_group] ***************************************************************************************************
changed: [localhost]

TASK [tower_group] ***************************************************************************************************
changed: [localhost]

TASK [Setup group children initially] ********************************************************************************
changed: [localhost]

TASK [tower_host] ****************************************************************************************************
changed: [localhost]

TASK [tower_host] ****************************************************************************************************
changed: [localhost]

TASK [Setup group hosts initially] ***********************************************************************************
changed: [localhost]

TASK [This should not be changed (group hosts test)] *****************************************************************
ok: [localhost]

TASK [Show number of hosts of group_c] *******************************************************************************
ok: [localhost] => {
    "msg": "group 76 number of hosts: 2 names of hosts: ['host_a', 'host_b']\n"
}

TASK [Repeat the preserve_existing_hosts (should still not be changed)] **********************************************
ok: [localhost]

TASK [This should not be changed (group children test)] **************************************************************
changed: [localhost]

TASK [Show number of children of group_c] ****************************************************************************
ok: [localhost] => {
    "msg": "group 76 number of children: 1 names of children: ['group_b']\n"
}

TASK [Repeat of prior task, this should not be changed] **************************************************************
ok: [localhost]

```

That one task:

> This should not be changed (group children test)

It doesn't just return the wrong changed status, it doesn't work correctly. It should have left `group_a` there and added `group_b`. However, it fails to leave `group_a` alone and removes it instead.
