### ISSUE TITLE
How to create the custom virtualenv with awx.awx collection included

### ISSUE THREAD

**Issue by momcilo78** [ansible/awx#7128]
##### ISSUE TYPE
 - awx.awx collection not available in custom environment

##### SUMMARY
I prefer to keep the default venv environment in the original state, and create a custom venv environment where we can install our own dependencies. The awx.awx contains the patched version of the original tower_job_launch.py (from awx.awx collection) which uses dict instead of list. This works in default environment after specifying collections: [awx.awx]. But does not work when creating custom environment. Please point out proper way to provide the collection inside custom venv.  

##### ENVIRONMENT
* AWX version: 11.20
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS Linux release 8.1.1911 (Core)
* Web Browser: any

##### STEPS TO REPRODUCE

Create virtual as described here:
https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

Use following playbook to try to launch another playbook. 
```
- hosts: all
  collections:
    # https://www.ansible.com/blog/introducing-the-awx-collection
    - awx.awx
  tasks:    
   - name: Lunch jobs
     awx.awx.tower_job_launch:
       job_template: invoked_job
       extra_vars:
         hello: world
```

##### EXPECTED RESULTS

After creating the custom venv, playbook is able to resolve the awx.awx collection.

##### ACTUAL RESULTS

Playbook uses the tower_jira_launch.py that comes with bundled ansible 2.9.7.
