### ISSUE TITLE
Built in collection awx.awx looks outdated

### ISSUE THREAD

**Issue by momcilo78** [ansible/awx#7193]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Bundled awx.awx collection inside /var/lib/awx/vendor/inventory_collections looks outdated. 
I have noticed that module tower_workflow_launch depends on ansible-tower-cli
You may want to consider update it, since this collection will be visible to anyone working with Default environment, and they may attempt at using it launch workflows. 

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS 8
* Web Browser:

##### STEPS TO REPRODUCE

Run following playbook (edit the actual workflow name)

```
- hosts: all
  tasks:
    - name: Launch workflow
      awx.awx.tower_workflow_launch:
      workflow_template: SOME_WORKFLOW_TEMPLATE
        extra_vars:
          jira_issue: ITSD-123
          automation_payload: Some payload...
```

##### EXPECTED RESULTS

Playbook launches the workflow job, with correctly passed extra_vars.

##### ACTUAL RESULTS
- possible dependency issue with ansible-tower-cli
- the module fails to launch workflow, since the module requires extra_vars as str instead of dict! (for tower_job_launch, this was dict).
