### ISSUE TITLE
Inventory does not provide actual information for the job

### ISSUE THREAD

**Issue by Aokigahara23** [ansible/awx#7231]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory sync  does not provide the running job with actual information. 
##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: boot2docker
* Ansible version:  2.9.7

##### STEPS TO REPRODUCE

1. Inventory is populated through vmware_vcenter plugin (tried custom script - same result)

2. I have a playbook with VM cloning via **vmware_guest** module
```yaml
- name: Clone the template
  vmware_guest:
    ### settings
```
3. Then i am refreshing my inventory and do the check that host is present in my inventory:
```yaml
- name: Refresh the inventory
   meta: refresh_inventory

# list of all available hosts in inventory
- name: print all hosts
  debug:
    var: groups.all

- name: Ensure the host is present in the inventory
  assert:
    that:
      - "test-vm in groups.all"
    fail_msg: Host test-vm was not found in the dynamic inventory
    success_msg: Host test-vm was found in the dynamic inventory
```
BUT!
```json
{
    "_ansible_verbose_always": true,
    "evaluated_to": false,
    "assertion": "'test-host in groups.all",
    "msg": "test-host was not found in the dynamic inventory",
    "_ansible_no_log": false,
    "changed": false
}
```

I have ansible's parody on "for loop" for this block of code, it iterates 5 times and sleep for 60 seconds on each iteration before refreshing the inventory. Just to be sure...

`debug` of `group.all` shows that `test-host` is not present in the inventory

The first thought was that AWX does not sync the inventory source dynamically (but in theory the job container is provided with .ini file and vmware_vcenter plugin so it should have no problem with retrieving the newly-created host). So i've made this kind of a hack:

```yaml
- name: update AWX inventory source
    uri:
      url: http://my-awx-web/api/v2/inventory_sources/22/update
      method: POST
      status_code: 202
      validate_certs: no

- name: Wait for the sync job
  pause:
    seconds: 120
```
It runs inventory source sync task on AWX host. And after successful sync i see `test-host` in AWX hosts in web ui.
Moreover, during job execution i have connected to the awx_task container. I found the job run directory in `/tmp/job_XX-xxxx`. With virtualenv located on awx_task:/var/lib/awx/venv/ansible, i ran 
`ansible-inventory -i /path/to/inventory --list` and my host `test-host` was there! But AWX job still continues to fail with "test-host was not found in the dynamic inventory". And `debug: var` of `groups.all` shows that my host isn't there.
