### ISSUE TITLE
tower_settings merge or facts

### ISSUE THREAD

**Issue by lshake** [ansible/awx#7277]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The awx collection module tower_settings should either support a merge option, or provide a tower_settings_facts module.  Currently for list types there appears to be no way to ensure a single list item is present or to retrieve the information without calling the api.

**Comment by john-westcott-iv** [comment]
The module should only be patching the settings endpoint with the new values you provide to it, not a full post so it should act like a merge. Is this not the behavior you are seeing? If not, can you send some sample playbooks?

**Comment by ryanpetrello** [comment]
Hey @Ishake, any feedback on @john-westcott-iv's question?

**Comment by ishake** [comment]
> Hey @ishake, any feedback on @john-westcott-iv's question?

@lshake see above (that l is an L not an i :D )

**Comment by ryanpetrello** [comment]
@ishake whoops 😄

**Comment by lshake** [comment]
Hey Folks. 

The issue is when the setting endpoint is a list, not a single value.  My example was the python environment, but I suspect that there are other settings of type list which behave the same.   Kubernetes has the same issue if I understand it correctly and have strategic merge as an option to merge list values, rather than overwriting them.   

In my use case, I want to allow different teams to maintain their own virtual envs, mostly to enable network teams to maintain their own virtual env including the required sdks for some devices, apps.    

I’ve not looked the awx collection since logging the feature request, so I maybe out of date, but I don’t think so.  

Lee.

**Comment by john-westcott-iv** [comment]
Given that ansible is a desired state machine, list values are always a replacement in the collection. In order to do an additive you would have to lookup the existing setting and then manually perform an addition. This can be achieved like:
```
- name: Add a new value to CUSTOM_VENV_PATHS
  tower_settings:
        name: "CUSTOM_VENV_PATHS"
        value: "{{ existing_settings + [ '/some/new/path' ] }}"
      vars:
        existing_settings: "{{ lookup('awx.awx.tower_api', 'settings/system')['CUSTOM_VENV_PATHS'] | default([]) }}"
```
