### ISSUE TITLE
Groups with the same name for a tree structure

### ISSUE THREAD

**Issue by bartheerman** [ansible/awx#7334]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
In Ansible, it is possible to arrange the groups in a tree structure. For example:

- customer1
  - palo
     > device1
     > device2
  - cisco
     > device3
     > device4
- customer2
  - palo
     > device5
  - cisco
     > device4

Under each customer, there is a group palo and cisco. This seems not to be possible using AWX because two groups cannot have the same name in an inventory.

**Comment by AlanCoding** [comment]
That's not actually what Ansible does. In the YAML inventory file format, they will allow syntax like that, but it's not 2 groups, it's just the same group. Example:

```yaml
all: # keys must be unique, i.e. only one 'hosts' per group
    hosts:
        test1:
        test2:
            host_var: value
    vars:
        group_all_var: value
    children:   # key order does not matter, indentation does
        customer1:
            children:
                cisco:
                    hosts:
                        test1:
        customer2:
            children:
                cisco:
                    hosts:
                        test2:
```

Use `ansible-inventory` to see an objective representation of what content is produced in practice.

```
$ ansible-inventory -i yaml/duplicate_group.yml --list --export
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under
development. This is a rapidly changing source of code and can become unstable at any point.
{
    "_meta": {
        "hostvars": {
            "test2": {
                "host_var": "value"
            }
        }
    },
    "all": {
        "children": [
            "customer1",
            "customer2",
            "ungrouped"
        ],
        "vars": {
            "group_all_var": "value"
        }
    },
    "cisco": {
        "hosts": [
            "test1",
            "test2"
        ]
    },
    "customer1": {
        "children": [
            "cisco"
        ]
    },
    "customer2": {
        "children": [
            "cisco"
        ]
    }
}
```

There are not 2 `cisco` groups. You just added it as a child of 2 different groups, and went through 2 passes of adding hosts. This is why `cisco` has 2 hosts, even though each "definition" of the group just added 1.

You can use the AWX UI or API to add existing groups as children to other groups, so you should be able to create this same inventory.
