### ISSUE TITLE
Develop a maintainable way to reference related objects

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#7356]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Modules in the AWX collection frequently reference related objects, consider:

```yaml
- name: Create Tower Ping job template
  tower_job_template:
    name: "Ping"
    job_type: "run"
    organization: "Default"
    inventory: "Local"
    project: "Demo"
    playbook: "ping.yml"
    credentials:
      - "Local"
    state: "present"
    tower_config_file: "~/tower_cli.cfg"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'my_survey.json') }}"
    custom_virtualenv: "/var/lib/awx/venv/custom-venv/"
```

In this example, the organization, inventory, project, and credentials are all related objects.

Each of these are naively specified by a single string field (typically the `name` field), but every model has its own set of uniqueness rules. This runs the risk of hitting duplicates if a project with the same name exists in multiple organizations, for example.

There is an existing solution to look up related objects based on other shared information. Like, how the `tower_group` module will only lookup child hosts in its same inventory. This logic exists in the code for individual modules (like `tower_group`), which is repetitive and prone to breaking. A proposal at #6430 is a way to move it to the shared module_utils, but may need additional simplification and cleanup.

Also, sometimes related objects will not share the same parent object. Imagine syntax like:

```yaml
    inventory: "Default++Local"
```

This could reference the inventory named "Local" in the "Default" organization. I write it this way because this is the syntax that named URL uses, and would avoid changing the field type.

We have another proposal to allow using a lookup plugin like:

```yaml
    inventory: "{{ query('awx.awx.tower_api', 'inventories', query_params={'organization__name': 'Default', 'name': 'Local'}) }}"
```

Proposed in #7286. Exact syntax is subject to change.

----

These solutions are not exclusive. We need 1 or more recommended way or doing things that will not require constant effort to keep functional.
