### ISSUE TITLE
Collection fails to resolve unified_job_template ids

### ISSUE THREAD

**Issue by squidboylan** [ansible/awx#7377]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

passing an id to `unified_job_template` params in the `schedule` and `workflow_job_template_node` modules fails because `module.resolve_name_to_id('unified_job_templates', unified_job_template)` fails (due to api behavior).

@ryanpetrello noted the CLI hits the same issue ( https://github.com/ansible/awx/issues/6587 ), so maybe we need/want an api fix for this.

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: docker on linux
* Ansible version:  2.9
* Operating System: ubuntu

##### STEPS TO REPRODUCE

run a playbook containing:

```
- hosts: localhost
  collections:
    - awx.awx
  vars:
    proj_name: project1
    inv_name: inventory1
    inv_source_name: inventory_source1
    jt_name: jt1
    wfjt_name: wfjt1
    organization_name: Default
    schedule_name: sched1
  tasks:
    - name: Create "{{ proj_name }}"
      tower_project:
        name: "{{ proj_name }}"
        organization: "{{ organization_name }}"
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git

    - name: Create "{{ inv_name }}"
      tower_inventory:
        name: "{{ inv_name }}"
        organization: "{{ organization_name }}"
        state: present

    - name: Add an inventory source to "{{ inv_name }}" using "{{ proj_name }}"
      tower_inventory_source:
        name: "{{ inv_source_name }}"
        inventory: "{{ inv_name }}"
        source: scm
        source_project: "{{ proj_name }}"
        source_path: "inventories/create_500_hosts.ini"

    - name: Create "{{ jt_name }}"
      tower_job_template:
        name: "{{ jt_name }}"
        organization: "{{ organization_name }}"
        project: "{{ proj_name }}"
        inventory: "{{ inv_name }}"
        playbook: chatty_tasks.yml
        job_type: run
        state: present
      register: jt

    - name: Create "{{ wfjt_name }}"
      tower_workflow_job_template:
        name: "{{ wfjt_name }}"
        organization: "{{ organization_name }}"
        inventory: "{{ inv_name }}"
      register: wfjt

    - name: Create a wf node
      tower_workflow_job_template_node:
        unified_job_template: "{{ jt.id }}"
        identifier: root
        organization: "{{ organization_name }}"
        workflow: "{{ wfjt_name }}"

    - name: Create a schedule
      tower_schedule:
        name: "{{ schedule_name }}"
        state: present
        unified_job_template: "{{ wfjt.id }}"
        rrule: "DTSTART:20191219T130551Z RRULE:FREQ=MINUTELY;INTERVAL=1"
```

##### EXPECTED RESULTS

the workflow node and schedule should be created

##### ACTUAL RESULTS

```
TASK [Create a wf node] ***************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The unified_job_templates 10 was not found on the Tower server"}
```

and without the wf node creation task:

```
TASK [Create a schedule] **************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The unified_job_templates 11 was not found on the Tower server"}
```
