### ISSUE TITLE
Cannot run dig lookup - Missing dnspython error

### ISSUE THREAD

**Issue by fchiacchiaretta** [ansible/awx#7442]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to use dig lookup, but it fails with missing dnspython library error.

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.10
* Operating System: Server: CentOS 7.8 , Client: Fedora 32
* Web Browser: Firefox 77.0.1

##### STEPS TO REPRODUCE
```yaml
- hosts: demo.example.com
  vars:
    fqdn: resolveme.example.com.
  tasks:
  - name: "The A record for resolveme.example.com."
    debug:
      msg: "{{ lookup('dig', '{{ fqdn }}', 'qtype=A') }}"
```

##### EXPECTED RESULTS
```
TASK [The A record for resolveme.example.com.] ********************************************************************************
ok: [demo.example.com] => {
    "msg": "1.2.3.4"
}

```
##### ACTUAL RESULTS
```
TASK [The A record for resolveme.example.com.] *****************************************
fatal: [demo.example.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The dig lookup requires the python 'dnspython' library and it is not installed"}
```

Is it possible to include dnspython library in ansible venv?

Best,
Federico Chiacchiaretta
