### ISSUE TITLE
SyntaxError: EOF while scanning triple-quoted string literal: PIP Module fails in Container Group when setting executable parameter

### ISSUE THREAD

**Issue by gen2fish** [ansible/awx#7453]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running a playbook with the pip module from a container group where the executable parameter is set, job errors out with encrypted playbook response and error:

```shell
SyntaxError: EOF while scanning triple-quoted string literal
command terminated with exit code 1
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1} PLAY RECAP ********************************************************************* awx-job-29124 : ok=3 changed=2 unreachable=0 failed=1 skipped=1 rescued=0 ignored=
```

##### ENVIRONMENT
* AWX version: 9.3.0
* AWX install method: docker
* Ansible version:  2.9.5
* Operating System: CentOS 7
* Web Browser: Firefox 

##### STEPS TO REPRODUCE
Playbook task as below using Python3 interpreter.

```yaml
    - name: Install Openshift Python Library
      pip:
        name: openshift
        executable: pip3
```

##### EXPECTED RESULTS

Job to run and pip to install while forwarding errors to the output window.

##### ACTUAL RESULTS

Job executes on target k8s cluster, pod gets created then terminates after 45 seconds. Job in AWX Errors with encrypted error details and SyntaxError: EOF while scanning triple-quoted string literal at the end.

##### ADDITIONAL INFORMATION

Job executes on leaf node using direct SSH without issue, error only occurs when using container groups.

I was originally running the hardcoded executable parameter when it was using the auto_legacy interpreter discovery. When using python2 it, understandably, fails due to my node not having setuptools for python2 installed.  Job executes successfully in all scenarios tested if the executable parameter is not declared.

**Comment by gen2fish** [comment]
In the container group, I am customizing the pod spec to run in a specific namespace.

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: cust-namespace
spec:
  containers:
    - image: ansible/ansible-runner
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity
```
