### ISSUE TITLE
the tower_role module should accept ids for related objects

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx#7498]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Parameters to the `tower_role` module will not resolve integer-like inputs as ids, only as names.

They should.

##### STEPS TO REPRODUCE

See details from

https://groups.google.com/g/awx-project/c/mRuVUCtgMhQ

something like

```yaml
  - name: Give team access to credential
    tower_role:
      credential: 5
      role: use
      team: testteam
```

##### EXPECTED RESULTS

looks up credential with id=5

##### ACTUAL RESULTS

problems finding credential

**Comment by jmartensson** [comment]
It not only tower_role, I also have issues when using tower_credential
```
   - name: Change owner of credential
     tower_credential:
       name: 62
       description: mycredential
       organization: myneworg
       credential_type: Machine
       state: present
```
This ends up with a new credential called '62' instead of making changes to the credential with id '62'
