### ISSUE TITLE
Galaxy Collection modules fail due to outdated packages

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/awx#7536]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Modules in the `azure.azcollection` Galaxy collection fail due to a missing API version.

Based on issues opened in the Azure collection like [this](https://github.com/ansible-collections/azure/issues/136), it seems as if the culprit is outdated azure packages in the python virtual environment.

How can I ensure that the collections downloaded automatically by AWX can execute successfully?

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on Linux
* Ansible version:  2.9.10
* Operating System: MacOS Catalina
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Enable collection download from AWX Jobs settings (using public Galaxy)
1. Define a collection in `/collections/requirements.yml` like this:

```yaml
---
collections:
  - name: azure.azcollection
```
1. Define a playbook that utilizes the collection:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: true
  collections:
    - azure.azcollection
  tasks:
    - name: Get vm info
      azure_rm_virtualmachine_info:
        resource_group: rg-awxdev
        subscription_id: xxxx-xxxxxxxx-xxxxx
        name: testvm01
        auth_source: msi
      register: output
    - debug:
        var: output
```

##### EXPECTED RESULTS

No errors, like when I run the module without the collection specified (which uses the `/ansible/modules/cloud/azure` module).
![Screen Shot 2020-07-02 at 11 29 54 AM](https://user-images.githubusercontent.com/18073815/86378355-92d79500-bc57-11ea-8903-e936b278ecce.png)

##### ACTUAL RESULTS

Module fails due to a missing API version, and I can see that by executing `/var/lib/awx/venv/ansible/bin/pip3.6 freeze` in the container, the versions of `azure-mgmt-*` are much older than those defined by the [Azure Collection's requirements file](https://github.com/ansible-collections/azure/blob/v0.1.3/requirements-azure.txt).
![86377033-d03b2300-bc55-11ea-84c2-d17fa3fe4684](https://user-images.githubusercontent.com/18073815/87079210-b3719300-c1f3-11ea-988b-3319623071ed.png)

##### ADDITIONAL INFORMATION
Package versions:
- Left is the output of `/var/lib/awx/venv/ansible/bin/pip3.6 freeze` when executed from *awx_task*.
- Right is https://github.com/ansible-collections/azure/blob/v0.1.3/requirements-azure.txt
![Screen Shot 2020-07-02 at 11 39 47 AM](https://user-images.githubusercontent.com/18073815/86379370-c2d36800-bc58-11ea-9477-32d531b142e2.png)
