### ISSUE TITLE
`plugins/modules/tower_inventory_source.py` does not allow for schedules to be set which GUI does

### ISSUE THREAD

**Issue by bherrin3** [ansible/awx#7580]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Within the GUI, it is permissible to set an inventory source to be ran on a schedule to remain updated. 

Within `tower_inventory_source`, there is no way via IaC (Infrastructure as Code) to configure in the same manner so production CI / CD pushes to PROD Ansible Towers get updated (and not over written).

This is required if updating the inventory could not be in workflows as you run the in parallel / often and it causes too much delay / if a blocking item within workflows.

#### Screen Shot of GUI

![image](https://user-images.githubusercontent.com/44168646/86951628-c7e45b80-c11f-11ea-8e94-fce3d56d27ab.png)

![image](https://user-images.githubusercontent.com/44168646/86951655-d16dc380-c11f-11ea-8dc0-70fe09a145ba.png)

##### ENVIRONMENT
* AWX version: latest
* AWX install method: n/a
* Ansible version:  latest
* Operating System: RHEL
* Web Browser: n/a

##### STEPS TO REPRODUCE

1. Attempt to configure an Ansible Tower with `tower_inventory_source` with an `rrule` similar to what is allowable / configurable in the GUI
2. Note this isn't currently possible

###### Example Code Snippet

`{
description: ""
name: "My New Test Schedule"
rrule: "DTSTART;TZID=America/New_York:20200708T000000 RRULE:FREQ=MINUTELY;INTERVAL=1"
}`
##### EXPECTED RESULTS

- Using the awx module, the Ansible Tower should have an inventory source configured with any valid `rrule` to sync the source.

##### ACTUAL RESULTS

Currently no possible Iac way to complete this action currently and the problem has to be worked around.

- Aa `hello-world` `job_template` that CAN be synced to an `inventory` (not `inventory_source`) that can be set on a schedule
- An HTTP POST to the `/api/v2/inventory_sources/id/schedules` (please note: these IDs change depending on how / when the AT was deployed, so this is problematic at best and not a real solution) with the above payload. 

##### ADDITIONAL INFORMATION

Any additional information van be provided.

Please note dev branch deployments of AT can also be given as deploying an AT from .zip is easy to do in our Dev Branches for customer acceptance testing.

Thanks!

**Comment by AlanCoding** [comment]
could you share the YAML tasks from your playbook that you've tried?

It's not the inventory source module that provides this functionality, it's the `tower_schedule` module. You should try using that and passing the inventory source name to it. That's the intended way to use it.

**Comment by kedark3** [comment]
@AlanCoding afaik @bherrin3 tried that and it did not work. @bherrin3 can you provide the input please?

**Comment by bherrin3** [comment]
## Salutations
@AlanCoding including previous conversation with @john-westcott-iv 

## Code Sample Requested
```
tower_schedules:
  - name: Sync Inventory Sources
    description: Sync the Tower Sources quickly to ensure that Smart Inventories are up-to-date
    rrule: "DTSTART:20200701T130551Z RRULE:FREQ=MINUTELY;INTERVAL=1"
    inventory: RHVM-02
```
## Previous Conversation

> 15:29 Brian Herring: Heyo Mr. Westcott
> 15:29 Question about awx collection inventory_source sync schedules without UJTs, when you have a moment
> 15:30 https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_schedule.py
> 15:53 john.westcott.iv Sure, what is the question?
> 16:07 Brian Herring: So, it looks like you need a UJT listed in the tower_schedule to actually setup a schedule
> 16:07 However, in the GUI, you can setup a tower_source sync without the need for a UJT
> 16:07 I don't see a way to IaC that with that module. Am I missing something?
> 16:10 john.westcott.iv Did you try just passing in the job name? Although technically different the job name will usually be enough for it to find the unified job template
> 16:11 Brian Herring: So, what I attempted to define was the following:
```
tower_schedules:
  - name: Sync Inventory Sources
    description: Sync the Tower Sources quickly to ensure that Smart Inventories are up-to-date
    rrule: "DTSTART:20200701T130551Z RRULE:FREQ=MINUTELY;INTERVAL=1"
    inventory: RHVM-02
```
> 16:12 I really want inventory_source not inventory
> 16:12 john.westcott.iv Ah, I think I see.
> 16:13 Brian Herring: 2. There is no job_template or node... this is a sync on an inventory source, nothing else
> 16:19 john.westcott.iv From a quick look, I don’t think this module will work for creating inventory schedules.
> 16:20 This module is interacting with the /api/v2/schedules endpoint
> 16:20 But when you create a schedule for an inventory source its being done through /api/v2/inventory_sources/<id>/schedules/
> 16:20 The schedule created there ends up under /api/v2/schedules but it references a unified job template that the UI will not show you.
> 16:21 Brian Herring: Right... but that module has no information about rrule or setting up a schedule... unless I ma missing something?
> 16:21 https://github.com/ansible/awx/blob/devel/awx_collection/plugins/modules/tower_inventory_source.py
> 16:21 john.westcott.iv Right, its not in there right now.
> 16:22 Brian Herring: waits for it
> 16:22 john.westcott.iv This is probably going to need an enhancement somewhere in order to make it work.
> 16:22 Well, not probably, it will
> 16:22 Do you want to open a bug report in github.com/ansible/awx ?
> 16:22 Brian Herring: I am more than happy to.
> 16:24 Brian Herring: ack. In the short-term, I have just created the source sync in the GUI. However, every time we push IaC to the Prod tower, it reverts the source sync (iirc)
> 16:24 john.westcott.iv I will also likely need to do some design work with the tower team on this as that would be a lot of parameters to pass into this module.
> 16:25 You could probably do it in IaC with just a URI call
> 16:25 Brian Herring: I suppose the other hack is to create a JT with a hello world that has a sync source in the JT that can be scheduled
> 16:25 john.westcott.iv That would be another hack.
> 16:26 I’d probably just say use URI for now unless its too much of a pain.
> 16:26 Brian Herring: I prefer that to a IaC URI hack I would have to add to the project CI on push definition that hacks a previous config, I think
> 16:26 I will figure out a mid-term solution that works. (edited) 
> 16:27 Thanks for your time, sir.
> 16:27 john.westcott.iv You could use tower_inventory_source which should return the source ID and then make an HTTP POST to /api/v2/inventory_sources/<id>/schedules with a payload like:
```
{
description: ""
name: "My New Test Schedule"
rrule: "DTSTART;TZID=America/New_York:20200708T000000 RRULE:FREQ=MINUTELY;INTERVAL=1"
}
```
> 16:27 The rrule you can use the lookup plugin to generate.
> 16:27 Brian Herring: ack. thank you, sir.
> 16:28 john.westcott.iv Anytime, let me know if you have any trouble with URI module and I’ll see what we can do about getting an actual module to cover this.

**Comment by AlanCoding** [comment]
I would expect it to look like this:

```yaml
- name: Build a schedule for Demo Job Template
  awx.awx.tower_schedule:
    name: "Sync Inventory Sources"
    state: present
    unified_job_template: "RHVM-02"
    rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
```

My expectation is that the name of the inventory source is passed to the `unified_job_template:` parameter. If "RHVM-02" is the name of the inventory, you need to look at its sources and replace it with an inventory source. If you want a schedule to update multiple inventory sources within the inventory, the API does not support that, so make separate schedules.

The parameter `inventory:` is not what you want.

**Comment by bherrin3** [comment]
@AlanCoding using / standardizing on the abstracted module and configuration usage in AT IaC name with a variable, hence the difference:

* https://github.com/redhat-cop/tower_configuration/blob/devel/roles/schedules/tasks/main.yml

Noted. Will re-attempt with that and report back.

**Comment by blomquisg** [comment]
@bherrin3 reopen if you get any additional info

**Comment by bherrin3** [comment]
@AlanCoding @blomquisg -- leaving in the closed state.

Modified the `tower_schedules` tower_configuration role variable (module source: awx.awx.tower_schedule) as suggested by @AlanCoding to implement:

```
tower_schedules:
  - name: "Sync Inventory Sources"
    state: present
    unified_job_template: "RHVM-02"
    rrule: "DTSTART:20191219T130551Z RRULE:FREQ=MINUTELY;INTERVAL=1"

```

This gave us the short-term functionality we require.

Thank you!
