### ISSUE TITLE
gcp_compute inventory plugin failing under 13.0.0

### ISSUE THREAD

**Issue by ronjarrell** [ansible/awx#7609]
##### ISSUE TYPE
gcp_compute inventory plugin failing under 13.0.0

##### SUMMARY
I have an inventory script that worked fine under 11.0.0, and still works under 2.9.6 from the command line, 
but fails with a:

```
awx/scratch.gcp.yml with auto plugin: Credential type 'serviceaccount' not
implemented
``` 
under 13.0.0

##### ENVIRONMENT
* AWX version: 13.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.10
* Operating System: Centos 7 on tower, Mac on client
* Web Browser: chrome
##### STEPS TO REPRODUCE

Using this script, which worked in 11.0.0
```
zones:
 - us-central1-a
 - us-central1-b
 - us-central1-c
 - us-central1-f
projects:
 - redacted
filters:
 - labels.environment = devel
 - labels.managed = "true"
groups:
 gcp_hosts: true
 gke: "'goog-gke-node' in (labels|list)"
auth_kind: serviceaccount
hostnames:
 - name
scopes:
 - https://www.googleapis.com/auth/compute
compose:
 dc: labels.hostname.split('_')[2]
 dc_grp: "'dc_' + labels.hostname.split('_')[2]"
 private_ip_address: networkInterfaces[0].networkIP
 ansible_host: networkInterfaces[0].networkIP
```

with a credential defined and assigned i get the 
```
awx/scratch.gcp.yml with auto plugin: Credential type 'serviceaccount' not
implemented
``` 
error.  I've generated a new key, and created a new credential, and assigned it to verify the key is ok.

##### EXPECTED RESULTS

Inventory to be updated

##### ACTUAL RESULTS

See error above.
