### ISSUE TITLE
AWX fails to try and install galaxy dependencies

### ISSUE THREAD

**Issue by hluaces** [ansible/awx#7712]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

AWX 12.0 project updates are not  updating the remote roles defined in the `roles/requirements.yml` file. 

I've checked the playbook that runs on each project update \[1\] \[2\] and it seems that the play named "_Install content with ansible-galaxy command if necessary_" \[3\] has blocks tagged with "install_roles" \[4\] and "install_collections" \[5\]. Those tags seem to be skipped for some reason and thus AWX is not even trying to download the roles.

EDIT: Apparently the tags with with the project update is ran are those on the "_SCM Update options_" section of the project settings. There's none for roles and collections which causes the play in charge of ansible-galaxy runs to never run. Not choosing any option doesn't make the tags go away as the job update will always be ran with the `update_git` tag. Screenshot in \[6\] where the tags are shown.

\[1\]: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml
\[2\]: https://github.com/ansible/awx/blob/devel/awx/playbooks/project_update.yml
\[3\]: https://github.com/ansible/awx/blob/71d3fd3dbc1d7c59756817a80c0e7ca673a862c3/awx/playbooks/project_update.yml#L115
\[4\]: https://github.com/ansible/awx/blob/71d3fd3dbc1d7c59756817a80c0e7ca673a862c3/awx/playbooks/project_update.yml#L137
\[5\]: https://github.com/ansible/awx/blob/71d3fd3dbc1d7c59756817a80c0e7ca673a862c3/awx/playbooks/project_update.yml#L161
\[6\]: 
![image](https://user-images.githubusercontent.com/3204332/88297459-33bdeb00-cd00-11ea-8be7-9924d79caf83.png)

##### ENVIRONMENT
* AWX version: 12.0.0
* AWX install method: Linux
* Ansible version:  2.9.9
* Operating System: CentOS7
* The project is on a SCM.
* The global option to download roles and collections is enabled.
* I've added extra verbosity to the project updates.

##### STEPS TO REPRODUCE

- Create a new SCM based project.
- Add a `roles/requirements.yml` file with some galaxy roles.
- Enable the global options to:
  * Download roles.
  * Download collections.
  * Run project updates on higher verbosity.
 - Run a project update.
 - Verify that the task "_Install content with ansible-galaxy command if necessary_" is not ran and that the project update has some tags associated with it (see screenshot) but none of those are the ones needed to run ansible-galaxy commands.

##### EXPECTED RESULTS

AWX should install the remote roles and collections after the project update has finished.

##### ACTUAL RESULTS

The project update job output skips the play tasked with running the `ansible-galaxy` commands.

A partial log below.

```
[...]

TASK [Set the git repository version] ******************************************
task path: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml:43
ok: [localhost] => {
    "ansible_facts": {
        "scm_version": "bfec46f6d83808a960a0cf453a6678702e0beb15"
    },
    "changed": false
}
TASK [Repository Version] ******************************************************
task path: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml:103
ok: [localhost] => {
    "msg": "Repository Version bfec46f6d83808a960a0cf453a6678702e0beb15"
}
META: ran handlers
META: ran handlers
PLAY [Install content with ansible-galaxy command if necessary] ****************
META: ran handlers
META: ran handlers
META: ran handlers
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ADDITIONAL INFORMATION

If I remove the tags and add a `tags: 'always'` to the relevant play, the task is run but I hit this problem:

```TASK [fetch galaxy roles from requirements.yml] ********************************
fatal: [localhost,]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'roles_destination' is undefined\\n\\nThe error appears to be in '/usr/local/lib/python3.7/dist-packages/awx-7.0.0-py3.7.egg/awx/playbooks/project_update.yml': line 128, column 9, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n      - name: fetch galaxy roles from requirements.yml\\n        ^ here\\n"}
```

Maybe this one last thing is related to https://github.com/ansible/awx/issues/4750

**Comment by hluaces** [comment]
I've just tried in 13.0.0 and it is happening aswell.

**Comment by hluaces** [comment]
If anyone is running into this, a dirty alternative is to modify the offending play on the container's `project_update.yml` playbook:

```yaml
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install content with ansible-galaxy command if necessary
  # This is necesarry for #7712
  tags: 'always'
  vars: 
   # These do not seem to be defined from AWX. See #4750
    roles_destination: "{{ project_path|quote }}/roles"
    collections_destination: "{{ project_path|quote/collections }}"
  tasks:

    - block:
        - name: detect requirements.yml
          stat:
            path: '{{project_path|quote}}/roles/requirements.yml'
          register: doesRequirementsExist

        - name: fetch galaxy roles from requirements.yml
          command: ansible-galaxy role install -r roles/requirements.yml -p {{roles_destination|quote}}{{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}
          args:
            chdir: "{{project_path|quote}}"
          register: galaxy_result
          when: doesRequirementsExist.stat.exists
          changed_when: "'was installed successfully' in galaxy_result.stdout"
          environment:
            ANSIBLE_FORCE_COLOR: false
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      when: roles_enabled|bool

    - block:
        - name: detect collections/requirements.yml
          stat:
            path: '{{project_path|quote}}/collections/requirements.yml'
          register: doesCollectionRequirementsExist

        - name: fetch galaxy collections from collections/requirements.yml
          command: ansible-galaxy collection install -r collections/requirements.yml -p {{collections_destination|quote}}{{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}
          args:
            chdir: "{{project_path|quote}}"
          register: galaxy_collection_result
          when: doesCollectionRequirementsExist.stat.exists
          changed_when: "'Installing ' in galaxy_collection_result.stdout"
          environment:
            ANSIBLE_FORCE_COLOR: false
            ANSIBLE_COLLECTIONS_PATHS: "{{ collections_destination }}"
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      when:
        - "ansible_version.full is version_compare('2.8', '>=')"
        - collections_enabled|bool

```
Note that I've:

- Removed the tags from the blocks.
- Added the `tags: 'always'` to the play.
- Added a `vars:` block because both `roles_destination` and `collections_destination` seem to be undefined for some reason.

This seems to properly clone roles and collections.
