### ISSUE TITLE
Running the development environment on Windows using wsl2

### ISSUE THREAD

**Issue by vrjram** [ansible/awx#7731]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Facing issue starting the redis container from the docker-compose.

Issue is with the following errors being received while starting the redis container.

1:C 28 Jul 2020 15:54:32.932 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf'

EX:
awx/tools/docker-compose.yml
```
 redis:
    image: redis:latest
    container_name: tools_redis_1
    user: ${CURRENT_UID}
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/redis_socket_standalone:/var/run/redis/"

    command: ["/usr/local/etc/redis/redis.conf"]
```

##### ENVIRONMENT
* AWX version: devel
* AWX install method: docker for windows, WSL2
* Ansible version:  2.9.10
* Operating System: Windows 10 Ver 2004
* Web Browser: Chrome

##### STEPS TO REPRODUCE

While following the steps at:
[Contributing.md](https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md)
make docker-compose-build is successful
make docker-compose fails

##### EXPECTED RESULTS

make docker-compose needs to be successful and be allowed to login to the awx portal.

##### ACTUAL RESULTS

The command errors out repeatedly while trying to bind to the redis socket which it cannot bind to.

The errors during the startup of redis are:

docker logs -f tools_redis_1
1:C 28 Jul 2020 15:54:32.932 # Fatal error, can't open config file '/usr/local/etc/redis/redis.conf'
