### ISSUE TITLE
upgrade from awx 13 to 14, postgres failed to restart

### ISSUE THREAD

**Issue by linuxcube** [ansible/awx#7854]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
postgres failed to restart from upgrade of awx v13 to v14

##### ENVIRONMENT
* AWX version: 14
* AWX install method: docker
* Ansible version:  2.8.3-1
* Operating System: RHEL 8.2
* Web Browser: Chrome/Firefox

##### STEPS TO REPRODUCE

docker stop ansible/awx:14.0.0 ansible/awx:14.0.0  redis postgres:10
rm rf /root/awx
git clone https://github.com/ansible/awx.git
cd awx/installer/
ansible-playbook -i inventory install.yml
docker ps

##### EXPECTED RESULTS
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                          PORTS                  NAMES
e0effec6e2ab        ansible/awx:14.0.0   "tini -- /usr/bin/la…"   31 minutes ago      Up About a minute               8052/tcp               awx_task
a3a328a5ffc3        ansible/awx:14.0.0   "tini -- /bin/sh -c …"   31 minutes ago      Up About a minute               0.0.0.0:80->8052/tcp   awx_web
8dd7063400a8        postgres:10          "docker-entrypoint.s…"   32 minutes ago      Restarting (1) 30 seconds ago                          awx_postgres
e0eb72177943        redis                "docker-entrypoint.s…"   2 weeks ago         Up About a minute               6379/tcp               awx_redis

##### ACTUAL RESULTS

postgres stuck in restart mode

##### ADDITIONAL INFORMATION

No additional details collected

**Comment by ryanpetrello** [comment]
`docker logs 8dd7063400a8` ?

**Comment by shanemcd** [comment]
Did you copy over your old inventory file with your passwords?

**Comment by ryanpetrello** [comment]
What @shanemcd said:

https://github.com/ansible/awx/blob/devel/INSTALL.md#upgrading-from-previous-versions

If you blew away your inventory file, upgrading is unlikely to work.

**Comment by agrisvv** [comment]
centos 8 from awx  13 to 14 after upgrade as usual with old inventory settings.
postgres docker restarting..

````

Data page checksums are disabled.

initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".

**Comment by linuxcube** [comment]
I did both, with and without old inventoy file....the outcome was the same.
Postgres not starting.

**Comment by linuxcube** [comment]
Hi agris....looks like some of us are in the same boat as you after
upgrade.

**Comment by egmar** [comment]
@linuxphone see this change https://github.com/ansible/awx/commit/06fd1316371c9a1e6482c8e38a6bf7bfc6b6e7f4 , perhaps its the cause

**Comment by agrisvv** [comment]
> @linuxphone see this change [06fd131](https://github.com/ansible/awx/commit/06fd1316371c9a1e6482c8e38a6bf7bfc6b6e7f4) , perhaps its the cause

modified installer reverted changes as in commit and installed again, but now it started with empty db.. will try to check where it gone..

**Comment by linuxcube** [comment]
Hi Agris,

That entry is already committed to the latest code, so this is not the solution….the issue remains.

**Comment by amtilghman** [comment]
I tested a devel build 2 days ago and had the same issue, was thinking it would be fixed before 14.0.0 (or i would have made an issue :) )

Just tried 12.0.0 > 14.0.0

Error was identical to person above:

initdb: directory "/var/lib/postgresql/data" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/data" or run initdb
with an argument other than "/var/lib/postgresql/data".
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

**Comment by linuxcube** [comment]
Hi Amtilghman, 

It looks like  we need a small patch for this….hopefully not too many users start upgrading and face the same issue.

**Comment by ekinof** [comment]
Same with me, I just tried to upgrade from 12.0.0 to 14.0.0, my postgres container doesn't work. I downgrade to 13.0.0 and now it works.

**Comment by kenchrcum** [comment]
Hello,
I had the same issue, I solved it by using 
`docker-compose down && docker-compose up -d`
It seemed to me the problem happened because the old AWX was still running when I started the installer.

**Comment by Luke239847** [comment]
> @linuxphone see this change [06fd131](https://github.com/ansible/awx/commit/06fd1316371c9a1e6482c8e38a6bf7bfc6b6e7f4) , perhaps its the cause

had the same issue and to change this file to the old version solved it for me

**Comment by dotslashcmd** [comment]
It seems that in the docker-compose generated by the V14 installer, the env variable PGDATA for the postgres container is missing. 

Docker-compose v 13 : 
```
  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /var/lib/pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy:
```

Docker-compose v 14  :


```  
postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /var/lib/pgdocker/10/data/:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      http_proxy:
      https_proxy:
      no_proxy:
```
