### ISSUE TITLE
AWXKit export/import - workflow job templates

### ISSUE THREAD

**Issue by watsonb** [ansible/awx#7857]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When exporting job templates and workflow templates from one AWX instance and importing them into another new instance, workflow templates have no nodes in them, such as other job templates, project syncs, inventory syncs, etc.

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: Ubuntu 18.04
* Web Browser: Chrome

The above is for the new instance.  The old instance is AWX 7.0.0 with Ansible 2.8.4, all other environment items are the same for the old instance.

##### STEPS TO REPRODUCE

1. Use awxkit's `awx` command to login and export artifacts from an existing AWX instance.  I use a playbook to do this and my task looks like this:

```yaml
- name: SHELL | export artifacts from {{ ap_awx_export_from }}
          shell: awx export -k --{{ item }} > awx_{{ ap_awx_export_from | urlsplit('hostname') }}_{{ item }}.json
          args:
            executable: /bin/bash
            creates: awx_{{ ap_awx_export_from | urlsplit('hostname') }}_{{ item }}.json
          environment:
            TOWER_HOST: "{{ ap_awx_export_from }}"
            TOWER_USERNAME: "{{ ap_awx_export_from_username }}"
            TOWER_PASSWORD: "{{ ap_awx_export_from_password }}"
            TOWER_OAUTH_TOKEN: "{{ ap_awx_export_token }}"
          tags: [ artifacts, export ]
          loop:
            - organizations
            - users
            - teams
            - credential_types
            - credentials
            - notification_templates
            - projects
            - inventory
            - inventory_sources
            - job_templates
            - workflow_job_templates
```

This command is executed on the new instance and, as shown, results in several *.json files corresponding to each AWX artifact type.

2. I have a subsequent task that performs the import into the new instance, but only imports the following artifacts: organizations, users, teams, credential_types, and credentials

3. I have another task which fixes the imported credentials by assigning actual values for each credential (e.g. SSH keys, passwords, vault passwords) since the import of credentials brings these things in empty.

4. I import additional artifacts in the following order: notification_templates, projects

5. I get a list of imported projects and perform an `awx projects update <proj_id> --wait` for each imported project to ensure they are all sync'd from Git repos

6. Finally, I import the remaining artifacts in the following order: inventory, inventory_sources, job_templates, workflow_job_templates

##### EXPECTED RESULTS

I expect imported workflow_job_templates to have the same workflow (job_templates, inventory syncs, project syncs, etc.) as they appeared in the system they were exported from.

##### ACTUAL RESULTS

A cursory glance at the AWX GUI shows everything seems OK on the surface, but when you open one of the workflow_job_templates in the GUI and view the Workflow Editor, you only see a Start node.

##### ADDITIONAL INFORMATION

N/A
