### ISSUE TITLE
vmware inventory plugin ignores filters

### ISSUE THREAD

**Issue by xTrekStorex** [ansible/awx#7899]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Ever since the vmware inventory plugin is used, starting with AWX 11.2.0, our host filters or rather all source vars are being ignored in the vCenter inventory source.
I already looked into the code that generates the YAML for the auto plugin and adjusted my source vars accordingly but that did not help.
I'm currently keeping our production AWX environment on 11.1.0 to continue using the inventory script instead, which works with these filters. These results are from a cloned AWX instance for dev, upgraded to 14.0.0.
If there is anything I should try, I will gladly do so.

##### ENVIRONMENT

* AWX version: 14.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.11
* Operating System: Debian 10 (Docker host)
* Web Browser: Chrome on Windows

##### STEPS TO REPRODUCE

AWX inventory sourced from vCSA 6.7.0.44000

source vars (removed {{ }} since they are stripped for the generated YAML anyways):
```
host_filters: >-
  runtime.powerstate == "poweredOn", 
  guest.guestid != "vmwarePhoton64Guest",
  guest.guestid != "other26xLinuxGuest",
  guest.guestid != "other3xLinux64Guest",
  guest.guestid != "otherLinux64Guest", 
  guest.guestid != "debian6_64Guest",
  guest.guestid != "debian7_64Guest", 
  guest.guestid != "win2000ServGuest", 
  guest.guestid != "winNetStandardGuest",
  config.guestid != "vmwarePhoton64Guest",
  config.guestid != "other3xLinux64Guest",
  config.guestid != "other26xLinuxGuest",
  config.guestid != "otherLinux64Guest",
  config.guestid != "otherLinuxGuest", 
  config.guestid != "debian4Guest",
  config.guestid != "debian5Guest", 
  config.guestid != "rhel6_64Guest",
  config.guestid != "debian7_64Guest",
  config.guestid != "win2000ServGuest",
  config.guestid != "winNetStandardGuest", 
  config.name != "Sophos_UTM",
  guest.ipaddress != "172.17.0.1",
  guest.ipaddress != "172.18.0.1",
  guest.ipaddress != "172.19.0.1",
  guest.ipaddress != "172.20.0.1" 
groupby_patterns: summary.vm.parent.name
alias_pattern: config.name
```

```
bash-4.4# cat /tmp/awx_1136869_pwb914h7/vmware_vm_inventory.yml
compose:
  ansible_host: guest.ipAddress
  ansible_ssh_host: guest.ipAddress
  ansible_uuid: 99999999 | random | to_uuid
  availablefield: availableField
  configissue: configIssue
  configstatus: configStatus
  customvalue: customValue
  effectiverole: effectiveRole
  guestheartbeatstatus: guestHeartbeatStatus
  layoutex: layoutEx
  overallstatus: overallStatus
  parentvapp: parentVApp
  recenttask: recentTask
  resourcepool: resourcePool
  rootsnapshot: rootSnapshot
  triggeredalarmstate: triggeredAlarmState
filters:
- runtime.powerstate == "poweredOn"
- guest.guestid != "vmwarePhoton64Guest"
- guest.guestid != "other26xLinuxGuest"
- guest.guestid != "other3xLinux64Guest"
- guest.guestid != "otherLinux64Guest"
- guest.guestid != "debian6_64Guest"
- guest.guestid != "debian7_64Guest"
- guest.guestid != "win2000ServGuest"
- guest.guestid != "winNetStandardGuest"
- config.guestid != "vmwarePhoton64Guest"
- config.guestid != "other3xLinux64Guest"
- config.guestid != "other26xLinuxGuest"
- config.guestid != "otherLinux64Guest"
- config.guestid != "otherLinuxGuest"
- config.guestid != "debian4Guest"
- config.guestid != "debian5Guest"
- config.guestid != "rhel6_64Guest"
- config.guestid != "debian7_64Guest"
- config.guestid != "win2000ServGuest"
- config.guestid != "winNetStandardGuest"
- config.name != "Sophos_UTM"
- guest.ipaddress != "172.17.0.1"
- guest.ipaddress != "172.18.0.1"
- guest.ipaddress != "172.19.0.1"
- guest.ipaddress != "172.20.0.1"
hostnames:
- config.name
keyed_groups:
- key: summary.vm.parent.name
  prefix: ''
  separator: ''
plugin: community.vmware.vmware_vm_inventory
properties:
- availableField
- configIssue
- configStatus
- customValue
- datastore
- effectiveRole
- guestHeartbeatStatus
- layout
- layoutEx
- name
- network
- overallStatus
- parentVApp
- permission
- recentTask
- resourcePool
- rootSnapshot
- snapshot
- triggeredAlarmState
- value
- capability
- config
- guest
- runtime
- storage
- summary
strict: false
with_nested_properties: true
```

##### EXPECTED RESULTS

Currently 66 hosts matching these filters (mostly but not only guestid other4xLinux64Guest) are added to inventory and grouped by their parent VM folder in vCenter.

##### ACTUAL RESULTS

All 292 VMs are added as hosts, even those that are powered off. That includes Windows servers, appliances and legacy VMs too old for Ansible (Python 3 etc). No hosts are grouped.

``` 
2.519 INFO     Updating inventory 3: vcsa01 <company>RZ
    3.097 INFO     Reading Ansible inventory source: /tmp/awx_1136869_pwb914h7/vmware_vm_inventory.yml
    3.099 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    3.099 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.099 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
   72.210 ERROR    ansible-inventory 2.9.11
   72.210 ERROR      config file = /etc/ansible/ansible.cfg
   72.210 ERROR      configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   72.210 ERROR      ansible python module location = /usr/lib/python3.6/site-packages/ansible
   72.210 ERROR      executable location = /usr/bin/ansible-inventory
   72.211 ERROR      python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
   72.211 ERROR    Using /etc/ansible/ansible.cfg as config file
   72.211 ERROR    Parsed /tmp/awx_1136869_pwb914h7/vmware_vm_inventory.yml inventory source with auto plugin
   72.786 INFO     Processing JSON output...
   72.798 INFO     Loaded 0 groups, 292 hosts
2020-08-13 11:35:34,266 DEBUG    awx.main.models.inventory Going to update inventory computed fields, pk=3
2020-08-13 11:35:34,281 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=3, in 0.014 seconds
   77.032 INFO     Inventory import completed for Import vcsa01.<company>.dom in 74.5s
```

##### ADDITIONAL INFORMATION

I originally used more filters like `{{ 'freebsd' not in config.guestid }}` however those are translated as strings in the plugin YAML such as

```
filters:
[...]
- '''freebsd'' not in guest.guestid'
```

I'd like to be able to use those again instead of adding a filter line for every VM to be excluded by `config.name`.

Removing the groupby_patterns line doesn't change the outcome.
From many hours of testing I found that `config.name != "xyz"` does indeed reduce the amount of imported hosts.
However all other filters including `runtime.powerstate == "poweredOn"` do not.
I also tried using `config.guestid == "other4xLinux64Guest"` instead of all the `!=`, in case filters were OR statements instead of AND, which did not work either.
Though that wouldn't have imported all required hosts anyway.

Running the import without any source vars imports 251 hosts (all powered on VMs) and groups them by guestid.
I could rebuild our job templates to limit to certain groups instead of whole inventory however I'd rather only have hosts in AWX that can actually be accessed by Ansible.

`runtime.powerstate` working by default but not with my filters seems to suggest some logical issue with my conditions. However I can't find anything and these exact conditions work fine with the inventory script.
