### ISSUE TITLE
Workflow Approval Templates are currently unexportable

### ISSUE THREAD

**Issue by zedr** [ansible/awx#7946]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The CLI command `export` cannot serialize any Approval Template nodes belonging to a Workflow Job Template. The reason given is that the command is "unable to construct a natural key for foreign key 'unified_job_template'". The Workflow is exported but lacks the node, leading to an incomplete workflow.

Perhaps it is due to a missing `identifier` attribute for this type of node?

**Edit**: renamed from "Lack of natural key makes Workflow Approval Templates unexportable"

##### ENVIRONMENT
* AWX version: Tower 7.3.1
* AWX install method: install script
* Ansible version:  2.9.11
* Operating System: RHEL
* Web Browser: Google Chrome

##### STEPS TO REPRODUCE

1. Create a new Workflow Job Template
2. Add a Job Template node
3. Add an Approval node
4. Run the AWX CLI export command, e.g. ` awx --conf.host=https://tower.local --conf.token=<MYTOKEN> --workflow_job_templates=12 export`
5. Observe the following warning log messages:
    > This object does not have a natural key: /api/v2/workflow_approval_templates/14/
    > Unable to construct a natural key for foreign key 'unified_job_template' of object /api/v2/workflow_job_template_nodes/2/.

##### EXPECTED RESULTS

The Approval node should appear inside `workflow_job_templates[].related.workflow_nodes`.

##### ACTUAL RESULTS

The Approval node is missing, e.g.:
```yaml
workflow_job_templates:
- allow_simultaneous: false

  (...)

  related:

    (...)
    workflow_nodes:
    - all_parents_must_converge: false
      diff_mode: null
      extra_data: {}
      identifier: 67024aa7-36fe-46c4-8665-b0ca825ca386
      inventory: null
      job_tags: null
      job_type: null
      limit: null
      natural_key:
        identifier: 67024aa7-36fe-46c4-8665-b0ca825ca386
        type: workflow_job_template_node
        workflow_job_template:
          name: Test Workflow
          organization:
            name: Default
            type: organization
          type: workflow_job_template
      related:
        always_nodes: []
        credentials: []
        failure_nodes: []
        success_nodes:
        - identifier: 38efaf33-21f2-4049-8bc5-b7537181255e
          type: workflow_job_template_node
          workflow_job_template:
            name: Test Workflow
            organization:
              name: Default
              type: organization
            type: workflow_job_template
      scm_branch: null
      skip_tags: null
      unified_job_template:
        name: Demo Job Template
        organization:
          name: Default
          type: organization
        type: job_template
      verbosity: null
      workflow_job_template:
        name: Test Workflow
        organization:
          name: Default
          type: organization
        type: workflow_job_template
    - !!! APPROVAL NODE SHOULD BE HERE !!!
  scm_branch: null
  survey_enabled: true
  webhook_credential: null
  webhook_service: ''
```

**Comment by snooyen** [comment]
I'm running into this as well when using awx.awx collection 16.0.0 (tried via awxkit awx cli 16.0.0 as well)

**Comment by ghost** [comment]
Hi,

We are trying to import a workflow with some approval. 
To know the syntax of this part we have tried an export of an existing workflow with some approval but isn't working. 

Even if the export wasn't possible related to this issue.
Does anyone have the syntax to do an import?

```yml
workflow_job_templates:
- allow_simultaneous: false
  name: test_approval
  natural_key:
    name: test_approval
    organization:
      name: my_organisation_test
      type: organization
    type: workflow_job_template
  organization:
    name: my_organisation_test
    type: organization
  related:
    workflow_nodes:
    - all_parents_must_converge: true
      identifier: test-approval
      natural_key:
        identifier: test-approval
        type: workflow_job_template_node
        workflow_job_template:
          name: test_approval
          organization:
            name: my_organisation_test
            type: organization
          type: workflow_job_template
      unified_job_template: # We are looking to write this part
        name: my_approval
        description: "Do this ?"
        timeout: 30
```

In this case I have on the UI of Ansible tower the image bellow. 

![Screen Shot 2021-11-19 at 8 42 49 PM](https://user-images.githubusercontent.com/25638379/142709895-471736dc-cebf-47cf-8186-f092c4676b42.png)

Thank you in advance to any one who may be able to give me some ideas.
