### ISSUE TITLE
Running awx.awx.tower_export module as an AWX job does not support job_templates parameter.

### ISSUE THREAD

**Issue by snooyen** [ansible/awx#8108]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I can run a playbook that uses the awx.awx.tower_export module locally, but this fails when being run as an AWX job.

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: K8s
* Ansible version:  2.9.11
* Operating System: Mac OSX
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1. Install the awx.awx collection version 14.1.0. 
2. Run the provided playbook locally via `ansible-playbook` -- runs sucessfully
3. Run the provided playbook as an AWX Job 

Playbook:
```
---
- name: awx assets export
  hosts: localhost
  debugger: on_failed
  gather_facts : false
  become: false
  tasks:
    - name: export job templates
      awx.awx.tower_export:
        job_templates: 'all'
        tower_host: "{{ source_awx }}"
        tower_username: "{{ source_awx_username }}"
        tower_password: "{{ source_awx_password }}"
      register: export_results

    - copy: content="{{ export_results.assets }}" dest=~/Tmp/awx_export.json
```

##### EXPECTED RESULTS

```
PLAY [awx assets export] ***************************************************************************************************************************

TASK [export job templates] ************************************************************************************************************************
ok: [localhost]

TASK [copy] ****************************************************************************************************************************************
ok: [localhost]

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```

PLAY [awx assets export] *******************************************************
TASK [export job templates] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (awx.awx.tower_export) module: job_templates Supported parameters include: all, tower_config_file, tower_host, tower_oauthtoken, tower_password, tower_username, validate_certs"}

```

**Comment by snooyen** [comment]
https://github.com/ansible/awx/blob/caa7b43fe00d290c4ef01f9b8ca18fd26122ce2e/awx_collection/plugins/modules/tower_export.py#L108

@john-westcott-iv 

Shouldn't the module define `job_templates` in the argument spec?

**Comment by AlanCoding** [comment]
That is added as it loops over `EXPORTABLE_RESOURCES`.

See example:

```yaml
- name: Export a job template named "My Template" and all Credentials
  tower_export:
    job_template: "My Template"
    credential: 'all'
```

I don't know how this worked for you locally, maybe you have an old version of the collection or something?
