### ISSUE TITLE
dynamic group creation with yaml inventory

### ISSUE THREAD

**Issue by sentient** [ansible/awx#8114]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I use an ec2 dynamic inventory plugin (called from a repository resource), combined with a yaml inventory plugin.

I try to create dynamic parent group . e.g. a monitoring group that is the parent of the elastic group and kibana group.
Described as in https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html#examples

```
all: 
  vars:
    all_var: whatever
          
  children:
    monitoring:
       vars:
          all_var: override 
      children:
        elastic:
        kibana:

```
It has the 'empty' hosts section. but I thought that issue was fixed quite some time ago ?

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker
* Ansible version:  2.9.11
* Operating System: Ubuntu
* Web Browser:

##### EXPECTED RESULTS

- I don't see the 'Monitoring' group created
- I don't see variables defined at sub groups populated. 

[WARNING]: Could not match supplied host pattern, ignoring: monitoring

(but I could do it on 'elastic'

Now when I create different files per group

all.yaml
elastic.yaml
kibana.yaml

I am able to set variables on a different group. 

So how can the inventory file create new groups. 

Or is the yaml inventory plugin not supported?
