### ISSUE TITLE
DEFAULT_ROLES_PATH contents not same as ansible-playbook roles search path

### ISSUE THREAD

**Issue by yurtesen** [ansible/awx#8143]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When I run a playbook, the paths searched for roles are
```
/tmp/awx_15_o_yqzfv6/project/playbooks/roles:/tmp/awx_15_o_yqzfv6/requirements_roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/awx_15_o_yqzfv6/project/playbooks
```
But when I include a role
```
- name: Include myrole
  include_tasks: "{{lookup('first_found', params)}}"
  vars:
    params:
      files: myrole/tasks/myfile_upload.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"
```
The DEFAULT_ROLES_PATH contains
```
['/tmp/awx_41_1yll22ps/requirements_roles', '/var/lib/awx/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']"
```

I believe there should not be any difference in role search paths and DEFAULT_ROLES_PATH

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker
* Ansible version:  2.9.11
* Operating System: Ubuntu 20.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Use `include_tasks` and search for DEFAULT_ROLES_PATH (see above for example task)

##### EXPECTED RESULTS

I expected DEFAULT_ROLES_PATH to contain
```
/tmp/awx_15_o_yqzfv6/project/playbooks/roles:/tmp/awx_15_o_yqzfv6/requirements_roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/awx_15_o_yqzfv6/project/playbooks
```

##### ACTUAL RESULTS

DEFAULT_ROLES_PATH contains
```
['/tmp/awx_41_1yll22ps/requirements_roles', '/var/lib/awx/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']"
```
