### ISSUE TITLE
awx.awx.tower_settings returns changed, but no change is applied

### ISSUE THREAD

**Issue by zigford** [ansible/awx#8270]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Simple task:
```
- name: Set LDAP Server
  awx.awx.tower_settings:
    settings:
      AUTH_LDAP_SERVER_URI: "ldaps://dc07.example.com:636"
```
returns changed, but debugging with `-vvv` shows unchanged:

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "name": null,
            "settings": {
                "AUTH_LDAP_SERVER_URI": "ldaps://dc07.example.com:636"
            },
            "tower_config_file": null,
            "tower_host": null,
            "tower_oauthtoken": null,
            "tower_password": null,
            "tower_username": null,
            "validate_certs": null,
            "value": null
        }
    },
    "old_values": {
        "AUTH_LDAP_SERVER_URI": "ldaps://dc06.example.com:636"
    },
    "values": {
        "AUTH_LDAP_SERVER_URI": "ldaps://dc06.example.com:636"
    }
}
META: ran handlers
META: ran handlers
```

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.0
* Operating System: Gentoo
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Setup AWX and get LDAP working manually via the Web interface to confirm settings.
Use the API to get LDAP settings and attemp to set them using tower_settings.
Full task can be seen here: https://zigford.org/awx_config_settings.txt
However, even attempting to change one setting does not work.

##### EXPECTED RESULTS

Settings are applied and visible in the interface or seen via the API

##### ACTUAL RESULTS

Nothing changes. If no settings were present before, no settings are present after running the task.
If attempting to change a setting, the change is not applied.

**Comment by beeankha** [comment]
On a 14.1.0 version of AWX I've run a playbook containing the following: 

```
- name: Configure LDAP settings
  tower_settings:
    settings:
      AUTH_LDAP_SERVER_URI: "ldaps://dc06.example.com:636"
      AUTH_LDAP_BIND_DN: "CN=AuthLDAP,OU=Service Accounts,OU=Utility,DC=example,DC=com"
      AUTH_LDAP_BIND_PASSWORD: ""
      AUTH_LDAP_START_TLS: false
      AUTH_LDAP_CONNECTION_OPTIONS:
        OPT_REFERRALS: '0'
        OPT_NETWORK_TIMEOUT: 30
      AUTH_LDAP_USER_SEARCH:
        - - "OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          - SCOPE_SUBTREE
          - "(sAMAccountName=%(user)s)"
        - - "OU=Staff,DC=example,DC=com"
          - SCOPE_SUBTREE
          - "(sAMAccountName=%(user)s)"
      AUTH_LDAP_USER_DN_TEMPLATE:
      AUTH_LDAP_USER_ATTR_MAP:
        first_name: givenName
        last_name: sn
        email: mail
      AUTH_LDAP_GROUP_SEARCH:
        - "OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
        - SCOPE_SUBTREE
        - "(objectClass=group)"
      AUTH_LDAP_GROUP_TYPE: ActiveDirectoryGroupType
      AUTH_LDAP_GROUP_TYPE_PARAMS: {}
      AUTH_LDAP_REQUIRE_GROUP:
      AUTH_LDAP_DENY_GROUP:
      AUTH_LDAP_USER_FLAGS_BY_GROUP:
        is_superuser:
          - "CN=GG_AWX_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
      AUTH_LDAP_ORGANIZATION_MAP:
        Company:
          users: "CN=GG_Infrastructure_Team_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          admins: "CN=GG_AWX_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          remove_admins: true
          remove_users: true
      AUTH_LDAP_TEAM_MAP:
        Servers and Storage:
          users: "CN=GG_Infrastructure_Team_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          organization: Company
          remove: true
        AppArchitecture:
          users: "CN=GG_ArchitectureDevelopment_Admins,OU=Privileged Users and Groups,OU=Utility,DC=example,DC=com"
          organization: Company
          remove: true

- name: Change LDAP Server URI
  tower_settings:
    settings:
      AUTH_LDAP_SERVER_URI: "ldaps://dc07.example.com:636"
```
and the output I get for that second task (my attempt to change the `AUTH_LDAP_SERVER_URI` using the `tower_settings` module) is: 
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "name": null,
            "settings": {
                "AUTH_LDAP_SERVER_URI": "ldaps://dc07.example.com:636"
            },
            "tower_config_file": null,
            "tower_host": [host url],
            "tower_oauthtoken": null,
            "tower_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tower_username": [username],
            "validate_certs": false,
            "value": null
        }
    },
    "old_values": {
        "AUTH_LDAP_SERVER_URI": "ldaps://dc06.example.com:636"
    },
    "values": {
        "AUTH_LDAP_SERVER_URI": "ldaps://dc07.example.com:636"
    }
}
```
which shows that the results do indeed change, and the UI displays the following:

<img width="982" alt="Screen Shot 2020-10-02 at 4 21 13 PM" src="https://user-images.githubusercontent.com/28930622/94966482-5bcd8580-04cb-11eb-8548-33a97eda3b05.png">


I am unable to reproduce this bug. @zigford how are you authenticating to your AWX instance (i.e., env vars, tower_cli config file, etc)? Are you able to get an access log from the machine affected while running the playbook?
