### ISSUE TITLE
[awx_collection] Be able to specify "scm" as a credential type instead of "Source Control"

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#8330]
##### ISSUE TYPE
 - Feature Idea

Right now to make an SCM credential you have to do:

```
  collections:
    - awx.awx
  tasks:
    - name: a scm cred
      tower_credential:
        name: project_cred
        credential_type: "Source Control"
        organization: foo
        inputs:
          username: foo
          password: foo
```

Would prefer to be able to do:

```
  collections:
    - awx.awx
  tasks:
    - name: a scm cred
      tower_credential:
        name: project_cred
        credential_type: scm
        organization: foo
        inputs:
          username: foo
          password: foo
```
