### ISSUE TITLE
Request to /api/v2/credentials/?name=XYZ returned 2 items

### ISSUE THREAD

**Issue by sebw** [ansible/awx#8435]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

- Concerns Ansible collection `awx.awx`
- Two credentials with the same name `XYZ` in two different organizations (`org1` and `org2`)
- Create a job template using  `tower_job_template`, in `org1` and credential `XYZ`
- playbook fails with `Request to /api/v2/credentials/?name=XYZ returned 2 items`

##### ENVIRONMENT
* awx.awx collection 15.0.1
* Ansible version:  2.9.13

##### STEPS TO REPRODUCE

```
  - name: create JT | SSSD_single_VM_update                                     
    tower_job_template:                                                         
      name: job                                                                 
      description: description                                                  
      organization: org1                                                        
      tower_host: "awx.example.org"                                         
      tower_username: "admin"                                                   
      tower_password: "password"                                                  
      job_type: "run"                                                           
      inventory: "Test inventory"                                               
      project: "Provisioning"                                                   
      playbook: "provisioning.yml"                                              
      verbosity: 4                                                              
      labels: "JT"                                                              
      credentials:                                                              
        - "XYZ"                                                             
      state: "present"                                                          
      validate_certs: no
```

##### EXPECTED RESULTS

I would expect the job to find only one credential.

##### ACTUAL RESULTS

Credentials from other organizations are returned.

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Request to /api/v2/credentials/?name=XYZ returned 2 items, expected 1", "query": {"name": "XYZ"},
```
