### ISSUE TITLE
Create Ansible module for Execution Environments in AWX collection

### ISSUE THREAD

**Issue by shanemcd** [ansible/awx#8445]
I have created the beginnings of this in https://github.com/ansible/awx/pull/8030. It needs to be rounded out and tested.

**Comment by yagomarques** [comment]
we created an automated test that covers the creation and update scenarios. We also did a manual test, using the collections and it’s working.
```
- name: Create a Execution Environment
  hosts: localhost
  tasks:
    - awx.awx.tower_execution_environment:
        name: "new-ee-using-collection"
        image: "some_image"
        description: "foobar"
        organization: ""
        pull: "missing"
```
