### ISSUE TITLE
In Kubernetes container groups, user-supplied .metadata.labels is ignored

### ISSUE THREAD

**Issue by domq** [ansible/awx#8486]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Due to `awx/main/scheduler/kubernetes.py` overriding the `.metadata.labels` of the pods it creates (instead of merging them with the user-supplied `pod_spec_override`), features such as pod anti-affinity between AWX runners cannot work.

##### ENVIRONMENT
* AWX version: 15.0.1 (also present in devel)
* AWX install method: openshift
* Ansible version:  irrelevant
* Operating System: Linux (all versions)
* Web Browser: irrelevant

##### STEPS TO REPRODUCE

1. Create a Kubernetes container group with the below piece of YAML as the pod spec override
1. Run a job out of this instance group

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    deploymentconfig: ansible-runner
  namespace: wwp-test
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: deploymentconfig
                operator: In
                values:
                  - ansible-runner
  # ...
```

##### EXPECTED RESULTS

The pods run by AWX as part of the container group should contain both the custom labels and the affinity structure.

##### ACTUAL RESULTS

Only the affinity structure shows up in the `Kind: pod` Kubernetes objects, rendering the `podAntiAffinity` clause inoperative (for lack of a label to match on under `metdata`)

##### ADDITIONAL INFORMATION

The cause is the equals sign on [this line](https://github.com/ansible/awx/blob/devel/awx/main/scheduler/kubernetes.py#L132).
