### ISSUE TITLE
ansible_winrm_transport: certificate should get the pub and private key from machine credentials

### ISSUE THREAD

**Issue by MalfuncEddie** [ansible/awx#8490]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
For Linux hosts you can specify the following in the machine credential type.

- username
- password
- SSH private key
- SSH certificate 
...

It would be nice if for windows hosts it could use the same input but where de pub/private key is filled in (and mapped to the ansible_winrm_cert_pem , ansible_winrm_cert_key_pem variables.
Although windows certificate is not the recommended practice it is quite handy in some situations.

- username
- password
- winrm_cert_pem
- winrm_cert_key_pem
...

You could even use the same machine credentials
If the variable "ansible_winrm_transport: certificate" is set 

use the pub/private keys to map to ansible_winrm_cert_pem and ansible_winrm_cert_key_pem.

This way you can safely store those certificates in AWX (and not in git for instance)

Alternative:
(idea from https://github.com/ansible/awx/issues/223#issuecomment-388457636)
It would be nice to have ansible_winrm_cert_pem and ansible_winrm_cert_key_pem reference a vault variable and not a file.

**Comment by Ulfy** [comment]
How does one currently use a cert for WinRM connections? I'm struggling to get AWX to connect to WIndows host using a Machine/SSH cred. Winrm wants the pub/key path specified, but that doesn't seem to work either.

**Comment by MalfuncEddie** [comment]
I've create a custom credential to solve this
input:

```yml
fields:
  - id: cert
    type: string
    label: Certificate
    secret: true
    multiline: true
  - id: key
    type: string
    label: Key
    secret: true
    multiline: true

```
injector:

```yml
env:
  MY_WINRM_CERT: '{{ tower.filename.cert_file }}'
  MY_WINRM_KEY: '{{ tower.filename.key_file }}'
file:
  template.cert_file: '{{ cert }}'
  template.key_file: '{{ key }}'

```

use in playbook

```yml
  vars:
    ansible_connection: winrm
    ansible_winrm_cert_key_pem: '{{ lookup("env", "MY_WINRM_KEY") }}'
    ansible_winrm_cert_pem: '{{ lookup("env", "MY_WINRM_CERT") }}'
```

**Comment by db0** [comment]
Very nice @MalfuncEddie . I've tweaked the injector to the following, which avoids having to use the lookup in the playbook

```yaml
file:
  template.key_file: '{{ private_key }}'
  template.cert_file: '{{ public_cert }}'
extra_vars:
  ansible_winrm_cert_pem: '{{ tower.filename.cert_file }}'
  ansible_winrm_cert_key_pem: '{{ tower.filename.key_file }}'
```
