### ISSUE TITLE
No option for credential input_source in either awx-cli or awx.awx ansible collection

### ISSUE THREAD

**Issue by howardjones** [ansible/awx#8495]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

With awx-cli and awx.awx, you can create a credential, but you can't link the fields to input_sources for external vaults.

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: kubernetes
* Ansible version:  2.9.13
* Operating System: CentOS 8 inside the container 
* Web Browser: Chrome 86

##### STEPS TO REPRODUCE

* create a credential in the web UI, and link it to a keyvault

* fetch back the same credential via awx-cli

    awx-cli credential get 10 -f json

##### EXPECTED RESULTS

I expected to see a section in the retrieved object for `input_sources` showing field names and the "back end" credential and metadata that they are actually being pulled from. Neither awx-cli or awx.awx has any options to set these values either.

##### ACTUAL RESULTS

No such data.

##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Credentials/Credentials_credentials_input_sources_create

POST /api/v2/credentials/{id}/input_sources/

**Comment by gazzerman2** [comment]
I see the same in 15.0.1 and I had it in 14.0.1 also - this is blocking me.
![Uploading Screenshot 2020-10-30 at 11.43.21.png…]()

**Comment by gazzerman2** [comment]
I see the same in 15.0.1 and it was the same in 14.0.1 also. This is blocking as I can't connect to a github repository.
![Screenshot 2020-10-30 at 11 43 21](https://user-images.githubusercontent.com/56310190/97701559-83e9dd80-1aa5-11eb-9a7b-426b9fa79d77.png)

**Comment by howardjones** [comment]
Also for /api/v2/organizations/2/galaxy_credentials/

**Comment by sean-m-sullivan** [comment]
As for galaxy credentials, the following works 
```
    - name: Create tower organization that pulls content from galaxy.ansible.com
      tower_organization:
        name: Foo
        state: present
    - name: Add Credential Into Tower
      tower_credential:
        name: Workshop Credential
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        organization: Foo
        inputs:
          url: "https://galaxy.ansible.com/"
          token: asdf
          auth_url: asdf
    - name: Create tower organization that pulls content from galaxy.ansible.com
      tower_organization:
        name: Foo
        state: present
        galaxy_credentials:
          - Workshop Credential
```

And for credential input sources via awx.awx, given the credentials have been created
```
    - name: Use CyberArk Lookup credential as password source
      tower_credential_input_source:
        input_field_name: password
        target_credential: gitlab
        source_credential: test
        metadata:
          object_query: "Safe=MY_SAFE;Object=awxuser"
          object_query_format: "Exact"
        state: present
```

However at the moment awxkit awx import/export does not do credential input sources, but does credential types and credentials.
