### ISSUE TITLE
Azure Collection error with AWX 15.0.01

### ISSUE THREAD

**Issue by skpy** [ansible/awx#8560]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Unable to use Azure collections.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* AWX Operating System: CentOS 7.8.2003 (Core)
* Client Web Browser: Firefox for MacOS

##### STEPS TO REPRODUCE

We would like to use the Azure Ansible collection to use AWX to interact with Azure.  We have a relatively simple play with a survey:
```
---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Generate password
      set_fact:
        password: "{{ host | password_hash('sha512') }}"

    - name: Create app Service Principal
      azure.azcollection.azure_rm_adserviceprincipal:
        app_id: "{{ azure_app_id }}"
        state: present
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"
      register: azure_output

    - name: Set SPN password
      azure.azcollection.azure_rm_adpassword:
        app_id: "{{ azure_app_id }}"
        service_principal_object_id: "{{ azure_output.object_id }}"
        state: present
        value: "{{ password }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_subscription_id }}"

- hosts: {{ host }}.internal.domain
  tasks:
    # write a file to /etc/creds/appname.credentials
    # with object_id, password, subscription_id and tenant_id
    - name: Save the data
      template:
        src: az_spn.j2
        dest: "/etc/creds/{{ appname }}.credentials"
        owner: root
        group: root
        mode: '0400'
```
This is very much a work in progress, as we're still figuring Azure out.

The repo of this playbook contains a `/collections/requirements.yml` file:
```
collections:
  - name: azure.azcollection
    source: https://galaxy.ansible.com
```

##### EXPECTED RESULTS

We expect AWX to connect to Azure to do something. We fully expect an error of some sort from Azure.

##### ACTUAL RESULTS

```
Identity added: /tmp/awx_1576_rr4u306g/artifacts/1576/ssh_key_data (/tmp/awx_1576_rr4u306g/artifacts/1576/ssh_key_data)
ansible-playbook 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_1576_rr4u306g/tmp3q10xohc as it did not pass its verify_file() method
Parsed /tmp/awx_1576_rr4u306g/tmp3q10xohc inventory source with script plugin
PLAYBOOK: app_spn.yml **********************************************************
2 plays in app_spn.yml
PLAY [localhost] ***************************************************************
META: ran handlers
TASK [Generate password] *******************************************************
task path: /tmp/awx_1576_rr4u306g/project/app_spn.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "password": "redacted"
    },
    "changed": false
}
TASK [Create app Service Principal] ********************************************
task path: /tmp/awx_1576_rr4u306g/project/app_spn.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325 `" && echo ansible-tmp-1604758685.4668112-497-185373600537325="` echo /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325 `" ) && sleep 0'
Using module file /tmp/awx_1576_rr4u306g/requirements_collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adserviceprincipal.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-485_ecgb5z0/tmpxo57n59w TO /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325/AnsiballZ_azure_rm_adserviceprincipal.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325/ /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325/AnsiballZ_azure_rm_adserviceprincipal.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325/AnsiballZ_azure_rm_adserviceprincipal.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1604758685.4668112-497-185373600537325/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_adserviceprincipal_payload_8bre0fp1/ansible_azure.azcollection.azure_rm_adserviceprincipal_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 238, in <module>
    from azure.mgmt.privatedns import PrivateDnsManagementClient
ModuleNotFoundError: No module named 'azure.mgmt.privatedns'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "app_id": "redacted",
            "app_role_assignment_required": null,
            "auth_source": "auto",
            "cert_validation_mode": null,…
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

##### ADDITIONAL INFORMATION
I read on #7536 about the venv.  Naively I tried connecting to the awx_task container, sourcing the `/var/lib/awx/venv/ansible/bin/activate` virtual environment, and then running `ansible-galaxy collection install azure.azcollection`.  This didn't work, either.

Is there a way to use the Azure Collection with AWX 15?  Or do we need to wait for the new "execution environments" feature?
