### ISSUE TITLE
ansible.tower.tower_group module is having an erratic behavior.

### ISSUE THREAD

**Issue by zaskan** [ansible/awx#8579]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Running the tower_group module, it is erratically removing the existing hosts from the existing groups instead of preserve them there. As I can see, the group IDs are preserved (it is not removing them)

##### ENVIRONMENT
* AWX version: 3.7.2
* AWX install method: Bundle Standalone
* Ansible version:  2.9.1
* Operating System: RHEL 8.2
* Web Browser: Chrome 86.0.4240.111

##### STEPS TO REPRODUCE

I created several hosts using the following template. It creates new hosts and assign them to 2 different groups depending on some variables. In this example, I launched 5 executions with different hostnames simultaneously.

```
#Add Host Linux to inventory LINUX_POSTINSTALL
- name: Add tower host (Linux)
  ansible.tower.tower_host:
    name: "{{ vm_hostname }}"
    tower_oauthtoken: "xxxxxxxxxxxxxxxx"
    validate_certs: no
    description: "{{ vm_hostname }}"
    inventory: "LINUX_POSTINSTALL"
    state: present
  when: machine_os_fact == 'RHEL'

#Add group Linux version to Host Linux
- name: Add tower group (RHEL version)
  ansible.tower.tower_group:
    name: "{{ rhel_version_fact }}"
    tower_oauthtoken: "xxxxxxxxxxxxxxxxxxxxxxxx"
    validate_certs: no
    inventory: "LINUX_POSTINSTALL"
    state: present
    hosts: "{{ vm_hostname }}"
  when: machine_os_fact == 'RHEL'

#Add group Linux localisation to Host Linux
- name: Add tower group (RHEL localisation)
  ansible.tower.tower_group:
    name: "{{ rhel_localisation_fact }}"
    tower_oauthtoken: "xxxxxxxxxxxxxxxxxxxxx"
    validate_certs: no
    inventory: "LINUX_POSTINSTALL"
    state: present
    hosts: "{{ vm_hostname }}"
  when: machine_os_fact == 'RHEL'
```
As you can see in the image below, apparently the module is adding to the group only the last execution.

![image](https://user-images.githubusercontent.com/24324312/98976456-a9e89680-2517-11eb-900b-04d0fd7d7060.png)

In the job output, we can see how the module is returning that the task are done ok. In this case, it is returning that "hostname3" is added to the groups.

```
ansible-playbook 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible/lib/python2.7/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible/bin/ansible-playbook
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_624_1dt9fhbh/tmphd1xuum6 as it did not pass its verify_file() method
Parsed /tmp/awx_624_1dt9fhbh/tmphd1xuum6 inventory source with script plugin
PLAYBOOK: create_group.yml *****************************************************
1 plays in create_group.yml
PLAY [Test] ********************************************************************
TASK [Gathering Facts] *********************************************************
task path: /tmp/awx_624_1dt9fhbh/project/create_group.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414 `" && echo ansible-tmp-1605200082.3-263112399318414="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414 `" ) && sleep 0'
Using module file /var/lib/awx/venv/ansible/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3hG7UUy/tmpZKaMGV TO /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414/ /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1605200082.3-263112399318414/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers
TASK [Add tower host (Linux)] **************************************************
task path: /tmp/awx_624_1dt9fhbh/project/create_group.yml:31
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133 `" && echo ansible-tmp-1605200090.21-2584096818133="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133 `" ) && sleep 0'
Using module file /tmp/awx_624_1dt9fhbh/requirements_collections/ansible_collections/ansible/tower/plugins/modules/tower_host.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3hG7UUy/tmpP1yxME TO /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133/AnsiballZ_tower_host.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133/ /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133/AnsiballZ_tower_host.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133/AnsiballZ_tower_host.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1605200090.21-2584096818133/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "id": 15, 
    "invocation": {
        "module_args": {
            "description": "hostname3", 
            "enabled": true, 
            "inventory": "LINUX_POSTINSTALL", 
            "name": "hostname3", 
            "new_name": null, 
            "state": "present", 
            "tower_config_file": null, 
            "tower_host": null, 
            "tower_oauthtoken": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "tower_password": null, 
            "tower_username": null, 
            "validate_certs": false
        }
    }, 
   …
TASK [Add tower group (RHEL version)] ******************************************
task path: /tmp/awx_624_1dt9fhbh/project/create_group.yml:56
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155 `" && echo ansible-tmp-1605200097.5-228059388741155="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155 `" ) && sleep 0'
Using module file /tmp/awx_624_1dt9fhbh/requirements_collections/ansible_collections/ansible/tower/plugins/modules/tower_group.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3hG7UUy/tmpM6SQM0 TO /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155/AnsiballZ_tower_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155/ /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155/AnsiballZ_tower_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155/AnsiballZ_tower_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1605200097.5-228059388741155/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "id": 7, 
    "invocation": {
        "module_args": {
            "children": null, 
            "description": null, 
            "hosts": [
                "hostname3"
            ], 
            "inventory": "LINUX_POSTINSTALL", 
            "name": "8.2", 
            "new_name": null, 
            "tower_config_file": null, 
            "tower_host": null, 
            "tower_oauthtoken": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "tower_password": null, 
            "tower_username": null, 
            "validate_certs": false, 
            "variables": null
        }
    }
}
TASK [Add tower group (RHEL localisation)] *************************************
task path: /tmp/awx_624_1dt9fhbh/project/create_group.yml:67
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292 `" && echo ansible-tmp-1605200104.56-170507897592292="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292 `" ) && sleep 0'
Using module file /tmp/awx_624_1dt9fhbh/requirements_collections/ansible_collections/ansible/tower/plugins/modules/tower_group.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3hG7UUy/tmpENU7Vr TO /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292/AnsiballZ_tower_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292/ /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292/AnsiballZ_tower_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292/AnsiballZ_tower_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1605200104.56-170507897592292/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "id": 9, 
    "invocation": {
        "module_args": {
            "children": null, 
            "description": null, 
            "hosts": [
                "hostname3"
            ], 
            "inventory": "LINUX_POSTINSTALL", 
            "name": "location", 
            "new_name": null, 
            "tower_config_file": null, 
            "tower_host": null, 
            "tower_oauthtoken": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "tower_password": null, 
            "tower_username": null, 
            "validate_certs": false, 
            "variables": null
        }
    }
}
META: ran handlers
META: ran handlers
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
```
If I run the job template again using an existing host, it removes every hosts from the existing groups and add it only the current hostname. 

![image](https://user-images.githubusercontent.com/24324312/98977581-0a2c0800-2519-11eb-97e2-56f7a8dd8e9b.png)

##### EXPECTED RESULTS

The current group assignation should be preserved if state = present.
##### ACTUAL RESULTS
The current group assignation is removed erratically.

**Comment by john-westcott-iv** [comment]
This is a common issue people run into. In the awx.awx collection things like the host list are descriptive. Meaning that you are telling Ansible exactly what state to put Tower into. As you found in your example above the collection is functioning as designed as you are using Ansible to put Tower into a state where the groups have a single host and you are calling that repeatedly which is causing whatever finished last to be the state that Tower is in.

Your request to modify the behavior to be additive, preserving the current state of the hosts in the inventory, if `state = present` introduces its own problem of how would you know when to remove hosts from the list? We could potentially say that if state = absent and hosts list is present than remove those hosts but what would happen if you were passing in a variable that you thought was set but it wasn't? In that case we would end up removing the entire group which is a dangerous behavior. We could also potentially add a flag like "add_hosts_to_existng" but this would open up another can of worms. In the case of this module `children` is another list so we would also need an "add_children_to_existing" flag. Other modules, like tower_job_template have even more parameters, each which would need their own additive flags which would make the modules complicated.

That said, all is not doom and gloom and I think you can achieve your desired behavior with the existing collection. To achieve this try using the `awx.awx.tower_api` plugin. This plugin allows you to get the current state of things like what hosts are in an existing group through the API. Here is an example playbook that may help you achieve what you are attempting to do:
```
---
- name: Test adding to a tower group
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx
  vars:
    inventory_name: "Group Add Test Inventory"
    group_name: "My Group"
  tasks:
    - name: Make sure my inventory is created
      tower_inventory:
        name: "{{ inventory_name }}"
        organization: "Default"
      register: the_inventory

    - name: Make sure my hosts to the inventory
      tower_host:
        name: "{{ item }}"
        inventory: "{{ inventory_name }}"
      loop:
        - "host1"
        - "host2"

    - name: Make sure my group exists
      tower_group:
        name: "{{ group_name }}"
        inventory: "{{ inventory_name }}"
      register: the_group

    - name: Add host1 to the tower group
      tower_group:
        name: "{{ group_name }}"
        inventory: "{{ inventory_name }}"
        state: present
        hosts: "{{ lookup('awx.awx.tower_api', 'groups/{}/all_hosts'.format(the_group.id), return_ids=True, wantlist=True) + [ 'host1' ] }}"

    - name: Add host2 to the tower group
      tower_group:
        name: "{{ group_name }}"
        inventory: "{{ inventory_name }}"
        state: present
        hosts: "{{ lookup('awx.awx.tower_api', 'groups/{}/all_hosts'.format(the_group.id), return_ids=True, wantlist=True) + [ 'host2'] }}"
```

Here you can see me getting the existing hosts for the group I created and then adding the host[12] to the list that I get back from Tower using the plugin. This way, the new host will always be added to the existing list of hosts.

There are two things I need to mention with this solution:

1) I see you were setting tower_oauthtoken and validate_certs in your example, connection info will also have to be passed into the lookup plugin. In my example I had environment variables set in my shell so auth settings were picked up by both the modules and the lookup plugin.

2) You mentioned running your play multiple times but didn't say if they were concurrent or serial executions. If they are concurrent have to think about the order of the multiple ansible processes. In my example above, the lookup plugin and tower_group are not running within a "transaction" meaning that if you had multiple forks running my playbook the call to lookup_api could return the same list, let's say an empty list. Then one fork could  could start by adding its host to the empty list and write that into Tower. The second fork will then write its host into the empty list it received and then write the new list into Tower. Without some kind of concurrency protection your tower could end up with similar or even more chaotic results that you have already seen.

Please let me know if you have an issues with the solution or any follow up questions.
