### ISSUE TITLE
Prepopulate surveys with values from yaml / ini

### ISSUE THREAD

**Issue by b0r1sp** [ansible/awx#859]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 - UI

##### SUMMARY

Would be nice to propulate a survey by reading in data from e.g. an .ini or .yaml file. Thus, these config files can be tracked in a git-repo.

##### ADDITIONAL INFORMATION

Examples for configuration YAML or INI style: 

##### YAML:

```yaml
.survey:
    name: "deployment"
    version: "v0.1"
    description: "Deploys this and that"
    questions:
        - variable: "WORK_DIR"
          description: "Target work directory"
          label: "Work directory:"
          required: true
          default: "/opt/domain_of_project"
          type: "string"
        - variable: "REPO"
          description: "Choose version"
          label: "Select Git Repository:"
          description: "Select which repo should be cloned for deployment"
          required: true
          default: customers/coke
          type: enum   
          options:
            - customers/fanta
            - customers/coke
            - customers/sprite
``` 

##### INI:

```ini

[config]
name=deployment
version=v0.1
description=Deploys this and that

[question 1]
variable=WORK_DIR
description=Target work directory
label=Work directory:
required=True
default=/opt/domain_of_project
type=string

[question 2]
variable=REPO
description=Select which repo should be cloned for deployment
label=Select Git Repository:
required=True
default=customers/coke
type=enum   
options=
  customers/fanta
  customers/coke
  customers/sprite
 
```
