### ISSUE TITLE
DockerHub Pull Rate Limiting: Add ability to specify alternative registry for Docker CentOS 8 and Redis images

### ISSUE THREAD

**Issue by isuftin** [ansible/awx#8639]
##### ISSUE TYPE

Because DockerHub limits pulls to a client, we're seeing issues in building AWX when Docker attempts pulling CentOS 8 and Redis images. We do have an in-house Artifactory server that does serve as a Docker image registry which we also use to mirror DockerHub and cache images locally. While we can set `dockerhub_base` in inventory to `my.artifactory.instance/docker-official-mirror/ansible`, the CentOS 8 and Redis images are hard-coded to use DockerHub.

To get around this, part of my playbook for building AWX includes:

```yml

    - name: Pull CentOS 8 image from DockerHub via Artifactory
      docker_image:
        name: my.artifactory.instance/docker-official-mirror/centos:8
        state: present
        pull: yes
      register: centos_image_pull

    - name: Pull Redis image from DockerHub via Artifactory
      docker_image:
        name: my.artifactory.instance/docker-official-mirror/redis:latest
        state: present
        pull: yes
      register: redis_image_pull

    - name: Tag CentOS 8 Image
      docker_image:
        name: my.artifactory.instance/docker-official-mirror/centos:8
        repository: centos:8
        pull: no
        state: present
      when: centos_image_pull.changed

    - name: Tag Redis Image
      docker_image:
        name: my.artifactory.instance/docker-official-mirror/redis:latest
        repository: redis:latest
        pull: no
        state: present
      when: redis_image_pull.changed

```

Then during the build stage, Docker just uses the local registry's images. However, it would be easier if we could specify something along the lines of `dockerhub_base_redis`, `dockerhub_base_centos` or just specify a private registry to grab ALL images from.
