### ISSUE TITLE
AWX Project module should allow forcing update

### ISSUE THREAD

**Issue by kedark3** [ansible/awx#8686]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We need to have ability to force project update in our tower using where we are using infrastructure as code. I am aware of the fact that we have `project_update` but Sean and I talked and he has initial code https://github.com/ansible/awx/compare/devel...sean-m-sullivan:project_update here.

Opening this issue to add visibility. 

Adding this enhancement will make https://github.com/redhat-cop/tower_configuration/tree/devel/roles/tower_role more useful for us(my team) as regular Tower Infra-as-Code (IaC) users.

Thanks @sean-m-sullivan

**Comment by sean-m-sullivan** [comment]
@wenottingham This feature has been added and merged, this can now be closed.

**Comment by yagomarques** [comment]
I noticed the project update is only triggering if we change something else

We use it to test.
```
    - name: Create a Project
      tower_project:
        name: "New Project - no update"
        description: "foobar"
        organization: "New Org"
        timeout: 10
        update_project: no
        scm_type: git
        scm_url: https://github.com/one-t/verification_repo.git
```

**Comment by sean-m-sullivan** [comment]
What do you mean by change something? in the previous example the update project is no, so it shouldn't trigger, and the timeout would be ignored.

I was looking at this with a 19.0.0 awx. and with this code
```
    - name: Create a Project
      awx.awx.tower_project:
        name: "New Project - no update"
        description: "foobar"
        organization: Default
        timeout: 10
        scm_type: git
        scm_url: https://github.com/one-t/verification_repo.git
        update_project: yes
```
The key here is update_project: yes , if you put no/false, it will behave like it did in the past, and not update the project, and its working as expected. If this is not the case can you go into more detail?
@yagomarques

**Comment by one-t** [comment]
Hi, Sean-

What we noticed in testing this is that the project update only occurs if the task reports a Changed status. 

Steps to reproduce:

1. Create a project using the `tower_project` task with `update_project` enabled
2. Push a new commit to the repository
3. Run the same task again

Expected result: Project update is triggered

Actual result: Project update is not triggered

Then,
1. Change something about the task- for example, change the `timeout` value to `30`
2. Run the task again

Result- timeout value is changed and the project update is triggered.

**Comment by sean-m-sullivan** [comment]
@one-t @yagomarques 
Found the issues, update is #10000

**Comment by yagomarques** [comment]
it's working! We exec the `tower_update` more than once and an update job was started for all task with the `update_project` enabled.

![image](https://user-images.githubusercontent.com/18562328/119699462-93a58680-be28-11eb-8d97-acd86b36b44a.png)

playbook:
```
- name: Create a Project
  hosts: localhost
  tasks:
    - awx.awx.tower_project:
        name: "new-awx-collection-project"
        description: "foobar"
        organization: Default
        timeout: 0
        scm_type: git
        scm_url: https://github.com/yagomarques/ansible-tower-samples
        update_project: yes
```
