### ISSUE TITLE
Redis socket issue, and work-a-round

### ISSUE THREAD

**Issue by velzend** [ansible/awx#8696]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
While trying to run a local AWX instance on my Mac using Docker and Docker compose, the OS was unable to create the socket binding for Redis. It was working without any issue before, and I think the issue started after performing the macOS Catalina upgrade to version 10.15.7 (19H15). Next, I am currently using Docker Engine version 19.03.13.

Long story short I still I have no clue why, and stopped looking for the actual root cause. 
Instead I went for a work-a-round by exposing the Redis socket volume mount point using a Busybox container.

docker-compose.yml (with the busybox work-a-round):
```yaml
version: '2'
services:

  web:
    image: ansible/awx:15.0.1
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "${PWD}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${PWD}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${PWD}/credentials.py:/etc/tower/conf.d/credentials.py"
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro"
    volumes_from:
      - redis_socket
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx:15.0.1
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "${PWD}/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "${PWD}/environment.sh:/etc/tower/conf.d/environment.sh"
      - "${PWD}/credentials.py:/etc/tower/conf.d/credentials.py"
    volumes_from:
      - redis_socket
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis:6.0.9-alpine
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "${PWD}/redis.conf:/usr/local/etc/redis/redis.conf:ro"
    volumes_from:
      - redis_socket

  redis_socket:
    image: busybox
    command: chmod 777 /var/run/redis && chown 999:1000 /var/run/redis
    volumes:
      - /var/run/redis/

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - pgdocker:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy:
      https_proxy:
      no_proxy:

volumes:
  pgdocker:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:

```

When not using the Busybox container and volume mount locally, the Redis container is unable to bind the redis.sock file and fails with the error message below:

Using the default Redis container:
```bash
$ docker-compose up redis
awx_redis is up-to-date
Attaching to awx_redis
awx_redis   | 1:C 26 Nov 2020 13:25:00.284 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
awx_redis   | 1:C 26 Nov 2020 13:25:00.284 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
awx_redis   | 1:C 26 Nov 2020 13:25:00.284 # Configuration loaded
awx_redis   | 1:M 26 Nov 2020 13:25:00.290 # Opening Unix socket: bind: Input/output error
```

Using the Alpine Redis container:
```bash
$ docker-compose up redis
Starting awx_redis ... done
Attaching to awx_redis
awx_redis   | 1:C 26 Nov 2020 13:27:17.414 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
awx_redis   | 1:C 26 Nov 2020 13:27:17.414 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
awx_redis   | 1:C 26 Nov 2020 13:27:17.414 # Configuration loaded
awx_redis   | 1:M 26 Nov 2020 13:27:17.420 # Opening Unix socket: bind: I/O error
```

Using the Alpine Redis with Busybox container:
```bash
docker-compose up redis
Starting awx_compose_redis_socket_1 ... done
Creating awx_redis                  ... done
Attaching to awx_redis
awx_redis       | 1:C 26 Nov 2020 13:30:12.450 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
awx_redis       | 1:C 26 Nov 2020 13:30:12.450 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
awx_redis       | 1:C 26 Nov 2020 13:30:12.450 # Configuration loaded
awx_redis       | 1:M 26 Nov 2020 13:30:12.455 * Running mode=standalone, port=0.
awx_redis       | 1:M 26 Nov 2020 13:30:12.455 # Server initialized
awx_redis       | 1:M 26 Nov 2020 13:30:12.456 * The server is now ready to accept connections at /var/run/redis/redis.sock
```

The redis.conf file:
```
bind 127.0.0.1
port 0
unixsocket /var/run/redis/redis.sock
unixsocketperm 770
```

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker for mac
* Ansible version:  n/a
* Operating System: n/a
* Web Browser: n/a

##### STEPS TO REPRODUCE

`docker-compose up redis`

##### EXPECTED RESULTS

Create and share the redis.sock socket across Redis, and AWX task/web containers.

##### ACTUAL RESULTS

The error from the Redis container logs:
`Opening Unix socket: bind: Input/output error` or `Opening Unix socket: bind: Input/output error`

The error/ stacktrace from the AWX web container logs:
```
awx_web     | 2020-11-26 13:26:45,747 WARNING  encountered an error communicating with redis.
awx_web     | Traceback (most recent call last):
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
awx_web     |     sock = self._connect()
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 905, in _connect
awx_web     |     sock.connect(self.path)
awx_web     | FileNotFoundError: [Errno 2] No such file or directory
awx_web     | 
awx_web     | During handling of the above exception, another exception occurred:
awx_web     | 
awx_web     | Traceback (most recent call last):
awx_web     |   File "/var/lib/awx/venv/awx/bin/daphne", line 8, in <module>
awx_web     |     sys.exit(CommandLineInterface.entrypoint())
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/daphne/cli.py", line 191, in entrypoint
awx_web     |     cls().run(sys.argv[1:])
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/daphne/cli.py", line 252, in run
awx_web     |     application = import_by_path(args.application)
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/daphne/utils.py", line 12, in import_by_path
awx_web     |     target = importlib.import_module(module_path)
awx_web     |   File "/var/lib/awx/venv/awx/lib64/python3.6/importlib/__init__.py", line 126, in import_module
awx_web     |     return _bootstrap._gcd_import(name[level:], package, level)
awx_web     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
awx_web     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
awx_web     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
awx_web     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
awx_web     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
awx_web     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/asgi.py", line 36, in <module>
awx_web     |     channel_layer = get_default_application()
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/channels/routing.py", line 29, in get_default_application
awx_web     |     module = importlib.import_module(path)
awx_web     |   File "/var/lib/awx/venv/awx/lib64/python3.6/importlib/__init__.py", line 126, in import_module
awx_web     |     return _bootstrap._gcd_import(name[level:], package, level)
awx_web     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
awx_web     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
awx_web     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
awx_web     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
awx_web     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
awx_web     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/routing.py", line 36, in <module>
awx_web     |     URLRouter(websocket_urlpatterns)
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/routing.py", line 25, in __init__
awx_web     |     raise e
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/routing.py", line 20, in __init__
awx_web     |     for k in r.scan_iter('asgi:*', 500):
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 2097, in scan_iter
awx_web     |     count=count, _type=_type)
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 2077, in scan
awx_web     |     return self.execute_command('SCAN', *pieces)
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 875, in execute_command
awx_web     |     conn = self.connection or pool.get_connection(command_name, **options)
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 1185, in get_connection
awx_web     |     connection.connect()
awx_web     |   File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
awx_web     |     raise ConnectionError(self._error_message(e))
awx_web     | redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.
```

**Comment by 16g** [comment]
any updates?

**Comment by velzend** [comment]
I have no updates...

I am still using the Busybox container to share the REDIS socket file across containers. 

@16g  are you facing the same issue?

**Comment by ArtemChekunov** [comment]
you see the error because of the default settings https://github.com/ansible/awx/blob/a74e7301cd224555da3f90c921b82d3964c6731c/awx/settings/defaults.py#L427

If you wish to make it flexible you need to define the settings in your config 
```
# grep BROKER_URL tower_settings.py
BROKER_URL = os.getenv("BROKER_URL")

# grep -B5  BROKER_URL docker-compose.yaml
  awx_task:
    image: ansible/awx_task:latest
    volumes:
      - ./tower_settings.py:/etc/tower/settings.py
    environment:
      BROKER_URL: "redis://redis:6379/0"
```
