### ISSUE TITLE
Kubernetes Annotations are improperly quoted (missing quotes)

### ISSUE THREAD

**Issue by hjkatz** [ansible/awx#8745]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Kubernetes annotations must be quoted, see issue: https://github.com/kubernetes/kubernetes/issues/67966

They are not, see here: https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/deployment.yml.j2#L10

Given input:

```yaml
kubernetes_ingress_annotations:
  my.company.com/some-annotation: "banana"
```

Will produce:

```yaml
metadata:
  annotations:
    my.company.com/some-annotation: banana
```

This should instead be:

```yaml
metadata:
  annotations:
    my.company.com/some-annotation: "banana"
```
