### ISSUE TITLE
Assets exported via awx.awx.tower_export should be importable via awx.awx.tower_import

### ISSUE THREAD

**Issue by watsonb** [ansible/awx#8748]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm working on export/import again to facilitate an AWX "blue/green" deployment scenario.  In the past, I made use of Ansible `shell` module to interact with the `awx` cli tool with mixed results.  Now I'm trying to leverage the `awx.awx.tower_*` modules for a cleaner and more reliable experience.

##### ENVIRONMENT

Instance "A" (awx.example.com)
* AWX version: 7.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.4
* Operating System: Ubuntu 18.04

Instance "B" (awx3.example.com)
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 18.04

"Controller running export/import playbook"
* Ansible version:  2.9.12
* Operating System: Ubuntu 20.04
* Web Browser: Chrome

The "controller" executing the export/import playbook targets Instance "B" during the run, hence all tasks are executing on the new 15.0.1 instance.

##### STEPS TO REPRODUCE

Given the following tasks:

```yaml
        - name: TOWER_EXPORT | export job_templates and workflow_job_templates from {{ ap_awx_export_from }}
          awx.awx.tower_export:
            tower_host: "{{ ap_awx_export_from }}"
            tower_oauthtoken: "{{ export_token }}"
            # job_templates: all
            job_templates: ap_hello_world_linux
            # workflow_job_templates: all
          register: template_assets
          tags: [ export, template_assets ]

        - name: DEBUG | template_assets
          debug:
            var: template_assets
          tags: [ export, template_assets ]

        - name: TOWER_IMPORT | import job_templates and workflow_job_templates to {{ ap_awx_import_to }}
          awx.awx.tower_import:
            tower_host: "{{ ap_awx_import_to }}"
            tower_oauthtoken: "{{ import_token }}"
            assets: "{{ template_assets.assets }}"
          tags: [ import, template_assets ]
```

##### EXPECTED RESULTS

I expect a single (existing) named job_template to be exported from instance "A" and imported into instance "B".

##### ACTUAL RESULTS

When I export a job_template from AWX instance "A", and try to import that job_template into AWX instance "B", I receive an error:

```bash
    Object import failed: Bad Request (400) received - {'job_slice_count': ['A valid integer is required.']}.
```

##### ADDITIONAL INFORMATION

Below is task output to include the debug task (discussion to follow):

```bash
TASK [TOWER_EXPORT | export job_templates and workflow_job_templates from https://awx.example.com] **********************************************************
Friday 04 December 2020  07:30:59 -0600 (0:00:00.034)       0:00:08.164 ******* 
Friday 04 December 2020  07:30:59 -0600 (0:00:00.034)       0:00:08.164 ******* 
ok: [awx3.example.com]

TASK [DEBUG | template_assets] **********************************************************************************************************************************
Friday 04 December 2020  07:31:01 -0600 (0:00:02.786)       0:00:10.950 ******* 
Friday 04 December 2020  07:31:01 -0600 (0:00:02.786)       0:00:10.950 ******* 
ok: [awx3.example.com] => 
  template_assets:
    assets:
      job_templates:
      - allow_simultaneous: false
        ask_credential_on_launch: false
        ask_diff_mode_on_launch: false
        ask_inventory_on_launch: true
        ask_job_type_on_launch: false
        ask_limit_on_launch: false
        ask_scm_branch_on_launch: false
        ask_skip_tags_on_launch: false
        ask_tags_on_launch: false
        ask_variables_on_launch: false
        ask_verbosity_on_launch: false
        become_enabled: false
        custom_virtualenv: null
        description: A simple template to test the CLI setting up a real job. (Make sure you add needed vault-credentials via GUI.)
        diff_mode: false
        extra_vars: ''
        force_handlers: false
        forks: 5
        host_config_key: ''
        inventory:
          name: example_all
          organization:
            name: Example
            type: organization
          type: inventory
        job_slice_count: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        job_tags: ''
        job_type: run
        limit: ''
        name: ap_hello_world_linux
        natural_key:
          name: ap_hello_world_linux
          type: job_template
        playbook: helloLinux.yml
        project:
          name: ap_hello_world
          organization:
            name: Example
            type: organization
          type: project
        related:
          credentials:
          - credential_type:
              kind: ssh
              name: Machine
              type: credential_type
            name: Ansible_User_SSH
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: Ansible_User_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: AWX_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: Azure_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: ExampleAdmin_User_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: SNOW_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          - credential_type:
              kind: vault
              name: Vault
              type: credential_type
            name: vCenter_VaultID
            organization:
              name: Example
              type: organization
            type: credential
          labels: []
          notification_templates_error: []
          notification_templates_started: []
          notification_templates_success: []
          schedules: []
          survey_spec:
            description: ''
            name: ''
            spec:
            - choices: ''
              default: ''
              max: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
              min: 0
              new_question: true
              question_description: ''
              question_name: Specify an inventory host or group to target
              required: true
              type: text
              variable: variable_host
        scm_branch: ''
        skip_tags: ''
        start_at_task: ''
        survey_enabled: true
        timeout: 0
        use_fact_cache: false
        verbosity: 0
    changed: false
    failed: false

TASK [TOWER_IMPORT | import job_templates and workflow_job_templates to https://awx3.example.com] ***********************************************************
Friday 04 December 2020  07:31:01 -0600 (0:00:00.036)       0:00:10.987 ******* 
Friday 04 December 2020  07:31:01 -0600 (0:00:00.036)       0:00:10.986 ******* 
fatal: [awx3.example.com]: FAILED! => changed=false 
  msg: |-
    Object import failed: Bad Request (400) received - {'job_slice_count': ['A valid integer is required.']}.
```
As shown, the exported data contains the string "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER" for some attributes (notably job_slice_count), when in fact this value is "1" in instance A's GUI and /api/v2 representation of the same template.

Indeed I would much rather export "all" job_templates, but limited this example to a single named template as the error output is far too verbose when exporting ~100 items.  I run into a similar problem when exporting `inventory` and `inventory_sources` assets.

Given the exported assets are registered in an Ansible variable, is there a clever mechanism (`set_fact` with some Jinja2 filters, other sequence of tasks, etc.) where I could replace all occurrences of "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER" within the registered variable to some sane/default value prior to importing the assets?

My current workaround when dealing with asset types that don't import due to throwing an error is something like this:

```yaml
        - name: SHELL | get export tower token from {{ ap_awx_export_from }}
          shell: awx login -f human --conf.insecure
          args:
            executable: /bin/bash
          environment:
            TOWER_HOST: "{{ ap_awx_export_from }}"
            TOWER_USERNAME: "{{ ap_awx_export_from_username }}"
            TOWER_PASSWORD: "{{ ap_awx_export_from_password }}"
          register: ap_awx_export_token_login
          when: config_inventory_method == 'cmdline'
          tags: [ always, export, inventory ]

        - name: SET_FACT | ap_awx_export_token
          set_fact:
            ap_awx_export_token: "{{ ap_awx_export_token_login.stdout.split('=')[1] }}"
          tags: [ always, export, inventory ]
          when: config_inventory_method == 'cmdline'

        - name: SHELL | export inventory from {{ ap_awx_export_from }}
          shell: awx export -k --{{ item }} > awx_{{ ap_awx_export_from | urlsplit('hostname') }}_{{ item }}.json
          args:
            executable: /bin/bash
            creates: awx_{{ ap_awx_export_from | urlsplit('hostname') }}_{{ item }}.json
          environment:
            TOWER_HOST: "{{ ap_awx_export_from }}"
            TOWER_USERNAME: "{{ ap_awx_export_from_username }}"
            TOWER_PASSWORD: "{{ ap_awx_export_from_password }}"
            TOWER_OAUTH_TOKEN: "{{ ap_awx_export_token }}"
          tags: [ artifacts, export, inventory ]
          loop:
            - inventory
          when: config_inventory_method == 'cmdline'

        - name: SLURP | get the contents of the inventory file
          slurp:
            src: /usr/local/home/ansible/awx_awx.kiewitplaza.com_inventory.json
          register: command_result
          tags: [ import, inventory ]
          when: config_inventory_method == 'cmdline'

        - name: SET_FACT | inventory_json
          set_fact:
            inventory_json: "{{ command_result['content'] | b64decode | to_json(ensure_ascii=False) | from_json }}"
          tags: [ import, inventory ]
          when: config_inventory_method == 'cmdline'

        - name: TOWER_IMPORT | import inventory to {{ ap_awx_import_to }}
          awx.awx.tower_import:
            tower_host: "{{ ap_awx_import_to }}"
            tower_oauthtoken: "{{ import_token }}"
            assets: "{{ inventory_json }}"
          tags: [ import, inventory ]
          when: config_inventory_method == 'cmdline'
```
Which "mostly" works but is something I was trying to avoid in the first place (using `shell` to `awx` cli).
