### ISSUE TITLE
Arbitrary role in job_event of tasks directly from playbook with host_pinned strategy

### ISSUE THREAD

**Issue by jplitza** [ansible/awx#8810]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When executing a playbook with `strategy: host_pinned` (not sure if necessary), the "role" attribute in the job_events of tasks sitting directly in the playbook may be populated with seemingly arbitrary other roles that are included in the playbook.

##### ENVIRONMENT
* AWX version: 15.0.1
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: Ubuntu 20.04
* Web Browser: Firefox 83.0

##### STEPS TO REPRODUCE

Run a playbook like the following on dozens of hosts and filtering for "role:myrole" (or looking at the job_events in the API)
```yaml
- hosts:  all
  serial:
  - 1
  - 10
  strategy: host_pinned
  pre_tasks:
  - name: Pre-Task
    meta: noop
  roles:
  - myrole
  post_tasks:
  - name: Post-Task
    meta: noop
```

##### EXPECTED RESULTS

No Pre- or Post-Task should ever show up while filtering, and their role attribute in the API is always empty.

##### ACTUAL RESULTS

All of Pre-Task, Post-Task and Gathering Facts show up for some hosts while filtering (you need to click on the "ok/changed" line because output is totally garbage for `strategy: host_pinned`), and looking at the relevant job_event in the API confirms they have set `"role": "myrole"`.
