### ISSUE TITLE
There are no available playbook directories in {project_base_dir}

### ISSUE THREAD

**Issue by weironz** [ansible/awx#8988]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
There are no available playbook directories in {project_base_dir}

##### ENVIRONMENT
* AWX version: 16.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.13
* Operating System: centos 7.8
* Web Browser: chrome

##### STEPS TO REPRODUCE

install AWX 16.0.0 with docker

##### EXPECTED RESULTS

when create projects support use Manual define playbooks

##### ACTUAL RESULTS

can not use Manual define playbooks

##### ADDITIONAL INFORMATION

```
Warning alert:WARNING:
There are no available playbook directories in {project_base_dir}. Either that directory is empty, or all of the contents are already assigned to other projects. Create a new directory there and make sure the playbook files can be read by the "awx" system user, or have {brandName} directly retrieve your playbooks from source control using the Source Control Type option above.
```

what inventory say:
```
# AWX project data folder. If you need access to the location where AWX stores the projects
# it manages from the docker host, you can set this to turn it into a volume for the container.
#project_data_dir=/var/lib/awx/projects
```

what i do next , but not effect

```
[root@jenkins installer]# docker exec -it awx_task bash
bash-4.4# cd /var/lib/awx/projects/

bash-4.4# useradd awx
bash-4.4# chown -R helloworld/

bash-4.4# ls -al
total 12
drwxr-xr-x  8 root root  179 Dec 29 03:01 .
drwxrwxr-x  1 root root   77 Dec 29 02:09 ..
drwxr-xr-x 16 root root 4096 Dec 29 03:02 _12__ansible_examples
-rwxr-xr-x  1 root root    0 Dec 29 03:01 _12__ansible_examples.lock
drwxr-xr-x  5 root root 4096 Dec 29 01:51 _8__awx_demo
-rwxr-xr-x  1 root root    0 Dec 29 01:51 _8__awx_demo.lock
drwxr-xr-x  4 root root   55 Dec 29 03:01 .__awx_cache
drwxr-xr-x  5 root root 4096 Dec 29 02:09 demo123
drwxr-xr-x  2 awx  awx    28 Dec 29 02:11 helloworld
drwxr-xr-x  2 root root    6 Dec 29 02:08 test

bash-4.4# ls -l helloworld/
total 4
-rw-r--r-- 1 awx awx 112 Dec 29 02:11 helloworld.yml
bash-4.4# 

```

**Comment by weironz** [comment]
i know how to resolve

```

```shell
mkdir /var/lib/awx/
docker cp awx_task:/var/lib/awx/projects/ /var/lib/awx/projects/
```

修改docker-compose.yml ，在web和task容器中挂载相同的卷

```yaml
# cd /root/.awx/awxcompose/
# vim docker-compose.yml 
  web:
    volumes:
      - /var/lib/awx/projects/:/var/lib/awx/projects/
  task:
    volumes:
      - /var/lib/awx/projects/:/var/lib/awx/projects/
```

修改inventory配置文件，取消project\_data\_dir注释

```shell
# cd awx-16.0.0/installer/

# cat inventory |grep project_data_dir
project_data_dir=/var/lib/awx/projects
```

重新部署awx

```shell
ansible-playbook -i inventory install.yml
```
在主机/var/lib/awx/projects目录下创建自己的playbooks项目

```yaml
[root@jenkins ~]# cat /var/lib/awx/projects/helloworld/helloworld.yml 
---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working!"
```

```
