### ISSUE TITLE
Async playbook tasks not cleaning up correctly with jumphost

### ISSUE THREAD

**Issue by frenchtoasters** [ansible/awx#9071]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We a playbook that is using `ansible_ssh_common_args` which proxy the command through a jumphost using ssh keys. The play we are running uses `command` to copy files between hosts, the play also has `async: 600` on it. 

The issue is that under the `/home/ansible/.ansible_async` folder leaves files behind that have the output of the single async file copy and _never_ cleans up the files. Over time this leads to the system running out of inodes as for every file that was copied a file is created, saved, and never deleted after the play. 

##### ENVIRONMENT
* AWX version: 11.2.0
* AWX install method: docker on linux
* Ansible version:  2.9.7
* Operating System: CentOS 8
* Web Browser: Firefox

##### STEPS TO REPRODUCE
Create jumphost credentials and configure job to use them https://developer.ibm.com/recipes/tutorials/multiple-jumphosts-in-ansible-tower-part-1/

Create playbook:

```
- name: copy files
  hosts: all
  gather_facts: yes
  vars:
    source_system_paths:
      - "/test" 
    source_host: ""
  tasks:
    - name: Sync Folders cmd
      become: true
      become_user: ansible
      command: time sudo rsync -av -e "/usr/bin/ssh -o StrictHostKeyChecking=no -i /home/ansible/.ssh/id_rsa" ansible@"{{ source_host }}":"{{ item }}" "{{ item }}"
      with_items:
        - "{{ source_system_paths }}"
      loop_control:
        extended: yes
      async: 600
      poll: 5
```
Schedule playbook to run and you will see on limit host a `/home/ansible/.ansible_async` folder that creates new files every run that are not deleted. 

##### EXPECTED RESULTS

Files created by the job in the `/home/ansible/.ansible_asnyc` would be deleted after the job has completed or the async task has completed. 

##### ACTUAL RESULTS

Files are left to be manually removed

##### ADDITIONAL INFORMATION

This was found about a month after a job running on a 5min interval was created and had upwards of 600k+ files in the directory.
