### ISSUE TITLE
Certain playbook output has unexpected delays

### ISSUE THREAD

**Issue by ryanpetrello** [ansible/awx#9085]
Run this playbook on an awx install that is doing little or nothing else:

```yaml
---

- hosts: all
  gather_facts: false
  tasks:
    - shell: 'echo "Hello, World" && sleep .1'
      with_sequence: start=0 end=100
```

...observe that none of the events are recorded, nor does any of the stdout show up in the UI *until* the playbook command finishes executing (then everything shows up at the end in a giant burst).
