### ISSUE TITLE
awx.awx.tower_job_template will update the limit to none if the parameter is not set

### ISSUE THREAD

**Issue by xding2020** [ansible/awx#9200]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

tower_job_template ansible module will update the limit of job template to none if the parameter is not set, instead of keeping it unchanged

##### ENVIRONMENT
* Ansible version:  2.9.4

##### STEPS TO REPRODUCE
1. Assuming ansible tower is ready and there is a job template with limit parameter set
2. Run an ansible playbook that contains a task updating the job template (but not updating the limit). e.g.:

```yaml
  - name: update template with corresponding venv
    awx.awx.tower_job_template:
      name: "{{ template_name }}"
      custom_virtualenv: "/var/lib/awx/venv/venv-test"
```

##### EXPECTED RESULTS
The job template is updated with limit unchanged

##### ACTUAL RESULTS
The limit of job template is set to none

**Comment by blomquisg** [comment]
@john-westcott-iv I think you've seen this type of issue before.  Can you give some feedback here, or point to another issue where you've talked about this?

**Comment by john-westcott-iv** [comment]
In this case we have a legitimate bug. We have a default of '' on the field (there are a couple) and later we are checking to see if the field is not pythons `None`. This will never be the case because we gave a default of ''. So, if you don't specify limit (or one of the other fields) the module will kindly set the limit as '' instead of leaving it alone.

**Comment by sean-m-sullivan** [comment]
I found the same behaviour happening within other modules and fields, Submitted PR to fix bug
```
plugins/modules/tower_credential_input_source.py:79:        description=dict(default=''),
plugins/modules/tower_credential_input_source.py:82:        source_credential=dict(default=''),
plugins/modules/tower_job_template.py:343:        description=dict(default=''),
plugins/modules/tower_job_template.py:349:        credential=dict(default=''),
plugins/modules/tower_job_template.py:350:        vault_credential=dict(default=''),
plugins/modules/tower_job_template.py:357:        job_tags=dict(default=''),
plugins/modules/tower_job_template.py:359:        skip_tags=dict(default=''),
plugins/modules/tower_job_template.py:360:        start_at_task=dict(default=''),
plugins/modules/tower_project.py:232:        scm_branch=dict(default=''),
plugins/modules/tower_project.py:233:        scm_refspec=dict(default=''),
plugins/modules/tower_ad_hoc_command.py:121:        module_args=dict(default=""),
```

**Comment by sean-m-sullivan** [comment]
@ryanpetrello with the above PR This is fixed and can be closed.

**Comment by kdelee** [comment]
Verified, this no longer stomps the limit value
```
- name: Verify Tower Collections Fixes
  hosts: localhost
  vars:
    ansible_connection: local
  collections:
    - awx.awx
  tasks:
    - name: Create Tower Ping job template
      tower_job_template:
        name: "Ping"
        job_type: "run"
        organization: "New Org"
        inventory: "New Inventory"
        project: "New Project"
        playbook: "ping.yml"
        limit: 'foo'
        instance_groups:
          - 'bar'
        state: "present"

    - name: Create Tower Ping job template
      tower_job_template:
        name: "Ping"
        job_type: "run"
        organization: "New Org"
        inventory: "New Inventory"
        project: "New Project"
        playbook: "ping.yml"
        instance_groups:
          - 'bar'
        state: "present"

```
