### ISSUE TITLE
No correct inventory files when it sourced from git project

### ISSUE THREAD

**Issue by etoosamoe** [ansible/awx#9283]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I have a Git repo with a lot of files, playbooks, roles, templates, tasks, etc. They store in directories in root dir e.g. hosts (for inventory files, about 10 files), host_vars, group_vars, roles

![image](https://user-images.githubusercontent.com/38806450/107514887-50960f00-6bbb-11eb-9300-d87a497dea69.png)

I added a project sourced from Git repo. Sync is OK. But when i try to select inventory file to add it, I see only a short list of random files from my project:

![image](https://user-images.githubusercontent.com/38806450/107515025-7f13ea00-6bbb-11eb-8141-058a6532190d.png)

I saw the https://github.com/ansible/awx/issues/174 and read about 50 lines cap, **but i CAN'T enter a text in Inventory File field**.

Maybe there is a best-practise way to organize my files? Maybe there is a way to specify a folder with my files?

p.s. if I try to select a playbook in template I see another files, including(!) my inventory files:
![image](https://user-images.githubusercontent.com/38806450/107515379-fcd7f580-6bbb-11eb-9f00-23746dddda6c.png)

Example of inventory file:

```
all:
  children:
  ##### PRODUCTION ######
    gitlab:
      hosts:
        gitl.s.local: 
        git.s.local: 
        gitl.s.local: 


    son:
      hosts:
        son.s.local: 

    for:
      hosts:
        for.s.local: 

    pro:
      hosts:
        pro.s.local: 
```

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method:  docker on linux
* Ansible version:  2.9.17
* Operating System: Ubuntu 20.04
* Web Browser: Chrome 

##### STEPS TO REPRODUCE

1. Create project sourced from Git with a lot of different files
2. Create an inventory sourced from this project
3. Create an template with a playbook from this project

##### EXPECTED RESULTS

In steps 2 and 3 I expect to see only inventory or playbook files.

##### ACTUAL RESULTS

I see a lot of files, but no needed files.
