### ISSUE TITLE
Requirements are skipped but then plugins listed there are not recognised

### ISSUE THREAD

**Issue by danielo515** [ansible/awx#9321]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX skips installing the collection requirements but then it fails because it finds plugins that it does not recognise

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: docker-compose
* Ansible version:  2.9.17
* Operating System: Ubuntu 18
* Web Browser: chrome

##### STEPS TO REPRODUCE

This is my requirements file:

```
# list of roles and collections to be installed using galaxy
---
roles:
  - name: dj-wasabi.telegraf
  - name: cloudalchemy.coredns
  - src: https://github.com/danielo515/ansible-modules-bitwarden
  - name: geerlingguy.git
  - name: geerlingguy.pip
  - name: geerlingguy.ansible
  - name: geerlingguy.docker
  - name: geerlingguy.nodejs
  - name: geerlingguy.awx

collections:
  - name: community.kubernetes
    source: https://galaxy.ansible.com
  - name: community.general
```

And here is a small inventory file trying to use one plugin from the community general:

```
# inventory.config file in YAML format
---
plugin: community.general.nmap
strict: False
address: 192.168.0.0/24
```

##### EXPECTED RESULTS

I want to AWX to install all requirements and being able to use my inventory plugins

##### ACTUAL RESULTS

Inventory plugin is not recognised and the sync fails

##### ADDITIONAL INFORMATION

```
TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/var/lib/awx/projects/_8__homelab_project/collections/requirements.yml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': {'ext': '.yml'}, 'ansible_loop_var': 'item'}) 
skipping: [localhost] => (item={'changed': False, 'stat': {'exists': False}, 'invocation': {'module_args': {'path': '/var/lib/awx/projects/_8__homelab_project/collections/requirements.yaml', 'follow': False, 'get_md5': False, 'get_checksum': True, 'get_mime': True, 'get_attributes': True, 'checksum_algorithm': 'sha1'}}, 'failed': False, 'item': {'ext': '.yaml'}, 'ansible_loop_var': 'item'}) 
```
