### ISSUE TITLE
awx.awx.tower_export missing Galaxy Credential in organizations

### ISSUE THREAD

**Issue by metabsd** [ansible/awx#9342]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`awx.awx.tower_export` is not exporting Galaxy Credential with the Organization

##### ENVIRONMENT
* AWX version: 15.0.0, 15.0.1, 17.0.1
* AWX install method: AWX Operator
* Ansible version:  2.9.17
* Operating System:  docker.io/ansible/awx:{VERSIONS}
* Web Browser: Edge, Chrome, Firefox

##### STEPS TO REPRODUCE

```
---
- name: awx assets export
  hosts: localhost
  debugger: on_failed
  gather_facts : false
  become: false
  tasks:
    - name: export job templates
      awx.awx.tower_export:
        all: True
        tower_host: awx.mydomain
        tower_username: admin
        tower_password: "{{ my_admin_password }}"
        validate_certs: no
      register: export_results

    - copy: content="{{ export_results.assets }}" dest=./awx_export.json
```

My organization have a Galaxy Credential but the export don't export it. So I finally figure out by redoing it manually and comparing.

An example of the Organization Export.
```
  "organizations": [
    {
      "name": "MyOrg",
      "description": "",
      "max_hosts": 0,
      "custom_virtualenv": null,
      "related": {
        "notification_templates": [],
        "notification_templates_started": [],
        "notification_templates_success": [],
        "notification_templates_error": [],
        "notification_templates_approvals": []
      },
      "natural_key": {
        "name": "MyOrg",
        "type": "organization"
      }
    }
  ]
```

##### EXPECTED RESULTS

I expect that the export will also export the organization with the galaxy credential to be able to download and install collection automatically in a project sync.

##### ACTUAL RESULTS

Missing Galaxy Credential in my Organization.
