### ISSUE TITLE
RFE: Inventory prompt for a single host

### ISSUE THREAD

**Issue by CvH** [ansible/awx#9355]
##### ISSUE TYPE
 - add an option to prompt for the target IP at template start
##### SUMMARY

A typical usecase is deployment of a new server or similar that is not yet at the inventory or should not be included at the inventory for reasons.

Currently there is no easy way (at least I am not aware) to run a playbook against a single ip/host.
Current workaround is to create a Inventory and add a single host `{"ansible_host": "10.1.1.123"}`, that is dangerous because if you forget to change the ip fubar can happen.
Another workaround is to add for every playbook workarounds like this + ask for the $var via a survey
```
- name: single server as target
  hosts: localhost
  gather_facts: true
  tasks:
    - add_host:
        hostname: "{{ target_host }}"
        groups: dynamically_created_hosts

- name: deploy something
  hosts: "dynamically_created_hosts"
  roles:
     - some-task
``` 

From my perspective a proper way would be a inventory that can ask for the ip address, like it works for example passwords at the credentials.
