### ISSUE TITLE
awx/tower module to shut

### ISSUE THREAD

**Issue by IPvSean** [ansible/awx#9447]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

in Ansible Workshops we setup Ansible Tower clusters in bulk and we have to issue SSL certs and turn tower on/off depending on what we are doing.

Right now we have a lot of tasks like this->

```
- name: make sure Ansible Tower
  shell: ansible-tower-service start
```

it would be ideal to have a module to do this.... I am not sure if it would be ok to just use `ansible.builtin.service` or if there is a certain order of operations needed with the ansible-tower-service cli command.

**Comment by john-westcott-redhat** [comment]
As of, roughly, 3.7 the ansible-tower-service script is really just wrapping systemctl. Because of this you could just use the service module for start/stop/restarts like so:
```
    - name: Shut down Ansible Tower
      service:
        name: ansible-tower.service
        state: stopped
```
