### ISSUE TITLE
awx.awx.tower_job_template not limiting credential lookup to organization

### ISSUE THREAD

**Issue by branic** [ansible/awx#9573]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

It is possible to have two credentials with the same name in two different organizations. When a user has access to both organizations and uses the `awx.awx.tower_job_template` module to create a job template in one organization with the duplicated credential name the job template creation fails because two credentials are returned and only one is expected.

##### ENVIRONMENT
* AWX version: current

##### STEPS TO REPRODUCE

1. Create two organization in AWX
2. Create a user that has access to both organizations and is able to use the credentials and has project admin and job template admin or org admin roles
3. Create a credential in the first organization named 'test-cred'
4. Create a credential in the second organization named 'test-cred'
5. Create a project in the first organization
6. Create an inventory in the first organization
7. Use the `awx.awx.tower_job_template` module to create a job template in the first organization using the credential, project, and inventory created in steps 3, 5, and 6

##### EXPECTED RESULTS

The job template is successfully created in the first organization using the credential from the first organization

##### ACTUAL RESULTS

The job template creation fails with an error:

```
Request to /api/v2/credentials/?name=svc-ansible returned 2 items, expected 1
```

##### ADDITIONAL INFORMATION

This could also happen for inventories that exist across organizations with the same name. The job template creation should limit the queries to the organization the job template is being created in (or at least have the option to do so).

**Comment by blomquisg** [comment]
@branic do you have a playbook that serves as a reproducer for this?

**Comment by branic** [comment]
@blomquisg here is a reproducer playbook.

```yaml
- name: Job Template Testing
  hosts: localhost
  gather_facts: false
  collections:
    - awx.awx

  vars:
    tower_host: tower.example.com
    tower_token: <REDACTED>
    validate_ssl_cert: false
    orgs:
      - test-org1
      - test-org2
    creds:
      - name: test_cred
        type: Machine
        org: test-org1
      - name: test_cred
        type: Machine
        org: test-org2
    inventory: "Test Inventory"
    project:
      name: "Test Project"
      git_repo: 'https://gitlab.example.com/example/ansible.git'
    job_template:
      name: "Test JT"
      playbook: example.yml
      inventory: "{{ inventory }}"
      credential_names:
        - "{{ (creds | first).name }}"

  tasks:
    - name: Create organizations
      tower_organization:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ item }}"
        state: present
      loop: "{{ orgs }}"

    - name: Create credentials
      tower_credential:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ item.name }}"
        organization: "{{ item.org }}"
        credential_type: "{{ item.type }}"
        state: present
      loop: "{{ creds }}"

    - name: Create inventory
      tower_inventory:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ inventory }}"
        organization: "{{ orgs | first }}"
        state: present

    - name: Create project
      tower_project:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ project['name'] }}"
        description: "Temporary playbook testing project"
        state: present
        scm_type: git
        scm_url: "{{ project['git_repo'] }}"
        organization: "{{ orgs | first }}"

    - name: Create job template
      tower_job_template:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: "{{ validate_ssl_cert | default(omit) }}"
        name: "Test Job Template"
        description: "Temporary playbook testing job template"
        state: present
        job_type: run
        playbook: "{{ job_template['playbook'] }}"
        inventory: "{{ job_template['inventory'] }}"
        credentials: "{{ job_template['credential_names'] }}"
        project: "{{ project['name'] }}"
        organization: "{{ orgs | first }}"
```

**Comment by branic** [comment]
Although I haven't tested it I also suspect that this type of error would be generated if an inventory being added to the JT had the same name in two different organizations.

**Comment by sean-m-sullivan** [comment]
So Tower allows admin users, or users of two orgs to use credentials from both orgs in a single job template, Job templates technically inherit their orgs from their project. In this situation this is an expected behavior, as the modules are built to reflect the options available in the api, and we don't have a way at the moment to support a cred+org lookup in a job template. 

This issue has been brought up and discussed here: #7356 , as its not just credentials that suffer from this. 

However there are a few solutions:
1. The currently recommended method is, Supply the credential ID directly or indirectly for the Credential. This can be done either manually supplying the credential ID, or using the [tower_api lookup plugin](https://github.com/ansible/awx/blob/devel/awx_collection/plugins/lookup/tower_api.py)

2. Using differently named credentials for different orgs. This may not be feasible to keep track of especially if you have job templates with the same name in different orgs, and are trying to keep some continuity. But there are options to doing what I've refered to as Tower as Code, Following the Infrastructure as Code principles. This involves using the awx.awx/ansible.tower modules to populate all items in tower. A good example of this can be found in the not officially supported [tower_configuration collection](https://galaxy.ansible.com/redhat_cop/tower_configuration), this would allow you to keep code in git, and use templated variable names like "test-cred-{{org_1}}"

At the moment the org is only used for lookup of the main object in all of the modules, for example project module uses it to lookup the project name, but not the git credentials.

**Comment by branic** [comment]
@sean-m-sullivan I didn't realize that IDs could be used directly with the modules instead of the names. I'll give that a try.

**Comment by beeankha** [comment]
Hi @branic , have you had success using the IDs vs names (or the lookup plugin)?

**Comment by branic** [comment]
@beeankha, I finally had some time to test this. Using `set_fact` and `query` with the `tower_api` lookup module I was able to successfully create the Job Template. The below Ansible playbook is a modification of the above playbook that works.

```yaml
- name: Job Template Testing
  hosts: localhost
  gather_facts: false
  collections:
    - awx.awx

  vars:
    tower_host: tower.example.com
    tower_token: <REDACTED>
    validate_ssl_cert: false
    orgs:
      - test-org1
      - test-org2
    creds:
      - name: test_cred
        type: Machine
        org: test-org1
      - name: test_cred
        type: Machine
        org: test-org2
    inventory: "Some Inventory"
    project:
      name: "Test Project"
      git_repo: 'https://gitlab.example.com/example/ansible.git'
    job_template:
      name: "Test JT"
      organization: test-org1
      playbook: example.yml
      inventory: "{{ inventory }}"
      credential_names:
        - "{{ (creds | first).name }}"

  tasks:
    - name: Determine AWX/Tower collection installed
      tower_meta:
      register: awx_collection

    - name: Create organizations
      tower_organization:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ item }}"
        state: present
      loop: "{{ orgs }}"

    - name: Create credentials
      tower_credential:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ item.name }}"
        organization: "{{ item.org }}"
        credential_type: "{{ item.type }}"
        state: present
      loop: "{{ creds }}"

    - name: Create inventory
      tower_inventory:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ inventory }}"
        organization: "{{ orgs | first }}"
        state: present

    - name: Create project
      tower_project:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: " {{ validate_ssl_cert | default(omit) }}"
        name: "{{ project['name'] }}"
        description: "Temporary playbook testing project"
        state: present
        scm_type: git
        scm_url: "{{ project['git_repo'] }}"
        organization: "{{ orgs | first }}"

    - name: Lookup credential
      set_fact:
        jt_cred: >-
          {{ query(awx_collection.prefix + '.tower_api',
                'credentials',
                query_params={ 'name__in' : (job_template['credential_names'] | join(',')),
                               'organization__name' : job_template['organization'] },
                host=tower_host,
                oauth_token=tower_token,
                verify_ssl=(validate_ssl_cert | default(omit) )
             ) | map(attribute='id') | map('string') | list }}

    - name: Create job template
      tower_job_template:
        tower_host: "{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token }}"
        validate_certs: "{{ validate_ssl_cert | default(omit) }}"
        name: "Test Job Template"
        description: "Temporary playbook testing job template"
        state: present
        job_type: run
        playbook: "{{ job_template['playbook'] }}"
        inventory: "{{ job_template['inventory'] }}"
        credentials: "{{ jt_cred }}"
        project: "{{ project['name'] }}"
        organization: "{{ job_template['organization'] }}"
```
