### ISSUE TITLE
Different behavior of ansible task on pure ansible and ansible plus AWX 

### ISSUE THREAD

**Issue by zurikus** [ansible/awx#9612]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Could you please explain why there is different task execution behavior on pure ansible and ansible + AWX. 
Pgbouncer packages (ver. 1.14) are already installed on server.

Ansible task: 

```
- hosts: pgsql_host
  become: true
  tasks:
    - name: Install pgbouncer packages
      dnf:
        name: "pgbouncer"
        state: present
        update_cache: true
```

Execution on pure ansible as expected: 

```
TASK [Install pgbouncer packages] *************************************************************************************************************************************************************
ok: [dv000200] => {"changed": false, "msg": "Nothing to do", "rc": 0, "results": []}
```

Execution on ansible plus AWX: 

```
TASK [pg-pgbouncer : Install pgbouncer packages] *******************************
changed: [dv000200] => {"changed": true, "msg": "", "rc": 0, "results": ["Installed: pgbouncer", "Installed: pgbouncer-1.15.0-1.rhel8.x86_64", "Removed: pgbouncer-1.14.0-3.rhel8.x86_64"]}
```

##### ENVIRONMENT
* AWX version: 9.1.1
* AWX install method: docker-compose
* Ansible version:  2.8.5
* Operating System: centos 8 (proxmox lxc)
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Execution of ansible task from pure ansible and on AWX behaves differrently.

```
- hosts: pgsql_host
  become: true
  tasks:
    - name: Install pgbouncer packages
      dnf:
        name: "pgbouncer"
        state: present
        update_cache: true
```

##### EXPECTED RESULTS

I do expect that pgbouncer package is not updating as it is already installed (as it is on pure ansible) 

##### ACTUAL RESULTS

Pgbouncer packages are updated, that leads to pgbouncer restart and all active session kill. 

##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#parameter-state

**Comment by ryanpetrello** [comment]
Hey @zurikus,

I'm not sure what's going on here, but AWX itself shouldn't be doing anything to change the content of your playbooks - my gut says there's probably something environment-specific going on here.  Just in case, giving this a shot on a newer version of AWX?

**Comment by zurikus** [comment]
Playbook is the same, but behavior of execution is different. 
At this moment as workaround I switched my playbook to exact versions of packages to avoid this issue. 

```
- hosts: pgsql_host
  become: true
  tasks:
    - name: Install pgbouncer packages
      dnf:
        name: "pgbouncer-1.15.0-1.rhel8.x86_64"
        state: present
        update_cache: true
```

I'm not able to test on latest version of AWX.
I provided code example, I will really appreciate if you can do that yourself. 
If you are unable to do that as well, we can close this issue.
