### ISSUE TITLE
awx.awx.tower_api returns incorrect results with 'return_all=true'

### ISSUE THREAD

**Issue by thijsvdn** [ansible/awx#9632]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using the tower_api lookup plugin, 'return_all=true' will return incorrect results for certain page sizes or when page_size is not explicitly set.

##### ENVIRONMENT
* AWX version: 17.1.0
* AWX install method: docker on linux
* Ansible version:  2.9.18
* Operating System: Debian
* Web Browser: n/a

##### STEPS TO REPRODUCE

Create a large number of schedules for a template (in my case 68). Run a lookup with the awx.awx.tower_api plugin without setting a page size or by setting it explicitly with `query_params={'page_size': '25'}`:

```    
  - name: Get trydent_update job template details
      set_fact:
        my_template: >-
          {{
             lookup(
               'awx.awx.tower_api',
               'job_templates',
               expect_one=true,
               host=tower_hostname,
               oauth_token=tower_token,
               query_params={'labels__search': 'my_template_label'}
             )
          }}

  - name: Get currently scheduled releases from AWX
    set_fact:
      my_schedules: >-
       {{
          lookup(
           'awx.awx.tower_api',
           my_template.related.schedules,
           return_all=true,
           max_objects=1000,
           host=tower_hostname,
           oauth_token=tower_token,
         )
       }}

    - name:
      debug:
        var: my_schedules
```

##### EXPECTED RESULTS

I expect the 68 schedules for 'my_template' to be returned, where objects 24 - 26 look like:

```
  {
     "id": 280,
     "name": "schedule Foo",
     "next_run": "2021-04-21T05:00:00Z",
     (...)
  },
  {
     "id": 289,
     "name": "schedule Bar",
     "next_run": "2021-04-21T04:00:00Z",
     (...)
  },
  {
     "id": 290,
     "name": "schedule Foobar",
     "next_run": "2021-04-21T04:00:00Z",
     (...)
  },
```
##### ACTUAL RESULTS

68 items are returned, however, the 25th schedule is incorrect. Schedule 'Bar' is missing completely and schedule 'Foobar' exists twice in the list.
```
  {
     "id": 280,
     "name": "schedule Foo",
     (...)
  },
  {
     "id": 290
     "name": "schedule Foobar",
     "next_run": "2021-04-21T04:00:00Z",
     (...)
  },
  {
     "id": 290,
     "name": "schedule Foobar",
     "next_run": "2021-04-21T04:00:00Z",
     (...)
  },
```

##### ADDITIONAL INFORMATION

All schedules are returned as expected in the AWX schedule overview and when calling the endpoint with a REST client.

This also happens calling `awx.awx.tower_api` with a page size of 1, in that case object 33 is missing and object 34 will be returned on positions 33 and 34. When setting the page size to 24, 50, 75 or 150 the expected results are returned.

**Comment by ryanpetrello** [comment]
@john-westcott-iv @beeankha @sean-m-sullivan,

Can one of you take a peek at this?  It looks like it might be a bug in the collection.

**Comment by ryanpetrello** [comment]
@jainnikhil30 @tchellomello this may be one of your radar as well 👀

**Comment by john-westcott-iv** [comment]
@ryanpetrello This looks like it might be an issue with the API. I created 100 schedules against a job template and if I go to /api/v2/job_templates/9/schedules/?page_size=1 I get one job back with let's say ID 25. Hitting the next link also gives me back ID 25.

**Comment by thijsvdn** [comment]
@john-westcott-iv, I agree that it indeed seems to be a problem in the API. A page size of 1 misbehaves when using the awx.awx.tower_api, but seems to work fine for me when calling /api/v2/job_templates/129/schedules/?page_size=1 and subsequent pages using a REST client.

With a page size of 2 however, things also break down for the latter scenario (68 items in total):

page 1:
#1 = **id 239**
#2 = id 246

page 2:
#1 = **id 239**
#2 = id 218

**Comment by john-westcott-iv** [comment]
It does seem inconsistent across the API end points. For example, we do test the pagination with page_size = 1 against users but it we also have a fairly low number of users. So it could be a combination of data size, page size and end point. https://github.com/ansible/awx/blob/6aff5d9b5a1d8f882bf6660f07a6cbc5bc0e98e1/awx_collection/tests/integration/targets/tower_lookup_api_plugin/tasks/main.yml#L113

**Comment by thijsvdn** [comment]
What also doesn't help is that the expected number of objects is returned, so even with a large number of users a test like `length() >= 3` would have missed this one.

**Comment by john-westcott-iv** [comment]
For anyone in the API team who picks this up, here are steps to replicate. Modify this playbook for your tower host, tower use and tower password and put in a job template ID that exists in your environment:
```
---
- name: Create 100 schedules
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx
  vars:
    tower_hostname: https://<hostname>
    tower_username: <user name>
    tower_password: <password>
    job_template_id: <job template ID>
  tasks:
    - name: Create 100 schedules
      tower_schedule:
        enabled: False
        name: "Sched {{ item }}"
        rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
        tower_host: "{{ tower_hostname }}"
        tower_password: "{{ tower_password }}"
        tower_username: "{{ tower_username }}"
        unified_job_template: "{{ job_template_id }}"
        validate_certs: False
      loop: "{{ query('sequence', 'start=1 end=100') }}"
```

Once you have 100 schedules go to /api/v2/job_templates/<job id>/schedules?page_size=1  and note the ID returned. Click on the next link and you should get the same ID on that page.

You can also test this with ansible using these tasks:
```
    - name: Get job template
      set_fact:
        my_template: >-
            {{
               lookup(
                 'awx.awx.tower_api',
                 'job_templates',
                 expect_one=true,
                 host=tower_hostname, username=tower_username, password=tower_password, verify_ssl=False,
                 query_params={'id': job_template_id}
               )
            }}

    - name: Get currently scheduled releases from AWX
      set_fact:
        my_schedules: >-
         {{
            lookup(
             'awx.awx.tower_api',
             my_template.related.schedules,
             return_all=true,
             max_objects=1000,
             host=tower_hostname, username=tower_username, password=tower_password, verify_ssl=False,
             query_params={'page_size': page_size | default(1)}
           )
         }}

    - name: Print schedule names
      debug:
        msg: "{{ item.name }}"
      loop: "{{ my_schedules }}"
      loop_control:
        label: ''

    - name: Add schedule names to a list
      set_fact:
        sched_names: "{{ (sched_names | default([])) + [ item.name ] }}"
      loop: "{{ my_schedules }}"
      loop_control:
        label: '{{ item.name }}'

    - name: Assert we got the correct number of assets
      assert:
        that:
          - "{{ my_schedules | length }} == 100"
          - "{{ sched_names | unique | length }} == 100"

    - name: Assert we got the correct number of names
      assert:
        that:
          - "{{ sched_names | unique | length }} == 100"
```
