### ISSUE TITLE
Toggling is_system_auditor & is_superuser from True to False Doesn't Work with tower_user module

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/awx#9663]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When attempting to toggle is_system_auditor or is_superuser from true to false using tower_user, Ansible does not report a changed status, nor does the action commit in the backend.

##### ENVIRONMENT
* AWX version: 17.0.0
* Ansible version:  2.9.18

##### STEPS TO REPRODUCE

1.) Create a Normal User.
2.) Attempt to change the is_system_auditor or is_superuser flag from true to false using tower_user.

##### EXPECTED RESULTS

I would expect the user record to be PATCH'd correctly.

##### ACTUAL RESULTS

PATCH'ing the user flag from false to true oddly works, but not vice versa.

**Comment by jainnikhil30** [comment]
Fixed with PR: https://github.com/ansible/awx/pull/9558

**Comment by one-t** [comment]
Tested, this is now working as expected.

**Comment by one-t** [comment]
```
    - name: Add tower user as a system administrator
      tower_user:
        username: admin-revoke
        password: foobarbaz
        email: jdoe@example.org
        superuser: yes
        state: present
      tags:
        - add

    - name: Remove system administrator privileges
      tower_user:
        username: admin-revoke
        password: foobarbaz
        email: jdoe@example.org
        superuser: no
        state: present
      tags:
        - revoke

    - name: Add tower user as a system auditor
      tower_user:
        username: audit-revoke
        password: foobarbaz
        email: jdoe@example.org
        auditor: yes
        state: present
      tags:
        - add

    - name: Remove Auditor
      tower_user:
        username: audit-revoke
        password: foobarbaz
        email: jdoe@example.org
        auditor: no
        state: present
      tags:
        - revoke
```
