### ISSUE TITLE
[18.0.0] Upgrade question: Migrations from Docker are not using minikube...?

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#9693]
##### SUMMARY
New installs use minikube. As I can read and see, upgrades/migratiosn from docker are not ending in minikube, am I right? I thought the docker installs are ending up migrating and using minikube?

**Comment by ryanpetrello** [comment]
Hey @Commifreak,

There isn't a migration path from Docker -> minikube.

17.x users who were deploying with Docker should follow these instructions to continue to deploy to Docker:
https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md
https://github.com/ansible/awx/tree/devel/tools/docker-compose

minikube is recommended for AWX users who want to deploy the AWX operator (https://github.com/ansible/awx-operator) to Kubernetes without having to manage a full-fledged Kubernetes cluster.  For more about Minikube, see: https://minikube.sigs.k8s.io/docs/

**Comment by Commifreak** [comment]
I was curious about the line saying `If you are migrating data from a Local Docker installation (17.0.1 and prior) to AWX 18.0 or higher, you can migrate your data to the development environment via the migrate.yml playbook.`

And: `AWX can also alternatively be installed and run in Docker, but this install path is only recommended for development/test-oriented deployments, and has no official published release.`

I believe, thats not what I want.

**Comment by ryanpetrello** [comment]
@Commifreak,

Yep, we don't recommend Docker-based deployment for production oriented deployments (instead we recommend people deploy to K8S).

**Comment by Commifreak** [comment]
Is there any way then to migrate from docker to it?

**Comment by shanemcd** [comment]
@Commifreak No automated or documented way. You could try hacking through it yourself with pg_dump / pg_restore.

**Comment by ryanpetrello** [comment]
Yep, what @shanemcd said - you could *probably* make a backup of the database, install a new AWX on Minikube, and restore the database dump.  But there's no automated tooling that I know of to do this today.

**Comment by Commifreak** [comment]
Okay, thanks. Since the pg db contains everything AWX need (settings, keys etc) this should probably work, right?

if yes and Iam able to do it, I tell the steps here.

**Comment by ryanpetrello** [comment]
One thing you'll want to make sure you copy *before* upgrading is the "secret key" value that's used to encrypt/decrypt secret values.  In Docker 17.x, this value is set in your inventory file: https://github.com/ansible/awx/blob/17.1.0/installer/inventory#L116

**Comment by james-crowley** [comment]
@ryanpetrello On a related note, moving from 17.X to 18.0, I noticed the `task` container is no longer in the deployment. Did you guys changes this feature?

Looking at the dev docker-compose file for 18.0 there is no mention of the task container. I tried digging through the operator as well to see what containers are getting deployed.

**Comment by ryanpetrello** [comment]
@james-crowley yep, in the base 18.x `docker-compose` deployment, all of the Tower services run in just one container.  PostgreSQL and Redis run in their own:

```shell
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                              NAMES
44ec933359f4        quay.io/awx/awx_devel:devel                        "/entrypoint.sh /bin…"   5 hours ago         Up 5 hours          0.0.0.0:6899->6899/tcp, 0.0.0.0:7899-7999->7899-7999/tcp, 0.0.0.0:8013->8013/tcp, 0.0.0.0:8043->8043/tcp, 0.0.0.0:8080->8080/tcp, 22/tcp, 0.0.0.0:8888->8888/tcp   tools_awx_1_run_fcf6716df37e
e9a3caef3534        postgres:12                                        "docker-entrypoint.s…"   16 hours ago        Up 16 hours         5432/tcp                                                                                                                                                           tools_postgres_1
c65a57109e5b        redis:latest                                       "redis-server /usr/l…"   16 hours ago        Up 16 hours         6379/tcp                                                                                                                                                           tools_redis_1
```

**Comment by james-crowley** [comment]
@ryanpetrello When deploying it via the operator I assume its pretty much the same thing expect postgres might be pulled out for OCP. 

What was the task container original there for? Database migrations/setting up default users? 

I did notice the task script was still in the 18.0 docker-compose folders. I got a PR coming in to fix some multi-arch issues with the moving of files for 17.X to 18.0. Do you want me to delete the task script as well?

**Comment by shanemcd** [comment]
The web / task containers are still separate when running on k8s. The development environment just shoves everything in a monolithic container because it was originally designed to mimic a VM. We have another development environment that mimics a k8s install: https://github.com/ansible/awx/blob/devel/docs/development/minikube.md

**Comment by ryanpetrello** [comment]
Yep ☝️

**Comment by Commifreak** [comment]
Okay,

I have now the new instance running. I did not used the guide here because I dont know if it is applicable: https://github.com/ansible/awx-operator/blob/devel/docs/migration.md - is it applicable? The old pg_db runs inside a docker on another server, would this work when I publish the ports from docker?

I tried pg_dump/pg_restore. The dump succeded but theres an issue before I want to try the restore...

How to stop the awx services before? minikube/kubectl only allows stop of the compltete deployment. When I stop the hundreds docker containers, they get recreated/started immediately. That no clean way to play with databases when awx is running.

Ideas?

```
minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
timeToStop: Nonexistent
```

```
minikube kubectl get deployments
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
awx            1/1     1            1           91m
awx-operator   1/1     1            1           92m
```

```
minikube kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
awx-6f7bd969db-dmfx2           4/4     Running   4          92m
awx-operator-57bcb58f5-s4xjc   1/1     Running   1          92m
awx-postgres-0                 1/1     Running   1          92m
```

How to proceed in a clean way?

**Comment by Commifreak** [comment]
Okay, I got it working.

First, I modified my old awx-postgre container to publish its port 5432 to 0.0.0.0 (Host). That worked. Details on how to do this are available if required.

Then, I used the migrate way from Operator (https://github.com/ansible/awx-operator/blob/devel/docs/migration.md) and ended up with a myawx.yml like this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: default
stringData:
  secret_key: awxsecret
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: default
stringData:
  host: "172.31.10.13"
  port: "5432"
  database: awx
  username: awx
  password: awxpass
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_old_postgres_configuration_secret: awx-old-postgres-configuration

---
apiVersion: v1
kind: Service
metadata:
  name: awx-service-custom-port
spec:
  type: NodePort
  selector:
    app: awx
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8052
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000

```

With this, the operator connected to the old pgsql, copied the data, created its own pgsql pod and migrated everything. It worked!

I can login using my old admin password and see all data. Secrest are there, I dod not yet tested, if ansible could decrypt it using the secret.

**Special note about IP/hostname fields here**: The Hostname and Port (e.g. "stringData") **MUST** be quoted! Otherwise a Read error occurs.

EDIT: I still cannot believe, that the awx team is saying docker is now for devel and k8s is for prod envs but leaving no complete migration to it for the pre-18-docker users. :(
