### ISSUE TITLE
Clarify what it means for project updates to have a default execution environment

### ISSUE THREAD

**Issue by balonik** [ansible/awx#9715]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Execution environment is not used when executing (manual) project sync.

Project sync is an Ansible Playbook run as well, it is expected to honor the Execution Environment setting?

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: AWX Operator
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Change the `Instance Group -> tower` definition to:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: my_custom_awx-ee:latest
      name: worker
      args:
        - ansible-runner
        - worker
```

Create new SCM project and try to sync.
The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.

Add new Execution Environment in AWX.
Edit the SCM project and define Default Execution Environment to the newly created Execution Environment.
The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.

##### EXPECTED RESULTS

Project Sync job will use the `Instance Group -> tower` setting if set.
Project Sync job will use the Default Execution Environment configured for that Project.

##### ACTUAL RESULTS

The embedded (default) `awx-ee` container in `awx` pod is still used for the execution of Project Sync.
