### ISSUE TITLE
Execution Environment defined on resources doesn't work with Container Groups

### ISSUE THREAD

**Issue by balonik** [ansible/awx#9716]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It should be possible to override Execution Environment by setting the appropriate settings in Project or Template definition.
In case Instance Group settings is modified to have a different default worker image like this

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: my_custom_awx-ee:latest
      name: worker
      args:
        - ansible-runner
        - worker
```

The image `my_custom_awx-ee:latest` is ALWAYS used for Jobs runs ignoring the Execution Environment settings in Project and Template.

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: AWX Operator
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Modify Instance Group settings:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: my_custom_awx-ee:latest
      name: worker
      args:
        - ansible-runner
        - worker
```

- Create Execution Environment with image path `my_project_1-ee:latest`.
- Create Project and Template. Configure either Project or Template to use the newly created Execution Environment.
- Launch Template. AWX will run the job using the Instance Group defined image instead of Execution Environment configured in Project or Template.

##### EXPECTED RESULTS

Job is executed using the `my_project_1-ee:latest` image.

```
$ k describe pod/awx-job-788-9d2wx | grep 'Image: '
    Image:         my_project_1-ee:latest
```

##### ACTUAL RESULTS

Job is executed using the `my_custom_awx-ee:latest` image.

```
$ k describe pod/awx-job-788-9d2wx | grep 'Image: '
    Image:         my_custom_awx-ee:latest
```

**Comment by shanemcd** [comment]
Ah... It looks like we're always using the EE defined in the Container Group definition. We need to override the `image` field when an EE is returned via our resolving logic. Thanks for opening this.

**Comment by stanislaspiron** [comment]
I had the same issue. I used the following workaround :

I created a new instance group with:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: my_project_1-ee:latest
      name: worker
      args:
        - ansible-runner
        - worker
```
then, in the template, I define this instance group.
