### ISSUE TITLE
[18 / minikube] Experiences and documentation...

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#9731]
##### ISSUE TYPE

 - Documentation

I dont know if seomeone is interested in the following text or if Iam just did something the wrong way, maybe someone could just some feedback on my thoughts.

I use ansible since version <10 via docker-compose. Just like many of us, I believe? Since AWX 18, it is not longer supported for prod-environments, as I read. So I decided to switch to the fancy new minikube version.

I never wokred with minikube or kubectl/k8s before, so this was new for me. I did not fully understand all the possibilities yet, sorry ;)

So, I have a Ubuntu VM. minikube must use the docker driver here. To be honest: I dont want a big cluster system just to get AWX running, so I wanted to keep it as simple as possible.

The first thing I noticed is, that the AWX Service (hint: A service is "an abstract way to expose an application"), uses a random port after each create. SInce I test some things and use docker, Iam forced to re-create the cluster multiple times.

The next thing is, that the default k8s docker container forces all ports to be only locally reachable (binds 127.0.0.1:*). I could create a nginx forwarder or something but: I want to keep things simple. 

After some search, I found the "new" --ports option for minikube.

**MY** command for create the cluster: `minikube start --cpus=4 --memory=8g --addons=ingress --driver=docker --ports=80:30000`. This forces docker to create a 0.0.0.0:80 to container:30000 forward.

I searched for a way to set a static NodePort for the AWX service, which is automatically created. I did not found anything.

So I ended up apllying a second service:

```yml
apiVersion: v1
kind: Service
metadata:
  name: awx-service-custom-port
spec:
  type: NodePort
  selector:
    app: awx
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8052
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
```

This created a new service (next to the default `awx-service`) with a static NodePort 30000 which is then forwarded to port 8052 on the AWX side, which is the HTTP-Port.

Is there an earlier way to define a static port?

The next thing thats not clear for me at all: **How to apply an AWX update** with this installation type? How can I upgrade to AWX 18.x, when it releases?

So, for the minikube-docker-driver users, there should be more informations on how to create an AWX installation with needed port forwardings.

**Commands used**

```bash
minikube start --cpus=4 --memory=8g --addons=ingress --driver=docker --ports=80:30000
minikube kubectl -- apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml
minikube kubectl apply -- -f myawx.yml
minikube kubectl apply -- -f awx_custom_port.yml
```

myawx.yml is the default from here, awx_custom_port.yml is the one above

**Last question**: Do I need this ingress addon for my setup? I did not understood what it does for me.

Is this setup ok? Or is there something I missed?

Thanks in advance :)
