### ISSUE TITLE
Provide some documentation to run AWX-EE with custom ssh config

### ISSUE THREAD

**Issue by lerminou** [ansible/awx#9753]
##### ISSUE TYPE
 - Documentation Bug Report

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube
* Ansible version:  X.Y.Z
* Operating System: redhat 8.3
* Web Browser:

##### STEPS TO REPRODUCE

To configure a running environment with a custom ssh key, there is some tasks not documented:

Here is a solution if needed   
We need to mount the SSH config directory into the task and web container :
Do not use the root `.ssh/` folder because the AWX worker run as **awx** user and has `permission denied` in the default root .ssh folder
```
  tower_web_extra_volume_mounts: |
     - name: "sshkey"
       mountPath: "/var/lib/awx/.ssh"
  tower_task_extra_volume_mounts: |
     - name: "sshkey"
       mountPath: "/var/lib/awx/.ssh"
  tower_extra_volumes: |
     - name: "sshkey"
       hostPath:
         path: "/root/awx-ssh"
```

And it's not enough ......    
we need to go the the IHM: `/#/instance_groups/container_group/1` and modify the default pod container like this: (double volume for the config file)
```
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  containers:
    - image: quay.io/ansible/awx-ee
      name: worker
      args:
        - ansible-runner
        - worker
      volumeMounts:
        - name: sshkey
          mountPath: /var/lib/awx/.ssh
        - name: sshconf
          mountPath: /etc/ssh/ssh_config.d/01-own.conf
  volumes:
    - name: sshkey
      hostPath:
        path: /root/awx-ssh
    - name: sshconf
      hostPath:
        path: /root/awx-ssh/config
```
