### ISSUE TITLE
AWX18 awx-ee doesn't load collection

### ISSUE THREAD

**Issue by lerminou** [ansible/awx#9768]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: minikube
* Ansible version:  2.11
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

My project contains a a file collections/requirements.yml
During the project synchro the collection is loaded in AWX

When I launch a job:
ERROR! couldn't resolve module/action 'pam_limits'. This often indicates a misspelling, missing collection, or incorrect module path.

pam_limits is included in the collection community.general
And when i go to the pod awx-ee, the collection is missing from the list

Inside the pod: k8s_awx-ee_awx-85ff87845c
```
bash-4.4$ ansible-galaxy collection list
# /usr/share/ansible/collections/ansible_collections
Collection           Version
-------------------- -------
amazon.aws           1.4.1  
ansible.posix        1.2.0  
awx.awx              18.0.0 
azure.azcollection   1.4.0  
community.kubernetes 1.2.0  
community.vmware     1.8.0  
google.cloud         1.0.2  
openstack.cloud      1.0.1  
ovirt.ovirt          1.2.5  
theforeman.foreman   2.0.1  
```

The operator yaml file allow to modify the web and task pod but not the ee container

##### EXPECTED RESULTS

my job is in success

**Comment by OneHappyForever** [comment]
How did you fix it? I have the same error.

**Comment by lerminou** [comment]
The same way as my other bug here :
https://github.com/ansible/awx/issues/9753
In the UI > instance groups > tower : modify the default pod definition 
Mount a volume with my local collections...

**Comment by OneHappyForever** [comment]
I see. 

I'm trying to figure out how to write the config. Do you have an example for this particular case (not SSH)?

Also, shouldn't AWX fix this issue with the requirements file failing?

**Comment by lerminou** [comment]
Yes it's just a workaround and I hope a real fix for this

Here is my working copy

On your host : 
```
root@redhat ~/.ansible  ansible-galaxy collection install -r collections-requirements.yml
 
```

On the UI definition 
```
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  containers:
    - image: quay.io/ansible/awx-ee
      name: worker
      args:
        - ansible-runner
        - worker
      volumeMounts:
        - mountPath: /var/lib/awx/.ssh
          name: sshkey
        - name: ansibleroles
          mountPath: /etc/ansible/roles
        - name: sshconf
          mountPath: /etc/ssh/ssh_config.d/01-own.conf
        - name: ansiblecollections
          mountPath: /home/runner/.ansible/collections/ansible_collections
  volumes:
    - name: sshkey
      hostPath:
        path: /root/awx-ssh
    - name: sshconf
      hostPath:
        path: /root/awx-ssh/ssh_config
    - name: ansibleroles
      hostPath:
        path: /root/.ansible/roles
    - name: ansiblecollections
      hostPath:
        path: /root/.ansible/collections/ansible_collections 
```
