### ISSUE TITLE
Need a way to auto-generate krb5.conf on Kubernetes deployments

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [ansible/awx#9807]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

As far as I can tell, there are no parameters in the 17.1 install playbook or 18.0 operator that allow you to configure the kinit realm information (set in the krb5.conf file) without rebuilding the image to include a krb5.conf file. (If there is a way to set this information, please let me know).

The closest thing I could think of is editing the configmap and deployment templates in the 17.1 build to include a krb5.conf file. I can't even imagine how it would work in 18.0 with the operator deployment.

Ideally I should be able to specify this krb5.conf through a parameter to the install playbook or the AWX Operator.

This is very important for setting up Kerberos support with Windows hosts on Kubernetes deployments and I can hardly believe that such a feature doesn't exist yet. If there already is a way of setting up Kerberos on Kubernetes deployments, please let me know.

**Comment by shanemcd** [comment]
Going to close this in favor of the issue referenced above ^

**Comment by BrandonALXEllisSS** [comment]
While I appreciate the feature idea, it looks like you can already do this using some hidden operator variables:

I added this to my kubeconfig:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-extra-files
data:
  krb5.conf: |
     <content of krb5.conf file>
```

And then adjusted my awx deployment config spec:
```
  tower_task_extra_volume_mounts: |
    - name: krb5
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  tower_extra_volumes: |
    - name: krb5
      configMap:
        defaultMode: 420
        items:
          - key: krb5.conf
            path: krb5.conf
        name: awx-extra-files
```
I haven't used it to run a playbook yet [since 18.0 broke windows](https://github.com/ansible/awx/issues/9863). But kinit works so it looks promising
