### ISSUE TITLE
AWX 18.0.0 - telegram module is missing

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9834]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
the telegram ansible module is missing in AWX 18

##### ENVIRONMENT
* AWX version: 18.0.0
* AWX install method: k3s, awx-operator
* Ansible version:  unknown, see #9829 
* Operating System: debian buster
* Web Browser: Firefox 87

##### STEPS TO REPRODUCE

A tried and trusted playbook of mine fails to execute from within AWX 18, it used to work fine in all previous versions.
Could be related to #9829 

##### EXPECTED RESULTS

I'd expect it "to work"

##### ACTUAL RESULTS

play fails, seems that the telegram module is missing.

##### ADDITIONAL INFORMATION

Output of play run:

```
ERROR! couldn't resolve module/action 'telegram'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/tmp/tmph0nln2m1/project/updates.yml': line 26, column 5, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  - name: telegram-notify
    ^ here
```

Relevant part of playbook:
```
 handlers:

  - name: telegram-notify
    telegram:
      msg: "{{ ansible_fqdn }}: updates installed."
      token: "{{ eregion_home_telegram_token }}"
      chat_id: "{{ eregion_home_telegram_chat_id }}"
    delegate_to: localhost
    changed_when: False

```
