### ISSUE TITLE
Pin down awx version via awx operator

### ISSUE THREAD

**Issue by MrAmbiG** [ansible/awx#9838]
##### ISSUE TYPE
 - Feature Idea
Please let us mention or pin down the awx version in the awx CRD or via operator. Currently I believe by default it deploy 18.x but what if tomorrow another newer version comes and the operator always deploys the latest, which might break our code running on awx 18 to break on 19 or later.

**Comment by shanemcd** [comment]
See https://github.com/ansible/awx-operator/issues/182

**Comment by MrAmbiG** [comment]
@shanemcd i wish it worked. line 118
```
                # tower_ee_images:
                #   description: Registry path to the Execution Environment container to use
                #   type: array
                #   items:
                #     type: object
                #     properties:
                #       name:
                #         type: string
                #       image:
                #         type: string
                tower_ee_images:
                  - name: awx
                    image: quay.io/ansible/awx:18
```
user@ubuntuserve:~/citadel/k8s/apps$ kl apply -f awx-operator0.8.0.yaml   
error: error validating "awx-operator0.8.0.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.tower_ee_images): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps: got "array", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false

file : https://raw.githubusercontent.com/ansible/awx-operator/0.8.0/deploy/awx-operator.yaml [unfortunately your documentation always asks people to use the operator from the devel branch even when we switch to release branch.]

```
                tower_ee_images:
                  - name: awx
                    image: quay.io/ansible/awx:18
                  description: Registry path to the Execution Environment container to use
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
```
error: error parsing awx-operator0.8.0.yaml: error converting YAML to JSON: yaml: line 127: did not find expected '-' indicator

```
                tower_ee_images:
                  # - name: awx
                  #   image: quay.io/ansible/awx:18
                  description: Registry path to the Execution Environment container to use
                  type: array
                  items:
                    type: object
                    properties:
                      name: awx
                        type: string
                      image: quay.io/ansible/awx:18
                        type: string
```
error: error parsing awx-operator0.8.0.yaml: error converting YAML to JSON: yaml: line 134: mapping values are not allowed in this context

**Comment by MrAmbiG** [comment]
never mind..
it is to be updated in the in the awx.yaml not operator.yaml and it wasnt clear from the documentation.
2 suggestion for the documentation:

1. update the operator url as per the release branch i am in, it always shows the operator from devel branch even though i am at a release branch
2. At the beginning of the advanced configuration heading, please mention that the options can be configured at awx.yaml (otherwise for an uninitiated person, it can be either operator or awx.yaml)
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  tower_ingress_type: Ingress
  tower_ee_images:
  - name: awx19
    image: quay.io/ansible/awx:19.0.0
```
