### ISSUE TITLE
AWX 19.0.0: awx-operator deployment is stuck setting up the database

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx#9854]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm trying to deploy a fresh, clean AWX 19 in K3s using the operator in version 0.8.0, and it never finishes - the operator pod log suggests that it is trying to restore some database backup from somewhere?

my deployment yaml file:
```
apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  tower_ingress_type: Ingress
  tower_hostname: awx.apps.eregion.home
  tower_ee_images:
    - name: "eregion.home EE"
    - image: "docker.io/lemmy04/awx-ee-community"

```
##### ENVIRONMENT
* AWX version: 19.0.0
* AWX install method: k3s, awx-operator 0.8.0
* Ansible version:  unknown
* Operating System: debian buster
* Web Browser: not relevat

##### STEPS TO REPRODUCE
kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.8.0/deploy/awx-operator.yaml
kubectl apply -f my_deployment_file.yaml

It never finishes, and "kubectl logs -f -- <operator pod> shows this at the end which eventually repeats itself:

```
TASK [installer : Stream backup from pg_dump to the new postgresql container] ***
task path: /opt/ansible/roles/installer/tasks/migrate_data.yml:59
-------------------------------------------------------------------------------
{"level":"info","ts":1617890658.5037224,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1617890658.510742,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version/openshift","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1617890658.51544,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1617890658.529352,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/pods/awx-postgres-0/exec","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"pods","Subresource":"exec","Name":"awx-postgres-0","Parts":["pods","awx-postgres-0","exec"]}}
```

##### EXPECTED RESULTS
I'd expect the deployment to eventually finish, or fail with some meaningful message - not repeat the same step over and over.

##### ACTUAL RESULTS

the deployment seems to be looping in setting up the database.

##### ADDITIONAL INFORMATION

lemmy04/awx-ee-community on docker hub is an EE image that I've built myself that has the ansible.windows and community.general collections already installed - that way my actual plays stay backwards compatible to ansible 2.9 and below.
