### ISSUE TITLE
tower-import Failed to import assets 'ApiV2' object has no attribute 'execution_environments

### ISSUE THREAD

**Issue by markatdxb** [ansible/awx#9876]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Im testing simple playbook to export and re-import the job template. Export works 

##### ENVIRONMENT
* AWX version: 14.1.0
* AWX install method: docker on linux
* Ansible version:  2.10.6
* Operating System: Ubuntu 20.04
* Web Browser: Edge

##### STEPS TO REPRODUCE

```
- name: Export a job template {{awx_template}} from DEV
      awx.awx.tower_export:
        tower_host: "{{awx_dev}}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: False
        job_templates: "{{awx_template}}"
      register: awx_export

    - name: Import template {{awx_template}} to TEST
      awx.awx.tower_import:
        tower_host: "{{awx_dev}}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: False
        assets: "{{ awx_export.assets }}"
```

##### EXPECTED RESULTS

successful import of assets

##### ACTUAL RESULTS

The full traceback is:
  File "/tmp/ansible_awx.awx.tower_import_payload_goeindqh/ansible_awx.awx.tower_import_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_import.py", line 91, in main
  File "/home/marek/.local/lib/python3.8/site-packages/awxkit/api/pages/api.py", line 333, in import_assets
    for resource in self._dependent_resources(data):
  File "/home/marek/.local/lib/python3.8/site-packages/awxkit/api/pages/api.py", line 209, in _dependent_resources
    data_pages = [getattr(self, resource)._create().__item_class__ for resource in EXPORTABLE_RESOURCES]
  File "/home/marek/.local/lib/python3.8/site-packages/awxkit/api/pages/api.py", line 209, in <listcomp>
    data_pages = [getattr(self, resource)._create().__item_class__ for resource in EXPORTABLE_RESOURCES]
  File "/home/marek/.local/lib/python3.8/site-packages/awxkit/api/pages/page.py", line 114, in __getattr__
    raise AttributeError("{!r} object has no attribute {!r}".format(self.__class__.__name__, name))
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "assets": {
                "job_templates": []
            },
            "tower_config_file": null,
            "tower_host": "https://ansible-dev",
            "tower_oauthtoken": null,
            "tower_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tower_username": "awx-user",
            "validate_certs": false
        }
    },
    "msg": "Failed to import assets 'ApiV2' object has no attribute 'execution_environments'"
