### ISSUE TITLE
Bastion host configuration

### ISSUE THREAD

**Issue by coudenysj** [ansible/awx#9893]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

We are using https://github.com/kubernetes-sigs/kubespray in AWX to spin up kubernetes clusters with the dynamic inventory logic of AWX.

Kubespray works a bastion host (part of the inventory), so all AWX traffic should go over that bastion host to the other nodes.

This is possible in AWX (see #4842, #8514, #2279, #2079, etc...), but it requires manually changing the ssh config on the task container of AWX.

Is this bastion node changes per cluster we set up, this is a lot of manual work.

It would be nice if, when the bastion node is configured in the AWX inventory too, that this config is used when running commands over that bastion host.

**Comment by wenottingham** [comment]
Hi - 

We've actually changed the architecture recently - there is no more task container. When deployed in kubernetes, all automation is run in the kubernetes cluster using what we call 'execution environments' - containers that run ansible.

You'd do this now likely by embedding that config in the execution environment itself, rather than make changes to AWX.

**Comment by artm** [comment]
Are there any instructions on configuring execution environment to use a single or multiple bastion hosts?
Could this be accomplished with mounting some configuration files from kubernetes config_maps / secrets?

**Comment by artm** [comment]
My current goal is to get the bastion host into known_hosts in the execution environment. What I tried is:

1. create a config map with known_hosts:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-awx-custom-config
  namespace: ansible-awx
data:
  ssh_know_hosts: |
    ... actual contents ...
```

2. Inside AWX go to Instance Groups, "default",  check "Customize pod specification" and add volume + mount to the pod specification, mounting it into `/home/runner/.ssh/known_hosts` because I figured that's where it belongs:

```yaml
# original yaml generated by awx or awx-operator
apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:0.6.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      # my customizations
      volumeMounts:
        - name: known-hosts
          mountPath: /home/runner/.ssh/known_hosts
          subPath: ssh_known_hosts
  volumes:
    - name: known-hosts
      configMap:
        name: ansible-awx-custom-config
```

but this doesn't seem to help, the jobs still fail with 

```
The authenticity of host '<BASTION IP>' can't be established.
```

**Comment by artm** [comment]
Ok, I've got it working for a single environment and can generalize from here. For those struggling, here is the outline of my solution:

A config map with ssh config that sets up a bastion host for an environment

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ansible-awx-ssh-configs
  namespace: ansible-awx
data:
  default: |
    Host * !BASTION-HOST-IP
      ProxyJump BASTION-HOST-IP
    Host BASTION-HOST-IP
      StrictHostKeyChecking no
      User PROXY-USER
      IdentityFile /home/runner/.ssh/PROXY-KEY
```

where `BASTION-HOST-IP` is the address of a bastion host for this environment (IP or domain name). `PROXY-USER` is the username to login to the bastion as and `PROXY-KEY` is the private key of the user (from a secret below).

A secret with the private key of the proxy user:

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: ansible-awx-ssh-keys
  namespace: ansible-awx
type: Opaque
data:
  default: # here base64ed actual key 
```

These two are in the cluster. And Inside AWX > "Instance Groups", "default", check "Customize pod specification", the pod specification now looks like:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:0.6.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      # custom config starts here
      volumeMounts:
        - name: ssh-config
          mountPath: /home/runner/.ssh/config
          subPath: default
        - name: ssh-keys
          mountPath: /home/runner/.ssh/PROXY-KEY # same as in the conflig map above
          subPath: default
  volumes:
    - name: ssh-config
      configMap:
        name: ansible-awx-ssh-configs
        defaultMode: 0400
    - name: ssh-keys
      secret:
        secretName: ansible-awx-ssh-keys
        defaultMode: 0400
  securityContext:
    runAsUser: 1000
```

Now the jobs using the default instance group are correctly connecting to the hosts via the configured bastion. To support multiple environments with different bastions we could for example place different configurations in different keys of the config map / secret.
